- src/mlpack/core/optimizers/lrsdp/lrsdp_function.cpp
this function is actually not very useful, since the augmented lagrangian's implementation is what the L-BFGS uses. however, it does confuse debug output.
> don't hardcore Evaluate for the lovasz theta objective function

- src/mlpack/methods/cf/cf_impl.hpp
these ratings will be ignored by the algorithm, so the user should be wary of this
> Warn if ratings of 0 are found

- CMakeLists.txt
clang does not support this option
> only use PGO when compiling with GCC

- src/mlpack/methods/matrix_completion/CMakeLists.txt
- src/mlpack/methods/matrix_completion/matrix_completion.cpp
- src/mlpack/methods/matrix_completion/matrix_completion.hpp
avoid a possible multiple definitions issue at link time
> move matrix_completion_impl.hpp to matrix_completion.cpp

- .gitignore
- src/mlpack/core/dists/gaussian_distribution.cpp
- src/mlpack/core/dists/gaussian_distribution.hpp
- src/mlpack/core/dists/regression_distribution.hpp
- src/mlpack/methods/gmm/em_fit_impl.hpp
- src/mlpack/methods/gmm/gmm_convert_main.cpp
- src/mlpack/methods/hmm/hmm_util_impl.hpp
- src/mlpack/tests/distribution_test.cpp
- src/mlpack/tests/gmm_test.cpp
- src/mlpack/tests/hmm_test.cpp
These series of commits adds caching of various factorizations and inverses of the covariance matrix for the gaussian distribution. Note that the previous version did not do error checking for positive definite (or even symmetric matrices) on construction-- this is no longer the case (via a cholesky decomposition attempt which fails if the assumption is violated).
In addition, various test cases had to be fixed to make this work. Previous test cases did not even use symmetric covariance matrices in some cases (who knows what the results were actually computing)!
> Add covariance factorization caching to gaussian distribution

- README.md
After doing a 
$ make install
I got this error
$error while loading shared libraries: libmlpack.so.1: cannot open shared object file: No such file or directory
So, I added the following change to the README file to make the README more helpful to noobs like me.
> shared object file issue after make install

- CMakeLists.txt
- src/mlpack/CMakeLists.txt
- src/mlpack/tests/mlpack_test.cpp
This branch makes UTF to give running test output like this
```
Running 460 test cases...
Entering test suite "MLPACKTest"
Entering test suite "AdaBoostTest"
Entering test case "HammingLossBoundIris"
Leaving test case "HammingLossBoundIris"; testing time: 874945mks
Entering test case "WeakLearnerErrorIris"
Leaving test case "WeakLearnerErrorIris"; testing time: 886266mks
Entering test case "HammingLossBoundVertebralColumn"
Leaving test case "HammingLossBoundVertebralColumn"; testing time: 8275244mks
Entering test case "WeakLearnerErrorVertebralColumn"
Leaving test case "WeakLearnerErrorVertebralColumn"; testing time: 8266254mks
Entering test case "HammingLossBoundNonLinearSepData"
Leaving test case "HammingLossBoundNonLinearSepData"; testing time: 2507713mks
Entering test case …
```
> Issue 344 - Better boost test output

- src/mlpack/methods/softmax_regression/softmax_regression.hpp
- src/mlpack/methods/softmax_regression/softmax_regression_function.cpp
- src/mlpack/methods/softmax_regression/softmax_regression_function.hpp
- src/mlpack/methods/softmax_regression/softmax_regression_impl.hpp
- src/mlpack/tests/softmax_regression_test.cpp
In issue332, data points from Gaussian distribution (base [1, 1, 1]) and points from base [9, 9, 9] can't not be well separating using softmax regression. The implementation of softmax regression haven't add the intercept term, which means the hypothesis space only contains 3-d planes crossing the origin. This patch try to fixed this problem by adding the intercept term to it.
> issue332 - add intercept term to softmax regression

- CMakeLists.txt
- src/mlpack/methods/det/dt_utils.cpp
There are two parts to the OpenMP support. First, cmake was instructed
to compile with compiler-appropriate OpenMP flags. Second, three OpenMP
pragmas were added to dt_utils.cpp to parallelize the cross-validation
loop. No non-pragma code changes were necessary.
> Add OpenMP support to density estimation tree code

- src/mlpack/core/tree/binary_space_tree/binary_space_tree.hpp
- src/mlpack/core/tree/binary_space_tree/binary_space_tree_impl.hpp
- src/mlpack/core/tree/binary_space_tree/breadth_first_dual_tree_traverser.hpp
- src/mlpack/core/tree/binary_space_tree/breadth_first_dual_tree_traverser_impl.hpp
- src/mlpack/core/tree/binary_space_tree/dual_tree_traverser.hpp
- src/mlpack/core/tree/binary_space_tree/dual_tree_traverser_impl.hpp
- src/mlpack/core/tree/binary_space_tree/single_tree_traverser.hpp
- src/mlpack/core/tree/binary_space_tree/single_tree_traverser_impl.hpp
- src/mlpack/core/tree/binary_space_tree/traits.hpp
- src/mlpack/methods/emst/dtb.hpp
- src/mlpack/methods/emst/dtb_impl.hpp
- src/mlpack/methods/fastmks/fastmks.hpp
- src/mlpack/methods/fastmks/fastmks_impl.hpp
- src/mlpack/methods/kmeans/dual_tree_kmeans.hpp
- src/mlpack/methods/kmeans/dual_tree_kmeans_impl.hpp
- src/mlpack/methods/neighbor_search/neighbor_search.hpp
- src/mlpack/methods/neighbor_search/neighbor_search_impl.hpp
- src/mlpack/methods/range_search/range_search.hpp
- src/mlpack/methods/range_search/range_search_impl.hpp
- src/mlpack/methods/rann/ra_search.hpp
- src/mlpack/methods/rann/ra_search_impl.hpp
- src/mlpack/tests/layer_traits_test.cpp
Template declaration duplication, which is fine with `gcc` but raises error with `clang`.
For example:
```
mlpack/core/tree/binary_space_tree/binary_space_tree_impl.hpp:231:28:
error: declaration of 'BoundType' shadows template parameter
template<typename BoundType, typename MatType> class SplitType>
```
> Fix build failure with clang (MacOS)

- src/mlpack/core/data/load_impl.hpp
- src/mlpack/tests/load_save_test.cpp
To fix #449 . If tsv files are given, it will be read as raw ASCII format.
Simple test cases also provided.
> load malformed CSVs correctly

- src/mlpack/methods/softmax_regression/softmax_regression.hpp
- src/mlpack/methods/softmax_regression/softmax_regression_function.cpp
- src/mlpack/methods/softmax_regression/softmax_regression_function.hpp
- src/mlpack/methods/softmax_regression/softmax_regression_impl.hpp
1 : add function Serialize to class SoftmaxRegression
2 : add function Train to class SoftmaxRegression
3 : fix bug--did not initialize fitIntercept
The test case "SoftmaxRegressionFunctionEvaluate" always fail on my machine
> Enhance class SoftmaxRegression

- src/mlpack/methods/softmax_regression/softmax_regression.hpp
- src/mlpack/methods/softmax_regression/softmax_regression_function.cpp
- src/mlpack/methods/softmax_regression/softmax_regression_function.hpp
- src/mlpack/methods/softmax_regression/softmax_regression_impl.hpp
- src/mlpack/tests/serialization_test.cpp
- src/mlpack/tests/softmax_regression_test.cpp
1 : remove inputSize from the constructors and data member
2 : provide static function initializeWeight to simplify constructor task
3 : change labels from arma::vec to arma::Row<size_t>
4 : update test cases
The labels of the SoftmaxRegressionFunction still need to be stored, else InitializeWeights() do not know the number of labels
> Enhance SoftmaxRegression

- doc/guide/timer.hpp
- src/mlpack/core.hpp
- src/mlpack/core/util/timers.cpp
- src/mlpack/core/util/timers.hpp
- src/mlpack/tests/cli_test.cpp
Runtime error exception will occur if a <b>Timer::Start</b> or <b>Timer::Stop</b> will be called twice.
> Add exception for starting & stopping given timer

- src/mlpack/methods/kmeans/max_variance_new_cluster_impl.hpp
Hi there!
There seems to be no check on the cluster size when it's decreased, yet it's used afterwards to update the variance. So, if the cluster size reaches zero, the variance is infinity. As a result, the cluster gets chosen in the next iteration and causes access to `furthestPoint == data.n_cols`, which is rather sad.
I simply added the same condition as in `Precalculate`.
> kmeans: small fix with inf variance

- src/mlpack/core/util/cli.cpp
- src/mlpack/core/util/timers.cpp
- src/mlpack/core/util/timers.hpp
CLI Destructor terminate the program timers properly even if the 'Timer::Stop' wasn't called.
> Terminate the program timers properly.

- src/mlpack/methods/naive_bayes/naive_bayes_classifier_impl.hpp
Change "invVar" to "variance" matrix when calculating testProbs.
By using "invVar" you have variances product in numenator, but it needs to be in denominator.
In addition there was potential problem with accuracy when calculate exponents and then calculate logarithm.
I fixed it too.
> Fix classification error

- src/mlpack/methods/ann/layer/base_layer.hpp
- src/mlpack/methods/ann/layer/bias_layer.hpp
- src/mlpack/methods/ann/layer/conv_layer.hpp
- src/mlpack/methods/ann/layer/dropout_layer.hpp
- src/mlpack/methods/ann/layer/linear_layer.hpp
- src/mlpack/methods/ann/layer/lstm_layer.hpp
- src/mlpack/methods/ann/layer/pooling_layer.hpp
- src/mlpack/methods/ann/layer/recurrent_layer.hpp
- src/mlpack/methods/ann/layer/softmax_layer.hpp
Implement move constructor and move assignment for ann modues.
By now only implement for linear_layer.hpp, base_layer.hpp and bias_layer.hpp, will implement for another classes step by step
> add move constructor and move assignment for ann modules

- src/mlpack/methods/logistic_regression/logistic_regression_main.cpp
The error message was "missing output_model",
while the variable used for detecting it was "outputFile",
which refers to the testing output, rather than the model output.
> Fix confusion in error message

- src/mlpack/methods/logistic_regression/logistic_regression_main.cpp
```c++
PARAM_STRING("input_model_file", "File containing existing model (parameters).",
"m", "");
PARAM_STRING("output_model_file", "File to save trained logistic regression "
"model to.", "M", "");
```
v.s.
```c++
const string inputModelFile = CLI::GetParam<string>("input_model");
const string outputModelFile = CLI::GetParam<string>("output_model");
```
> Update GetParam<>(parameterName) per marcos

- CMake/CreateArmaConfigInfo.cmake
- CMake/CreateGitVersionHeader.cmake
I tried to use mlpack as a submodule of my project. Building such setup failed since some files were generated outside of mlpack source tree.
> Use CMAKE_CURRENT_SOURCE_DIR during files generation.

- src/mlpack/methods/ann/cnn_impl.hpp
- src/mlpack/methods/ann/ffn_impl.hpp
- src/mlpack/methods/ann/rnn_impl.hpp
The name of network conflict with the data member--"netowrk", this bug related to issues #531
> fix bug--ann constructor hide the name of network

- src/mlpack/core/util/cli.cpp
- src/mlpack/core/util/cli.hpp
- src/mlpack/core/util/timers.cpp
- src/mlpack/core/util/timers.hpp
- src/mlpack/tests/cli_test.cpp
The commit includes changes for replacement of timers code with std::chrono library of C++11. Instead of 2 maps, we now use 3 maps. The extra map stores the starting time_point of the timer and rest the timers map stores the duration of microseconds elapsed in the timer. Since, this works cross-platform, the unnecessary codes have been removed.
> Changes to solve issue #498: Replacing timer implementation

- src/mlpack/core/util/backtrace.cpp
> Fixes bfd.h: config.h must be included before this header

- src/mlpack/methods/ann/init_rules/kathirvalavakumar_subavathi_init.hpp
For libarmadillo4 and libarmadillo-dev obtained from ubuntu repository, I got the following error when I instantiated KathirvalavakumarSubavathiInitialization.
error: Mat::init(): requested size is not compatible with column vector layout
terminate called after throwing an instance of 'std::logic_error'
what():  Mat::init(): requested size is not compatible with column vector layout
Aborted (core dumped)
Fixed the error by changing dataSum from colvec to rowvec.
> Fixed std::logic_error

- src/mlpack/core/arma_extend/arma_extend.hpp
Manually set `ARMA_{64,32}BIT_WORD` for `{_WIN64,otherwise}` for windows build
This potentially eliminate tons of `warning C4267`
> Manually set flag for _WIN64

- src/mlpack/methods/neighbor_search/neighbor_search_rules_impl.hpp
Hi,
Reading the code of nearest neighbor search, I noticed an error.
I hope this is useful!
> Neighbor search: Fix error in adjustedScore calculation.

- src/mlpack/methods/kmeans/elkan_kmeans_impl.hpp
AFAICT, the old code always killed all centroids if one cluster is empty.
Keeping the last centroids is much more stable.
> Bug fix for Elkan?

- src/mlpack/tests/cosine_tree_test.cpp
I think I solved the problem.
This problem happens due to miscalculations.
The cosines and cosineMax are computed two times (in CosineTree::CosineNodeSplit and in the test).
And the first cosineMax may differ significantly from the second one.
For example, look at the debug output below
`THIS IS TREE 0xbcbe978`
`cosineMax = 0.99999999999999988898`
`cosineMin = 0.73421824357373099978`
`cosines`
`0.75763372746624790821 0.75999261009165319791 0.75479082605226166525` `0.75788044353107164586 0.99999999999999988898 0.73421824357373099978 `
`THIS IS TEST 0xbcbe978`
`TreeDepth = 11`
`cosineMax = 0.75999261009165330893`
`cosineMin = 0.73421824357373111081`
`cosines`
`1 0.75763372746624801923 0.75999261009165330893 0.75479082605226177627` `0.7578804435310718679 0.73421824357373111081 `
All sets …
> Fix bug #358 (CosineTreeTest/CosineNodeCosineSplit test sometimes fails, only on i386)

- src/mlpack/methods/ann/layer/log_softmax_layer.hpp
Refine of pull request #612 
constexpr make sure the variable can initialize at compile time
static make sure the variable will initialize only once
> only initialize variable once

- src/mlpack/tests/cli_test.cpp
Fixes the build for MinGW-w64 as it uses lowercase headers, unchanged for case-insensitive native windows platforms.
> MinGW: use lowercase windows.h

- src/mlpack/methods/det/dt_utils.cpp
Apparently I have to cast altough both fold and testSize are of size_t type:
```
/home/xantares/projects/mlpack/src/mlpack/methods/det/dt_utils.cpp: In function ‘mlpack::det::DTree* mlpack::det::Trainer(arma::mat&, size_t, bool, size_t, size_t, std::__cxx11::string)’:
/home/xantares/projects/mlpack/src/mlpack/methods/det/dt_utils.cpp:195:72: error: no matching function for call to ‘min(intmax_t, arma::uword)’
size_t end = std::min((fold + 1) * testSize, (size_t) cvData.n_cols);
^
```
> Fix a cast in dt_utils.cpp

- CMakeLists.txt
- README.md
- doc/tutorials/README.md
- doc/tutorials/neighbor_search/neighbor_search.txt
- src/mlpack/core.hpp
- src/mlpack/methods/neighbor_search/CMakeLists.txt
fixes #532
Make a copy of mlpack_knn/mlpack_kfn both on Windows and *unix.
Update documentation which references 'allknn' or 'allkfn').
> Rename mlpack_allknn/mlpack_allkfn to mlpack_knn/mlpack_kfn

- CMakeLists.txt
Since mlpack_allkfn/mlpack_allknn have been renamed, no man pages will
be generated for them.
> Remove non-existent man page targets

- src/mlpack/core/kernels/epanechnikov_kernel.cpp
The misplaced parenthesis around the comparison of the absolute
values of bandwidth and distance could cause erronus results. In
addition, this caused a "-Wabsolute-value" warning:
src/mlpack/core/kernels/epanechnikov_kernel.cpp:41:14:
warning: taking the absolute value of unsigned type 'bool' has no effect [-Wabsolute-value]
} else if (std::abs(bandwidth > std::abs(distance)))
> BUG: Misplaced parenthesis in comparison of absolute values

- src/mlpack/methods/ann/activation_functions/logistic_function.hpp
`arma::Math<>` has been deprecated and instead have new `arma::Datum<>` with exactly same constants. So, changing the `arma::Math<eT>::log_max()` to `arma::Datum<eT>::log_max`.
> Deprecated arma function replaced by new arma constant

- src/mlpack/core/data/split_data.hpp
As the title said, std::make_tuple do not need to move, because the compiler will 
1 : directly construct the tuple when it can
2 : move the tuple if case 1 can not be done
move is good, but direct construct is even better, use std::move to move the tuple would forbid the compiler to do the optimization
> fix performance issue--forgot to move name parameters

- HISTORY.md
- src/mlpack/core/data/serialization_template_version.hpp
- src/mlpack/methods/lsh/lsh_search.hpp
- src/mlpack/methods/lsh/lsh_search_impl.hpp
- src/mlpack/prereqs.hpp
- src/mlpack/tests/serialization_test.cpp
I modified Train() to accept an extra argument, a std::vector of projection tables (arma::mat). If the size of the vector and the tables it contains is correct, Train retrains the algorithm to use the specified projection tables.
The user can also call setProjectionTables() which simply calls Train().
The user can also see the projection tables by calling getProjectionTables()
> Lsh table access

- src/mlpack/methods/lsh/lsh_search_impl.hpp
The current code allocates space equal to the reference set and then uses arma::find to identify non-zero indices which are returned as the candidate set. This results in large memory allocations and slows down candidate search.
My change loops over the hash tables twice, first counting the number of reference points in the same bucket as the query and then a second time to actually add candidates to the reference set. This provides a small performance bump which should get more significant for larger reference sets.
> LSH optimization: LSHSearch::ReturnIndicesFromTable uses less memory

- src/mlpack/core/arma_extend/CMakeLists.txt
- src/mlpack/core/arma_extend/arma_extend.hpp
- src/mlpack/core/arma_extend/fn_ind2sub.hpp
- src/mlpack/methods/CMakeLists.txt
- src/mlpack/methods/edge_boxes/CMakeLists.txt
- src/mlpack/methods/edge_boxes/edge_boxes_main.cpp
- src/mlpack/methods/edge_boxes/feature_extraction.hpp
- src/mlpack/methods/edge_boxes/feature_extraction_impl.hpp
- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/ind2sub_test.cpp
Feature extraction part of edge_boxes algorithm.
> edge_boxes: feature extraction

- src/mlpack/core/data/binarize.hpp
`#inlcude <omp.h>` seems to be not needed. and it breaks build on mac.
`size_t` is not supported in omp for windows.
> delete include omp statement

- src/mlpack/methods/lsh/lsh_main.cpp
- src/mlpack/methods/lsh/lsh_search.hpp
- src/mlpack/methods/lsh/lsh_search_impl.hpp
- src/mlpack/tests/lsh_test.cpp
This is a small change to add that function. I would have added it to the Multiprobe commit but though I should keep that one clean.
> Adds ComputeRecall function to LSHSearch for easier tuning

- src/mlpack/core/tree/rectangle_tree/dual_tree_traverser_impl.hpp
- src/mlpack/core/tree/rectangle_tree/hilbert_r_tree_auxiliary_information_impl.hpp
- src/mlpack/core/tree/rectangle_tree/hilbert_r_tree_split_impl.hpp
- src/mlpack/core/tree/rectangle_tree/r_star_tree_split_impl.hpp
- src/mlpack/core/tree/rectangle_tree/r_tree_split_impl.hpp
- src/mlpack/core/tree/rectangle_tree/rectangle_tree.hpp
- src/mlpack/core/tree/rectangle_tree/rectangle_tree_impl.hpp
- src/mlpack/core/tree/rectangle_tree/single_tree_traverser_impl.hpp
- src/mlpack/core/tree/rectangle_tree/x_tree_split_impl.hpp
- src/mlpack/tests/rectangle_tree_test.cpp
I removed the `RectangleTree::Points()` method. Unfortunately, we can not remove `RectangleTree::Children()` so easy since sometimes we have to modify the pointers. We can use friend classes instead i.e. use `tree.children[i]` instead of `tree.Children()[i]`.
> Removed RectangleTree::Points()

- src/mlpack/core/tree/rectangle_tree/discrete_hilbert_value_impl.hpp
- src/mlpack/core/tree/rectangle_tree/dual_tree_traverser_impl.hpp
- src/mlpack/core/tree/rectangle_tree/hilbert_r_tree_auxiliary_information_impl.hpp
- src/mlpack/core/tree/rectangle_tree/hilbert_r_tree_descent_heuristic_impl.hpp
- src/mlpack/core/tree/rectangle_tree/hilbert_r_tree_split_impl.hpp
- src/mlpack/core/tree/rectangle_tree/r_star_tree_descent_heuristic_impl.hpp
- src/mlpack/core/tree/rectangle_tree/r_star_tree_split_impl.hpp
- src/mlpack/core/tree/rectangle_tree/r_tree_descent_heuristic_impl.hpp
- src/mlpack/core/tree/rectangle_tree/r_tree_split_impl.hpp
- src/mlpack/core/tree/rectangle_tree/rectangle_tree.hpp
- src/mlpack/core/tree/rectangle_tree/rectangle_tree_impl.hpp
- src/mlpack/core/tree/rectangle_tree/single_tree_traverser_impl.hpp
- src/mlpack/core/tree/rectangle_tree/x_tree_split_impl.hpp
- src/mlpack/tests/rectangle_tree_test.cpp
I removed `RectangleTree::Children()`. Thus, `SplitType` and `AuxiliaryInformationType` become friend classes of the `RectangleTree` class.
Moreover, I made some RectangleTree::NumDescendants() optimizations proposed by Marcos Pividori.
> RectangleTree::NumDescendants() optimization and some RectangleTree fixes

- src/mlpack/methods/gmm/gmm_impl.hpp
The probabilities variable is not passed to the fitter when running multiple trials.
> Added missing function argument

- src/mlpack/core/tree/rectangle_tree/r_plus_tree_split_impl.hpp
- src/mlpack/core/tree/rectangle_tree/r_star_tree_split.hpp
- src/mlpack/core/tree/rectangle_tree/r_star_tree_split_impl.hpp
- src/mlpack/core/tree/rectangle_tree/x_tree_split.hpp
- src/mlpack/core/tree/rectangle_tree/x_tree_split_impl.hpp
- src/mlpack/methods/adaboost/adaboost_impl.hpp
- src/mlpack/methods/ann/layer/one_hot_layer.hpp
- src/mlpack/methods/ann/layer/vr_class_reward_layer.hpp
- src/mlpack/methods/perceptron/perceptron_impl.hpp
- src/mlpack/methods/radical/radical.cpp
I replaced `SortStruct` by `std::pair` in the R* tree and the X tree and fixed some compiler warnings about uninitialized variables. I did some tests, `std::pair` provides some speedups in `mlpack_knn` for the R* tree and the X tree.
> Replaced SortStruct by std::pair

- src/mlpack/core/tree/rectangle_tree.hpp
- src/mlpack/core/tree/rectangle_tree/r_plus_tree_split_impl.hpp
- src/mlpack/core/tree/rectangle_tree/traits.hpp
- src/mlpack/tests/rectangle_tree_test.cpp
If we are going to split an overflowed node we have to ensure that the resulting nodes have the desired capacity.
The R+/R++ tree has non-overlapping children, so we should fix the traits.
> Fixed a segfault in RPlusTreeSplit. Fixed traits for the R+/R++ tree.

- src/mlpack/core/tree/binary_space_tree/traits.hpp
I update TreeTraits for Ball Trees, to set HasOverlappingChildren = true.
It shouldn't make any difference in current implementation because HasOverlappingChildren is not used in any method.
I thought it could be useful in the future. :)
> Fix TreeTrait for BallTree.

- doc/tutorials/kmeans/kmeans.txt
Changed vector classes of 'assignments' to comply with the corresponding method calls.
Fixes compile errors for those samples.
> Fixing vector classes to comply with method calls.

- CMake/mlpack_coverage.in
- CMakeLists.txt
- src/mlpack/CMakeLists.txt
Added mlpack_coverage script to generate report by running tests (run 'mlpack_coverage --help' for options)
mlpack_coverage script can upload the results to coveralls
Header file functions are successfully added with -fkeep-inline-functions
Added functionality to cpp-coveralls script to upload the locally generated lcov report
> Added test coverage framework

- src/mlpack/core/boost_backport/boost_backport.hpp
I think that was the mistake in the previous PR.
Sorry!
> Fixes off-by-one in boost_backport.hpp for boost 1.55.0

- src/mlpack/core/tree/binary_space_tree/midpoint_split_impl.hpp
I tried to compare the vantage point tree with `BallTree` and came across a segfault.
Since `BallBound[d].Mid()` is equal to the center, one child may be empty. In this case the following loop may lead to a segfault (if `right = 0` then `right-1 = SIZE_MAX`)
```
while ((data(splitDimension, right) >= splitVal) && (left <= right))
right--;
```
> Fixed an error in MidpointSplit that may lead to a segfault

- src/mlpack/core/dists/gamma_distribution.cpp
- src/mlpack/core/dists/gamma_distribution.hpp
- src/mlpack/tests/distribution_test.cpp
Instead of using the dataset itself, this Train() function only needs the dataset statistics. This function works for 1-dimensional distributions only (you can only provide 1 number for each statistic).
This is useful for my code in LSHModel, where instead of using data to fit the distribution, we create a regression function that can predict the arithmetic and geometric mean of squared distances given the size of the dataset. Since we don't have the actual distances - we only have an estimation of the distances' statistics - we can't use the previous Train() function in GammaDistribution.
I modified my code so that the Train() that accepts the dataset simply calls this function for each row after computing the statistics, to avoid code reuse.
I also added a test to make sure this …
> Adds a Train() function that only needs dataset statistics

- src/mlpack/core/dists/gamma_distribution.cpp
- src/mlpack/core/dists/gamma_distribution.hpp
- src/mlpack/tests/distribution_test.cpp
While implementing LSHModel I realized I would need the `GammaDistribution::Probability(x)` function. I remembered I mentioned in https://github.com/mlpack/mlpack/issues/733 I said I'd do it at some point, so I completed it now.
I also added a `Probability(x, dimension)`, for evaluating a single dimension at a time. This is useful for my implementation, and might prove useful to others since the gammas are completely independent here.
There's only one thing that bugs me: I'm not sure how to test the `Train(observations, probability)` function, so I haven't written a test for that yet.
> GammaDistribution: Adds functionality to solve #733

- src/mlpack/methods/neighbor_search/sort_policies/furthest_neighbor_sort.hpp
@rcurtin 
Was this change https://github.com/mlpack/mlpack/commit/b067ee4bb6cff16be8efb1ad4923052bc12a13c5#diff-1aaf3b3b22ad7dee835d64635b303703L155
intensional? 
It breaks some tests in my computer...
> Fix furthest neighbor sort policy.

- src/mlpack/core/tree/rectangle_tree/discrete_hilbert_value.hpp
- src/mlpack/core/tree/rectangle_tree/discrete_hilbert_value_impl.hpp
- src/mlpack/core/tree/rectangle_tree/hilbert_r_tree_auxiliary_information.hpp
- src/mlpack/core/tree/rectangle_tree/hilbert_r_tree_auxiliary_information_impl.hpp
- src/mlpack/core/tree/rectangle_tree/hilbert_r_tree_split_impl.hpp
- src/mlpack/core/tree/rectangle_tree/no_auxiliary_information.hpp
- src/mlpack/core/tree/rectangle_tree/r_plus_plus_tree_auxiliary_information.hpp
- src/mlpack/core/tree/rectangle_tree/r_plus_plus_tree_auxiliary_information_impl.hpp
- src/mlpack/core/tree/rectangle_tree/rectangle_tree.hpp
- src/mlpack/core/tree/rectangle_tree/rectangle_tree_impl.hpp
- src/mlpack/core/tree/rectangle_tree/x_tree_auxiliary_information.hpp
- src/mlpack/tests/rectangle_tree_test.cpp
I've fixed the copy constructor of `RectangleTree` and implemented move constructor for PR #765 .
> Fixed copy constructor of RectangleTree and added move constructor.

- src/mlpack/core.hpp
- src/mlpack/core/tree/binary_space_tree/binary_space_tree_impl.hpp
- src/mlpack/core/tree/binary_space_tree/traits.hpp
- src/mlpack/core/tree/cover_tree/cover_tree.hpp
- src/mlpack/core/tree/cover_tree/cover_tree_impl.hpp
- src/mlpack/core/tree/cover_tree/traits.hpp
- src/mlpack/core/tree/rectangle_tree/traits.hpp
- src/mlpack/core/tree/tree_traits.hpp
- src/mlpack/core/util/CMakeLists.txt
- src/mlpack/core/util/deprecated.hpp
- src/mlpack/methods/kmeans/dual_tree_kmeans_impl.hpp
- src/mlpack/methods/neighbor_search/neighbor_search.hpp
- src/mlpack/methods/neighbor_search/neighbor_search_impl.hpp
- src/mlpack/methods/neighbor_search/ns_model_impl.hpp
- src/mlpack/tests/akfn_test.cpp
- src/mlpack/tests/aknn_test.cpp
- src/mlpack/tests/kfn_test.cpp
- src/mlpack/tests/knn_test.cpp
- src/mlpack/tests/rectangle_tree_test.cpp
@rcurtin 
I moved into a new branch, and I didn't realize this would close the PR. The previous PR was https://github.com/mlpack/mlpack/pull/743.
At this point everything is ready to merge. The only problem is that many warnings are shown when compiling because many methods use the deprecated constructors, passing a pointer to the reference tree.
It would take some time to update all that parts of the code.
Thanks
> Use move semantics to set a given reference tree in NeighborSearch class.

- COPYRIGHT.txt
- src/mlpack/core.hpp
- src/mlpack/core/tree/binary_space_tree/binary_space_tree.hpp
- src/mlpack/core/tree/binary_space_tree/binary_space_tree_impl.hpp
- src/mlpack/core/tree/cover_tree/cover_tree.hpp
- src/mlpack/core/tree/cover_tree/cover_tree_impl.hpp
- src/mlpack/core/tree/rectangle_tree/rectangle_tree.hpp
- src/mlpack/core/tree/rectangle_tree/rectangle_tree_impl.hpp
- src/mlpack/core/tree/spill_tree/spill_tree.hpp
- src/mlpack/methods/emst/dtb_rules_impl.hpp
- src/mlpack/methods/kmeans/dual_tree_kmeans_rules_impl.hpp
- src/mlpack/methods/neighbor_search/sort_policies/furthest_neighbor_sort_impl.hpp
- src/mlpack/methods/neighbor_search/sort_policies/nearest_neighbor_sort_impl.hpp
- src/mlpack/methods/range_search/range_search_rules_impl.hpp
Changed functions in the Tree Type API to use references. Refactored all relevant files.
Functions changed:
```
ElemType MinDistance(const TreeType* other);
ElemType MaxDistance(const TreeType* other);
math::RangeType<ElemType> RangeDistance(const TreeType* other);
```
> issue #787 - Replace `MinDistance(TreeType*)` with `MinDistance(TreeType&)`

- src/mlpack/core/data/imputer.hpp
- src/mlpack/core/data/map_policies/missing_policy.hpp
- src/mlpack/methods/preprocess/preprocess_imputer_main.cpp
- src/mlpack/tests/imputation_test.cpp
added an overload that applies imputation to all "dirty" dimensions.
All dimensions that have more than 0 NumMappings are applied.
> improve the imputer program

- src/mlpack/core/util/CMakeLists.txt
- src/mlpack/core/util/cli.cpp
- src/mlpack/core/util/cli_deleter.hpp
- src/mlpack/core/util/log.cpp
- src/mlpack/core/util/singletons.cpp
- src/mlpack/core/util/singletons.hpp
This is a solution for #524.  It actually functions about the same as that solution but creates a separate file for singletons (`src/mlpack/core/singletons.cpp`).  As a result of this change it is possible to create a program that has `#include <mlpack/core.hpp>` without linking against libmlpack.so, if no mlpack symbols are used.  This was not possible before.
I'll leave this for a couple of days before I merge it.
@theSundayProgrammer: I know this took a very long time for me to get around to, but here is (finally) a solution.  Like I said it is essentially equivalent to yours, just arranged differently.
> Put all singletons in libmlpack.so

- src/mlpack/methods/neighbor_search/kfn_main.cpp
- src/mlpack/methods/neighbor_search/knn_main.cpp
- src/mlpack/methods/neighbor_search/neighbor_search.hpp
- src/mlpack/methods/neighbor_search/neighbor_search_impl.hpp
- src/mlpack/methods/neighbor_search/ns_model.hpp
- src/mlpack/methods/neighbor_search/ns_model_impl.hpp
- src/mlpack/tests/knn_test.cpp
- src/mlpack/tests/serialization_test.cpp
@rcurtin 
This PR removes the reverse compatibility code inside `NeighborSearch` class.
This is intended to be merged for version 3.0.0.
The only difference with the PR https://github.com/mlpack/mlpack/pull/762  is the last commit.
I will rebase on top of master when https://github.com/mlpack/mlpack/pull/762 is merged, so it will be clearer.
Thanks!
Marcos
> Search mode 3.0.0

- src/mlpack/core/util/prefixedoutstream_impl.hpp
so I looked into why R was complaining that `std::cout` was referenced when linking against mlpack -- and it turns out that the (sole !!) remaining use of `std::cout` appears to be an instance that ought to have been converted to `destination`
this PR does that
no Travis build on my side; I just used to have a clone rather than fork and did not have Travis set up to build when I just committed this but it should work out just fine
> switch last (!) remaining std::cout to destination

- COPYRIGHT.txt
- src/mlpack/core.hpp
- src/mlpack/core/util/prefixedoutstream_impl.hpp
- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/cli_test.cpp
- src/mlpack/tests/prefixedoutstream_test.cpp
- src/mlpack/tests/timer_test.cpp
Changes /src/mlpack/core/util/prefixedoutstream_impl.hpp
> Fixes #755 Log compatibility with std::fixed and std::setprecision

- src/mlpack/methods/hmm/hmm_impl.hpp
- src/mlpack/methods/hmm/hmm_train_main.cpp
- src/mlpack/tests/hmm_test.cpp
That can cause training to fail sometimes.  Instead, optimization seems to perform better when using random intiialization.
This is a fix that came out of some debugging in the IRC channel.
> HMM initialization: don't use equal initial probabilities.

- COPYRIGHT.txt
- src/mlpack/core.hpp
- src/mlpack/core/dists/gamma_distribution.cpp
- src/mlpack/core/dists/gamma_distribution.hpp
- src/mlpack/tests/distribution_test.cpp
> adds GammaDistribution::Train(observations, probabilities)

- src/mlpack/methods/naive_bayes/nbc_main.cpp
It's a pretty trivial fix, but something I came across this week.
There seems to be a bit more around it -- some references to 'matrix' when the input at this level (ie `main()`) -- really is a file.  I can poke some more if you want.
> minor documentation update

- src/mlpack/core.hpp
- src/mlpack/core/optimizers/adam/adam.hpp
- src/mlpack/core/optimizers/adam/adam_impl.hpp
- src/mlpack/tests/adam_test.cpp
`SimpleAdaMaxTestFunction` test is currently failing with values of `coordinates` vector as `[-nan; -45.59; -nan]` after optimization. For our context, the original values were `[6; -45.6; 6.2]` to begin with.
So as it appears, Optimize function is reducing positive values to `-nan` which might be the case due to `0 / 0` (I'm suspecting somewhere during the iterations atleast one of the elements of `u` and `m` at the same index become zero) and minimal change seen on negative values.
> Implementation of AdaMax optimizer.

- src/mlpack/core/util/backtrace.cpp
- src/mlpack/core/util/cli.hpp
- src/mlpack/core/util/prefixedoutstream.cpp
- src/mlpack/core/util/prefixedoutstream.hpp
- src/mlpack/core/util/prefixedoutstream_impl.hpp
- src/mlpack/core/util/singletons.cpp
- src/mlpack/core/util/singletons.hpp
- src/mlpack/tests/mlpack_test.cpp
- src/mlpack/tests/prefixedoutstream_test.cpp
Relevant issue : #755 
A few issues : 
* After the user sets up custom flags, `arma` objects are printed with the set precision, but the stream does not align matrix elements.
* During build, a `pragma` message appears
> In file included from /home/shikhar/Documents/dev/mlpack-fork/src/mlpack/../mlpack/core.hpp:217:0,
from /home/shikhar/Documents/dev/mlpack-fork/src/mlpack/tests/test_tools.hpp:15,
from /home/shikhar/Documents/dev/mlpack-fork/src/mlpack/tests/mlpack_test.cpp:25:
/home/shikhar/Documents/dev/mlpack-fork/src/mlpack/../mlpack/prereqs.hpp:20:17: note: #pragma message: Armadillo was included before mlpack; this can sometimes cause prob
lems.  It should only be necessary to include <mlpack/core.hpp> and not <armadillo>.
#pragma message "Armadillo was included before mlpack; this …
> Fix support for printing arma objects with custom precision 

- src/mlpack/tests/load_save_test.cpp
The file load_save_test.cpp generate warnings that were not suppressed when using mlpack_test to run unit tests. A guard has been added for all test invocations, that sets Log::Warn.ignoreInput to true temporarily while tests are run, and resets to its earlier value. 
The earlier setting set Log::Warn.ignoreInput to false at the end of a test, this caused subsequent files to pick up this flag and output warnings.
> Suppressing Warning from unit test

- src/mlpack/core/util/prefixedoutstream_impl.hpp
Changes `prefixedoustream_impl.hpp`
> Avoid use of internal Armadillo structures in prefixedoustream_impl.hpp

- src/mlpack/tests/gmm_test.cpp
- src/mlpack/tests/test_tools.hpp
Fixes #932.
I have changed the interface of `CheckMatrices` in test_tools.hpp to take tolerance values, with a default parameter to avoid changing existing code.
> Fix GMMTest comparisions

- COPYRIGHT.txt
- src/mlpack/core.hpp
- src/mlpack/methods/softmax_regression/softmax_regression.hpp
- src/mlpack/methods/softmax_regression/softmax_regression_impl.hpp
- src/mlpack/tests/softmax_regression_test.cpp
Added a few overloads to Classify method is softmax regression and the tests for them, so that Softmax and Logistic regression have a uniform interface
Noticed two failed tests. Unable to verify if these are due to anything that I have changed
`load_save_test.cpp(683): fatal error: in "LoadSaveTest/LoadHDF5Test": critical check test.n_rows == 4 has failed [2 != 4]`
`nmf_test.cpp(95): fatal error: in "NMFTest/NMFRandomDivTest": absolute value of arma::norm(v - wh, "fro") / arma::norm(v, "fro"){0.071824514847599066} exceeds 0.014999999999999999`
Please verify and comment on any changes to be made
Thank you
> Uniform interface for Softmax and Logistic Regression

- src/mlpack/methods/adaboost/adaboost_impl.hpp
A fix for issue in #821. The problem was that for the given training set, ```rt``` value was a very small value greater than ```1``` which caused the calculation of log of a negative value. Hence the additional check of the value of ```rt```. If the value of ```rt = 1``` then the denominator in the calculation of ```alphat``` is zero. ```DBL_MAX``` is introduced to avoid calculating log of ```inf```.
After this change
- The reported crash is fixed. 
- The adaboost algorithm now converges in one iteration on the given dataset. 
- The problem with serializing and deserializing ```nan``` is behind the curtains. I'll look into it next.
> Adaboost error fix

- src/mlpack/methods/ann/layer/add_merge_impl.hpp
Hey,
While going through the NN layers code, came across this small typo, which is harmless. But just for mlpack's sake!
> #include "add_merge.hpp" instead of #include "add_merge_impl.hpp" in add_merge_impl.hpp

- src/mlpack/methods/ann/ffn.hpp
This is a small pull request that restores balance to the universe by changing '_infomration_' to '_information_'. 
Thanks Marcus for sharing that tweet! :)
> Correct minor typo in ffn.hpp

- src/mlpack/tests/convolutional_network_test.cpp
CNN used to get stuck in local minima and couldn't converge in the given number of iterations. #922
* Since the network is performing only binary classification task of recognizing 4 and 9, so number of output units in the CNN network has been updated to 2. This reduces the number of parameters in the network, hence avoiding wrong classification due to weights which could not be trained in the given number of iterations.
* Reduced number of units in full connected layers to reduce number of trainable parameters. 
* Reduced learning rate of optimizer to converge easily in given number of iterations. 
* Removed loop which performs the same test five times, hence reducing the testing time. 
* Renamed `error` variable as `correct` for more clarity because it counts the number of correct …
> Fix VanillaNetworkTest

- src/mlpack/methods/CMakeLists.txt
- src/mlpack/methods/block_krylov_svd/CMakeLists.txt
- src/mlpack/methods/block_krylov_svd/randomized_block_krylov_svd.cpp
- src/mlpack/methods/block_krylov_svd/randomized_block_krylov_svd.hpp
- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/block_krylov_svd_test.cpp
Implementation of the randomized block krylov svd method from the "Randomized Block Krylov Methods for Stronger and Faster Approximate Singular Value Decomposition" paper.
Turns out the randomized svd method causes some instabilities when used for the edges boxes method  since the exact svd method takes way to much time the randomized block krylov svd method is a good alternative. Note the method gives more accurate results for fewer iterations but is slower per iteration than the randomized svd method. Here are some runtime timings for different datasets.
```
data size: 10x10
----------------------------
svd: 0.399944 ms
econ: 0.212553 ms -- error: 0
krylov: 0.675249 ms -- error: 3.84883e-16
randomized: 0.740294 ms -- error: 1.73457e-08
data size: 100x100
---------------------------- …
```
> Randomized Block Krylov Method.

- src/mlpack/methods/hoeffding_trees/hoeffding_tree_model.cpp
Potential null dereferences of other.giniHoeffdingTree, other.giniBinaryTree, other.infoHoeffdingTree, other.infoBinaryTree on lines 72, 74, 76, and 78 respectively.  CodeAi fixes these issues by tightening the if condition to verify that each pointer variable is not null before use in the constructor.  
See the bug reports below for more information:
[CodeAiBugReport_mlpack_src_mlpack_methods_hoeffding_trees_hoeffding_tree_model_cpp_78.pdf](https://github.com/mlpack/mlpack/files/917104/CodeAiBugReport_mlpack_src_mlpack_methods_hoeffding_trees_hoeffding_tree_model_cpp_78.pdf)
[CodeAiBugReport_mlpack_src_mlpack_methods_hoeffding_trees_hoeffding_tree_model_cpp_76.pdf](https://github.com/mlpack/mlpack/files/917101/CodeAiBugReport_mlpack_src_mlpack_methods_hoeffding_trees_hoeffding_tree_model_ …
> CodeAi fixed 4 null pointer dereferences in hoeffding_tree_model.cpp

- COPYRIGHT.txt
- src/mlpack/core.hpp
- src/mlpack/core/tree/cover_tree/cover_tree_impl.hpp
- src/mlpack/core/tree/rectangle_tree/r_plus_tree_split_impl.hpp
- src/mlpack/core/tree/spill_tree/spill_tree_impl.hpp
- src/mlpack/core/util/cli.cpp
- src/mlpack/core/util/cli.hpp
- src/mlpack/core/util/output_param_impl.hpp
- src/mlpack/core/util/singletons.cpp
- src/mlpack/methods/adaboost/adaboost_model.cpp
- src/mlpack/methods/adaboost/adaboost_model.hpp
- src/mlpack/methods/cf/cf.cpp
- src/mlpack/methods/fastmks/fastmks.hpp
- src/mlpack/methods/hoeffding_trees/hoeffding_tree_model.cpp
- src/mlpack/methods/lsh/lsh_search.hpp
- src/mlpack/methods/neighbor_search/neighbor_search_rules.hpp
- src/mlpack/methods/rann/ra_search_rules.hpp
- src/mlpack/prereqs.hpp
- src/mlpack/tests/serialization.hpp
- src/mlpack/tests/test_tools.hpp
Change some includes to reduce compilation time. 
PR for issue #722
* Remove #include \<queue\> and \<iostream\> from prereqs.hpp. Add includes in files that need them. 
* Use AdaBoost forward declaration in adaboost_model
* Move some includes from header to cpp file in util/cli.cpp
* Remove unnecessary includes in some other files
> Reduce compilation time - PR for #722

- src/mlpack/methods/ann/init_rules/gaussian_init.hpp
Please find more discussions about this [here](https://github.com/mlpack/mlpack/pull/934).
Briefly speaking, it seems the init function goes wrong when the desired mat has pre-allocated memory. But I don't know why.
> Fix a bug in gaussian init

- src/mlpack/methods/reinforcement_learning/environment/cart_pole.hpp
- src/mlpack/methods/reinforcement_learning/environment/mountain_car.hpp
- src/mlpack/methods/reinforcement_learning/replay/CMakeLists.txt
- src/mlpack/methods/reinforcement_learning/replay/random_replay.hpp
- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/rl_components_test.cpp
Random replay with a simple unit test
> Add random replay for DQN

- src/mlpack/methods/reinforcement_learning/policy/CMakeLists.txt
- src/mlpack/methods/reinforcement_learning/policy/greedy_policy.hpp
- src/mlpack/tests/rl_components_test.cpp
Add epsilon greedy policy and a simple test case.
> Add epsilon greedy policy for DQN

- src/mlpack/core/optimizers/ada_delta/ada_delta.hpp
- src/mlpack/core/optimizers/ada_grad/ada_grad.hpp
- src/mlpack/core/optimizers/adam/adam.hpp
- src/mlpack/core/optimizers/gradient_descent/gradient_descent.hpp
- src/mlpack/core/optimizers/gradient_descent/gradient_descent_impl.hpp
- src/mlpack/core/optimizers/minibatch_sgd/minibatch_sgd.hpp
- src/mlpack/core/optimizers/minibatch_sgd/minibatch_sgd_impl.hpp
- src/mlpack/core/optimizers/rmsprop/rmsprop.hpp
- src/mlpack/core/optimizers/sgd/sgd.hpp
- src/mlpack/core/optimizers/sgd/sgd_impl.hpp
- src/mlpack/core/optimizers/smorms3/smorms3.hpp
- src/mlpack/methods/regularized_svd/regularized_svd_function.cpp
- src/mlpack/methods/regularized_svd/regularized_svd_function.hpp
As discussed here https://github.com/mlpack/mlpack/pull/1014, I added some new APIs for some optimizers.(`ada_delta`, `ada_grad`, `adam`, `gradient_descent`, `minibatch_sgd`, `rmsprop`, `sgd`, `smorms3`) I just added the new API as @zoq suggested and didn't delete the old one. So even this PR is merged, all the optimizers will still have consistent API to some extent. We need to continue refactoring all the optimizers and finally delete the old API. Maybe @rcurtin , @micyril and I can work on this together in the future. But I think now it's necessary to merge this PR so I can go further in the DQN PR and async RL methods.
> Add new API for some optimizers

- src/mlpack/core/cv/CMakeLists.txt
- src/mlpack/core/cv/meta_info_extractor.hpp
- src/mlpack/core/util/sfinae_utility.hpp
- src/mlpack/tests/cv_test.cpp
- src/mlpack/tests/sfinae_test.cpp
Add a tool for extracting meta information about machine learning algorithms.
> Extracting meta information

- src/mlpack/tests/serialization.hpp
- src/mlpack/tests/test_tools.hpp
Fix for #1052 
`FilterFileName()` does not handle the corner case of `inputString` being empty, but I think it should be fine here.
> Use unique filenames in Serialization tests

- src/mlpack/methods/naive_bayes/naive_bayes_classifier.hpp
- src/mlpack/methods/naive_bayes/naive_bayes_classifier_impl.hpp
This is an alternate solution to #1051.  It actually allows more flexibility---now I can pass in subviews, etc. to `NaiveBayesClassifier::Train()`, and I can still use `NaiveBayesClassifier` with non-double types (i.e. `NaiveBayesClassifier<float>`.  Since all overloads of `Train()` are templatized, this should satisfy the conditions needed for the hyper-parameter tuner.
@micyril: what do you think?  Is this an acceptable alternate approach?
> Refactor NaiveBayesClassifier to have templated Train() functions.

- src/mlpack/core/optimizers/parallel_sgd/parallel_sgd_impl.hpp
- src/mlpack/methods/regularized_svd/regularized_svd_function_impl.hpp
- src/mlpack/tests/parallel_sgd_test.cpp
- src/mlpack/tests/regularized_svd_test.cpp
I was thinking how we could easily prevent such an issue, and I think we could configure travis to build with and without OpenMP support. I think using jenkins to test regular PR's might also be an option.
> Use omp_get_thread_num and omp_set_num_threads only if OpenMP supported.

- src/mlpack/bindings/cli/parameter_type.hpp
- src/mlpack/core/CMakeLists.txt
- src/mlpack/core/data/dataset_mapper.hpp
- src/mlpack/core/data/dataset_mapper_impl.hpp
- src/mlpack/core/data/map_policies/increment_policy.hpp
- src/mlpack/core/hpt/CMakeLists.txt
- src/mlpack/core/hpt/bind.hpp
- src/mlpack/core/hpt/cv_function.hpp
- src/mlpack/core/hpt/cv_function_impl.hpp
- src/mlpack/core/hpt/deduce_hp_types.hpp
- src/mlpack/core/hpt/fixed.hpp
- src/mlpack/core/hpt/hpt.hpp
- src/mlpack/core/hpt/hpt_impl.hpp
- src/mlpack/core/optimizers/CMakeLists.txt
- src/mlpack/core/optimizers/gradient_descent/gradient_descent.hpp
- src/mlpack/core/optimizers/gradient_descent/gradient_descent_impl.hpp
- src/mlpack/core/optimizers/grid_search/CMakeLists.txt
- src/mlpack/core/optimizers/grid_search/grid_search.hpp
- src/mlpack/core/optimizers/grid_search/grid_search_impl.hpp
- src/mlpack/core/util/param.hpp
- src/mlpack/core/util/param_data.hpp
- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/hpt_test.cpp
- src/mlpack/tests/imputation_test.cpp
See the previous discussion [here](https://github.com/micyril/mlpack/pull/2).
> Add a hyper-parameter tuning module

- CONTRIBUTING.md
This adds a simple `CONTRIBUTING.md` that lays out a policy for how to merge PRs.  Since we have grown in size over the years, having some kind of framework for this should be helpful in making PRs get merged faster.
> Add guidelines and process for contributing.

- src/mlpack/bindings/cli/end_program.hpp
- src/mlpack/bindings/python/mlpack/cli.pxd
- src/mlpack/bindings/python/mlpack/cli_util.hpp
- src/mlpack/bindings/python/print_pyx.cpp
- src/mlpack/core/util/cli.cpp
- src/mlpack/core/util/cli.hpp
- src/mlpack/core/util/mlpack_main.hpp
- src/mlpack/core/util/timers.cpp
- src/mlpack/core/util/timers.hpp
- src/mlpack/tests/timer_test.cpp
This should fix #1133.  @sgiurgiu: you can try this branch and see if it fixes your problem.  I wrote a simple test to imitate your bug report.
Since `std::this_thread::get_id()` is guaranteed to produce a different result for every thread, I simply made the `Timers` class hold a set of timers for each possible thread, then when the result is printed, each timer across all threads is summed up.  So in the code in #1133, if you printed the value of the timers at the end of the program, it would be the sum of all softmax regression trainings.
> Make timers threadsafe by holding one timer for each thread.

- src/mlpack/core/util/cli.cpp
- src/mlpack/core/util/mlpack_main.hpp
Add a ``total_time`` timer that is added by default for each mlpack program.
> Reinclude 'total_time' timer.

- src/mlpack/core/optimizers/sgd/sgd_impl.hpp
- src/mlpack/core/optimizers/spalera_sgd/spalera_sgd_impl.hpp
- src/mlpack/methods/ann/layer/fast_lstm_impl.hpp
- src/mlpack/methods/ann/layer/gru_impl.hpp
- src/mlpack/methods/ann/layer/lstm_impl.hpp
- src/mlpack/methods/ann/rnn.hpp
- src/mlpack/methods/ann/rnn_impl.hpp
- src/mlpack/tests/recurrent_network_test.cpp
I tried to build an LSTM network with batch size > 1, but there were some Armadillo shape errors.  I believe this code fixes that; however, the tests do not work right now.  I need to redesign the tests...
> Fix recurrent layers' compatibility with batch sizes > 1.

- CMakeLists.txt
CMake was including the line wrap.  Thanks to @extrowerk for pointing this one out. :)
> Avoid line wrap which made invalid .pc files.

- src/mlpack/core/tree/cosine_tree/cosine_tree.cpp
- src/mlpack/methods/pca/pca_main.cpp
- src/mlpack/tests/cne_test.cpp
- src/mlpack/tests/frankwolfe_test.cpp
- src/mlpack/tests/momentum_sgd_test.cpp
- src/mlpack/tests/pca_test.cpp
- src/mlpack/tests/quic_svd_test.cpp
- src/mlpack/tests/random_forest_test.cpp
- src/mlpack/tests/recurrent_network_test.cpp
- src/mlpack/tests/spalera_sgd_test.cpp
- src/mlpack/tests/svd_batch_test.cpp
I took a look at the nightly matrix build on masterblaster and took a note of all the tests that failed.  Then for each of them I went through and diagnosed whether the failure was random or if it was some other issue.  In every case except one (`regularizedOMP`) the tolerances of the test just needed to be adjusted to account for the random failures.
This is related to #922.
> Fix randomly failing tests

- src/mlpack/core/tree/octree/octree.hpp
- src/mlpack/core/tree/octree/octree_impl.hpp
The issue is a result of a Windows build session, not sure why clang/gcc is able to build this code without any complaints on Linux/mac OS.
> Octree: adjust SplitType/TypeInfo structure

- COPYRIGHT.txt
- src/mlpack/core.hpp
- src/mlpack/core/util/CMakeLists.txt
- src/mlpack/core/util/test_helper.hpp
- src/mlpack/methods/linear_regression/linear_regression_main.cpp
- src/mlpack/prereqs.hpp
- src/mlpack/tests/linear_regression_test.cpp
- src/mlpack/tests/main_tests/linear_regression_test.cpp
- src/mlpack/tests/main_tests/pca_test.cpp
This PR contains tests for LinearRegression bindings as well as some fixes of binding itself. Aside from `main_tests/linear_regression_test.cpp` the following changes were made 
In `linear_regression_main.cpp`:
- output_predictions became `PARAM_ROW_OUT` (it was `PARAM_COL_OUT` and **never worked** because `LinearRegression` class outputs `rowvec predictions`). **Please confirm if this is correct and there is no need to use a transformation from row to column instead**.
- `std::move` trained model to `output_model` was moved to the end, after prediction proceudre. Earlier we tried to predict responses with using moved away model (and got an error)
- Lambda parameter was never used. Fixed that.
- Added error message if we trying to extract responses from a training data that consist only …
> LinearRegression binding fixes and tests

- src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp
hoeffding_tree didn't support using last column of dataset as labels. This PR makes label parameter optional and accepts last column of dataset as labels if it is not provided explicitly.
> making label parameter optional

- src/mlpack/core/optimizers/fw/constr_lpball.hpp
- src/mlpack/methods/approx_kfn/drusilla_select_impl.hpp
- src/mlpack/methods/naive_bayes/naive_bayes_classifier_impl.hpp
- src/mlpack/methods/perceptron/perceptron_impl.hpp
- src/mlpack/tests/binarize_test.cpp
- src/mlpack/tests/main_tests/softmax_regression_test.cpp
While building mlpack I encountered some warning messages corresponding to "uninitialised variables and unused variables". Hence I tried to remove them.
> removed some warning messages

- .appveyor.yml
- CMakeLists.txt
> Have AppVeyor run the tests too

- src/mlpack/core/util/sfinae_utility.hpp
- src/mlpack/methods/amf/update_rules/svd_complete_incremental_learning.hpp
- src/mlpack/methods/amf/update_rules/svd_incomplete_incremental_learning.hpp
- src/mlpack/methods/gmm/em_fit_impl.hpp
- src/mlpack/methods/lsh/lsh_main.cpp
- src/mlpack/methods/reinforcement_learning/training_config.hpp
- src/mlpack/tests/arma_extend_test.cpp
- src/mlpack/tests/main_tests/decision_tree_test.cpp
- src/mlpack/tests/serialization.hpp
Right now the docker matrix build fails for boost 1.66:
http://masterblaster.mlpack.org/job/docker%20mlpack%20nightly%20build/armadillo_version=armadillo-7.100.3,boost_version=boost_1_66_0,buildmode=debug,compiler_version=gcc-7.2.0,label=linux-amd64/
I spent way too long digging into it, and this is the fix I came up with.  Basically we just need to ensure the ifstream/ofstream doesn't close before the archive is destructed.  Also I fixed a few warnings.
> Boost serialization 1.66 fix

- doc/tutorials/optimizer/optimizer.txt
- doc/tutorials/tutorials.txt
This is basically a striped-down version of "A generic and fast C++ optimization framework".
> Optimizer tutorial

- src/mlpack/core/tree/greedy_single_tree_traverser.hpp
- src/mlpack/core/tree/greedy_single_tree_traverser_impl.hpp
- src/mlpack/methods/neighbor_search/neighbor_search_impl.hpp
- src/mlpack/tests/knn_test.cpp
Fix for #1222 
Traverser traverse through greedy technique till more than `k` points are available and after that base case is taken over all the descendant points.
In order to access `k` value  through greedy, a private member `k` has been declared which is default set to 0 and hence do not interfere with the generality of traverser.For trees like kd-tree, ball tree which stores points in leaf nodes `k` can be set using `K()`.
> Greedy Traverser Fix for KNN

- src/mlpack/core/boost_backport/CMakeLists.txt
- src/mlpack/core/boost_backport/boost_backport_serialization.hpp
- src/mlpack/core/boost_backport/collections_load_imp.hpp
- src/mlpack/core/boost_backport/collections_save_imp.hpp
- src/mlpack/core/boost_backport/vector.hpp
- src/mlpack/prereqs.hpp
**TL,DR**: This PR backports `boost/serialization/vector.hpp` for boost 1.58 (and earlier) because of various failing tests related to different serialization behaviors in v1.58 and later versions.
In boost v1.58 when objects of type `std::vector<arma::mat>` are loaded, the vector gets appended to rather than being cleared and rewritten. See [this](https://stackoverflow.com/questions/34042933/boost-vector-serialization-append-issue) question on SO to understand the issue. As a result of this, several tests (`PerceptronSerializationTest`, `DecisionStumpSerializationTest`, `GMMLoadSaveTest` etc) failed while running mlpack_test with boost 1.58. Another problem that this behavior of v1.58 created (which I pointed out on IRC - [link](http://mlpack.org/irc/mlpack.20180207.html)) was that …
> Fix serialization issue for boost v1.58

- src/mlpack/methods/amf/termination_policies/simple_residue_termination.hpp
In SimpleResidueTermination, there should be no limit on the number of iterations if maxIterations == 0:
https://github.com/mlpack/mlpack/blob/617a2acb52617e98f681a34137a7381e7c017db2/src/mlpack/methods/amf/termination_policies/simple_residue_termination.hpp#L31-L45
But the IsConverged() function ignores this in its return statement:
https://github.com/mlpack/mlpack/blob/617a2acb52617e98f681a34137a7381e7c017db2/src/mlpack/methods/amf/termination_policies/simple_residue_termination.hpp#L68-L86
which leads to nmf's immediate termination:
```
➜  build git:(master) mlpack_nmf --input_file test_data_3_1000.csv --rank 2 --verbose --max_iterations 0
[WARN ] Should pass either '--h_file (-H)' or '--w_file (-W)' or both; no output will be saved!
[INFO ] Loading 'test_data_3_1000.csv' as CSV data. …
```
> fix maxIterations=0 bug in SimpleResidueTermination

- .travis.yml
This commit does a switch back to the Trusty image, since the Xenial image is unstable.
> Switch back to the Trusty image

- COPYRIGHT.txt
- doc/tutorials/kmeans/kmeans.txt
- src/mlpack/core.hpp
- src/mlpack/methods/kmeans/kill_empty_clusters.hpp
- src/mlpack/methods/kmeans/kmeans.hpp
- src/mlpack/methods/kmeans/kmeans_impl.hpp
- src/mlpack/tests/kmeans_test.cpp
Fixes #1232 
While clustering instead of filling empty clusters with `DBL_MAX` empty clusters are entirely removed.
> Removing empty clusters instead of killing them.

- src/mlpack/core/optimizers/sdp/lrsdp_function.hpp
- src/mlpack/core/optimizers/sdp/lrsdp_function_impl.hpp
Reduces number of computations by taking `R^T * C ` first in objective function and `R^T * A` in constraints converting objective function to `Tr((R^T * C) * R)` and similarly constraints to `Tr((R^T * A) * R)`.
> Optimized LRSDP Computations

- src/mlpack/methods/neighbor_search/kfn_main.cpp
- src/mlpack/methods/neighbor_search/knn_main.cpp
- src/mlpack/methods/neighbor_search/neighbor_search_impl.hpp
Solves #1259
Throw errors if k is set equal to the number of reference points when query data is not provided, in both kfn and knn.
> Fix neighbor search edge case

- CMakeLists.txt
mlpack actually compiles fine in those cases but when you try to run the tests there is a segfault that I believe to be a compiler error in initialization.
I spent a while debugging it and wasn't able to really find any reason for the failure, but I think that clang 3.4.2 is so old that we don't need to worry about it.  So I think it is reasonable to issue an error during configuration if clang is too old.
Example failure: http://masterblaster.mlpack.org/view/docker/job/docker%20mlpack%20nightly%20build/240/armadillo_version=armadillo-6.500.5,boost_version=boost_1_49_0,buildmode=debug,compiler_version=llvm-3.4.2,label=linux-amd64/
> Disallow compilation on clang 3.4 and older.

- src/mlpack/tests/main_tests/logistic_regression_test.cpp
I guess I have filed a bunch of PRs today but they are all simple...
The `LogisticRegressionMainTest/LRDecisionBoundaryTest` test can sometimes fail:
http://masterblaster.mlpack.org/job/docker%20mlpack%20nightly%20build/241/armadillo_version=armadillo-7.100.3,boost_version=boost_1_49_0,buildmode=release,compiler_version=llvm-3.5.2-patch,label=linux-amd64/
In order to handle this I have just changed the testing strategy.  Previously the test checked if every assignment was 0 when the decision boundary was 1, and it then checked that every assignment was 1 when the decision boundary was 0.  But this can fail when the point lies directly on the decision boundary.
Thus all I've done here is changed the test so that it ensures that the results are different for at least one point when we …
> Fix LogisticRegressionMainTest

- src/mlpack/methods/decision_tree/all_categorical_split.hpp
- src/mlpack/methods/decision_tree/all_categorical_split_impl.hpp
- src/mlpack/methods/decision_tree/best_binary_numeric_split.hpp
- src/mlpack/methods/decision_tree/best_binary_numeric_split_impl.hpp
- src/mlpack/methods/decision_tree/decision_tree.hpp
- src/mlpack/methods/decision_tree/decision_tree_impl.hpp
- src/mlpack/methods/decision_tree/decision_tree_main.cpp
- src/mlpack/tests/decision_tree_test.cpp
- src/mlpack/tests/main_tests/decision_tree_test.cpp
Early stopping is a regularisation method for decision trees i.e. it reduces overfitting. In this method, the splitting of the node is prevented if the information gain is less than the given threshold. 
This PR introduces the paramter `minimumGainSplit` to the Decision Tree API for the users to stop the growth of the tree if the gain is less than the threshold.
Tests for early stopping and implemetnation of post-pruning (another regularisation technique for decision tree) will be added in the following commits.
> Regularisation for Decision Tree.

- src/mlpack/core/math/random.hpp
This PR adds a `SetFixedRandomSeed()`function to allow tests to set a predefined random seed.
I am writing binding test for CF and found that it's hard to test whether a certain parameter is used when I cannot set a fixed random seed (setting random seed was disabled in #1264). What I was trying to do was to run `mlpack()` multiple times with different values set to the tested parameter each time, to see if the results are different. This is impossible or hard to be done in CF when random seed cannot be set, and it is probably the same in other binding tests in #1152 (like nmf).  So I added this function to allow tests programs to set a **predefined** random seed. In this way every run of `mlpack_test` in a single build still gives the same testing results.
So in a binding test case, the …
> Allow setting a fixed random seed in binding tests

- src/mlpack/core/optimizers/sdp/primal_dual_impl.hpp
- src/mlpack/core/tree/binary_space_tree/binary_space_tree_impl.hpp
- src/mlpack/core/tree/cover_tree/cover_tree_impl.hpp
- src/mlpack/core/tree/octree/octree_impl.hpp
- src/mlpack/core/tree/rectangle_tree/rectangle_tree_impl.hpp
- src/mlpack/core/tree/rectangle_tree/x_tree_split_impl.hpp
- src/mlpack/core/tree/spill_tree/spill_tree_impl.hpp
- src/mlpack/methods/det/dtree_impl.hpp
- src/mlpack/methods/hmm/hmm_train_main.cpp
- src/mlpack/tests/main_tests/hmm_generate_test.cpp
- src/mlpack/tests/main_tests/hmm_train_test.cpp
- src/mlpack/tests/main_tests/hmm_viterbi_test.cpp
- src/mlpack/tests/momentum_sgd_test.cpp
- src/mlpack/tests/nmf_test.cpp
- src/mlpack/tests/radical_test.cpp
- src/mlpack/tests/sdp_primal_dual_test.cpp
- src/mlpack/tests/spalera_sgd_test.cpp
I've fixed a number of tests that I found to be occasionally failing:
* `NMFRandomDivTest`: allow multiple trials of the test to prevent the effects of bad random seeds.
* Serialization tests: with Boost 1.49 and LLVM 5.0.1 (and possibly other compilers), serialization tests can sometimes fail.  After digging to the bottom of the issue I concluded that the best solution was a workaround, so now trees avoid serializing any null pointers.
* `HMMTrainMainTest/HMMTrainReuseGaussianModelTest`: it looks like sometimes the retraining actually moves the HMM model too much, so I set the tolerance for the retraining to a very large value.
* `XTreeTraverserTest`: in a very uncommon edge case, the number of descendants and the bound isn't properly reset.
> Miscellaneous test fixes

- src/mlpack/methods/ann/layer/batch_norm.hpp
- src/mlpack/methods/ann/layer/batch_norm_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
Updated the backward step formula for the Batch Normalization layer, this should pass the Gradient Check test:
- http://masterblaster.mlpack.org/view/docker/job/docker%20mlpack%20nightly%20build/armadillo_version=armadillo-7.100.3,boost_version=boost_1_49_0,buildmode=debug,compiler_version=gcc-7.2.0,label=linux-amd64/
@Manthan-R-Sheth let me know what you think.
> Update backward step.

- src/mlpack/methods/mean_shift/mean_shift.hpp
- src/mlpack/methods/mean_shift/mean_shift_impl.hpp
- src/mlpack/methods/mean_shift/mean_shift_main.cpp
- src/mlpack/tests/main_tests/mean_shift_test.cpp
In mean shift, when max_iterations specified is too low w.r.t size of data (e.g. 2 max iterations with `iris_test.csv` and 9 max iterations with `test_data_3_1000.csv`), the program terminates after throwing an instance of `std::invalid_argument`.
>what(): Requested value of k (1) is greater than the number of points in reference set (0).
Aborted (core dumped)
This is because we may not have any centroids converged after max iterations of the mean shift algorithm and then run the `neighbor::KNN.search` with an empty matrix.
This PR fixes this by adding 1 centroid previously calculated if the `centroids` matrix is empty.
> Fix bug in mean shift when max_iterations is too low w.r.t size of data

- src/mlpack/tests/gmm_test.cpp
- src/mlpack/tests/nesterov_momentum_sgd_test.cpp
- src/mlpack/tests/svd_incremental_test.cpp
After watching the nightly and weekly docker matrix builds, I adjusted tolerances for three tests:
* NesterovMomentumSGDSpeedUpTest
* SVDIncompleteIncrementalRegularizationTest
* GMMTrainEMMultipleGaussians
Once I merge this I'll start those builds again, as well as the monthly build, and hopefully everything should pass for once. :)
> Adjust tolerances to fix failing matrix build tests.

- src/mlpack/methods/range_search/range_search.hpp
- src/mlpack/methods/range_search/range_search_impl.hpp
- src/mlpack/methods/range_search/rs_model.hpp
- src/mlpack/methods/range_search/rs_model_impl.hpp
Updated the methods and constructors in `range_search` to pass-by-value instead of the 2 overload methods as suggested in #1021.
> RangeSearch: update methods and constructors to pass-by-value

- src/mlpack/bindings/python/setup.py.in
Fix issue where ``CMAKE_CXX_FLAGS`` is automatically set and doesn't start with a space.
> Space between compiler flags

- src/mlpack/methods/ann/layer/CMakeLists.txt
- src/mlpack/methods/ann/layer/alpha_dropout.hpp
- src/mlpack/methods/ann/layer/alpha_dropout_impl.hpp
- src/mlpack/methods/ann/layer/layer_types.hpp
- src/mlpack/tests/ann_layer_test.cpp
This is towards completion of PR #1278.
> Alpha dropout

- src/mlpack/methods/ann/layer/CMakeLists.txt
- src/mlpack/methods/ann/layer/alpha_dropout.hpp
- src/mlpack/methods/ann/layer/alpha_dropout_impl.hpp
- src/mlpack/methods/ann/layer/layer_types.hpp
- src/mlpack/tests/ann_layer_test.cpp
This PR adds a variant of dropout - alpha_dropout - as proposed in this [NIPS Paper](https://arxiv.org/pdf/1706.02515.pdf).  
I will add the tests once the implementation is approved.
> Add Alpha Dropout Layer

- src/mlpack/methods/ann/layer/dropout.hpp
- src/mlpack/methods/ann/layer/dropout_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
This PR removes the unnecessary rescale boolean variable used in the dropout layer.  The user should not be given the option of rescaling the inputs during the testing phase.  The inputs are scaled during the training phase so that the expected sum remains unchanged.
@zoq please have a review of the changes.
> Remove Rescale Boolean Variable from Dropout Layer

- src/mlpack/methods/ann/layer/CMakeLists.txt
- src/mlpack/methods/ann/layer/flexible_relu.hpp
- src/mlpack/methods/ann/layer/flexible_relu_impl.hpp
- src/mlpack/methods/ann/layer/layer_types.hpp
- src/mlpack/methods/ann/layer/leaky_relu.hpp
- src/mlpack/tests/ann_layer_test.cpp
This is in continuity to #1281.
Function call overheads have been removed and code is simplified to include the calculation in `Forward() `and `Backward()`.
> Implement Flexible ReLU 

- src/mlpack/methods/ann/init_rules/CMakeLists.txt
- src/mlpack/methods/ann/init_rules/he_init.hpp
- src/mlpack/methods/ann/init_rules/lecun_normal_init.hpp
- src/mlpack/tests/init_rules_test.cpp
This PR adds the following initialization rules with regards to issue #1228:
1. He initialization as given in this [paper](https://www.cv-foundation.org/openaccess/content_iccv_2015/papers/He_Delving_Deep_into_ICCV_2015_paper.pdf). 
2. Lecun Normal initialization as given in this [paper](http://yann.lecun.com/exdb/publis/pdf/lecun-98b.pdf) and also used in [Self Normalizing Networks](https://arxiv.org/pdf/1706.02515.pdf). 
I will add the tests for the same after the implementation is approved.
> Add He Initialization and Lecun Normal Initialization

- src/mlpack/tests/arma_extend_test.cpp
Recent versions of armadillo emit warnings when the result of iterator postfix increment/decrement is not used.  The void statement by itself isn't sufficient to suppress these warnings.
> fix unused result warning

- src/mlpack/methods/reinforcement_learning/environment/acrobat.hpp
- src/mlpack/methods/reinforcement_learning/environment/cart_pole.hpp
- src/mlpack/methods/reinforcement_learning/environment/mountain_car.hpp
- src/mlpack/methods/reinforcement_learning/q_learning_impl.hpp
The previous implementation did not care about the terminal condition and its reward. Hence I am adding terminal condition to the environment, to take care of the terminal conditions .
> Add terminal Reward .

- src/mlpack/methods/ann/loss_functions/CMakeLists.txt
- src/mlpack/methods/ann/loss_functions/KLDivergence.hpp
- src/mlpack/methods/ann/loss_functions/KLDivergence_impl.hpp
- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/loss_functions_test.cpp
This PR adds a `loss_functions` folder inside the `ann` folder.  The KL Divergence loss has been implemented and put into this folder.
Tests for KL Divergence loss function have been added as well.
> Add Loss Functions Folder, KL Divergence Loss

- CMake/CreateArmaConfigInfo.cmake
- CMakeLists.txt
- src/mlpack/core/util/arma_config_check.hpp
If the user is compiling their application with OpenMP but mlpack was not compiled with OpenMP (or vice versa) we issue a warning.  This situation can cause disaster with recent versions of Armadillo.
This solves #1358.  (Or, at least, it tells the user what is wrong in situations that can lead to #1358.)
> Warn differences in OpenMP settings.

- COPYRIGHT.txt
- src/mlpack/core.hpp
- src/mlpack/methods/neighbor_search/neighbor_search.hpp
- src/mlpack/methods/neighbor_search/neighbor_search_impl.hpp
Switching lvalue reference and rvalue reference overload to pass-by-value argument in the Neighbor Search algorithm, as suggested at #1021 issue.
A user can pass the data by making a copy (Method(data)) or, avoiding copies if possible, by moving the data into the method (Method(std::move(data))).
> Update NeighborSearch: Switching l-rvalue reference overload to pass-by-value

- src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp
The variable 'model' may not be initialized, thus causing a compile warning in
src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp:251
> Add missing check to suppress compiler warning

- doc/joss_paper/paper.bib
- doc/joss_paper/paper.md
This adds the mlpack JOSS paper to the mlpack repository, which is required for the submission to JOSS:  https://github.com/openjournals/joss-reviews/issues/703
I think that we could either remove it or leave it in the repository after the submission is done.
> Add JOSS paper for submission.

- src/mlpack/core/optimizers/CMakeLists.txt
- src/mlpack/core/optimizers/bigbatch_sgd/CMakeLists.txt
- src/mlpack/core/optimizers/bigbatch_sgd/adaptive_stepsize.hpp
- src/mlpack/core/optimizers/bigbatch_sgd/backtracking_line_search.hpp
- src/mlpack/core/optimizers/bigbatch_sgd/bigbatch_sgd.hpp
- src/mlpack/core/optimizers/bigbatch_sgd/bigbatch_sgd_impl.hpp
- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/bigbatch_sgd_test.cpp
Implementation of Big-batch Stochastic Gradient Descent (BBSGD) as described in: "Big Batch SGD: Automated Inference using Adaptive Batch Sizes" by Soham De et al.
> Big-batch Stochastic Gradient Descent (BBSGD)

- src/mlpack/methods/reinforcement_learning/environment/CMakeLists.txt
- src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp
- src/mlpack/tests/rl_components_test.cpp
This adds the Pendulum environment (https://gym.openai.com/envs/Pendulum-v0/) which is a continuous control environment with no terminal state. This should fix #1322 as once this is merged all the classic control environments from OpenAI Gym will be added to mlpack's reinforcement learning module.
> Added Pendulum continuous environment of OpenAI Gym

- src/mlpack/methods/ann/layer/convolution_impl.hpp
- src/mlpack/methods/ann/layer/transposed_convolution_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
Adjustments:
- adjust the weights size inside the ann layer test, to avoid memory issue
- use advanced constructor inside the convolution method
``std::move`` should work as well, we could get back to the original solution if we decide that's cleaner.
> Convolution adjustements

- src/mlpack/methods/ann/layer/lookup.hpp
Just added an alias for the existing lookup layer, to use it as embedding layer.
> embedding layer

- COPYRIGHT.txt
- src/mlpack/core.hpp
- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/main_tests/nca_test.cpp
Tests for the NCA binding, to insure its inputs and outputs work correctly. 
Added a nca_test.cpp file under maint_test.
> Add tests for command-line and Python bindings (nca)

- CMakeLists.txt
> Only build man pages if CLI programs are being built.

- README.md
- doc/guide/build.hpp
- doc/guide/python_quickstart.hpp
- src/mlpack/bindings/python/print_doc_functions_impl.hpp
- src/mlpack/methods/adaboost/adaboost_main.cpp
- src/mlpack/methods/decision_tree/decision_tree_main.cpp
- src/mlpack/methods/perceptron/perceptron_main.cpp
- src/mlpack/methods/random_forest/random_forest_main.cpp
- src/mlpack/methods/rann/krann_main.cpp
This is a collection of fixes for the issues brought up by @rasbt:
* Clarify how to use the Python bindings without installation and mention when `LD_LIBRARY_PATH` might be needed. (#1416)
* Print `output = ` before automatically-generated calls to Python bindings in documentation. (#1418)
* Change name of `perceptron` variable in the perceptron code documentation. (#1419)
* Rewrite the kRANN documentation since it was written specifically for command-line bindings and never updated.
* Write the random forest documentation since it seems it never actually got written.
Since these fix some fairly important documentation issues from the Python angle, I would have no problem doing a release after this merge as mlpack 3.0.2.
> JOSS documentation fixes

- src/mlpack/core/cv/k_fold_cv.hpp
- src/mlpack/core/cv/k_fold_cv_impl.hpp
- src/mlpack/core/math/shuffle_data.hpp
- src/mlpack/methods/softmax_regression/softmax_regression_function.cpp
- src/mlpack/tests/cf_test.cpp
- src/mlpack/tests/cv_test.cpp
- src/mlpack/tests/math_test.cpp
I've modified the KFoldCV class so that there is an optional 'shuffle' parameter, and made a few other changes also:
* Better handling of sparse matrices to fix #1411 throughout the codebase.
* Better handling of datasets where the number of points is not evenly divisible by `k` in `KFoldCV`.  @micyril, if you like, you can take a look at what I did and see if there are any issues.  Basically the modification amounts to holding a `lastBinSize`, since the last cross-validation bin may hold fewer points than the others, and then modifying the `GetTrainingSubset()` and `GetValidationSubset()` functions.
The shuffling is done at the beginning of any call to `KFoldCV::Evaluate()`.
This fixes #1409.
> Add shuffle parameter to KFoldCV constructor

- src/mlpack/tests/bigbatch_sgd_test.cpp
Remove the random seed from the test cases.
> BigBatchSGD remove random seed

- HISTORY.md
- src/mlpack/methods/radical/radical.cpp
Looks like the Visual Studio compiler gets confused since `svd` is a namespace name and also a function name out of the `arma` namespace, so like @kilasuelika pointed out, we can just specify the namespace to fix it.
> Fix #1443 by specifying namespace

- HISTORY.md
- src/mlpack/methods/local_coordinate_coding/local_coordinate_coding_main.cpp
I have removed a check that would mean that the user must pass either 'initial_dictionary' or 'input_model' to any call of the program.  This makes it impossible to run LCC with a random initial dictionary.
I think this would be sufficient for releasing 3.0.3 as a bugfix, but we can also wait a little if there are more fixes or functionality.
> Fix invalid error in local_coordinate_coding

- .travis.yml
- src/mlpack/core/metrics/mahalanobis_distance.hpp
This is pretty simple, and should fix the failing Travis build.  I also improved the documentation for `MahalanobisDistance` to fix #1453.  There's no actual functionality change to the library itself.
> Travis and documentation fix

- src/mlpack/core/math/random.hpp
- src/mlpack/methods/cf/cf_main.cpp
- src/mlpack/methods/kernel_pca/kernel_pca_main.cpp
- src/mlpack/methods/lmnn/lmnn_main.cpp
- src/mlpack/methods/nca/nca_main.cpp
- src/mlpack/methods/preprocess/preprocess_split_main.cpp
- src/mlpack/methods/radical/radical_main.cpp
Check whether the BINDING_TYPE is NULL or not. The order of mlpack_main.cpp inclusion is also corrected all over the codebase.
> Fix math::RandomSeed() BINDING_TYPE macro condition

- COPYRIGHT.txt
- doc/guide/build.hpp
- doc/tutorials/tutorials.txt
- src/mlpack/core.hpp
Minor changes to link core.hpp and tutorials.txt to the recently added Windows build tutorial and sample app.
Let me know if I missed any other ref location.
> Fix/add references to Win tutorials and sample app

- src/mlpack/bindings/python/setup.py.in
Also simplify the CXXFLAGS setting process.
I found that these fields were missing from the package uploaded to PyPI back when I packaged mlpack 3.0.0, and today I pushed mlpack 3.0.2 and noticed I needed to modify the script.  So it would be a good thing to merge these into master.
If you see any changes that we should make to the documentation please feel free.  Here is the PyPI page this results in:
https://pypi.org/project/mlpack3/
We could modify it a bit---for instance, scikit actually loads their entire README into the long description with code like:
```
with open('README.rst') as f:
LONG_DESCRIPTION = f.read()
```
But unless someone explicitly wants me to do that (and it's no problem if anyone does want it), I'll leave it as-is.
> Add documentation fields to setup.py.in

- src/mlpack/methods/lmnn/lmnn_function.hpp
- src/mlpack/methods/lmnn/lmnn_function_impl.hpp
> LMNN: Bounds for slack term

- src/mlpack/core/optimizers/bigbatch_sgd/adaptive_stepsize.hpp
- src/mlpack/methods/lmnn/lmnn_function_impl.hpp
It seems LMNNOptimizerTest from main tests is randomly failing. This PR is for dealing with this issue.
> Resolve random failing of LMNN Test

- CMakeLists.txt
- README.md
- doc/guide/build.hpp
- doc/guide/build_windows.hpp
This fixes #1473, and I'll release mlpack 3.0.3 with this and some other fixes once this is merged.
Basically this just adds a CMake configuration option `USE_OPENMP` that allows the user to specify whether or not to use OpenMP.
So you can now configure as
```
$ cmake -DUSE_OPENMP=OFF ..
```
and OpenMP won't be used.
I also noticed the mlpack paper citation in the readme is out of date, so I updated that too. :)
> Make use of OpenMP optional

- src/mlpack/tests/lmnn_test.cpp
@manish7294 ---take a look at this and tell me what you think.
Basically all I have done is reworked the low-rank LMNN tests so that they can be included in the test suite.  It's true that sometimes the low-rank LMNN may randomly perform poorly (or at least very differently) based on initial starting point, so I've made it so that it can take three trials (or up to five with BBSGD since it seems to perform worse).
> Update LMNN low-rank tests to use all three optimizers.

- src/mlpack/methods/logistic_regression/logistic_regression.hpp
- src/mlpack/methods/logistic_regression/logistic_regression_impl.hpp
Hi,
It is sometimes useful to have the final objective of the trained model, especially if it failed to train properly.
It has been useful for me, letting you have this as it may well be useful for others.
Cheers,
Rob
> Return the final objective of the trained model

- src/mlpack/methods/linear_regression/linear_regression.cpp
Basically what I have done here is that following Anisa's email, I identified that linear regression actually creates an NxN matrix.  I think the old implementation scaled as O(N^2 d).  I then spent a little time at a whiteboard thinking about how to avoid that, and only use O(d^2) memory.  That resulted in this implementation, which scales as O(Nd^2 + d^3) where the O(Nd^2) comes from the covariance matrix computation and the O(d^3) comes from the `arma::solve()` call.
On a simple low-dimensional example with lots of points, the implementation scales much better.  I tested with a 200k point subset of the higgs dataset (28d), and the actual computation was 0.04s (whereas the loading time was like 1.4s).
Maybe for very high-dimensional datasets this implementation could be somewhat …
> Replace linear regression implementation with something faster.

- src/mlpack/methods/ann/layer/batch_norm.hpp
- src/mlpack/methods/ann/layer/batch_norm_impl.hpp
- src/mlpack/methods/ann/layer/elu.hpp
- src/mlpack/methods/ann/layer/layer_norm.hpp
- src/mlpack/methods/ann/layer/layer_norm_impl.hpp
- src/mlpack/methods/ann/loss_functions/earth_mover_distance_impl.hpp
- src/mlpack/tests/serialization_test.cpp
- batch normalization layer serialization test
- layer normalization layer serialization test
> Layer serialization

- src/mlpack/methods/rann/ra_search.hpp
- src/mlpack/methods/rann/ra_search_impl.hpp
For RASearch constructors and the class method Train, replace copy and move overloads with single pass-by-value methods. The user can use `std::move(referenceSet)` to prevent copying of the dataset. Implements the guidelines set in #1021 .
> Replace copy and move overloads with pass-by-value for RASearch class

- doc/policies/trees.hpp
Trees also require their StatisticType to have a default constructor to work properly.
> Add constructor to StatisticType docs

- CMake/allexec2man.sh
- CMake/exec2man.sh
- CMakeLists.txt
- src/mlpack/bindings/cli/CMakeLists.txt
- src/mlpack/bindings/python/CMakeLists.txt
- src/mlpack/bindings/python/setup.py.in
- src/mlpack/methods/CMakeLists.txt
- src/mlpack/tests/CMakeLists.txt
This is a collection of fixes for issues @marcespie has opened recently.  It includes the following changes:
* (#1516) stop using -lrt since it isn't needed
* add linking against -pthread for std::thread usage when using g++
* (#1518) use /bin/sh not /bin/bash
* (#1518) don't gzip man pages
* (#1520) refactor dependencies on `man` target so they're automatically added when `add_cli_executable()` is called
* (#1521, #1478) fix bad handling of spaces in CXXFLAGS in Python `setup.py`
* (#1521, #1425?) fix bad usage of `OpenMP_CXX_FLAGS` in Python `setup.py`
* (#1522) handle DESTDIR correctly for Python bindings (the CMake glue previously didn't)
@marcelotrevisani I'm not sure why you closed #1478, but I've pulled that branch in here and we can merge it as part of this one.  In my basic …
> Fixes from marcespie

- CMakeLists.txt
This is a fix for #1530, verified by @marcespie.  It fixes an intermittent problem when using Ninja to build mlpack.
> Fix dependency ordering for mlpack_gitversion and mlpack_arma_config targets

- src/mlpack/methods/neighbor_search/neighbor_search.hpp
- src/mlpack/methods/neighbor_search/neighbor_search_impl.hpp
Replace copy and move overloads of the method Train in class NeighborSearch with pass-by-value. This pull request implements the guidelines suggested in #1021.
> Replace copy and move overloads with pass-by-value for NeighborSearch

- src/mlpack/methods/mean_shift/mean_shift_impl.hpp
The previous mean shift code would disallow a single cluster if it only held one point.  This fix allows single-point clusters.  @ShangtongZhang: I wouldn't mind if you could take a quick look at this and ensure it doesn't break anything unforeseen. :)
This should be a fix for issue #1526.
> Mean shift: allow single-point clusters

- src/mlpack/methods/decision_tree/decision_tree.hpp
- src/mlpack/methods/decision_tree/decision_tree_impl.hpp
- src/mlpack/methods/decision_tree/decision_tree_main.cpp
Replace arguments of decision trees with pass by value arguments so the user can choose whether to copy or move the data. This makes reference to #1021.
> Decision tree pass by value

- src/mlpack/methods/ann/ffn.hpp
- src/mlpack/methods/ann/ffn_impl.hpp
- src/mlpack/methods/ann/rnn.hpp
- src/mlpack/methods/ann/rnn_impl.hpp
Previously, models would always re-initialize their weights after loading.  But we have to increment the serialization version for backwards compatibility.  I opened this because a user sent me an email that pointed out the problem.
@ShikharJ: does the GAN code need to be correspondingly updated?  I see that there is a serialize function there, but it seems very different in its behavior.
> Explicitly serialize the 'reset' parameter.

- CMakeLists.txt
- src/mlpack/bindings/python/CMakeLists.txt
So we can't "re-set" the default value.  This change makes the option defined with its default conditionally.  No actual functionality change here, other than that now Python bindings are properly disabled on Windows.
> CMake doesn't allow overloading of an option.

- src/mlpack/methods/perceptron/perceptron_main.cpp
The warning should be issued if `output` is specified but `test` is not... not the other way around.
> Fix inappropriate warning Barak pointed out in #1564.

- src/mlpack/core/metrics/mahalanobis_distance.hpp
- src/mlpack/core/metrics/mahalanobis_distance_impl.hpp
- src/mlpack/core/tree/binary_space_tree/binary_space_tree_impl.hpp
- src/mlpack/core/tree/cellbound.hpp
- src/mlpack/core/tree/cellbound_impl.hpp
- src/mlpack/core/tree/hrectbound.hpp
- src/mlpack/core/tree/hrectbound_impl.hpp
- src/mlpack/tests/tree_test.cpp
This fixes #1579.
@reverendbedford: sorry, the patch was just a little more complex than I thought.  You can use this branch to fix the issue, or wait until it is merged.  Thanks again for pointing out the issue. :+1:
> Handle instantiated metrics for BinarySpaceTree.

- CMakeLists.txt
- doc/guide/build_windows.hpp
- src/mlpack/bindings/cli/CMakeLists.txt
- src/mlpack/tests/CMakeLists.txt
This is to improve on the issues encountered in #1524.  It adds some description on debugging Boost configuration failures, and also disables autolinking with Boost which apparently causes some problems.
I have not tried these steps directly on Windows but instead on Linux and they seem to work.  If someone would like to verify (and update if needed on what's wrong), I can update the Boost configuration steps.
> Update Windows tutorial and build options

- CMake/allexec2man.sh
- CMakeLists.txt
- src/mlpack/CMakeLists.txt
- src/mlpack/bindings/cli/CMakeLists.txt
- src/mlpack/bindings/python/CMakeLists.txt
These changes are for #1578 and #1576:
* Use `GNUInstallDirs` from CMake, which lets the user configure things like LIBDIR, INCLUDEDIR, etc.  On Windows, we just set these to their existing defaults, but they can be configured there also.
* A few minor formatting fixes.
* Fix another Linux-ism for the `find` call in `allexec2man.sh`.
> CMake fixes and GNUInstallDirs

- src/mlpack/methods/kernel_pca/kernel_pca_main.cpp
- src/mlpack/tests/distribution_test.cpp
- src/mlpack/tests/main_tests/kernel_pca_test.cpp
- src/mlpack/tests/nmf_test.cpp
- src/mlpack/tests/recurrent_network_test.cpp
Looking through the jobs on ci.mlpack.org, I took a list of tests that were failing and tried to adjust tolerances on each of them to reduce the failure probability.
@saksham189: some of the kernel PCA main tests were failing intermittently.  For instance, the sampling scheme test would fail because the new dimensionality was only 1, meaning that the Nystroem method would select only one point.  Since the dataset only had 5 points, the probability of failure was the probability that the random sampling scheme would select the same point as the ordered sampling scheme, which in this case was 20%.  A larger dataset and a higher new dimensionality appear to have fixed the problem.  One other test needed a bit of changes too.  Take a look at the changes and let me know if I broke anything (or …
> Fixes for intermittently failing tests

- CMakeLists.txt
- doc/guide/build_windows.hpp
- src/mlpack/bindings/python/CMakeLists.txt
- src/mlpack/bindings/python/PythonInstall.cmake
This should solve #1621.  I had to refactor the CMake installation scripts for Python a bit to make it work right.
I also set BUILD_SHARED_LIBS=OFF by default on Windows as suggested in #1611.
> CMake installation fixes

- src/mlpack/methods/ann/layer/layer_types.hpp
- src/mlpack/methods/ann/layer/sequential.hpp
- src/mlpack/methods/ann/layer/sequential_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
I also added the `DeleteModules()` function to the `Sequential` object as there was no way to free memory of added layers(with no pointers) when `model == true`.
> Add support for residual blocks.

- CMake/FindEnsmallen.cmake
As per discussion over irc earlier today. I have set the Ensmallen lookup path to /deps/ensmallen. It will help in avoiding re-download of ensmallen.
> Download ensmallen only if not available

- src/mlpack/core/cv/meta_info_extractor.hpp
MSVC C3546 (there are no parameter packs available to expand) workaround.
> MSVC C3546 workaround

- CONTRIBUTING.md
Previously, we used to say that we would merge after one approval and a few days, or after two approvals immediately.  This was to ensure high code quality.  But as time has gone on, it's become kind of clear that this has also made merges pretty slow.
So, I think that we should change the policy so that as soon as something has one approval from someone on the Contributors team it can be merged.  And if others want to review it before it gets merged, it seems like the best idea would just be to post a comment asking to wait until they can review it before merge.
I sent an email about this to some in the contributors team and there was no objection (actually there was not much response at all), so I'll take that to mean that basically everyone would be okay with this. :)
I'll let this sit …
> Update contribution policy.

- src/mlpack/core/util/mlpack_main.hpp
- src/mlpack/methods/nmf/nmf_main.cpp
- src/mlpack/tests/main_tests/nmf_test.cpp
This fixes #1646, which pointed out that NMF returns transposed W/H matrices from the Python bindings (and this is true of the command-line bindings too).  The solution was to detect whether or not the binding type is going to transpose the matrices (via the new macro BINDING_MATRIX_TRANSPOSED) and use that to control the behavior in `nmf_main.cpp`.
I also made the `NMFMainTest` a little more robust by using non-square matrices for decomposition.
> Fix NMF saving and loading of matrices.

- .travis.yml
- src/mlpack/methods/nystroem_method/nystroem_method_impl.hpp
- src/mlpack/tests/gmm_test.cpp
- src/mlpack/tests/random_forest_test.cpp
I saw the Jenkins build was unstable so I decided to debug the tests.  This contains fixes for five intermittently failing tests:
* `GMMTrainEMOneGaussian`: instead of checking each element of the trained mean and covariances, we can just check the l2-norm of the differences.
* `GMMTrainEMMultipleGaussians`: I overhauled this test so that (1) Gaussians in the mixture have a minimum weight of roughly 0.2; (2) multiple trials are allowed to prevent failures due to GMM converging to some local minimum.
* `WeightedCategoricalLearningTest` and `UnweightedCategoricalLearningTest`: random forests aren't always guaranteed to be better than decision trees, so adjust the tolerance more.
* `KernelPCASamplingSchemeTest`: here I actually found an issue in `NystreomMethod`, where we divide by the …
> Various test fixes

- .github/ISSUE_TEMPLATE/0-bug.md
- .github/ISSUE_TEMPLATE/1-documentation.md
- .github/ISSUE_TEMPLATE/2-question.md
Here is a basic idea for issue templates.  This should help us classify issues that people open more quickly, and hopefully help get the information we need to take care of the issues more quickly.
It seems like we can automatically apply labels to some of these, which is great, so I have done that where applicable (but the "question" template could be a feature request or a question or something else, so we can just let mlpack-bot label it as `unlabeled`).
> Add issue templates

- src/mlpack/tests/q_learning_test.cpp
I noticed that the test `QLearningTest/MountainCarWithDQN` occasionally fails.  Some of the other tests in `q_learning_test.cpp` have been adapted to run with multiple trials, and I believe that the mountain car test is suffering from random failures much in the way the other tests did.  So the change here simply runs the test up to three times if it fails, which should reduce the failure probability so that it is insignificant.
> Allow multiple trials of MountainCarWithDQN test.

- src/mlpack/bindings/python/mlpack/matrix_utils.py
> Handling pandas.core.series.Series in matrix_utils.py

- src/mlpack/methods/logistic_regression/logistic_regression_main.cpp
- src/mlpack/tests/main_tests/logistic_regression_test.cpp
With respect to issue #1565 : 
I have made changes to the `logistic_regression_main.cpp`
I have tested the binding for renamed parameters/options.
@rcurtin kindly review the changes. Let me know if any updates are needed. 
Thank you
> Option consistency in logistic regression #1565

- COPYRIGHT.txt
- HISTORY.md
- src/mlpack/core.hpp
- src/mlpack/methods/adaboost/adaboost.hpp
- src/mlpack/methods/adaboost/adaboost_impl.hpp
- src/mlpack/methods/ann/ffn.hpp
- src/mlpack/methods/ann/ffn_impl.hpp
- src/mlpack/methods/ann/gan/gan.hpp
- src/mlpack/methods/ann/gan/gan_impl.hpp
- src/mlpack/methods/ann/rbm/rbm.hpp
- src/mlpack/methods/ann/rbm/rbm_impl.hpp
- src/mlpack/methods/ann/rnn.hpp
- src/mlpack/methods/ann/rnn_impl.hpp
- src/mlpack/methods/decision_stump/decision_stump.hpp
- src/mlpack/methods/decision_stump/decision_stump_impl.hpp
- src/mlpack/methods/decision_tree/decision_tree.hpp
- src/mlpack/methods/decision_tree/decision_tree_impl.hpp
- src/mlpack/methods/hmm/hmm.hpp
- src/mlpack/methods/hmm/hmm_impl.hpp
- src/mlpack/methods/lars/lars.cpp
- src/mlpack/methods/lars/lars.hpp
- src/mlpack/methods/linear_regression/linear_regression.cpp
- src/mlpack/methods/linear_regression/linear_regression.hpp
- src/mlpack/methods/local_coordinate_coding/lcc.hpp
- src/mlpack/methods/local_coordinate_coding/lcc_impl.hpp
- src/mlpack/methods/logistic_regression/logistic_regression.hpp
- src/mlpack/methods/random_forest/random_forest.hpp
- src/mlpack/methods/random_forest/random_forest_impl.hpp
- src/mlpack/methods/sparse_coding/sparse_coding.hpp
- src/mlpack/methods/sparse_coding/sparse_coding_impl.hpp
Hi, 
This is pull Request for #1483 Issue.
I have changed three classifiers 
1) adaboost - returning ztProduct as it's upper bound for training error
2) decision stump - returning the entropy after splitting.
3) decision tree - returning final entropy of the tree . Added some code to get final entropy in recursive decision   tree.
Let me know if I have returned something wrong.
Update One:
Changed Two Classifiers 
1) HMM - In this returning final log likelihood obtained after training using data sequences.
2) Random Forest  - Returning average entropy of all the decision trees trained under the forest
(Not Sure of this)
Update Two:
1) LARS : Returning final absolute maximum correlation after training
2) Linear_regression : Returning least squares error after training.
3) sparse_coding : …
> Adapted Classifiers

- src/mlpack/methods/ann/CMakeLists.txt
- src/mlpack/methods/ann/brnn.hpp
- src/mlpack/methods/ann/brnn_impl.hpp
- src/mlpack/methods/ann/layer/add_merge.hpp
- src/mlpack/methods/ann/layer/add_merge_impl.hpp
- src/mlpack/methods/ann/layer/concat.hpp
- src/mlpack/methods/ann/layer/concat_impl.hpp
- src/mlpack/methods/ann/layer/layer_traits.hpp
- src/mlpack/methods/ann/layer/recurrent.hpp
- src/mlpack/methods/ann/layer/recurrent_impl.hpp
- src/mlpack/methods/ann/rnn.hpp
- src/mlpack/methods/ann/visitor/CMakeLists.txt
- src/mlpack/methods/ann/visitor/backward_visitor.hpp
- src/mlpack/methods/ann/visitor/backward_visitor_impl.hpp
- src/mlpack/methods/ann/visitor/gradient_visitor.hpp
- src/mlpack/methods/ann/visitor/gradient_visitor_impl.hpp
- src/mlpack/methods/ann/visitor/run_set_visitor.hpp
- src/mlpack/methods/ann/visitor/run_set_visitor_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
- src/mlpack/tests/recurrent_network_test.cpp
TODOS
Refer https://github.com/mlpack/mlpack/issues/1580
> Add Bidirectional RNN

- src/mlpack/bindings/python/mlpack/matrix_utils.py
- src/mlpack/bindings/python/tests/test_python_binding.py
> FIX copying Pandas DataFrames for Python bindings

- src/mlpack/methods/adaboost/adaboost_impl.hpp
- src/mlpack/methods/ann/rbm/rbm_impl.hpp
I noticed gcc -Wreorder warning, because the parameters were unordered when initializing.
> Resolve gcc parameter reorder warning for clean build.

- src/mlpack/methods/ann/loss_functions/negative_log_likelihood.hpp
As mentioned, fix typo in negative_log_likelihood. 
The consistency of interface, I found that there are two interfaces in negative_log_likelihood.hpp
```c++
//! Get the input parameter.
InputDataType& InputParameter() const { return inputParameter; }
//! Modify the input parameter.
InputDataType& InputParameter() { return inputParameter; }
```
But in some other loss function, they have not. Shall we just keep it or remove?  Literally, it didn't affect the functionality.
> fix typo in negative_log_likelihood

- src/mlpack/methods/ann/init_rules/const_init.hpp
Added a default value to the ConstInitialization constructor that allows it to be used as a template argument.
Initializes the weight matrix to 0.
> Created default value for ConstInitialization constructor

- src/mlpack/core/dists/discrete_distribution.cpp
- src/mlpack/core/dists/discrete_distribution.hpp
- src/mlpack/core/dists/gamma_distribution.cpp
- src/mlpack/core/dists/gamma_distribution.hpp
- src/mlpack/core/dists/gaussian_distribution.hpp
- src/mlpack/core/dists/laplace_distribution.hpp
- src/mlpack/core/dists/regression_distribution.cpp
- src/mlpack/core/dists/regression_distribution.hpp
- src/mlpack/methods/gmm/em_fit.hpp
- src/mlpack/methods/gmm/gmm.hpp
I noticed some functions don't synchronize parameter's name with `@param` in documents of `src/mlpack/core/dists` and `src/mlpack/methods/gmm/`. Also, I edited some files to comply with the style guidelines.
> Synchronize parameter's name with @param in `dists` and `gmm` directory.

- src/mlpack/core/dists/discrete_distribution.hpp
- src/mlpack/core/dists/gaussian_distribution.hpp
This PR removes inline implementation of LogProbability function for different distributions as discussed in https://github.com/mlpack/mlpack/pull/1749#discussion_r264014523.
Thanks
> Remove Inline Implimentation

- src/mlpack/tests/ann_layer_test.cpp
Because the `ANNLayerTest/GradientTransposedConvolutionLayerTest` is probabilistic test, I noticed it was failed sometimes, so to make it robust, check it five times.
> Make `GradientTransposedConvolutionLayerTest` robust.

- src/mlpack/core/data/load_arff_impl.hpp
- src/mlpack/tests/load_save_test.cpp
Resolves #1791.
Rectifies the reason for the failure of memory checks in #1756 for issue #1754. 
Added `is_open()` to make sure if file exists
```c++  
// if file is not open throw an error (file not found).
if (!ifs.is_open())
```
Also, added test for `NonExistentFileARFFTest` .
> Added additional check to LoadARFF.

- src/mlpack/methods/ann/activation_functions/hard_sigmoid_function.hpp
- src/mlpack/methods/ann/layer/base_layer.hpp
- src/mlpack/tests/activation_functions_test.cpp
I wanted to make a review of my work. I have added a hard sigmoid function. Thank you so much
> Add hard sigmoid

- src/mlpack/core/data/load_csv.cpp
- src/mlpack/tests/load_save_test.cpp
Added Regex for quoted strings so that LoadCSV along with mlpack::data::DatasetInfo cab load text from CSV files.
Resolves #1754. 
|    |                               |        | 
|----|-------------------------------|--------| 
| 1  | row 2                         | row 3  | 
| 2  | "row 2, with comma"           | row 3  | 
| 3  | row 2 with \"embedded quote\" | row 3  | 
| 4  |  row 2 with \n new line       | row 3  | 
| 5  |  row 2 with embedded \\       | row 3  | 
| 11 |                               | row 33 | 
```c
std::cout << "Data :" << std::endl;
for (size_t i = 0;i<dataset.n_cols;i++){
std::cout<<dataset.at(0,i)<<"\t";
for (size_t j = 1; j < info.Dimensionality(); ++j)
std::cout<<info.UnmapString(dataset.at(j,i),j,0)<<"\t" ;
std::cout<<std::endl;
}
```
For the CSV file the …
> Added quoted_strings to regex in LoadCSV (#1754) .

- src/mlpack/bindings/python/get_cython_type.hpp
- src/mlpack/bindings/python/get_printable_type_impl.hpp
- src/mlpack/bindings/python/mlpack/matrix_utils.py
- src/mlpack/bindings/python/print_input_processing.hpp
- src/mlpack/bindings/python/print_pyx.cpp
- src/mlpack/bindings/python/tests/test_python_binding.py
- src/mlpack/bindings/python/tests/test_python_binding_main.cpp
> Fix Type Error (Check type of Every parameter)

- src/mlpack/bindings/markdown/print_doc_functions_impl.hpp
This PR rectifies generation markdown [python documentation(mlpack-3.0.4)](http://www.mlpack.org/doc/mlpack-3.0.4/python_documentation.html).
Eg. Converted from 
```python
>>> from mlpack import softmax_regression()
```
to
```python
>>> from mlpack import softmax_regression
```
> Rectified imports in Python documentation

- src/mlpack/core/cv/metrics/f1_impl.hpp
- src/mlpack/core/cv/metrics/recall_impl.hpp
- src/mlpack/methods/linear_regression/linear_regression.cpp
In this PR I did ->
1. In f1_impl.hpp variable numberOfClassInstances is shorten to positiveLabels at line
85 and 88 because at line 85 condition (labels == c) holds true only for positive classes in the 
respective cases in for loop whereas numberOfClassInstances signifies both positive and negative
classes but in recall metric we deal with only positiveLabels. I also shorten numberOfPositivePredictions
to positivePredictions only as the variable name is too big.
2. In recall_impl.hpp I did the same as in f1_impl.hpp.
> Increase Code Readability

- src/mlpack/core/cv/metrics/average_strategy.hpp
- src/mlpack/core/data/imputer.hpp
- src/mlpack/core/data/map_policies/increment_policy.hpp
- src/mlpack/methods/linear_regression/linear_regression.hpp
- src/mlpack/tests/imputation_test.cpp
This PR corrects the following documentation ->
1. Corrects incorrect documentation in imputation_test.cpp.
2. Removes extra given from line 71 in imputer.hpp.
3. Corrects the miss-leading comment at line 25 in increment_policy.hpp.
4. Swap comments at line 89 and 90 in linear_regression.hpp to match the exact sequence of function   
parameters for more readability and to avoid any confusion at first look.
> Documentation fixups

- .travis.yml
- src/mlpack/bindings/python/mlpack/matrix_utils.py
I noticed that Travis is not successfully building the Python bindings.  This should (hopefully) fix that.  It may take a few tries to get right, so I'll post another comment when I'm done with it.
@Yashwants19: in debugging locally, I found that some of the Python tests had some problems, so I had to update `matrix_utils.py` to fix these issues.  There were two main problems---using `y.flatten()` doesn't convert `dtype` if it's not the desired dtype (in fact it just reinterprets it, so `int(1)` does not become `float64(1)`), and also when we are not copying, using `y.flatten()` as a buffer causes problems because it goes out of scope and the memory is cleared when we leave `to_matrix()`, but it is still used by the program.  The changes here should fix that, but let me know if you see …
> Travis Python fixes

- src/mlpack/bindings/python/mlpack/matrix_utils.py
- src/mlpack/bindings/python/print_input_processing.hpp
- src/mlpack/bindings/python/tests/test_python_binding.py
I was surprised to see that after merging #1816, the Travis build broke.  I was able to reproduce it locally, and after spending some time digging into it, I managed to fix three problems:
1. Avoid the use of `ravel()` and `reshape()` in `print_input_processing.hpp`.  This is because those methods *may* sometimes copy the matrix, and when this gets passed to C++, the copied memory goes out of scope and there are segfault issues.
2. Simplify `to_matrix()` handling of Pandas issues to avoid use of `flatten()`, which has to the same problem: `flatten()` may return an object with new memory, which immediately goes out of scope after the `to_matrix()` call, which then causes later allocation/deallocation problems.
3. Fix a couple tests, which were testing against the wrong matrix's value.
This …
> Python fixes for Travis build

- src/mlpack/methods/reinforcement_learning/q_learning.hpp
Adding accessors for the network, so users can retrieve the q-learned parameters
Function naming is consistent with AsyncLearning
This is related to #1861
> Adding accessors for the network

- src/mlpack/methods/ann/rnn_impl.hpp
```c++
const size_t rho = 5;
arma::cube questions = arma::ones(1,2,rho);
arma::cube answers = arma::ones(1,2,rho);
mlpack::ann::RNN<mlpack::ann::MeanSquaredError<> > model(rho);
model.Add<mlpack::ann::Linear<> >(1, 10);
model.Add<mlpack::ann::LSTM<> >(10,10);
model.Add<mlpack::ann::Linear<> >(10, 1);
model.Parameters().randu();
model.Predict(questions, answers);
```
Running the above snippet produces :
```bash
error: Mat::submat(): indices out of bounds or incorrectly used
terminate called after throwing an instance of 'std::logic_error'
what():  Mat::submat(): indices out of bounds or incorrectly used
Aborted (core dumped)
```
However, if the last line in the above snippet is replaced by:
```c++
model.Train(questions, answers);
model.Predict(questions, answers);
```
It works perfectly. …
> Rectified Predict() in rnn_impl (#1846).

- src/mlpack/methods/reinforcement_learning/q_learning.hpp
I have added accessors for state and environment variables in q-learning. Users would like to see the state and environment in which they are.
> Added accessors for state and environment 

- doc/guide/build_windows.hpp
Based on #1874, the following changes were made:
- Re-organized the tutorial structure so it's not that confusing: installation via vcpkg is introduced as an alternative to the build process with the option to skip it and continue with the build steps.
- Removed all the hardcoded versions of mlpack and dependencies from the paths, so we don't need to unnecessarily maintain the tutorial updated when new versions are released.
- Moved the alternative cmake GUI instructions to an appendix (so one main tutorial path can be followed).
- Added a NOTE about the ENSMALLEN dependency, that must be manually specified if cmake can't automatically download it
- Moved third party/old tutorials to a new section, so users can refer to them in case of issues
> Refactor Windows Build Tutorial

- src/mlpack/methods/ann/layer/concat.hpp
- src/mlpack/methods/ann/layer/concat_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
I have added an axis parameter for `Concat<>` layer to help achieve concatenation along a specific axis. It would help in models which need concat along an arbitrary axis.
Besides, the axis it also needs `inputShape` from the previous layer.
> Added support for concat along an axis.

- doc/guide/python_quickstart.hpp
- src/mlpack/bindings/python/print_input_processing.hpp
- src/mlpack/bindings/python/tests/test_python_binding.py
- src/mlpack/bindings/python/tests/test_python_binding_main.cpp
- src/mlpack/core/util/param.hpp
This is a fix for #1772.
Essentially, what I found is that there was extra spacing for required matrix arguments in the generated `.pyx` files:
```
if isinstance(copy_all_inputs, bool):
if copy_all_inputs:
SetParam[cbool](<const string> 'copy_all_inputs', copy_all_inputs)
CLI.SetPassed(<const string> 'copy_all_inputs')
else:
raise TypeError("'copy_all_inputs' must have type 'bool'!")
input_tuple = to_matrix(input, dtype=np.double, copy=CLI.HasParam('copy_all_inputs'))
if len(input_tuple[0].shape) > 2:
input_tuple[0].shape = (input_tuple[0].shape[0], 1)
input_mat = arma_numpy.numpy_to_mat_d(input_tuple[0], input_tuple[1])
SetParam[arma.Mat[double]](<const string> 'input', dereference(input_mat))
CLI.SetPassed(<const string> 'input')
del input_mat
```
I fixed this and added tests to ensure …
> Python spacing fix

- CMakeLists.txt
- HISTORY.md
While reading #1866 I realized that if CMake downloads ensmallen for the build, if the user installs mlpack it *only* installs the mlpack headers, meaning they can't ever build anything against mlpack unless they go and also install ensmallen.
This PR fixes that by having CMake install ensmallen, but only when it is downloaded during the build process because it is not available on the system.
> Install ensmallen headers when downloaded during build.

- HISTORY.md
- src/mlpack/bindings/markdown/binding_info.hpp
- src/mlpack/methods/decision_tree/all_categorical_split_impl.hpp
- src/mlpack/methods/decision_tree/all_dimension_select.hpp
- src/mlpack/methods/decision_tree/best_binary_numeric_split_impl.hpp
- src/mlpack/methods/decision_tree/decision_tree.hpp
- src/mlpack/methods/decision_tree/decision_tree_impl.hpp
- src/mlpack/methods/decision_tree/decision_tree_main.cpp
- src/mlpack/methods/decision_tree/gini_gain.hpp
- src/mlpack/methods/decision_tree/information_gain.hpp
- src/mlpack/methods/decision_tree/multiple_random_dimension_select.hpp
- src/mlpack/methods/decision_tree/random_dimension_select.hpp
- src/mlpack/methods/random_forest/random_forest.hpp
- src/mlpack/methods/random_forest/random_forest_impl.hpp
- src/mlpack/methods/random_forest/random_forest_main.cpp
- src/mlpack/tests/decision_tree_test.cpp
- src/mlpack/tests/main_tests/random_forest_test.cpp
- src/mlpack/tests/random_forest_test.cpp
I had a chance to look into it today and I actually found two bugs in the random forest:
* The decision tree was not properly initializing the dimension selector in the case of numeric-only data.
* The random forest was not giving bootstrapped data to the decision trees.
I added a test to check that dimensions are selected randomly, and adapted the other tests (since bootstrapped data no longer gives the same guarantees as we have when we train directly on the full dataset).
> Fix random forest lack of randomness (#1887)

- src/mlpack/tests/dcgan_test.cpp
- src/mlpack/tests/gan_test.cpp
I went over the O'Reilly test and they use `sigmoid_cross_entropy_with_logits` because the output of the discriminator is unscaled (there is no `softmax` or `sigmoid` layer at the end). Therefore, I have switched to using `SigmoidCrossEntropyError`, which gives a finite value for the loss function and solves the `nan` encountered here https://github.com/mlpack/mlpack/pull/1724
Earlier `CrossEntropyError` would produce `nan` while taking log of negative unscaled output from discriminator.
@ShikharJ @walragatver let me know what you think.
> Fix O'Reilly GAN Test

- src/mlpack/tests/random_forest_test.cpp
I was about to release mlpack 3.1.1 with the random forest test fixes, but I found that the tests failed with probability that was too high.  I spent a little time with the tests and I tuned them so that they don't fail now.  Specifically, the categorical dataset tests had significant problems; the reason is that 3 of the 5 dimensions are completely noise; so if the random forest selects sqrt(5) ~= 2 dimensions at each split, the probability of getting only noise is far too high.  This is a really bad case for random forests, and so it can be fixed simply by selecting more dimensions for each split.
I also increased the tolerance margins a little bit, so that the tests have no failures in 1000 trials (on my system at least).  It seems to be a very rare case that the random forest does …
> Make random forest tests more robust

- src/mlpack/methods/ann/gan/gan.hpp
- src/mlpack/methods/ann/gan/gan_impl.hpp
- src/mlpack/methods/ann/gan/wgan_impl.hpp
- src/mlpack/methods/ann/gan/wgangp_impl.hpp
- src/mlpack/tests/gan_test.cpp
Previously during training the predictors were not being shuffled for the discriminator so, they were visited in the same order while `EvaluateWithGradient` was called on discriminator.
> Introduce Memory Sharing Between GAN and FFN

- CONTRIBUTING.md
This was pointed out by rajs123 in IRC; thanks rajs123!  I checked that there are no other references to `involved.html` in the repository.
> Fix link to 'getting involved'

- src/mlpack/methods/ann/layer/glimpse_impl.hpp
- src/mlpack/methods/ann/layer/max_pooling_impl.hpp
- src/mlpack/methods/ann/layer/mean_pooling_impl.hpp
Hi @zoq, @ShikharJ,
While working on GAN serialization I have found an error in `mean pooling` layer. It was producing an `integer divide by zero` error after serialization at `line 60` in `mean_pooling_impl.hpp`. This is because the parameters  `inputWidth`, `inputHeight`, `outputWidth`, `outputHeight` were not serialize. 
I have also modified serialization of some other layers namely `max_pooling` and `glimpse`. Let me know your thoughts regarding the same.
> Fix serialization of glimpse, maxPooling and meanPooling layers.

- src/mlpack/tests/main_tests/random_forest_test.cpp
Just some quick fixes that I put together based on looking at the recent Jenkins nightly build failures.  I found a logical error in one test and increased the number of trials for another.
> Random forest test stability fixes

- src/mlpack/methods/ann/layer/batch_norm.hpp
- src/mlpack/methods/ann/layer/batch_norm_impl.hpp
- src/mlpack/methods/ann/layer/layer_norm.hpp
- src/mlpack/methods/ann/layer/layer_norm_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
I have added a linear layer for all numerical gradient tests behind the layer being tested.
This PR also include a fix in the implementation of `Backward` for BatchNorm layer. 
Closes https://github.com/mlpack/mlpack/issues/1923
> Add linear layer in model for numerical gradient tests

- src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp
- src/mlpack/tests/reward_clipping_test.cpp
- src/mlpack/tests/rl_components_test.cpp
As said in [pr](https://github.com/mlpack/mlpack/pull/1912), remove the [1] in Pendulum's action definition.
> Change the pendulum action type to double

- src/mlpack/methods/ann/layer/batch_norm_impl.hpp
- src/mlpack/methods/ann/layer/layer_norm_impl.hpp
`inputMean = input.each_row() - mean;`
Now if we take `arma::mean(-2 * inputMean, 0)` that would be 0 so we, can remove that from the computation.
> Minor Optimisation in Backward computation

- doc/guide/python_quickstart.hpp
While traveling I had a little downtime (everyone else in my group appears to have fallen asleep... but I am not tired since it's the middle of the day) so I decided to fix this quick issue. :)
The Python quickstart documentation is currently incorrect, as pointed out by #1795.  This quick patch fixes it.
I've manually updated the pages on the website to work around the issue.
> Fix PyPI documentation error.

- .appveyor.yml
This is intended to handle #1942.  I think it will work, but I need to test using the generated AppVeyor artifact first.  The goal is just to have `german.csv` in the `sample-ml-app\data\` directory upon install.
> Copy data for sample Windows installer

- src/mlpack/bindings/python/PythonInstall.cmake
This is @marcespie's patch from #1963.  Thanks Marc!
> Fix stray quotes during Python install.

- src/mlpack/methods/det/dt_utils_impl.hpp
gcc 9.1.1 throws errors like
```
src/mlpack/methods/det/dt_utils_impl.hpp:189:3: error: ‘folds’ not specified in enclosing ‘parallel’
src/mlpack/methods/det/dt_utils_impl.hpp:192:33: error: ‘testSize’ not specified in enclosing ‘parallel’
src/mlpack/methods/det/dt_utils_impl.hpp:194:61: error: ‘cvData’ not specified in enclosing ‘parallel’
```
These variables are used inside `omp parallel for default(none)` clause and they are not marked as `shared`. Looks like the previous versions of gcc didn't throw any errors since the variables are declared as `const`.
> [Ready] gcc-9 build fixes

- src/mlpack/methods/radical/radical.cpp
- src/mlpack/tests/main_tests/radical_test.cpp
Hi, 
This is a fix for failing `radical test` during the build. 
Following are the observations. 
1. `RadicalDiffNoiseStdDevTest`, `RadicalDiffReplicatesTest`, `RadicalDiffAnglesTest`, `RadicalDiffSweepsTest` fail occasionally. They failed `21` times in `10000` iterations. 
2.  After digging in it is being found `The covariance matrix` is not correctly remade after decomposing it during `whitening` of the `data matrix`.  
3. Earlier the output was exploding the values were coming in the range `1e7 to 1e14`. After modification the output is coming in `0 to 1` range. 
I am quite new to `ICA`. So, let me know if this is wrong.
> Fix failing radical test.

- .appveyor.yml
- src/mlpack/methods/linear_svm/linear_svm_function_impl.hpp
@gmanlan pointed out in #1863 that the AppVeyor build configuration doesn't actually use Visual Studio 2017 like it's supposed to.  This is an attempt to fix that.  (And if it works, I'll also add Visual Studio 2019 to the build matrix.)
> Use correct Visual Studio version in AppVeyor

- CMake/RunProgram.cmake
- src/mlpack/core/util/mlpack_main.hpp
- src/mlpack/core/util/param.hpp
- src/mlpack/methods/kde/kde_main.cpp
While skimming through various emails I noticed that the nightly job that builds the mlpack-git Markdown documentation was failing.  That means that https://mlpack.org/doc/mlpack-git/cli_documentation.html will 404 until we get this fix incorporated (I suppose that I could rebuild after hand-patching, but I'd prefer to just merge this and then the problem goes away on its own).
But, this Markdown binding generation failure didn't actually trigger any build failure or anything like this.  So I did some digging and came up with these changes:
1) Make any programs executed by CMake cause a fatal error if those programs themselves fail.
2) Remove use of `PRINT_PARAM_STRING()` macro inside of documentation for an individual program option.  The reason for this is that `PRINT_PARAM_STRING()` …
> Fix Markdown binding issue

- HISTORY.md
- src/mlpack/core/tree/cover_tree/cover_tree_impl.hpp
- src/mlpack/methods/kde/kde_rules_impl.hpp
Frequently, the test `KDETest/EpanechnikovCoverSingleKDETest` fails:
http://ci.mlpack.org/job/docker%20mlpack%20nightly%20build/armadillo_version=armadillo-6.500.5,boost_version=boost_1_49_0,buildmode=debug,compiler_version=gcc-7.2.0,label=docker/lastCompletedBuild/testReport/
```
[Exception] - difference{37.9501%} between bfEstimations[i]{0.6164662373649441} and treeEstimations[i]{0.99350104568814213} exceeds 8%
== [File] - /home/jenkins/workspace/docker mlpack nightly build/armadillo_version/armadillo-6.500.5/boost_version/boost_1_49_0/buildmode/debug/compiler_version/gcc-7.2.0/label/docker/repo/src/mlpack/tests/kde_test.cpp
== [Line] -233
```
I spent some time digging into this and this was kind of a funny bug to dig into.  I first determined that some of the prunes were invalid---it …
> Fix intermittently failing Epanechnikov kernel KDE test

- src/mlpack/core/tree/cover_tree/cover_tree_impl.hpp
- src/mlpack/methods/fastmks/fastmks_main.cpp
- src/mlpack/tests/load_save_test.cpp
- src/mlpack/tests/main_tests/fastmks_test.cpp
I dug into #1767 and found that the issue is actually not the fact that the hyperbolic tangent kernel is only conditionally positive definite.  Instead, for the optdigits dataset, the issue is that the dot product between each point is sufficiently large that every kernel evaluation is identical---meaning that the distance between points is always 0.
This then means that the cover tree gets built in a weird way that is actually invalid.  So I fixed this bug in e584aea.
While I was in there, I also made the FastMKS binding check for a valid value of k, if it is passed, and added a test for it.  And I hid the `Log::Fatal` output from the one test that tries to load `nonexistentfile.arff`. :)
> FastMKS segfault fix

- src/mlpack/methods/cf/normalization/z_score_normalization.hpp
Writing a zero to a sparse matrix causes the element to be deleted. The zero is then immediately overwritten by a non-zero value.  When using iterators, this is horribly inefficient: memory re-allocation + copying.  It also has the potential to screw up the validity of the sparse matrix iterators.
> fix: avoid writing zero via sparse matrix iterator

- src/mlpack/methods/cf/normalization/item_mean_normalization.hpp
- src/mlpack/methods/cf/normalization/overall_mean_normalization.hpp
- src/mlpack/methods/cf/normalization/user_mean_normalization.hpp
More fixes in the same vein as #1989
Writing a zero to a sparse matrix causes the element to be deleted. The zero is then immediately overwritten by a non-zero value. When using iterators, this is horribly inefficient: memory re-allocation + copying. It also has the potential to screw up the validity of the sparse matrix iterators.
> more fixes to avoid writing zero via sparse matrix iterator

- src/mlpack/methods/cf/normalization/combined_normalization.hpp
- src/mlpack/methods/cf/normalization/item_mean_normalization.hpp
- src/mlpack/methods/cf/normalization/overall_mean_normalization.hpp
- src/mlpack/methods/cf/normalization/user_mean_normalization.hpp
- src/mlpack/methods/cf/normalization/z_score_normalization.hpp
- src/mlpack/tests/cf_test.cpp
On macOS double-precision serialization is not lossless, using float is probably the easiest solution here.
> double-precision serialization is not lossless

- src/mlpack/tests/q_learning_test.cpp
- src/mlpack/tests/reward_clipping_test.cpp
The previous version failed once in 100 runs (due to the limited model size and test time), so to make this even more stable I just run the test multiple times.
> DQN reward-clipping test adjustments.

- src/mlpack/tests/rl_components_test.cpp
since we use a random action there is no guarantee that we will reach the maximum number of steps.
> Fix Pendulum task max steps test

- src/mlpack/tests/linear_svm_test.cpp
Sometimes we can get unlucky and L-BFGS won't optimize quite right.  I ran about 60k trials of the test and there were 5 failures, so I increased the tolerance so that none of those failures would have happened.
> Increase Linear SVM test tolerance slightly

- src/mlpack/tests/lsh_test.cpp
I was surprised to find, when digging, that the LSH `MultiprobeTest` failure is actually caused by points having the exact same distance from each other (and the random projections being *just right* to cause the failure).  So, we can work around this by randomly adding some noise to the iris dataset.  I ran about 6000 trials and had no failures; I expect that this test will not fail anymore.
This fix is part of #1993.
> Fix very occasional LSH test failures

- src/mlpack/tests/main_tests/knn_test.cpp
In `KNNMainTest/KNNAllTreeTypesTest`, I found out that the tree type, `r-plus`, failed with the seed `1567791088`, so I increased `k` from 10 to 15 to make this test robust.
During about 4,000 iterations with random seeds, any error didn't happen.
> Fix `KNNMainTest/KNNAllTreeTypesTest` 

- src/mlpack/tests/rbm_network_test.cpp
I saw the test fail in one of the recent build matrix jobs, so I thought we should loosen this tolerance just a bit.  I do believe the ssRBM is still working fine.  This is related to #1993.
> Widen tolerance for ssRBMClassificationTest

- HISTORY.md
- src/mlpack/core/math/random.hpp
- src/mlpack/methods/gmm/gmm_train_main.cpp
- src/mlpack/tests/main_tests/gmm_train_test.cpp
I found a number of things that needed to be rewritten here, and in order to properly get these tests to succeed, I also had to add a `kmeans_max_iterations` option to the binding (which I also added a test for).  It was a little more involved than I had hoped.
> Fix intermittent failures in GMMTrainMainTest

- src/mlpack/tests/data/braziltourism.arff
- src/mlpack/tests/data/braziltourism_test.arff
- src/mlpack/tests/main_tests/decision_tree_test.cpp
I was trying to debug some occasional `DecisionTreeMainTest` bugs that I've seen in the past.  I found a few in `main_tests/decision_tree_test.cpp`, and now this test runs without any valgrind issues.
I also found that when `braziltourism.arff` was added, the labels were stripped and placed in a different file---but the `@attribute` for those labels wasn't removed.  That meant that mlpack was loading an extra column of garbage every time, which could (depending on a lot of things) occasionally cause issues.
> Fix occasional `DecisionTreeMainTest` bugs

- .travis.yml
- src/mlpack/methods/reinforcement_learning/q_learning.hpp
- src/mlpack/methods/reinforcement_learning/q_learning_impl.hpp
- src/mlpack/methods/reinforcement_learning/worker/n_step_q_learning_worker.hpp
- src/mlpack/methods/reinforcement_learning/worker/one_step_q_learning_worker.hpp
- src/mlpack/methods/reinforcement_learning/worker/one_step_sarsa_worker.hpp
- src/mlpack/tests/feedforward_network_test.cpp
I was surprised to find that parts of mlpack depend on parts of the ensmallen API that changed between ensmallen 1 and ensmallen 2.  Specifically, the changes were to the `UpdatePolicy` types for ensmallen; now, because the ensmallen optimizers can take any type, the `UpdatePolicy` classes like `VanillaUpdate` and `AdamUpdate` got a lot more complex.
I reworked the code as necessary to handle these changes.  At some point, we can bump our minimum required version of ensmallen to 2.10.0 and then we can remove the `#if`s that I had to put all over the place.
This fixes #2008 from the mlpack side (there is also mlpack/ensmallen#131).
> ensmallen 2 compatibility fixes

- src/mlpack/tests/decision_tree_test.cpp
I spent a long time trying to reproduce this on my system but I found that it only happens on a specific version of LLVM when compiling without debug symbols.  This suggested that valgrind was needed, which definitely exposed what the bug was: an invalid index.
The only thing that's not clear is what I was thinking when I wrote that code! :)  89c5566596 was the offending commit.
> Fix `DecisionTreeTest/PerfectTrainingSet`

- .appveyor.yml
- .travis.yml
- .travis/config.hpp
- HISTORY.md
- README.md
- doc/guide/build.hpp
- src/mlpack/core/util/arma_config_check.hpp
- src/mlpack/methods/linear_svm/linear_svm_impl.hpp
- src/mlpack/tests/cf_test.cpp
This should fix the Travis build, updates the documentation, and should also remove some now-unnecessary code.
> Update Armadillo to minimum version of 8.400.0.

- src/mlpack/tests/q_learning_test.cpp
Sometimes we can get unlucky with the initial state and the restricted settings we are using for the test, so I slightly increased the number of trails and optimized the network architecture.
> Fix occasional `QLearningTest/DoublePoleCartWithDQN` failure.

- src/mlpack/tests/linear_svm_test.cpp
In order to work around mlpack/ensmallen#136, I adapted the `LinearSVM` tests that use `ens::L_BFGS` to run multiple times and added comments pointing out why multiple trials are run.
See also #1993.
> LinearSVM test workarounds

- src/mlpack/tests/hmm_test.cpp
- src/mlpack/tests/main_tests/gmm_train_test.cpp
It took me a long time to debug `GmmTrainMainTest/GmmTrainTrialsTest` because it was quite hard to reproduce.  Once I finally did get it reproduced, the error turned out to be pretty simple... just an invalid `std::move()`.
Also, I updated the tolerance for one of the HMM tests based on @sriramsk1999's report in IRC.
I think this is probably the last fix to solve #1993; or, at least, it's the last regularly failing tests I am seeing right now. :)
> Additional test fixes

- CMakeLists.txt
- README.md
- doc/guide/build.hpp
This updates the documentation and the CMake configuration to require ensmallen 2.10.0 or greater.
> Update minimum version of ensmallen.

- CMakeLists.txt
@rcurtin , Did you on purpose leave arma version in CMake, if so please go ahead and close it :)
> Update Armadillo to minimum version of 8.400.0

- CMake/FindEnsmallen.cmake
- HISTORY.md
@jeffin143 noticed in IRC that if even old ensmallen versions are installed, CMake will still successfully configure (but then fail to build).
After a little while of digging I discovered that one single character is the culprit:
Since we call `find_package(Ensmallen ...)`, which calls `FindEnsmallen.cmake`, we must use the name `Ensmallen` not `ensmallen` in the call to `find_package_handle_standard_args()`, otherwise the version check is not enforced.
> Enforce ensmallen version check

- src/mlpack/methods/ann/ffn.hpp
- src/mlpack/tests/feedforward_network_test.cpp
Expose the the instantiated network; see https://github.com/mlpack/mlpack/issues/2041 for more details.
> Expose the instantiated network.

- HISTORY.md
- README.md
- doc/guide/python_quickstart.hpp
Finally, after quite a long time, I've managed to get control of the `mlpack` package name on PyPI:
https://pypi.org/project/mlpack/
And now that the mlpack/mlpack-wheels repository is successfully uploading wheels, we can update the documentation to point out that you can simply do `pip install mlpack` (at least on OS X and manylinux systems---Windows is still in progress).
I also found that `conda-forge` packages mlpack so we can reference them in our documentation.
> Update documentation to point to correct pip and conda packages

- src/mlpack/core/dists/gaussian_distribution.hpp
this APIs are needed when one wants to deploy a trained hmm model into a different implementation using the parameters obtained by mlpack training methods.
I am personally using it to deploy a HMM model into a bare metal embedded platform written in C.
> added api to access cov specs of gmm

- src/mlpack/methods/ann/layer/atrous_convolution.hpp
- src/mlpack/methods/ann/layer/atrous_convolution_impl.hpp
- src/mlpack/methods/ann/layer/convolution.hpp
- src/mlpack/methods/ann/layer/convolution_impl.hpp
It looks like `padding` layer is not serialized in the `convolution` and `atrous` convolution layer. Due to this #1770 was failing.
I have pushed similar changes in #1770 as weil so we can merge this or directly we can merge #1770.
> Serialize padding layer in convolution layer and atrous convolution layer.

- src/mlpack/core/tree/cover_tree/cover_tree.hpp
- src/mlpack/core/tree/cover_tree/cover_tree_impl.hpp
- src/mlpack/core/tree/spill_tree/spill_tree.hpp
- src/mlpack/core/tree/spill_tree/spill_tree_impl.hpp
- src/mlpack/tests/knn_test.cpp
This, along with #2023 is for resolving #1957. In this PR:
- Move/Copy Assignment for SpillTree/CoverTree
- Tests for both
However, on compiling, I get a massive number of errors which fill my terminal window completely. These errors take place for the target mlpack_approx_kfn.  
I have narrowed down the problem area to the commented code in Copy Assignment of SpillTree. I would like some help debugging this error :)
> Move/Copy Assignment operators for CoverTree and SpillTree

- src/mlpack/tests/cf_test.cpp
I looked into the random failures that were showing up in #2058 and spent a little while debugging.  The `BiasSVD` algorithm does seem to give worse results than the other algorithms, failing much more often.  So I adjusted the tolerance.
@zoq we can merge this, or you can cherry-pick the commit into #2058 and we can close this---up to you.
> Fix random failures for RecommendationAccuracyBiasSVDTest`

- GOVERNANCE.md
As a part of our acceptance to NumFOCUS, we've been asked to formalize our governance procedures.  In the past I don't think we've found this necessary, but it certainly can't hurt.  In this draft I've tried to formalize the procedures that pretty closely reflect what we already do.
This is open for comments from anyone!  If you have any comments, please feel free to add them and we can discuss.
I'll merge this (in whatever form it ends up being) a week after discussion ends, to give time for anyone to comment.
> Governance guidelines

- src/mlpack/methods/neighbor_search/neighbor_search_impl.hpp
- src/mlpack/methods/range_search/range_search_impl.hpp
This fixes #2078.  Thanks @HugoSoszynski for pointing this out.  It was pretty straightforward to dig into `RangeSearch` and figure out that we were leaving the `referenceSet` pointer dangling and not deleting it.
So, instead, when a `RangeSearch` object is being constructed with default arguments, we avoid allocating a matrix for `referenceSet` unless `naive` is true, and instead construct `referenceTree` on a temporary `arma::mat()` that we `std::move()` to the tree constructor.
The same issue existed in `NeighborSearch` so I modified that also.
> Fix memory handling issues of RangeSearch and NeighborSearch.

- src/mlpack/methods/ann/layer/fast_lstm.hpp
- src/mlpack/methods/ann/layer/lstm.hpp
This comes out of the discussion for #2048, where part of the issue is that the `LSTM` layer must be preceded by the `IdentityLayer` if it's intended to be used as the first layer of the network.  I've just added some documentation to that for the `LSTM` and `FastLSTM` layer.  (I am not sure it applies to both, but I *think* that it does.)
This may not be the best place for this documentation, but I'm not sure where else to put it, so if anyone has any better suggestions just let me know.  Alternately, removing the need for the `IdentityLayer` is a possibility, but I don't know how easy that is.  (I suppose, I could just open an issue for it?)
> Update LSTM documentation to indicate need for IdentityLayer

- .github/FUNDING.yml
GitHub opened up the Sponsors tool. It allows financial support for developers and projects, since we are part of NumFOCUS this will be handled by NumFOCUS.
> GitHub + NumFOCUS Sponsor button.

- HISTORY.md
- src/mlpack/methods/ann/layer/atrous_convolution.hpp
- src/mlpack/methods/ann/layer/atrous_convolution_impl.hpp
- src/mlpack/methods/ann/layer/convolution.hpp
- src/mlpack/methods/ann/layer/convolution_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
Hi,
I have modified `convolutional` layer. But I have a doubt. Should we take all four padding dimension's as an argument in `convolution.hpp`. Currently we only take two dimension as argument in `constructor`. I have kept it as it is for now. I think taking all four padding dimension's would be good but it may break backward compatibility. Let me know what you think.
> Valid and Same padding option in convolution layers.

- .github/FUNDING.yml
Add a custom link to point to the form located at numfocus.org, which is now online.
> Sponsor button - custom link

- README.md
While waiting for my space station in Kerbal Space Program to achieve the right orbit, I modified the `README.md` to include attribution for NumFOCUS as described here: https://github.com/numfocus/templates/blob/master/fiscal-sponsor-readme-attribution.md
> Add attribution for NumFOCUS to README.md

- CMake/CheckHash.cmake
- CMakeLists.txt
- COPYRIGHT.txt
- HISTORY.md
Validation is done by a macro which takes .md5 file URL and the file
directory. On hash failure the downloaded files are deleted. Currently
used for stb library only.
> Add md5 validation for downloaded libraries

- HISTORY.md
- src/mlpack/CMakeLists.txt
I edited `src/mlpack/bindings/python/CMakeLists.txt` to append the mlpack version to `__init__.py`. By doing that, we can check the mlpack version in Python code, using the command below. (However, although I tried to place the `__version__` at the bottom of the file, I couldn't find any good way.)
**[Result]**
**[Image]**
> Add mlpack version to __init__.py

- .ci/ci.yaml
- .ci/linux-steps.yaml
- src/mlpack/methods/ann/layer/layer_types.hpp
- src/mlpack/methods/ann/layer/weight_norm_impl.hpp
- src/mlpack/tests/CMakeLists.txt
BOOST_ROOT is now set in the azure v2017 image (relevant change seems to be [1], pre-installing boost).
Remove BOOST_ROOT from the environment to prevent attempting to use a
boost which is incompatible with the compiler.
[1] microsoft/azure-pipelines-image-generation#732
> unset BOOST_ROOT (azure pipelines)

- CMakeLists.txt
It seems like for the coverage build to work correctly, it needs to link against `libquadmath`.  Check out the errors from Jenkins:
```
[ 17%] Linking CXX executable ../../../../bin/mlpack_adaboost                                                                                                 
/usr/bin/ld: CMakeFiles/mlpack_adaboost.dir/adaboost_main.cpp.o: undefined reference to symbol 'isnanq@@QUADMATH_1.0'                                         
//usr/lib/x86_64-linux-gnu/libquadmath.so.0: error adding symbols: DSO missing from command line                                                              
collect2: error: ld returned 1 exit status …
```
> Fix coverage build by linking against quadmath

- CMake/mlpack_coverage.in
I thought that #2094 would fix the coverage build, but it looks like there's one more problem---the test scripts don't run because the paths contain spaces.  These changes should hopefully make the test scripts run correctly.
> Handle paths with spaces in coverage script

- CMakeLists.txt
This fixes #2097.  Our CMake configuration looks at the list of libraries used at link time, and then converts things like `/usr/local/lib/libarmadillo.so` into `-L/usr/local/lib/ -larmadillo`.  The only thing is, the regular expression I wrote hardcoded the `.so` extension, but that's not right for OS X, where the extension is `.dylib`.  I adjusted the regular expression to handle any extension, and also fixed uses of `.` (which matches any character) to `[.]` (which only matches the period).
Thanks @tomjpsun for pointing out the issue! :+1:
> Fix pkgconfig regular expression

- CMakeLists.txt
After dealing with some Boost CMake issues with Boost 1.70 for a while (and the comment in #2097), I spent some time today reading into what is actually going on.  My conclusion is this:
* CMake 3 is a complete redesign of CMake and prescribes a totally new way of writing CMake configuration scripts that depend on imported targets, instead of `find_package()` calls that set a bunch of variables.
* According to that line of thought, the entire way we are doing our CMake configuration is dogmatically "wrong": https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/
* Boost 1.70 now, by default, uses this new CMake approach to import targets, even when the `MODULE` parameter is passed to `find_package()` (which is supposed to force "the old way").
* I don't have any desire to …
> Force Boost_NO_BOOST_CMAKE to be on

- CMakeLists.txt
- HISTORY.md
- src/mlpack/bindings/julia/CMakeLists.txt
#1949 attempted to add the following behavior:
- If the user does not set `BUILD_JULIA_BINDINGS`, then build Julia bindings if Julia is available, but if Julia isn't available, don't crash during configuration.
- If the user *does* set `BUILD_JULIA_BINDINGS` to `ON`, then fail during configuration if Julia isn't found.
- If the user sets `BUILD_JULIA_BINDINGS` to `OFF`, don't search for Julia or build Julia bindings at all.
It turns out that this behavior is actually quite difficult to get, and actually the current implementation has a bug so that if you run `cmake` twice and don't have Julia available, there will be a configuration failure.  So I have removed the auxiliary variables that control it and set the behavior to the same as the Python bindings, which is that they are built if …
> Remove "smart" handling of `BUILD_JULIA_BINDINGS`

- src/mlpack/methods/ann/layer/atrous_convolution.hpp
- src/mlpack/methods/ann/layer/convolution.hpp
- src/mlpack/methods/ann/layer/linear_no_bias.hpp
- src/mlpack/tests/ann_layer_test.cpp
1. Add accessor and mutator functions for the padding dimensions of the Convolution Layer.
2. Add accessor function for obtaining the input and output dimensions of the LinearNoBias layer.
> Add mutator and accessor functions for some layers

- COPYRIGHT.txt
- doc/guide/build_windows.hpp
Update the Visual Studio version to VS2019, tool set version to v142, and corresponding CMake commands.
Add extra instructions to ensure CMake can run correctly.
> Update the tutorial for building mlpack from source on Windows

- src/mlpack/methods/gmm/em_fit_impl.hpp
- src/mlpack/methods/gmm/gmm.cpp
When training a HMM or GMM model with high dimension data, the model parameters overflow resulting in `nan` or `inf` value. This can be addressed by doing all calculation in log space.
> convert claculation to log space for em_fit

- CMake/FindStbImage.cmake
- HISTORY.md
I noticed that people often get STB include bugs.  This happens because the `FindStbImage.cmake` file will actually append `stb/` to the end of the CMake variable representing the STB include path.  When CMake reconfigures, it will append `stb/` even if the include directory has already been found, so you can end up with STB include directories like `/home/ryan/src/mlpack/build/deps/stb/stb/` which isn't correct.
So, I replaced that functionality with a regex that checks to see whether the include directory ends in `stb`, and only adds `stb/` if that is *not* the case.
@mulx10 let me know what you think of this. :+1:
> Safer adding of stb/ suffix to include directory.

- src/mlpack/CMakeLists.txt
- src/mlpack/bindings/python/ConfigureSetup.cmake
- src/mlpack/bindings/python/setup.py.in
All the Jenkins builds started failing yesterday with a mysterious error!  When I dug into it, I found that paths with spaces were not being handled correctly when configuring the Python bindings.  I think that the actual proximate cause of why this build failure started happening now is that a system upgrade on mlpack.org caused the versions of mlpack's Python dependencies to be new enough that the bindings started being built---and since the jobs on Jenkins have spaces in their names, their paths on disks therefore have spaces in the names, and this now caused the code to fail.
The patch here should fix that by handling more carefully when directories have spaces in them.  That required a little bit of strangeness in the `setup.py` itself, but it seems to work.
We'll see if it builds …
> Fix handling of directories with spaces for CMake Python binding configuration

- doc/tutorials/ann/ann.txt
This PR has 2 changes, which might not be apparent due to a single commit. The changes are as follows:
1. Updated a variable name :  `trainLabelsTemp` to `trainLabels`. Otherwise the example would not compile giving a `undeclared Variable Error`. [This change was necessary]
2. Added Header files, namespace and main(), so that the code is an easy-run copy-paste kind. [This is a suggested Change]
> doc: fixed variable name issue & added header files

- .ci/macos-steps.yaml
Hi everyone, since across multiple PRs the CTest fails on OSX-python27, I found a quick fix to remedy the situation. Kindly have a look.
Thanks.
> Quick-Fix OSX-python27 Bind error.

- src/mlpack/core/dists/gaussian_distribution.cpp
- src/mlpack/core/math/lin_alg.cpp
- src/mlpack/core/math/lin_alg.hpp
- src/mlpack/methods/gmm/eigenvalue_ratio_constraint.hpp
- src/mlpack/methods/gmm/gmm.cpp
- src/mlpack/methods/gmm/positive_definite_constraint.hpp
- src/mlpack/methods/kernel_pca/kernel_rules/naive_method.hpp
- src/mlpack/methods/kernel_pca/kernel_rules/nystroem_method.hpp
- src/mlpack/tests/lin_alg_test.cpp
Handling : https://github.com/mlpack/mlpack/issues/1840
@conradsnicta - Let me know if I am missed something.
> fix:don't assume that arma::eig_sym() always succeeds

- doc/guide/build.hpp
These packages aren't available on the versions of Ubuntu that many people appear to be using (see, for instance, #2232, and the question seems to get asked a lot in IRC).
So, this clarifies the documentation to point out that those packages are only available on 19.10 and newer, and then also points out that CMake will (currently) automatically download those dependencies if they are not found.
It also bumps the version indicated in the documentation, which apparently wasn't done at the time of the last release. :)
> Clarify availability of libensmallen-dev and libstb-dev.

- README.md
- src/mlpack/bindings/julia/CMakeLists.txt
- src/mlpack/bindings/julia/mlpack/Project.toml.in
As part of the Julia package registration process, it was requested that I specify a version of Julia with which the package is compatible.  It turns out that `julia = "1.3"` actually means it'll be compatible with any 1.x release.
The change is already in the new mlpack/mlpack.jl repository, but better to push it back here to reduce the amount of work needed for the manual deployment of new Julia binding versions.
> Add specific versions of dependencies for Julia.

- .ci/linux-steps.yaml
Python Bindings test fails across multiple PR ever since zipp released 3.1 version. The issue can be referenced from this [link](https://github.com/jaraco/zipp/issues/48). I think they will fix it soon but incase it takes a while here is a solution that should work.
> Quick Fix Python Ctest Binding Failure

- README.md
So after an IRC discussion, I've added the NumFOCUS badge to the mlpack page along with the code coverage and build status badges. 
Obviously, I'm biased in thinking that this looks good so let me know what all of you think :)
> New NumFOCUS badge mockup

- src/mlpack/methods/ann/loss_functions/log_cosh_loss.hpp
I found this morning that the master build fails with gcc 9.2.1.  This change fixes an incorrect return type, which caused the compilation issue.  I'm not sure how many other compilers catch this issue (it seems like most of the CI tests are passing).  Anyway, easy fix.
> Fix return type of A().

- src/mlpack/methods/ann/layer/max_pooling.hpp
- src/mlpack/tests/ann_layer_test.cpp
In order to solve #2252, I started testing pooling layers with some inputs. Mean pooling layer works fine for all kind of inputs however maxpooling layer gives the following error on testing with rectangular inputs.
```
fatal error: in "ANNLayerTest/MaxPoolingTestCase": std::logic_error: Mat::submat(): indices out of bounds or incorrectly used
/Users/Open-Source/mlpack/src/mlpack/tests/ann_layer_test.cpp:3039: last checkpoint: "MaxPoolingTestCase" test entry
```
The same inputs work on PyTorch.
I think I have the fix, if it fails across multiple devices I will add it in the next commit.
Please forgive me if I have made a blunder that makes this happen.
Thanks.
> Pooling Tests fail on Rectangular inputs?

- src/mlpack/tests/ann_layer_test.cpp
So recently #2265 was merged, Unfortunately it wasn't tested / rebased after PR #2259, Where switch from r-value references was made. Due to this reason the tests still used `std::move` so this is a PR to fix that. Kindly merge this as soon as you can to fix the build. This is something that requires urgent attention, we can't let the build fail.
Thanks.
> Fix build according to r-value tests [Urgent]

- src/mlpack/bindings/markdown/print_docs.cpp
> 2. Make it so that any time programInfo.documentation() is called from any function in src/mlpack/bindings/markdown/, any instances of | are properly escaped (assuming that escaping works with Kramdown). Note that in src/mlpack/bindings/markdown/, any functions just call out to different bindings languages.
This hopefully fixes issue #2270 (escaping does work in kramdown! :)). This should take care of the "|" symbol issue in the markdown for all bindings.
> Fixed markdown pipe symbol issue

- .ci/windows-steps.yaml
- src/mlpack/bindings/julia/CMakeLists.txt
- src/mlpack/bindings/julia/julia_util.cpp
- src/mlpack/bindings/julia/julia_util.h
- src/mlpack/bindings/julia/mlpack/cli.jl.in
- src/mlpack/bindings/julia/print_input_processing_impl.hpp
I mistakenly thought that Julia's `Int` type always matched C/C++'s `int` type; this is incorrect---Julia's `Int` type instead matches `size_t`.  Therefore, we have to use the `Cint` type in Julia.  This PR fixes that and all associated handling, and should fix the currently-failing Julia build.
> Use Cint to match C++'s int type, not Julia's Int.

- src/mlpack/methods/ann/layer/elu.hpp
Small fix, I realized ELU didn't have a Deterministic() function. This PR adds it
> Added Deterministic() function to ELU

- src/mlpack/tests/adaboost_test.cpp
- src/mlpack/tests/convolutional_network_test.cpp
- src/mlpack/tests/feedforward_network_test.cpp
In a recent pull request of mine (#2276 ), @rcurtin recommended a better way of computing error between predicted and ground truth labels using "arma::accu". This resulted in cleaner code, and I saw quite a few instances in mlpack test files that could benefit from this clean up as well.
This doesn't have to be merged if it isn't necessary. I thought I'd make this suggestion, that's all :smile:
> Cleaner code for a few test files

- .ci/windows-steps.yaml
- HISTORY.md
- src/mlpack/methods/lars/lars.cpp
- src/mlpack/methods/lars/lars.hpp
- src/mlpack/tests/lars_test.cpp
This is basic implementation to compute cost error for lars fix:#1735 . In this method I only implemented 
||Y-beta*x|| method to calculate error
> Adding ComputeError function in lars class

- src/mlpack/core/arma_extend/arma_extend.hpp
This is based on the findings in https://github.com/Homebrew/homebrew-core/issues/52003 and Conrad's workaround in https://gitlab.com/conradsnicta/armadillo-code/-/commit/0166bc036c5c6754402f60b0b2ffeb0914ea2939.
In essence, the breakages in the OS X builds are caused by HDF5 updating from 1.10 to 1.12 and this is a reverse-incompatible change (!).  So this replicates Conrad's fix for new versions of Armadillo, which is to force the HDF5 1.8 API.  We do the same here, since it will still be needed for older versions of Armadillo.
See also #2320 and related issues.
Let's see if it builds successfully...
> Alternate Homebrew HDF5 fix

- src/mlpack/methods/ann/layer/concat_performance_impl.hpp
- src/mlpack/methods/ann/layer/reinforce_normal.hpp
- src/mlpack/methods/ann/layer/reinforce_normal_impl.hpp
- src/mlpack/methods/ann/loss_functions/huber_loss_impl.hpp
- src/mlpack/methods/ann/loss_functions/kl_divergence_impl.hpp
- src/mlpack/methods/ann/loss_functions/log_cosh_loss_impl.hpp
Hi everyone, I noticed some parameters weren't serialized in some layers while I was going through concat layer. So I took a look at other layers as well and added serialization for them as well. This is an attempt to fix the same. I would love to hear your thoughts regarding this.
Hopefully last Bugfix before the release.
Thanks.
> Serialization Fix for some ANN layers.

- doc/tutorials/ann/ann.txt
I followed a few closed issues #1415 , #1525, #1532 where people had trouble with the first tutorial (a simple feed forward network for the thyroid dataset) on this page `https://www.mlpack.org/doc/mlpack-3.2.2/doxygen/anntutorial.html`. I believe this chain of issues culminated with @rcurtin 's closed pull-request #1534 , where he changed the dataset itself from three rows of "one-hot-encodings labels" to a single row of "scalar labels". This led to more cleaner code in the corresponding test files (you could checkout the pull request).
If I'm not mistaken the tutorial on the mlpack page hasn't caught up with this change, and so trip up beginners when trying to get the example to run. I noticed that #2150 had a made a few changes in this regard (included headers and fixed variable …
> Improved ANN Tutorial for FFN - Thyroid Dataset Example

- src/mlpack/core/arma_extend/arma_extend.hpp
This is a based on a [suggestion](https://github.com/mlpack/mlpack/commit/682d25f69b14b159a2ff44393aaa638f3a14588d#commitcomment-38061822).  Thanks @conradsnicta! :+1:
> Use HDF 1.10 API instead of 1.08.

- HISTORY.md
- src/mlpack/methods/ann/loss_functions/CMakeLists.txt
- src/mlpack/methods/ann/loss_functions/cosine_embedding_loss.hpp
- src/mlpack/methods/ann/loss_functions/cosine_embedding_loss_impl.hpp
- src/mlpack/tests/loss_functions_test.cpp
In reference to issue #2200, I have implemented cosine embeddings.
Use Cases:
1. Get Cosine Similarity or dissimilarity between two vectors.
2. Useful in text classification.
3. Useful in face recognition (embedding based).
4. Clustering.
It is implemented in Pytorch, documentation can be found [here](https://pytorch.org/docs/stable/nn.html#cosineembeddingloss).
Test cases can be found [here](https://colab.research.google.com/drive/1Epmw0TKK20OILNOc1hTLA_cnBCmuBtE3#scrollTo=pyjnHHpQJvOm).
> Add Cosine Embeddings.

- src/mlpack/core/util/arma_traits.hpp
This patch corrects handling of Armadillo vector types by `IsVector`.
Without this patch, mlpack will not compile with Armadillo 9.870 (and development version 9.869).
Armadillo 9.870 has extended handling of sparse submatrix views. In addition to `arma::SpSubview`, it now has `arma::SpSubview_col` and `arma::SpSubview_row`.  The latter two types are vector types, so `IsVector` needs to be adjusted accordingly.
> corrections to handle vector types in Armadillo 9.870

- HISTORY.md
- src/mlpack/methods/logistic_regression/logistic_regression_impl.hpp
- src/mlpack/methods/softmax_regression/softmax_regression_impl.hpp
- src/mlpack/tests/logistic_regression_test.cpp
This PR fixes #2358.  I actually had it ready a few hours ago but then life happened to me and I hadn't clicked the 'create pull request' button yet. :)
Basically, what I found was that when a `LogisticRegression` object is created, it sets a `parameters` vector that is used for the initial point during training.  However, if the object is created and then `Train()` is called with a parameter vector of a different size, then training will fail!
So, this PR fixes that by ensuring that the parameters vector used for training is the same size as expected by the model.  I also found a similar bug in `SoftmaxRegression`.
I've added the original test case to the test cases for logistic regression, too. :)
Thanks to @trento89 for finding the issue! :+1:
> Fix LogisticRegression parameter size 

- HISTORY.md
- src/mlpack/CMakeLists.txt
While packaging mlpack 3.3.0 for Fedora, I found that the CXXFLAGS used for compilation of mlpack (and set via `CMAKE_CXX_FLAGS`) weren't actually being used by Cython when compiling the Python bindings.  After some digging I realized why: `CMAKE_CXX_FLAGS` is not actually set to the project's `CMAKE_CXX_FLAGS` when the `ConfigureSetup.cmake` script is called to turn `setup.py.in` to `setup.py`.  That means the `cxx_flags` variable in `setup.py.in`, which is set like this:
```python
cxx_flags = '${CMAKE_CXX_FLAGS}'.strip()
```
was actually being set to the empty string.
This PR fixes that by explicitly setting `CMAKE_CXX_FLAGS` as a CMake variable when calling `ConfigureSetup.cmake`.
> Pass CXXFLAGS correctly to Python build

- src/mlpack/methods/ann/activation_functions/elish_function.hpp
- src/mlpack/methods/ann/activation_functions/hard_sigmoid_function.hpp
- src/mlpack/methods/ann/activation_functions/identity_function.hpp
- src/mlpack/methods/ann/activation_functions/lisht_function.hpp
- src/mlpack/methods/ann/activation_functions/logistic_function.hpp
- src/mlpack/methods/ann/activation_functions/mish_function.hpp
- src/mlpack/methods/ann/activation_functions/rectifier_function.hpp
- src/mlpack/methods/ann/activation_functions/softplus_function.hpp
- src/mlpack/methods/ann/activation_functions/softsign_function.hpp
- src/mlpack/methods/ann/activation_functions/swish_function.hpp
- src/mlpack/methods/ann/activation_functions/tanh_function.hpp
The input parameters of the various activations in ann module have inconsistency in the inputs for calculating derivatives. Some (like tanh) require the **activations** [ i.e. f(x) ] as input while others (like softplus) require the **data** [ i.e. plain x ] as input. 
Since these are different for different activations, having a correct parameter description is necessary, to identify what input (either data or activation) is required for calculating the derivative.
Comments are welcome :)
> Changes in parameter description for activation functions in ANN module

- HISTORY.md
- src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp
- src/mlpack/tests/rl_components_test.cpp
While working with the Pendulum environment, I noticed that it has some bugs which need to be removed:
1) `AngleNormalize` [here](https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp#L205) is used to normalize the angle between -PI to PI just like [here](https://github.com/openai/gym/blob/master/gym/envs/classic_control/pendulum.py#L92). However the current implementation uses `fmod()` which is not the same as `%` used in python for cases of negative numbers. Thus the changes have been made accordingly.
2) The correct reward function [here](https://github.com/openai/gym/blob/master/gym/envs/classic_control/pendulum.py#L44) uses `m*l**2` which means `m*(l^2)` and not `(m*l)^2`.
3) As said …
> Changes in the Pendulum-v0 implementation

- .ci/ci.yaml
This removes the Python 2.7 CI build from Azure Pipelines.
I think that this is a reasonable thing to do, since we keep having trouble with it (due to Homebrew versions, pip versioning issues, and so forth), and since Python 2.7 is EOL anyway.  I think that it will save us time to just remove the build altogether from Azure Pipelines, instead of continually trying to debug it.
Happy to consider other ideas too, I just wanted to propose this as a low-effort possibility.
> Remove Python 2.7 build from OS X.

- src/mlpack/methods/linear_svm/CMakeLists.txt
Looks like this was just overlooked; I think because the linear SVM binding was merged during the development of the Julia bindings.  This PR will make `mlpack.linear_svm()` available from Julia.
> Add Julia binding for linear SVM.

- HISTORY.md
- src/mlpack/methods/lars/lars.cpp
- src/mlpack/methods/lars/lars.hpp
- src/mlpack/tests/lars_test.cpp
Aims to close #2372.
Changes made :
- Add Copy Constructor and Move Constructor.
- Add Copy and Move Assignment Operator.
- Add Tests for assignment and copy constructors. Test were adapted from the one mentioned in #2372.
One thing that requires a close look : Clean up of other object in move Constructor.
Other points:
1. A few other methods also lack this function so they might also fail. I will probably test them and add them maybe in another PR so that we can at least close #2372. That way it will be easy to review as well as easier for me to make changes in other layers as well.
Thanks a lot!
> Add Copy, Move Constructors and Copy, Move Operators for LARS class.

- src/mlpack/methods/adaboost/adaboost_main.cpp
I was showing someone how to use the AdaBoost Julia bindings today and I noticed that the example actually doesn't have any labels---but those are required because AdaBoost is a supervised technique.  This PR fixes that by adding `labels` to the example.
> Fix AdaBoost documentation example

- src/mlpack/methods/lars/lars.cpp
Hi everyone,
Just removing some warnings while building mlpack. Unfortunately I missed them in my PR as they didn't showed up locally.
Thanks.
> Remove -Wreorder warning in  LARS.

- HISTORY.md
- src/mlpack/methods/lsh/lsh_search.hpp
- src/mlpack/methods/lsh/lsh_search_impl.hpp
- src/mlpack/tests/lsh_test.cpp
I was working on a project that involved nearest neighbor search for a very high dimensional dataset (100k+ dimensions) where the only realistic representation is with an `arma::sp_mat`.  However, `LSHSearch` only took `arma::mat`.  So I refactored it such that the input data can now be an `arma::sp_mat`.
This turns out to be easy and not require any additional refactoring---the first step of LSH is to multiply with a (dense) projection matrix, and then past there everything is dense (but much smaller).
It gets nice results; on a subset of my test data which had size 63k dimensions by 123k points (with 0.006% nonzero elements), the LSH structure took 4.3s to build, and then 24s to compute 12 nearest neighbors.  The approximation level was about ~1.2, which isn't so bad.
I can't compare …
> Templatize `LSHSearch` to allow sparse matrices

- src/mlpack/methods/ann/activation_functions/softplus_function.hpp
- src/mlpack/tests/activation_functions_test.cpp
Hey!
While working on https://github.com/mlpack/mlpack/pull/1912, after training for a few iterations, I noticed that every parameter would turn `null`! Turns out that it was because the `Fn` function for `softplus_function` has a small error.
Since softplus turns close to linear for high input values, we can just return x instead of `log(1 + exp(x))`. Because as x goes higher (around 700), `exp(700)` turns infinity, causing null errors in further calculations.
Further, I find `20` to be an acceptable threshold as done [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/activation.py#L662). 
Let me know your thoughts :)
> Forward function update for softplus_function.hpp

- HISTORY.md
- src/mlpack/methods/.vscode/settings.json
- src/mlpack/methods/ann/dists/CMakeLists.txt
- src/mlpack/methods/ann/dists/normal_distribution.hpp
- src/mlpack/methods/ann/dists/normal_distribution_impl.hpp
- src/mlpack/tests/ann_dist_test.cpp
Hey!
The implementation of Normal Distribution in https://github.com/mlpack/mlpack/pull/1912 had a small bug in the `LogProbablity()` function. Also, the backward pass and tests for the class was not present. 
This is an attempt to complete the work, as normal distribution is of use in many places, especially for continuous action space environments in RL module.
For the tests, I have taken 4 random values of `mean`, `sigma` and `x` to produce corresponding LogProbabilites and gradients, and compared it with pytorch's implementation.
I use this snippet to get the `prob`, `dmu` and `dsigma`.
```python
mu = torch.tensor(1.1, requires_grad = True)
std = torch.tensor(0.1, requires_grad = True)
n = Normal(mu, std)
action_tensor = torch.tensor(1.05, requires_grad = False)
log_prob = …
```
> Addition of Normal Distribution to ANN module

- src/mlpack/core/metrics/CMakeLists.txt
- src/mlpack/core/metrics/iou_metric.hpp
- src/mlpack/core/metrics/iou_metric_impl.hpp
- src/mlpack/core/metrics/lmetric.hpp
- src/mlpack/tests/metric_test.cpp
Hey everyone,
This PR aims to add IoU metric to this repo. I need to add more detailed tests for it. Also some metrics such ip_metric don't have tests in `metric_tests.cpp`. Did I miss something?
Also, This metric is for bounding boxes which I would need for NMS and object detection algorithm. I do plan on opening another PR to add mIoU to take as input a matrix where each pixel is label. That is more useful for segmentation so I have left that for now.
Files changed:
- metrics/CMakeLists.txt
- metrics/iou_metric.hpp
- metrics/iou_metric_impl.hpp
- tests/metric_tests.cpp
Changes made :
- Added IoU metric (only for bounding boxes).
- Added a simple test. (will add more soon).
Let me know if I missed something. 
Thanks a ton! 
Regards.
> Add IoU metric for bounding boxes.

- .ci/windows-steps.yaml
I rehosted armadillo-8.400.0.tar.gz somewhere else, so this should fix the Windows builds.
> Don't use masterblaster.mlpack.org anymore in CI steps

- .ci/linux-steps.yaml
Looks like the azure build with `DEBUG=ON` failed across all PR's over the last days, I don't really have any further information so this is more like a shot in the dark.
> Check ci build issue with DEBUG=ON

- HISTORY.md
- src/mlpack/methods/linear_svm/linear_svm_impl.hpp
- src/mlpack/methods/linear_svm/linear_svm_main.cpp
While trying to integrate `linear_svm()` into my company's software, I found two bugs; one simple, one rather subtle:
1. `no_intercept` is backwards---you have to specify `no_intercept` to get an intercept.  This PR corrects the behavior. :)
2. The intercept was not properly being added in the call to `Classify()`.  Specifically, we were using `data.n_rows - 1` to get the index of the intercept in `parameters`---but if there is an intercept, then `data` has one fewer row than `parameters`!  So we should use `parameters.n_rows - 1` instead.
> Fix linear SVM binding bugs

- src/mlpack/methods/lsh/lsh_main.cpp
I was working with `mlpack_lsh` on a project and I wanted to use it like this (from Julia):
```julia
_, _, model = mlpack.lsh(reference=dataset, ...)
```
and then later on in my code, I wanted to do search on only the reference dataset.  (This should be done by leaving `query` unspecified but specifying `input_model`.)
```julia
distances, neighbors, _ = mlpack.lsh(input_model=model, k=5)
```
However, this issues an error---claiming that search can't be done unless `reference` or `query` is specified.  But this isn't true; even the LSH code itself will work correctly if `input_model` is specified (then it takes the reference dataset from the input model as the query set).  So, I've just corrected the error checking.
> Allow using only `--input_model` with `mlpack_lsh`

- doc/guide/julia_quickstart.hpp
- src/mlpack/methods/lsh/lsh_search.hpp
Two things I noticed while poking around today:
1. The Julia quickstart documentation is wrong.  It doesn't return `Dict`s, so I fixed the inaccurate sentence (by removing it).
2. In #2395 it looks like I forgot to return the correct type in the `ReferenceSet()` function.  This didn't trigger a build failure because the function was never called in the tests when `MatType` *wasn't* `arma::mat`.
> Quick Saturday fixes

- src/mlpack/methods/rann/krann_main.cpp
This is a simple one---`GetPrintableParam` was being called with the wrong type, resulting in errors like
```
[FATAL] Attempted to access parameter --input_model as type N6mlpack8neighbor7RAModelINS0_9NearestNSEEE, but its true type is PN6mlpack8neighbor7RAModelINS0_9NearestNSEEE!
```
But... these don't show up in the test suite, because... there is no test for the krann binding!  I guess I closed #1152 too early. :)  I'll open another issue for that.
> Fix type in mlpack_krann binding

- .appveyor.yml
- .ci/linux-steps.yaml
The source (https://ftp.fau.de/) we use to download armadillo has a faulty RAID controller:
"The machine has a faulty RAID controller. Until a replacement part arrives, bad performance and crashes are to be expected. Mirrors will NOT be updated for now. Sorry for the inconvenience."
so switch to another source for now to fix the Linux build jobs.
> ftp.fau.de - faulty RAID controller

- src/mlpack/methods/ann/layer/transposed_convolution_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
Transposed convolution should check for correctness only when output width / height is specified.
In #1493, A check was added in this layer which went on subsequent modifications in further layers. However the drawback of such a check is that if user doesn't pass outputW or outputH to the layer the layer will always give fatal. That means we will always have to specify outputW, outputH. I have added a check to ensure both of them aren't zero.
CC: @zoq
> Bug Fix : Check correctness of shape in Transposed Conv. layer only when output width and height aren't zero.

- src/mlpack/core/util/param.hpp
This is just a fix to some out-of-date documentation.  A long time ago I strangely thought it was a good idea to put massive amounts of effort into a metaprogramming shim that allowed us to have `Serialize()` functions that matched the capitalization style of the mlpack style guide, instead of just using the boost::serialization `serialize()`.  Later, after the surfacing of numerous bugs I realized the entire thing was a bad idea to begin with and removed that entire shim (although it was pretty cool to write!).
This PR just fixes that I apparently forgot to update when I made that change.
> Clarify comment---Serialize() is long gone.

- HISTORY.md
- src/mlpack/methods/approx_kfn/approx_kfn_main.cpp
- src/mlpack/methods/approx_kfn/qdafn_impl.hpp
- src/mlpack/tests/qdafn_test.cpp
While binding mlpack into my company's product, I found that `mlpack_approx_kfn` does not work correctly when searching with `k > 1`. Specifically, all neighbors returned except the last one have distance `-1` and invalid neighbor indices.
I discovered that this bug existed because of an apparent failure in thinking on my part that caused the results to be sorted backwards in the priority queue that collects candidates. When I fixed that, I also had to handle the situation where points could be added to the priority queue multiple times; so I added some deduplication code.
This situation existed in part because it turns out the tests I wrote only test with `k = 1`. So I added some tests that test for greater values of `k` too. :)
> Extract the correct number of neighbors for QDAFN.

- src/mlpack/methods/ann/layer/batch_norm.hpp
- src/mlpack/methods/ann/layer/virtual_batch_norm.hpp
Hey everyone,
I have changed the parameter description for the batch norm layer a bit. From parameter description it wasn't clear to me what units mean, hence added the word 'channels' which is more commonly used. Kindly let me know what you think.
Regards.
> Change parameter description in BatchNorm layer to make it more clear.

- src/mlpack/bindings/julia/CMakeLists.txt
This fixes the error reported by @zoq from the build farm:
http://ci.mlpack.org/job/pull-requests%20mlpack%20memory/5261/console
This is caused because CMake is not properly passing filenames with spaces in them to the `COMMAND` CMake command.
@Yashwants19 I think this problem also exists with the Go CMake configuration; basically, I made sure to just strip any `"` around arguments when calling `cmake(COMMAND ...)`.
> Allow Julia CMake configuration to handle spaces in directories

- HISTORY.md
- src/mlpack/core/cv/metrics/facilities.hpp
- src/mlpack/core/cv/metrics/silhouette_score.hpp
- src/mlpack/core/cv/metrics/silhouette_score_impl.hpp
- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/cv_test.cpp
- src/mlpack/tests/facilities_test.cpp
Silhouette Score is a widely used metric for clustering algorithms, I thought it be nice to have it here.
- Add Pairwise Distance (and test)
- Add Silhouette Score (and test)
- Add test for AssertSizes (already implemented, added test)
> Add Silhouette Score and Pairwise Distance

- src/mlpack/methods/ann/rbm/rbm.hpp
I'm not sure why this didn't trigger a failed doxygen build before, actually.  But it seems like there was just a typo in a formula that caused Doxygen to not actually compile all the formulas correctly.
> Fix equation definition.

- doc/tutorials/tutorials.txt
Noticed the RL tutorial isn't linked on our site, this should fix it I think
> Linking RL tutorial

- src/mlpack/CMakeLists.txt
This actually should have happened earlier, when we released mlpack 3.3.0!
Basically the change here is that we should be building, e.g., `libmlpack.so.3.3` not `libmlpack.so.3.2` since the version is now 3.3.x.
I edited the release preparation guide to account for this:
https://github.com/mlpack/mlpack/wiki/ReleasePreparationGuide
During the next release I'll incorporate this into the scripts (and hopefully it will never be a problem again!).
> Update to soversion libmlpack.so.3.3

- src/mlpack/core/tree/cellbound_impl.hpp
- src/mlpack/tests/cli_test.cpp
I found in `CLITest` that we have several places where we call `Log::Fatal.ignoreInput = true` and it's unnecessary.  We should only need to do that to prevent a bunch of output right before we expect something to throw an exception.  But in these cases, we expect parsing to succeed, and so there should be no problem with leaving `ignoreInput` to its default value of `false`.
> Remove unnecessary Log::Fatal `ignoreInput` settings

- README.md
Oops---thanks @zoq for pointing this out.  The README said that the minimum version of Julia is 3.2.2, but that's not true---the minimum version required for Julia should be 1.3.0.
> Fix version of Julia in documentation.

- src/mlpack/methods/ann/layer/batch_norm.hpp
- src/mlpack/methods/ann/layer/batch_norm_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
Hey everyone,
There is an issue with how the batch norm layer is implemented in mlpack. Details for it are mentioned below.
Pre-reqs:
For simplicity, let's take an example where batch norm is used for computer vision problems (dataset is made up of images).
In mlpack, each column represents a separate image and each row has imageWidth * imageHeight * imageDepth.
In most libraries like PyTorch the batch norm layer requires inputChannels and generates a weight and bias matrix of size equal to inputChannels.
Eg. For an input of size`(16, 16, 32)` the batch norm layer in PyTorch will be of the form : `nn.BatchNorm2d(32)` and that will create a weight and bias matrix of size `32 x 1`.
Issue : 
In mlpack, The batch norm takes the input Rows as input i.e. imageWidth * imageHeight * imageDepth …
> Extending Support of BatchNorm layer to Convolutional Layer output.

- HISTORY.md
- src/mlpack/core/data/load_arff_impl.hpp
- src/mlpack/tests/load_save_test.cpp
In the process of fixing #2478, I misunderstood the ARFF spec:
> Values of string and nominal attributes are case sensitive
https://www.cs.waikato.ac.nz/~ml/weka/arff.html
So, as a result, I didn't actually fix the problem in #2486, since the loader I had was case-insensitive, leading to the issue that @pesoke reported as a follow-up.
These changes force case-sensitivity in the ARFF loader when a dimension has a categorical type with specified categories, like this:
```
@attribute dimension_name {A, B, C, D}
```
instead of computing categories after they have been converted to lowercase, this computes categories as they are specified in the ARFF file exactly.
Then, while parsing, if a dimension is categorical and the categories were specified as in the example above, then if that …
> Fix ARFF loader to be case sensitive

- CMake/mlpack-config.cmake.in
This fixes [the same bug](https://github.com/mlpack/ensmallen/commit/1aa9e2e991c140aed3c15d871890f9ce756e0197) that appeared in Ensmallen. I noticed this but I couldn't reproduce it correctly especially when the installation was done via Homebrew, but after Ensmallen's fix, I investigated it, and it's working as expected now.
> fixed a typo that the caused incorrect configuration of the cmake

- src/mlpack/bindings/julia/print_doc.hpp
Hi @rcurtin, I think so we are not printing model type correctly [here](https://github.com/mlpack/mlpack.jl/blob/ab0a526f5936aa8829becd32dd3f5143c80532ac/src/adaboost.jl#L104). It is printing `unknow_` and not `AdaBoostModel` in Julia documentation. I have tried to resolve this issue in the PR.
Thank You.
> Fix ModelType Julia Documentation.

- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/image_load_test.cpp
- src/mlpack/tests/linear_regression_test.cpp
- src/mlpack/tests/main_tests/image_converter_test.cpp
- src/mlpack/tests/main_tests/linear_regression_test.cpp
Refer : https://github.com/mlpack/mlpack/issues/2523
> Migrate linear regression tests from boost to catch2

- doc/guide/sample_ml_app.hpp
This comes out of #2538.  There is a bug in the example program: the `sample` point to `Classify()` is specified incorrectly; it is intended that it should be one point that is 23 dimensions, but it's specified in such a way that it results in a matrix with one row and 23 columns (but what we need is 23 rows and one column).
This PR fixes that issue and clarifies in the example code that mlpack is column-major.
> Fix data in sample ML app to be column-major.

- src/mlpack/tests/ann_layer_test.cpp
Hey everyone, 
While working on my project, I noticed there weren't tests for Conv. layers. This PR adds tests to show that the output of the Conv. layer matches PyTorch's implementation.
[Test Link](https://colab.research.google.com/drive/1WHRldnsE0eFb-XWQnQuLEQmQQnoZKaia?usp=sharing).
Regards,
Kartik.
> Add tests for Convolutional layer.

- src/mlpack/bindings/go/CMakeLists.txt
- src/mlpack/bindings/go/mlpack/arma_util.go
- src/mlpack/bindings/go/mlpack/io_util.go
I noticed (while preparing JuliaPackaging/Yggdrasil#1346) that we distribute a library that's just called `libgo_util.so`.  I thought maybe this library name could potentially be confusing or interfere with another system library or another package's library, so this PR just changes the name from `libgo_util.so` to `libmlpack_go_util.so`, which should hopefully help make it clearer what the purpose of the library is.
@Yashwants19 let me know if you see any issue with this change. :+1:
> Rename libgo_util.so to libmlpack_go_util.so.

- HISTORY.md
- src/mlpack/methods/logistic_regression/logistic_regression.hpp
- src/mlpack/methods/logistic_regression/logistic_regression_function.hpp
- src/mlpack/methods/logistic_regression/logistic_regression_function_impl.hpp
- src/mlpack/methods/logistic_regression/logistic_regression_impl.hpp
- src/mlpack/tests/logistic_regression_test.cpp
`ak` in the chat channel pointed out that incremental logistic regression via successive calls to `Train()` don't seem to work as the documentation suggests.  When I looked into the code, it does seem like there is a bug.  So this PR changes the behavior of `Train()` to only reset the parameters vector when it is of a different size.  It also corrects some slightly inaccurate documentation.
> Fix documentation for incremental logistic regression

- src/mlpack/methods/ann/rbm/rbm.hpp
- src/mlpack/methods/ann/rbm/rbm_impl.hpp
- src/mlpack/methods/ann/rbm/spike_slab_rbm_impl.hpp
- src/mlpack/tests/rbm_network_test.cpp
- src/mlpack/tests/serialization_test.cpp
Trying to remove remove r-value reference from RBM module to maintain the code.
> Removing r-value reference from RBM

- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/kernel_pca_test.cpp
- src/mlpack/tests/kernel_test.cpp
- src/mlpack/tests/kernel_traits_test.cpp
- src/mlpack/tests/main_tests/kernel_pca_test.cpp
> migrate kernel_* related test from boost to catch2

- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/bayesian_linear_regression_test.cpp
- src/mlpack/tests/main_tests/bayesian_linear_regression_test.cpp
> Migrate bayesian_linear_regression related test from boost to catch2

- src/mlpack/tests/ann_layer_test.cpp
Looks like the `GradientMultiheadAttentionTest` sometimes fails by a really small margin, so I just increased the threshold.
> Increase threshold to avoid occasional test failures.

- HISTORY.md
- src/mlpack/bindings/cli/parse_command_line.hpp
- src/mlpack/tests/io_test.cpp
This fixes a serious problem found by @Yashwants19 where required matrix options could not be used from the command-line:
```
$ ./bin/mlpack_preprocess_split                                 \
>     --input_file covertype-small.data.csv                     \
>     --input_labels_file covertype-small.labels.csv            \
>     --training_file covertype-small.train.csv                 \
>     --training_labels_file covertype-small.train.labels.csv   \
>     --test_file covertype-small.test.csv                      \
>     --test_labels_file covertype-small.test.labels.csv        \
>     --test_ratio 0.3                                          \
>     --verbose
terminate called after throwing an instance of 'CLI::OptionNotFound'
what():  input_file not found
Aborted (core dumped)
```
The …
> Prepend "--" to options when checking that they are there.

- CMake/FindGo.cmake
I noticed that the OS X Go builds were failing during CMake configuration like this:
```
-- Go not found: Found unsuitable version "go version go1.15 darwin/amd64
", but required is at least "1.11.0" (found /usr/local/bin/go)
```
See, e.g., https://dev.azure.com/mlpack/mlpack/_build/results?buildId=4307&view=logs&jobId=4ad28a20-a210-5db1-5cbb-cda6f2d26943&j=4ad28a20-a210-5db1-5cbb-cda6f2d26943&t=dbf69b48-0c7c-5f5f-9546-6e5df880e0ba
So, this PR just fixes the regex that extracts the version from Go to accept when there is no patch version.
@Yashwants19 let me know what you think or if I overlooked something. :+1:
> Fix regex for versions of Go without a patch version

- src/mlpack/core/cv/cv_base_impl.hpp
This is a follow-up to #2614.  It just means that when the user tries to construct a `KFoldCV` or `SimpleCV` object, if they pass the number of classes incorrectly (i.e. as an `int`), then the warning will now point out that the type should be `size_t`.
So, for instance, this code does not work:
```
int numClasses = 2;
double validationSize = 0.2;
SimpleCV<DecisionTree<>, Accuracy> scv(validationSize, testData, testLabel, numClasses);
```
but this code does:
```
size_t numClasses = 2;
double validationSize = 0.2;
SimpleCV<DecisionTree<>, Accuracy> scv(validationSize, testData, testLabel, numClasses);
```
So now, if you write the first thing, the error that you get points out that the type of `numClasses` should be `size_t`.
@GLmontanari let me know if you think this message would have …
> Clarify that the type should be size_t for numClasses in CVBase

- COPYRIGHT.txt
- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/dbscan_test.cpp
- src/mlpack/tests/main_tests/dbscan_test.cpp
Regarding issue #2523 
The tests ran successfully on my local system build.
> Migrate DBSCAN test from boost to catch2

- src/mlpack/methods/ann/layer/softmax_impl.hpp
- src/mlpack/methods/ann/layer/softmin_impl.hpp
This PR is a result from the discussion and the results [here](https://github.com/mlpack/mlpack/pull/2621#discussion_r499231425). The current forward implementation of Softmax and Softmin activation functions were considerably slow than what @zoq proposed in the previously mentioned discussion.
The decision was took based upon the Softmin implementation and the code for testing could be seen here for the  [current implementation](https://gist.github.com/Aakash-kaushik/a51a1543ef76b8c0a8285e5ce51c5de4) and here for the [implementation](https://gist.github.com/Aakash-kaushik/d877015f971001787fd2e43f0b2596c9) in this PR .
execution time for current implementation: `222150`
execution time for implementation in this PR: `149912`
Approx `48%` faster than the current implementation.
> Forward implementation changed for softmin and softmax activation function

- src/mlpack/tests/CMakeLists.txt
- src/mlpack/tests/metric_test.cpp
Referencing issue #2523 
Replaced 
```
BOOST_REQUIRE_CLOSE_FRACTION(x, y, 1e-z) with 
```
with
```
REQUIRE(x == Approx(y).epsilon(1e-(z+2)));
```
> Migrate metric test from Boost to Catch2Migration

- CMakeLists.txt
- HISTORY.md
This fixes #2615 .
*A bunch of context*:
Armadillo has, as an internal configuration option, the preprocessor macro `ARMA_64BIT_WORD`.  If this is set (which it is by default), then during compilation, Armadillo matrix indices will be 64 bit integers.  If it isn't set, they will be 32 bit.  Now, this is a little bit of a problem because mlpack is *not* a header-only library, and so if mlpack itself is compiled with `ARMA_64BIT_WORD`, but then a program that links against mlpack is compiled *without* `ARMA_64BIT_WORD`, a nightmare of debugging awaits, because any symbols in the compiled program will have 32-bit `arma::uword` but libmlpack.so will expect 64-bit `arma::uword`.  One time, I did this inadvertently, and lost several hours of my life trying to figure out what in the world was …
> Pass CMAKE_SIZEOF_VOID_P explicitly to CreateArmaConfig.cmake

- src/mlpack/methods/ann/layer/batch_norm.hpp
- src/mlpack/methods/ann/layer/batch_norm_impl.hpp
- src/mlpack/methods/ann/layer/convolution.hpp
- src/mlpack/methods/ann/layer/convolution_impl.hpp
- src/mlpack/tests/ann_visitor_test.cpp
Hey everyone,
This PR adds weights size to BatchNorm and Conv Layer.
Related Issue : #2590
Regards.
> Add WeightSize to BatchNorm and Conv Layer.

- CMakeLists.txt
- Doxyfile
- HISTORY.md
- README.md
- doc/examples/sample-ml-app/sample-ml-app/sample-ml-app.vcxproj
- doc/guide/build.hpp
- doc/guide/python_quickstart.hpp
- doc/guide/sample_ml_app.hpp
- src/mlpack/core/util/version.hpp
This automatically-generated pull request adds the commits necessary to
make the 3.4.2 release.
Once the PR is merged, mlpack-bot will tag the release as HEAD~1 (so
that it doesn't include the new HISTORY block) and publish it.
Or, well, hopefully that will happen someday.
When you merge this PR, be sure to merge it using a *rebase*.
* Added Mean Absolute Percentage Error.
* Added Softmin activation function as layer in ann/layer.
* Fix spurious ARMA_64BIT_WORD compilation warnings on 32-bit systems (#2665).
> Release version 3.4.2

- scripts/release-mlpack.sh
- scripts/update-website-after-release.sh
This just adds the two release scripts used to release a version of mlpack automatically, just like in ensmallen.
Anyone should be able to run `scripts/release-mlpack.sh <major> <minor> <patch>` in order to automatically open a pull request for a release, and then mlpack-bot should do the rest automatically once that automatically-opened PR is merged.  I'm excited about this!  It can help remove me as a bottleneck to releases. :)
> Add release scripts

- COPYRIGHT.txt
- src/mlpack/tests/akfn_test.cpp
- src/mlpack/tests/aknn_test.cpp
- src/mlpack/tests/callback_test.cpp
- src/mlpack/tests/cf_test.cpp
- src/mlpack/tests/decision_tree_test.cpp
- src/mlpack/tests/facilities_test.cpp
This is in reference to issue #2715 .
Adding FAIL message when calling data::Load in following files:
`aknn_test.cpp`
`akfn_test.cpp`
`callback_test.cpp`
`cf_test.cpp`
`decision_tree_test.cpp`
`facilities_test.cpp`
> adding FAIL message to akfn_test, aknn_test and 4 more tests when calling data::Load

- src/mlpack/methods/ann/layer/dropout.hpp
- src/mlpack/methods/ann/layer/dropout_impl.hpp
- src/mlpack/tests/feedforward_network_test.cpp
This pull request is in reference to #2625 
It adds the copy and move constructors and assignment operators to the Dropout layer.
> Adding Copy and Move constructors in Dropout Layer

- CMakeLists.txt
- Doxyfile
- HISTORY.md
- README.md
- doc/guide/build.hpp
This just adds a `BUILD_DOCS` option to the CMake configuration.  Now, if someone is having Doxygen issues, they can disable that from the build by setting `-DBUILD_DOCS=OFF`.  I also updated documentation so that people can know that the option exists.
This is necessary as part of getting Jenkins working correctly again for the Doxygen build and other builds.
> Add BUILD_DOCS option to enable/disable building documentation.

- src/mlpack/methods/ann/layer/convolution.hpp
As discussed with @zoq in gitter. I have changed the comments to prevent possible confusion between number of input maps and size of the input and between number of output maps and size of output.
> changed comments in convolution.hpp

- src/mlpack/methods/ann/loss_functions/mean_squared_error.hpp
- src/mlpack/methods/ann/loss_functions/mean_squared_error_impl.hpp
In accordance with #2005 ,
After giving a careful thought and looking at the code, I figured out that it is not just the `input` variable that is somewhat misleading, but the `output` variables is also a little imprecise. 
To, explain my thoughts, consider a neural network or in general any ML `model`. The `model` takes some `input` and spits out some `predictions`. Then those `predictions` along with the `target labels` are fed into a `loss function` that returns `loss` which measures the goodness of `prediction`. (Being precise with the choice of words here)
Now, in the current implementation of loss functions, we have an `input` variable, that is actually the `prediction` and `output` is actually the calculated `loss` value.
Although all the variable names in the current implementation …
> Improved variable names in MSE

- src/mlpack/tests/callback_test.cpp
- src/mlpack/tests/svd_batch_test.cpp
Reference #2715 .
Changes to file ```callback_test.cpp``` made according to this [comment](https://github.com/mlpack/mlpack/pull/2717#pullrequestreview-536109228).
Missed out file ```svd_batch_test.cpp``` during the initial screening of files for the issue.
> Added FAIL messages to svd_batch_test and argument fix for callback_test.

- src/mlpack/methods/ann/layer/fast_lstm.hpp
- src/mlpack/methods/ann/layer/fast_lstm_impl.hpp
- src/mlpack/methods/ann/rnn.hpp
- src/mlpack/methods/ann/rnn_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
- src/mlpack/tests/feedforward_network_test.cpp
Reference #2625 
This PR attempts to add the copy and move constructors to RNN and FastLSTM layers.
> Adding Copy and Move Constructors for RNN and FastLSTM layer.

- src/mlpack/methods/ann/layer/spatial_dropout_impl.hpp
- src/mlpack/methods/ann/layer/virtual_batch_norm_impl.hpp
I have added an assert statement in `spatial_dropout_impl.hpp` and `virtual_batch_norm_impl.hpp` that asserts that the input size must be divisible by the number of input maps. Like there is one in `batch_norm_impl.hpp`.
> Adding assert statement to spatial dropout and virtual batch norm

- .ci/macos-steps.yaml
- src/mlpack/bindings/go/mlpack/capi/arma_util.hpp
- src/mlpack/bindings/julia/julia_util.cpp
- src/mlpack/bindings/python/mlpack/arma_util.hpp
*(updated description now that it is fixed)*
It turns out that our CI failures on OS X with the Julia and Python bindings are not actually the result of Julia or Python versioning issues but instead a change with how Armadillo handles its deallocation decisions.
Armadillo objects have a `mem_state` parameter, which internally indicates whether or not the object is "responsible" for the memory it is using.  In older versions of Armadillo, in the destructors, if `mem_state` was `0` then the memory was deallocated, and if it was `1` then this meant the memory was just an alias of some other object and no deallocation should happen.
Our bindings were written to depend on this internal behavior, but with Armadillo 10 the behavior is changed, because now Armadillo can "reuse" memory if you …
> Avoid accidental deallocations in bindings for Armadillo 10+

- src/mlpack/methods/preprocess/preprocess_split_main.cpp
I was binding the `preprocess_split` binding into my company's product, and during code review these typographical issues were pointed out. :)
I also removed the warning printed when `test_ratio` is specified---none of the other bindings print warnings when a parameter takes its default value, so the change here just brings `preprocess_split` into line with the other bindings. :+1:
CC: @jeffin143 :)
> Clarify preprocess_split documentation

- src/mlpack/methods/lars/lars.cpp
This PR fixes a very unexpected edge case that arises in the LARS algorithm.  Even describing the situation is not particularly easy, and I am not sure I have accurately described it here.
LARS is a regression algorithm that proceeds by adding one feature at a time to the model.  It's a super clever algorithm that actually manages to recover *all* models of the form
```
argminᵦ ∥ Xβ - Y ∥² + λ ∥ β ‖₁
```
for all possible values of `λ`.
Super loosely summarized, the algorithm works like this:
- Pick the next feature `i` that isn't already in the model that is maximally correlated with the responses `Y`.
- Compute the maximum weight `βᵢ` is before another feature needs to be added to the model.
- Repeat until all features are added to the model.
The situation reported in #2749 is a very …
> Fix edge case for similarly-correlated LARS dimensions.

- src/mlpack/bindings/go/get_printable_type_impl.hpp
- src/mlpack/bindings/go/print_type_doc_impl.hpp
This comes from a discussion in IRC:
> One thing I was suprised by, though, is that I expect assignments to be an int vector (array/slice), but its treated as a float64 array
So I took a look at the documentation, and it is true that Gonum doesn't actually support holding `int`s.  Therefore I thought it was worthwhile to remove any documentation that might cause people to think they are holding `int`s, being clear that the type is the same as when floating point values are used.
@Yashwants19 let me know what you think about this change or if you have an alternate suggestion. :+1:
> Gonum can't hold ints, so remove slightly confusing documentation.

- CMakeLists.txt
- HISTORY.md
This PR tries to solve #2773 .
The default options for all bindings are set to "OFF" in this.
> Disabling bindings by default in cmake.

- src/mlpack/methods/ann/layer/reparametrization.hpp
- src/mlpack/methods/ann/layer/reparametrization_impl.hpp
- src/mlpack/tests/feedforward_network_test.cpp
This PR is regarding the issue #2625 and I have added copy and move constructors for `Reparametrization`  layer and also added the corresponding tests.
> Added copy and move constructors in Reparametrization layer

- HISTORY.md
- README.md
- doc/guide/build.hpp
- src/mlpack/bindings/R/CMakeLists.txt
- src/mlpack/bindings/python/CMakeLists.txt
- src/mlpack/bindings/python/PythonInstall.cmake
This comes out of the discussion in #2775.
Right now, the Python bindings will simply be installed to `CMAKE_INSTALL_PREFIX`, even if `PYTHON_EXECUTABLE` is set to some other location.  This PR does not automatically extract the path of the Python installation from `PYTHON_EXECUTABLE`, but simply adds a `PYTHON_INSTALL_PREFIX` option so that a separate location for the Python bindings to be installed can be specified.
@BJWiley233 do you think that you could try these changes and see if they work correctly?
> Add PYTHON_INSTALL_PREFIX CMake option

- HISTORY.md
- src/mlpack/core/util/param_checks.hpp
- src/mlpack/core/util/param_checks_impl.hpp
- src/mlpack/methods/kmeans/CMakeLists.txt
- src/mlpack/methods/kmeans/kmeans_main.cpp
- src/mlpack/methods/kmeans/kmeans_plus_plus_initialization.hpp
- src/mlpack/tests/kmeans_test.cpp
- src/mlpack/tests/main.cpp
I implemented the k-means++ initialization strategy for k-means like three years ago but for some reason never got around to contributing it back upstream.  So, here it is.
https://en.wikipedia.org/wiki/K-means%2B%2B
It's quite an effective initialization strategy, and is often used in practice.  It seems to often outperform the Bradley/Fayyad refined start strategy that we have implemented.
> Add k-means++ initialization.

- src/mlpack/methods/ann/layer/multiply_constant.hpp
- src/mlpack/methods/ann/layer/multiply_constant_impl.hpp
- src/mlpack/methods/ann/layer/multiply_merge.hpp
- src/mlpack/methods/ann/layer/multiply_merge_impl.hpp
- src/mlpack/methods/ann/rnn_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
Reference Issue #2625.
Changes to file ```rnn_impl.hpp``` remove the warning ```x will be initialised after y``` during ```make```.
> Added Copy and Move constructors to Multiply Layers

- src/mlpack/methods/pca/pca.hpp
- src/mlpack/methods/pca/pca_impl.hpp
This added member  function(in PCA class) takes 2 parameters the data(source) and the transformed data matrices and gives the user an option to pass 2 parameters only and  this function will create the variables to store eigenvalues and eigenvectors and perform PCA as usual.
I have also documented another overload just  above this one which was doing similar task.
> Adding another overload member function of PCA::Apply() 

- src/mlpack/methods/ann/layer/fast_lstm_impl.hpp
- src/mlpack/methods/ann/layer/lstm_impl.hpp
This PR is an attempt to solve #2747 and possibly also #2713 (but I am not sure).  I am not confident that this is the right solution, but it at least seems to work on the example code in #2747.
I dug into the `RNN::ResetCells()` function to see if somehow there was some state that was not properly being reset.  I found that the `LSTM` and `FastLSTM` layers attempt to avoid resizing the memory used to hold the internal state when possible, but don't always set the values back to 0.  This could cause different prediction results (and, it *could* cause different serialized model results too.  But I feel like we shouldn't serialize the internal state of an LSTM?).
I replaced this by simply calling `.zeros()` with the new desired size of the object always; this is because Armadillo 10 has new …
> Make sure all state values are set to zero on reset.

- .ci/macos-steps.yaml
`brew cask install` is no longer supported, use `brew install --cask` instead.
> brew cask instal is no longer supported

- src/mlpack/methods/ann/layer/CMakeLists.txt
- src/mlpack/methods/ann/layer/layer.hpp
- src/mlpack/methods/ann/layer/layer_types.hpp
- src/mlpack/methods/ann/layer/lp_pooling.hpp
- src/mlpack/methods/ann/layer/lp_pooling_impl.hpp
- src/mlpack/methods/ann/layer_names.hpp
- src/mlpack/tests/ann_layer_test.cpp
Added LP                                                     pooling layer. 
https://pytorch.org/docs/stable/generated/torch.nn.LPPool2d.html#torch.nn.LPPool2d
> Added LP pooling  layer

- src/mlpack/methods/ann/loss_functions/CMakeLists.txt
- src/mlpack/methods/ann/loss_functions/hinge_loss.hpp
- src/mlpack/methods/ann/loss_functions/hinge_loss_impl.hpp
- src/mlpack/tests/loss_functions_test.cpp
Reasons for this PR:
1. The Hinge Loss function is currently implemented as ```Hinge Embedding Loss``` in mlpack. This implementation is only correct for 1D tensors and doesn't give the right answers for tensors that are higher than 1 dimension. This [colab notebook](https://colab.research.google.com/drive/1iA1pHNxRE9fVxB01oJUEiM2BTCACQHmK?usp=sharing) highlights this by comparing with the [tensorflow](https://www.tensorflow.org/api_docs/python/tf/keras/losses/hinge) implementation. Also, the current implementation only incorporates mean reduction. This PR adds an additional ```reduction``` parameter to choose between mean and sum reduction.
2. Issue #2444 and PR #2495 aim to change the implementation of ```Hinge Embedding Loss``` to the Hinge Embedding Loss function in …
> Added Hinge Loss to loss functions

- src/mlpack/tests/CMakeLists.txt
I noticed while reviewing #2844 that this file actually isn't being compiled and run in the tests.  The PR is an easy fix. :)
> Make sure feedforward_network_2_test.cpp gets compiled and run.

- src/mlpack/core/util/to_lower.hpp
- src/mlpack/methods/ann/layer/atrous_convolution_impl.hpp
- src/mlpack/methods/ann/layer/convolution_impl.hpp
- src/mlpack/methods/ann/layer/transposed_convolution_impl.hpp
The previous implementation did not correctly iterate over the output string.  Specifically, if the `output` parameter was empty when the function was called, no transformation would be done.  So, using `std::back_inserter()` instead seems to fix the behavior and solve #2838.
> Use `std::back_inserter()` for `util::ToLower()`

- src/mlpack/bindings/go/print_type_doc_impl.hpp
- src/mlpack/bindings/markdown/print_docs.cpp
- src/mlpack/methods/amf/termination_policies/simple_residue_termination.hpp
- src/mlpack/methods/amf/update_rules/svd_complete_incremental_learning.hpp
I noticed that on the binding documentation pages, sometimes the anchors in the left margin don't work:
https://www.mlpack.org/doc/mlpack-git/cli_documentation.html
So, if you click on `mlpack_adaboost`, it doesn't actually link anywhere, because the link points to the anchor `#adaboost`, but the name of the section is `#mlpack_adaboost`.
This PR just adds a little bit of processing to use the right anchor link, and also fixes a few compilation warnings that I found.
> Fix anchor links in generated Markdown documentation

- HISTORY.md
- src/mlpack/methods/lars/lars.cpp
- src/mlpack/methods/lars/lars.hpp
This fixes #2857.
The PR adds `Lambda1()`, `Lambda2()`, `UseCholesky()`, and `Tolerance()` members so that the parameters of LARS training can be modified after creating the object.  The only "trickiness" is that we now must recompute `elasticNet` and `lasso` (internal members) when we start training, since the user may have modified the `lambda1` or `lambda2` values.
Should be an easy review, I think. :)
> Add functions to modify parameters for LARS

- src/mlpack/tests/adaboost_test.cpp
Several AdaBoost tests check that a boosted learner produced by AdaBoost performs better on the training set than a single weak learner.  However, this is not actually guaranteed---in typical situations, a boosted learner _will_ do better than a single weak learner, but there is no theory to support this in all cases.  Therefore, the tests are flawed; I fixed them by instead testing that a boosted learner gets performance at least close to that of a single weak learner.  (Technically even this is not guaranteed but I would be astonished to find datasets that aren't worst-case where that condition doesn't hold.)
The route to finding this problem was very strange indeed; the problem was reported in #2827.  As it turns out, tiny handling differences in floating-point arithmetic cause the …
> Loosen tolerances for AdaBoost test

- src/mlpack/methods/random_forest/bootstrap.hpp
Eliminated the use of ```for``` loop from the ```Bootstrap``` function.
Timed the ```Bootstrap``` function with ```dataset```, ```labels``` and ```weights``` of ```100000000 (1e8)``` elements.
Results (Average of 15 trials)
```
Without for loop (New implementation): 8.238 seconds
With for loop (Old implementation): 11.105 seconds
```
> Optimising the Bootstrap function

- src/mlpack/methods/reinforcement_learning/environment/CMakeLists.txt
- src/mlpack/methods/reinforcement_learning/environment/env_type.cpp
- src/mlpack/methods/reinforcement_learning/environment/env_type.hpp
This fixes #2854.
`env_type.hpp` previously initialized some static members, but initializing a static member in a header file means that if that header is included in multiple different places, the member will be multiply defined.  In this PR I've fixed the issue by simply moving the initialization of static members into a .cpp file, which will then be compiled into `libmlpack.so`.
As a result, now those static members will live in `libmlpack.so` and not in any downstream application compiled by the user.
@nishantkr18 if you don't mind taking a look and making sure I'm not unintentionally breaking something, it would be great. :)  Thanks!
> Move initialization of static environment members into a cpp file

- src/mlpack/tests/tree_traits_test.cpp
I do think this is a typo, unless if this is intended
> Remove addition t from the word test

- HISTORY.md
- src/mlpack/methods/decision_tree/all_categorical_split.hpp
- src/mlpack/methods/decision_tree/all_categorical_split_impl.hpp
- src/mlpack/methods/decision_tree/best_binary_numeric_split.hpp
- src/mlpack/methods/decision_tree/best_binary_numeric_split_impl.hpp
- src/mlpack/methods/decision_tree/decision_tree.hpp
- src/mlpack/methods/decision_tree/decision_tree_impl.hpp
- src/mlpack/methods/random_forest/random_forest.hpp
- src/mlpack/methods/random_forest/random_forest_impl.hpp
- src/mlpack/tests/decision_tree_test.cpp
While fixing #2872, I noticed that there is a template parameter `ElemType` for `DecisionTree` and `RandomForest` that is currently entirely unused.  In fact, it gets in the way and is confusing a little bit, so I thought it was better to remove it.
In addition, I changed some function signatures to force `arma::vec` for the `classProbabilities` member to actually fix #2872.
This is an API change, but since the next release is 4.0.0 anyway, it should be okay to break reverse compatibility in this minor way.
> Remove ElemType template parameter from DecisionTree

- HISTORY.md
- src/mlpack/bindings/python/setup.py.in
@zoq reported yesterday that a build with Python and `-DUSE_OPENMP=OFF` fails.  As it turns out, the reason for this is that an empty argument gets appended to the list of compilation flags, and then when those are joined with a space, we end up with two spaces in the compilation command.  For whatever reason, setuptools/cython does not like this, and it causes a compilation failure with a strange error message:
https://gist.github.com/zoq/8d65e3caf0a58ef9772e8466caeaf3cc
I fixed the issue by only adding `${OpenMP_CXX_FLAGS}` to the list of compilation arguments if it isn't empty.
> Handle empty OpenMP_CXX_FLAGS correctly

- src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression.cpp
- src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression.hpp
- src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression_impl.hpp
This fixes #2879.
I added the `CenterData()`, `ScaleData()`, `MaxIterations()`, and `Tolerance()` functions to change the training parameters of `BayesianLinearRegression`.
I also changed the variable name `nIterMax` to `maxIterations` to better match other parts of the codebase, and similarly for `tol` -> `tolerance`.
@mercierc you originally wrote this code, so please let me know if this breaks anything unintentionally that I overlooked.  It seems to pass the tests just fine. :)
> Add methods to `BayesianLinearRegression` to change training parameters

- src/mlpack/bindings/cli/print_type_doc_impl.hpp
- src/mlpack/core/data/detect_file_type.cpp
- src/mlpack/core/data/detect_file_type.hpp
- src/mlpack/core/data/load.hpp
- src/mlpack/tests/load_save_test.cpp
This changes the behavior of CSV loading in `data::Load()` (the overload that does not take a `DatasetInfo`).
Specifically, before this PR, if you had a CSV of this form:
```
a,b,c,d
1,2,3,4
5,6,7,8
```
it would actually be loaded as a matrix with *three* columns, treating the CSV row `a,b,c,d` as `0,0,0,0`.  This turned out to be part of a user issue in #2889.  Therefore, I wrote a patch for `data::Load()` to try and parse the first row of a CSV as `double`s.  If it succeeds, then we assume that the CSV file does not have a header row, and we load the first row as data.  If we cannot parse the first row of a CSV as `double`s, then we assume the CSV file does have a header, and we skip the first row.
I also updated documentation accordingly.
> Auto-detect a CSV header in `data::Load()`

- CMake/go/AppendModel.cmake
In `Append.cmake`(Go-bindings build essentials) flow control statements are not properly nested. Hence I have tried to fix the issue in this PR.
> Fix Go-bindings flow control nesting.

- src/mlpack/bindings/R/mlpack/DESCRIPTION.in
I had notice a `LazyData` [NOTE](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/mlpack-00check.html) at CRAN mlpack result. Hence I have tired to fix this Note in this PR.
> Fix LazyData Note in R-bindings.

- README.md
We clean-up the Jenkins jobs and figured that we can remove the Linux build job that runs once something is merged into master, since the Azure pipeline also runs. With the removal we also have to update the badge to source Azure instead of Jenkins.
> Use Azure build as badge source.

- src/mlpack/tests/main_tests/gmm_generate_test.cpp
- src/mlpack/tests/main_tests/gmm_probability_test.cpp
- src/mlpack/tests/main_tests/range_search_test.cpp
I guess you only run into the issue if you don't use cotire.
> Include string header to resolve undefined type error

- src/mlpack/tests/ann_dist_test.cpp
- src/mlpack/tests/ann_layer_test.cpp
I refactored tests for file 'ann_dist_test.cpp' in location  mlpack/tests/ . I am also still searching to see if there are any similar issues in other tests.
The link to the issue : https://github.com/mlpack/mlpack/issues/2897
The current one used abs(x-y) to check if values are almost equal. I refactored it with approx_value() funciton provided by armadillo.
> Refactor tests to use approx_equal() 

- CMake/Autodownload.cmake
- CMakeLists.txt
This pull request provides the Autodownloader for mlpack dependencies.
It can be used with current and future dependencies.
This one is born from working with #2531, with help from @rcurtin and @zoq.
It is ready to merge, with minor reviews are always welcome.
> The Autodownloader.

- CMake/FindArmadillo.cmake
Authored-by: Ryan Curtin <ryan@ratml.org>
> Fix find armadillo by rcurtin.

- .ci/linux-steps.yaml
- .ci/macos-steps.yaml
- .ci/windows-steps.yaml
- .github/workflows/main.yml
- HISTORY.md
- README.md
- doc/guide/build.hpp
- src/mlpack/tests/CMakeLists.txt
This is a follow-up to a suggestion by @conradsnicta in #2524.
Currently, users who download and build mlpack from source will *always* build `mlpack_test`, unless the user manually sets `BUILD_TESTS` to `OFF` when they configure with CMake.  But users are different than developers, and users are primarily interested in using the software for their own ends, not building and running the tests.  Especially given how memory- and compute-hungry the compilation process for `mlpack_test` is, I agree that it would be a good idea to disable this by default.
So, now, `mlpack_test` is not a part of the `all` target.  This means that a user who builds mlpack with `make` will not need to sit through the process of waiting for the tests to build.  (Or, more likely, waiting for their compilation to …
> Don't build mlpack_test as part of make.

- README.md
- doc/guide/build.hpp
- src/mlpack/bindings/cli/CMakeLists.txt
- src/mlpack/tests/CMakeLists.txt
This pull request is not related to cross-compilation.
> If we are building mlpack statically then build executable statically

- README.md
This comes from #2524, and just adds a link to the vision document PDF to the README.  It should wait to be merged until once mlpack/mlpack.org#48 is also merged.
> Add a link to the vision document in the readme

- src/mlpack/core/data/is_naninf.hpp
Fix build error when building x64-uwp:
```
5>D:\buildtrees\mlpack\src\82feaae439-1a0b09363c.clean\src\mlpack\core\data\is_naninf.hpp(44,13): error C4146: unary minus operator applied to unsigned type, result still unsigned (compiling source file D:\buildtrees\mlpack\src\82feaae439-1a0b09363c.clean\src\mlpack\core\data\load.cpp) [D:\buildtrees\mlpack\x64-uwp-dbg\src\mlpack\mlpack.vcxproj]
D:\buildtrees\mlpack\src\82feaae439-1a0b09363c.clean\src\mlpack\core\data\load_arff_impl.hpp(270): message : see reference to function template instantiation 'bool mlpack::data::IsNaNInf<eT>(T &,const std::string &)' being compiled [D:\buildtrees\mlpack\x64-uwp-dbg\src\mlpack\mlpack.vcxproj]
with
[
eT=arma::u32,
T=arma::u32
] (compiling source file …
```
> Fix uwp build error C4146

- src/mlpack/bindings/cli/add_to_cli11.hpp
- src/mlpack/bindings/cli/cli_option.hpp
- src/mlpack/bindings/cli/get_param.hpp
- src/mlpack/bindings/cli/get_printable_param_impl.hpp
- src/mlpack/bindings/cli/get_raw_param.hpp
- src/mlpack/bindings/cli/in_place_copy.hpp
- src/mlpack/bindings/cli/output_param_impl.hpp
- src/mlpack/bindings/cli/parameter_type.hpp
- src/mlpack/bindings/cli/set_param.hpp
- src/mlpack/tests/cli_binding_test.cpp
- src/mlpack/tests/io_test.cpp
Solves #2817.
As recommended by @rcurtin, I have added extra elements to `TupleType` of type `size_t` that store the number of rows and number of columns for the matrix parameters. So, `TupleType` for matrix is now `std::tuple<arma::mat, std::string, size_t, size_t>`.
I have also changed corresponding files in `bindings/cli` to account for the added elements.
Now, we get the correct matrix size for CLI:
```bash
./mlpack_adaboost -t data.csv -l classes.csv -M model.bin -v 
[DEBUG] Compiled with debugging symbols.
[INFO ] Loading 'data.csv' as CSV data.  Size is 4 x 4.
[INFO ] Loading 'classes.csv' as raw ASCII formatted data.  Size is 4 x 1.
[INFO ] 2 classes in dataset.
[INFO ] 
[INFO ] Execution parameters:
[INFO ]   help: 0
[INFO ]   info: 
[INFO ]   input_model_file: 
[INFO ] …
```
> storing size of matrix in cli bindings

- CMakeLists.txt
- README.md
- doc/guide/build.hpp
This comes from the discussion in #2939.
* I added a check to our CMake configuration to ensure that, if GCC is used, version 5.x or newer is used.
* I added some documentation for what to do on RHEL7/CentOS 7, where the default version of GCC is 4.8.
> Add some notes for usage on RHEL7

- CMakeLists.txt
- README.md
- doc/guide/build.hpp
Both of these variables were forgotten, when we created the autodownloader.
Time to remove them.
> Clean old no longer used download var for ensmallen and stb

- src/mlpack/methods/ann/layer/mean_pooling.hpp
When inputmatrix size is greater than approx 20 * 20, this new method is faster, but then input is    less than 20*20  this  method is around 5~10  microseconds slower.
https://colab.research.google.com/drive/1MmJoeJfFaJ--ugz8VAViHsHTjssYCn3L?usp=sharing
>  faster forward pass of mean pool layer

- src/mlpack/bindings/python/print_type_doc_impl.hpp
I noticed that the Doxygen build for the website failed:
http://ci.mlpack.org/job/mlpack.org%20nightly%20rebuild/227/consoleFull
The issue is just a missing semicolon. :smile:  This didn't get noticed during CI testing, because it will only appear when building Markdown bindings (which is what the website does).
> Fix missing semicolon in Python type documentation

- HISTORY.md
- src/mlpack/methods/decision_tree/decision_tree.hpp
- src/mlpack/methods/hoeffding_trees/hoeffding_tree.hpp
- src/mlpack/methods/hoeffding_trees/hoeffding_tree_impl.hpp
- src/mlpack/tests/hoeffding_tree_test.cpp
In #2962, @xlindo pointed out some issues when trying to train a Hoeffding tree after it was created with an empty constructor.  I went through the code and realized that there are some situations where this does not work correctly; therefore, I went through and refactored things such that the code in #2962 now works.  In essence, the problem was that a `HoeffdingTree<>` stores a `data::DatasetInfo` and a few other parameters that track how many dimensions are in the data and what type those are, but the code does not provide clear facilities for how to modify those quantities.
Specifically, I made the following changes:
- I added a bunch of documentation to the overloads of `Train()` to be clear about when the tree will and won't be reset.
- I added a specific parameter `resetTree` to …
> Better handling of empty Hoeffding trees

- HISTORY.md
- src/mlpack/bindings/julia/print_param_defn.hpp
- src/mlpack/bindings/julia/tests/runtests.jl
While playing with the mlpack Julia bindings, I noticed that there is a bug in serialization that only happens in some niche cases.
Specifically, we serialize and deserialize the model directly to an IO stream, but we don't take the length of the serialized model into account.  This means that at deserialization time, we eat everything in the stream---this screws up deserialization of anything that comes *after* the mlpack model.
Here's an example of a badly-behaved deserialization function:
```
function deserializeDecisionTreeModel(stream::IO)::DecisionTreeModel
buffer = read(stream)
DecisionTreeModel(ccall((:DeserializeDecisionTreeModelPtr, decision_treeLibrary), Ptr{Nothing}, (Ptr{UInt8}, UInt), Base.pointer(buffer), length(buffer)))
end
```
The solution here is, luckily, pretty easy: …
> Julia: serialize the length of the model

- .ci/linux-steps.yaml
- src/mlpack/methods/ann/gan/metrics/CMakeLists.txt
It looks like the CI builds have started failing, and this might be a factor of the Linux CI systems now using CMake 3.20.  Let's see if this simple fix fixes things... (it's kind of a shot in the dark).
> Try to fix CI with CMake 3.20

- src/mlpack/methods/ann/layer/padding.hpp
- src/mlpack/methods/ann/layer/padding_impl.hpp
- src/mlpack/tests/ann_layer_test.cpp
The current implementation of the padding layer only accounted for a single filter and added the padding to only a single filter even if there were multiple of them, this PR aims to account for that and the code works but there are somethings that i would like to discuss.
1. This layer was implemented by taking inspiration from the maxpool layer and in that there are two params which are `inputWidth` and `inputHeight` now i don't think those params are auto initialized in a `FFN` class and that class is used as a module rather than a direct layer because of those two params? (I might be wrong here).
2. If we want to use the padding class directly as a layer it would require that it now accepts `inputWidth` and `inputHeight`  or whever it is used as amoudle it would require that we update …
> Padding layer fix for multiple filters

- HISTORY.md
- src/mlpack/core/data/load.hpp
- src/mlpack/core/data/load_csv.hpp
I was trying to put together an example for @RishabhGarg108 of how to use a pre-populated `DatasetInfo` object to load categorical data.  Here's the code I wrote:
```c++
#include <mlpack/core.hpp>
using namespace arma;
using namespace mlpack;
using namespace mlpack::data;
int main()
{
// Load the iris dataset, but mark the 2nd and 3rd dimensions as categorical.
DatasetInfo di(4);
di.Type(1) = Datatype::categorical;
di.Type(2) = Datatype::categorical;
mat m;
data::Load("iris.csv", m, di);
std::cout << "Loaded 'iris.csv':\n";
for (size_t i = 0; i < 4; ++i)
{
std::cout << " - Dimension " << i << ": " << di.Type(i) << ", " << di.NumMappings(i)
<< " mappings." << std::endl;
}
m.print("m:");
}
```
But, much to my surprise, this did not work, and the data was continually loaded as numeric!
As I …
> LoadCSV: only reset the DatasetMapper if the dimensionality is wrong

- src/mlpack/methods/reinforcement_learning/q_learning.hpp
- src/mlpack/methods/reinforcement_learning/sac.hpp
- src/mlpack/methods/reinforcement_learning/worker/n_step_q_learning_worker.hpp
- src/mlpack/methods/reinforcement_learning/worker/one_step_q_learning_worker.hpp
- src/mlpack/methods/reinforcement_learning/worker/one_step_sarsa_worker.hpp
Some of the reinforcement learning structs are defined using the `ENS_VERSION_MAJOR` macro---but there is no guarantee that ensmallen has been included first!  So this PR fixes that by simply including ensmallen.hpp in all files that use `ENS_VERSION_MAJOR`.
This should fix @JackMBenson's issue in #2987.
> Include ensmallen so ENS_VERSION_MAJOR is defined.

- src/mlpack/core/tree/rectangle_tree/rectangle_tree.hpp
> Use std::is_same instead of boost::is_same

- src/mlpack/methods/ann/layer/batch_norm_impl.hpp
- src/mlpack/methods/ann/layer/virtual_batch_norm_impl.hpp
While loading models which were using any of these two layer the weights param were not properly initialized because loading was set to false, setting it to true does the trick. 
Thanks to @zoq and @kartikdutt18 for helping find it out.
Closes #2561
> Corrects wrong serialization for BatchNorm and Virtual BN

- src/mlpack/methods/ann/layer/layer_types.hpp
Moving the `sequential` Layers from `MoreTypes` to `LayerTypes` because preTrained models created with these required us to move these layers to make it work and while deserializing it requires that both the layers still be in `LayerTypes` which is currently not the case so the tests in models repo fail and any user who would try to use them would face a similar error in deserialization 
More Info on this [commnet](https://github.com/mlpack/models/pull/63#issuecomment-870899105) 
Related to the [Addtition of resnet Module](https://github.com/mlpack/models/pull/63)
cc: @kartikdutt18, @zoq
> Move Sequential layers to LayerTypes

- src/mlpack/methods/ann/layer/CMakeLists.txt
- src/mlpack/methods/ann/layer/layer.hpp
- src/mlpack/methods/ann/layer/layer_types.hpp
- src/mlpack/methods/ann/layer/relu6.hpp
- src/mlpack/methods/ann/layer/relu6_impl.hpp
- src/mlpack/tests/activation_functions_test.cpp
Initial draft PR for addition of ReLU6
PyTorch reference [here](https://pytorch.org/docs/stable/generated/torch.nn.ReLU6.html)
Requirement: Needed to Implement [Mobilenet V1](https://github.com/mlpack/models/pull/72)
Function Originally introduced in the paper: [MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications](https://arxiv.org/pdf/1704.04861)
> Addition of ReLU6

- HISTORY.md
- src/mlpack/methods/softmax_regression/softmax_regression_main.cpp
- src/mlpack/tests/main_tests/softmax_regression_test.cpp
This solves #2997 by adding a 'probabilities' option to the softmax regression binding.  This allows users to not just get class predictions via `predictions` but also the probabilities for each class.  I guess this option must have been overlooked when the original binding was written!
> Add 'probabilities' option to softmax regression binding

- CMakeLists.txt
- src/mlpack/CMakeLists.txt
To import mlpack in Project by FetchContent, some issue appear because the PATH arn't correct.
Change SOURCE by CURRENT_SOURCE because findPackage(FindStbImage.cmake) fail.
> Change CMAKE_SOURCE_DIR to CURRENT_SOURCE for easily import mlpack in Project

- .ci/linux-steps.yaml
- .ci/macos-steps.yaml
- .ci/windows-steps.yaml
- .github/workflows/main.yml
- .github/workflows/update-boost-version.yaml
- CMakeLists.txt
- README.md
- doc/guide/build.hpp
Bump minimum Armadillo version to 9.800.6, see https://github.com/mlpack/ensmallen/pull/318 for more details.
> Bump minimum Armadillo version to 9.800

- CMakeLists.txt
This is a follow up from #3033.  I just added the strategy we settled on to the `CMakeLists.txt` so that next time we want to bump it, we perhaps have a little bit of information on where we're trying to keep the minimum version set. :)
> Document Armadillo version policy

- src/mlpack/core/data/split_data.hpp
- src/mlpack/core/util/size_checks.hpp
- src/mlpack/tests/size_checks_test.cpp
- src/mlpack/tests/split_data_test.cpp
Issue: #2991 
Document discussing the changes ideas:
https://docs.google.com/document/d/1fdNIKlXlcOAXTVIhdSeDvxYS9F5-95qviFZxjsBswBQ/edit?usp=sharing
@zoq
> Add checks for labels and input sizes for split function

- src/mlpack/methods/ann/layer/relu6.hpp
- src/mlpack/methods/ann/layer/relu6_impl.hpp
Serialization is not used in this layer, therefore the warning of
an unused parameter is becoming annoying when trying to compile the
mlpack_test, making it impossible to find different errors in small
terminal. Since we are using boost_visitor, the unfolding of layers
is taking several pages of the terminal to print this small warning.
Hoping that this will mitigate one of the warnings.
> Remove ar parameter to avoid the warning

- src/mlpack/methods/ann/layer/group_norm.hpp
- src/mlpack/methods/xgboost/loss_functions/sse_loss.hpp
Following up on my last PR, this one is similar and trying to achieve the same objective.
I am trying to remove all warnings from `mlpack_tests` therefore this PR clean the reorder error.
> Clean reorder warning

- README.md
This PR fixes the readme RedHat installation line
> Add a missing line for Redhat installation instruction

- COPYRIGHT.txt
- src/mlpack/methods/pca/decomposition_policies/exact_svd_method.hpp
- src/mlpack/methods/pca/decomposition_policies/quic_svd_method.hpp
- src/mlpack/methods/pca/decomposition_policies/randomized_block_krylov_method.hpp
- src/mlpack/methods/pca/decomposition_policies/randomized_svd_method.hpp
Changed "right singular **values**" to "right singular **vectors**". 
The term "right singular values" does not exist.
> Fix comments in files that implement SVD methods for PCA

- src/mlpack/methods/linear_svm/linear_svm_function_impl.hpp
LinearSVM<MatType>::Shuffle local variable `newData` is changed to `MatType` instead of `arma::mat`.
> Create variable using MatType instead of arma::mat

- CMakeLists.txt
This is a patch ported from the msys2 project: msys2/MINGW-packages#9972.
It adapts the options used when compiling with MinGW.  It seems to have worked for the packaging in the referenced PR, and @MehdiChinoune agreed that I should upstream the patch.
So, here it is. :)
edit: oops, I pushed the branch to `origin`, not my fork.  Sorry about that... I'll be sure to delete this branch when it's merged.
> Fix compilation options for MinGW

- .ci/ci.yaml
- .ci/macos-steps.yaml
- COPYRIGHT.txt
I have removed the requirement of Xcode 12.2 as macOS 11 is the latest one in the azure pipeline. And this PR is for the macOS pipeline only.
Relevant Issue:
https://github.com/actions/virtual-environments/issues/4060
> Test Pipeline hotfix

- doc/tutorials/ann/ann.txt
This is a quick fix for #3108.  It hopefully won't be too long-term since we're replacing our ANN boost::visitor implementation anyway, but it was so easy to make this change I figured it would be worthwhile in the meantime. :)
> Update ANN parameter access documentation

- doc/guide/bindings.hpp
This is a follow-up to #2995 which has its own issue: #3049.
Basically, when the bindings were revamped to be threadsafe, I forgot to update the guide that describes the automatic binding system.  So, this PR just updates everything, and so hopefully it should be an easier (and more up-to-date!) read for anyone interested in learning about the binding system. :)
> Update binding documentation for threadsafe IO

- COPYRIGHT.txt
- src/mlpack/core/tree/cosine_tree/cosine_tree.cpp
- src/mlpack/core/tree/cosine_tree/cosine_tree.hpp
- src/mlpack/prereqs.hpp
- src/mlpack/tests/cosine_tree_test.cpp
As #3095 suggests, I removed the remaining `boost::heap::priority_queue` parts in `mlpack/core/tree/cosine_tree/cosine_tree.hpp` and changed the way to push/pop items in `mlpack/core/tree/cosine_tree/cosine_tree.cpp` and `mlpack/tests/cosine_tree_test.cpp`.
> Replace boost::heap::priority_queue with std::vector

- COPYRIGHT.txt
- HISTORY.md
- src/mlpack/methods/perceptron/perceptron.hpp
- src/mlpack/methods/perceptron/perceptron_impl.hpp
- src/mlpack/tests/cv_test.cpp
- src/mlpack/tests/perceptron_test.cpp
This should fix #3176.
In that issue, using `KFoldCV` with `Perceptron` did not work, because there was no constructor available that took weights for the data.  (There is a constructor that takes weights, but it *also* takes another `Perceptron` object.  That one is used by `AdaBoost`, but the hyperparameter tuning framework and the cross-validation framework require a constructor that only takes data and instance weights.)
So, I added that constructor in this PR and tests.
I also found that `Perceptron::Classify()` did not resize the predictions to the appropriate size, so I fixed that too.
> Add weighted data constructor to `Perceptron`

- src/mlpack/core/util/size_checks.hpp
- src/mlpack/methods/adaboost/adaboost_impl.hpp
- src/mlpack/methods/kmeans/kmeans_impl.hpp
- src/mlpack/methods/linear_regression/linear_regression.cpp
- src/mlpack/methods/matrix_completion/matrix_completion.cpp
This pull request aims to solve some tasks in issue #2820 with help of #2370 as discussed in the comments.
Tasks done : 
Added size checks using CheckSameSizes and CheckSameDimensionality utilities in 
Please review and provide suggestions.
> Added Size checks for Matrix Completion, Kmeans and Linear Regression

- src/mlpack/methods/linear_regression/linear_regression_main.cpp
Reported on [the mailing list](http://knife.lugatgt.org/pipermail/mlpack/2022-May/004684.html):
```
NB I'm not sure why I get a warning with this invocation - it seems to follow the documentation and it does actually produce "newPredicts.csv" with the Y' values:
[mkb at hec003-ssd](http://knife.lugatgt.org/cgi-bin/mailman/listinfo/mlpack) ~/EEC/mlpack-examples$ mlpack_linear_regression -v --training_file newTrain.csv --test_file newTest.csv  -o newPredicts.csv
[WARN ] '--output_predictions_file (-o)' ignored because '--test_file (-T)' is specified!
[INFO ] Loading 'newTrain.csv' as CSV data.  Size is 48 x 3322.
[INFO ] Loading 'newTest.csv' as CSV data.  Size is 47 x 833.
[INFO ] Saving CSV data to 'newPredicts.csv'.
```
Indeed, this was just a simple error in the code: the warning that …
> Fix `linear_regression` warning

- README.md
Fixes #3209 
```
383 | Github is used for bug tracking, and can be found at
384 | https://github.com/mlpack/mlpack/.
385 | It is easy to register an account and file a bug there, and the mlpack
386 | development team will try to quickly resolve your issue.
```
Updated Issues URL in Line 384 of [README.md](https://github.com/mlpack/mlpack/blob/master/README.md) from https://github.com/mlpack/mlpack/ to https://github.com/mlpack/mlpack/issues
> Updated link to repository issues page in README.md

- src/mlpack/methods/fastmks/fastmks_rules.hpp
- src/mlpack/methods/fastmks/fastmks_rules_impl.hpp
We previously used `boost::priority_queue` inside of the `FastMKSRules` class so that we could easily iterate over the elements of the priority queue---this was the reason we didn't use `std::priority_queue`.  But, we can achieve the same functionality by using a `std::vector` with a max-heap created on top of it, with `std::make_heap()`.
There is no functionality change here, just a change in the data structure---and a step closer to no more boost. :)
> Remove boost::priority_queue from FastMKS

- src/mlpack/tests/convolutional_network_test.cpp
I noticed after merging #2777 that `VanillaNetworkBatchSizeTest` was failing.  As it turns out, the reason is that the code did not initialize the `singleGradient` matrix with zeros, which is problematic because we then have a loop where we add to `singleGradient` in each iteration.
> Fix VanillaNetworkBatchSizeTest

- src/mlpack/core/data/load_arff.hpp
- src/mlpack/core/data/load_arff_impl.hpp
- src/mlpack/core/data/string_algorithms.hpp
- src/mlpack/tests/serialization_test.cpp
I noticed that the last piece of Boost usage remaining is in the `LoadARFF()` function, which @heisenbuug worked on adapting in #3098.  But, #3098 has a merge conflict now, since some other parts of mlpack have changed under it.  So I adapted that a little bit by cherry-picking the commits from that branch and made it pass the tests.  Thanks @heisenbuug for getting it started!  Hopefully this can get it across the finish line. :)
> Remove boost tokenization from LoadARFF()

- LICENSE.txt
I removed no-longer-accurate stanzas about dependent code and did a bit of reorganization:
* We no longer backport any Boost code.
* We no longer reproduce any Armadillo code.
* STB is a dependency, not inlined.
Hopefully this will help Github detect the license correctly.
> Update license to help Github's processing

- src/mlpack/tests/cv_test.cpp
In #3190 I added a test for `KFoldCV` for the perceptron, which is based on a similar test that uses the Naive Bayes classifier.  However, the way that the perceptron trains is different, and it turns out we do not have a guarantee that the last point will indeed be classified incorrectly; it is actually possible that the weights the perceptron may learn may get the last point right.
I thought about potential workarounds for a while, then I realized that the purpose of the test is to ensure that `KFoldCV` compiles successfully for the `Perceptron`; so I made the test "easier".  It still checks whether or not `KFoldCV<Perceptron>` compiles and works.
> Fix `KFoldCVPerceptronTest`

- src/mlpack/methods/ann/layer/add_impl.hpp
- src/mlpack/methods/ann/layer/alpha_dropout_impl.hpp
- src/mlpack/methods/ann/layer/concatenate_impl.hpp
- src/mlpack/methods/ann/layer/convolution_impl.hpp
- src/mlpack/methods/ann/layer/dropout_impl.hpp
- src/mlpack/methods/ann/layer/log_softmax_impl.hpp
- src/mlpack/methods/ann/layer/padding.hpp
- src/mlpack/methods/ann/layer/padding_impl.hpp
- src/mlpack/methods/ann/layer/radial_basis_function_impl.hpp
- src/mlpack/methods/ann/layer/softmax_impl.hpp
- Added `Layer<MatType>()` in the constructor wherever it is missing.
- Added copy and move constructor in PaddingType layer.
- Fixed SoftmaxType move constructor.
> Correction in ANN layers

- src/mlpack/methods/ann/layer/adaptive_max_pooling_impl.hpp
- src/mlpack/methods/ann/layer/adaptive_mean_pooling_impl.hpp
Fixed serialization issue. This issue first appeared when trying the serialization test on SqueezeNet.
Gives `[FATAL] Given output shape (94556213170576, 94556213170192) is not possible for given input shape (13, 13).`
On gdb
```cpp
$1 = {<mlpack::ann::Layer<arma::Mat<double> >> = {_vptr.Layer = 0x55ff936de0e8 <vtable for mlpack::ann::AdaptiveMeanPoolingType<arma::Mat<double> >+16>,
inputDimensions = std::vector of length 3, capacity 3 = {13, 13, 5}, outputDimensions = std::vector of length 3, capacity 3 = {94556213170576, 94556213170192, 5},
validOutputDimensions = false, training = false}, poolingLayer = {<mlpack::ann::Layer<arma::Mat<double> >> = {
_vptr.Layer = 0x55ff936de190 <vtable for mlpack::ann::MeanPoolingType<arma::Mat<double> >+16>, inputDimensions = std::vector of length 3, …
```
> Adaptive Pooling Hotfix

- src/mlpack/tests/ann_layer_test.cpp
- src/mlpack/tests/loss_functions_test.cpp
matrix initialisation via `operator<<` now emits a compile time deprecation warning as of armadillo 11.2+.
to avoid the deprecation warnings, change matrix initialisation to use C++11 iniitalizer_list.
cf. https://github.com/mlpack/ensmallen/pull/347
> avoid deprecation warnings in armadillo 11.2+

- src/mlpack/methods/det/dt_utils_impl.hpp
Thanks to @SuvarshaChennareddy for pointing this out in #3238!
In fe7d1039 (that commit is from 2012!), I made some changes to the density estimation tree cross-validation code.  When I did that, I inadvertently changed the loop that maximized negative error to a loop that maximized error---that's backwards!  So, I went through the original code before that commit, compared it with the changes in the commit, and this revealed the issue.  I inverted the computation of `thisError`, and renamed it more accurately to `thisNegError`.
(I also changed some `+=`s to `=` for clarity, since those values were only ever assigned once.)
> Fix DET cross-validation loop

- src/mlpack/methods/ann/layer/convolution_impl.hpp
- src/mlpack/methods/ann/layer/grouped_convolution_impl.hpp
Forgot to serialize `useBias` and `paddingType`, which is setting `useBias` to false, causing unexpected problems while using serialized models.
> Serialization Hotfix

- src/mlpack/methods/adaboost/adaboost_impl.hpp
While testing Armadillo 11.2.x for [this issue](https://gitlab.com/conradsnicta/armadillo-code/-/issues/218), I found a small bug: the alias created by `unsafe_col()` gets overwritten when it's updated!  One solution is to move the `arma::rowvec` declaration into the loop; but the other solution, which is probably better, is just to use `max()` directly.  (I think very many years ago, that was not an option, as that function didn't exist then.)
> Don't use alias in `Adaboost::Classify()`

- src/mlpack/core/math/range.hpp
This is a second attempt at #3270.  The description is copied below:
A long time ago, it seemed like a good idea to change `RangeType<T>` to `Range<T>` for mlpack 3; but, in https://github.com/mlpack/mlpack/pull/2777, we adopted the convention that the "default" type was the "short name", and the templated type had `Type<>` on the end; e.g., `Linear` is `LinearType<arma::mat>`.
I don't see any reason to change that convention, so, I just removed the comment here; we can keep `Range = RangeType<double>`.
> Remove `RangeType` change comment (attempt #2)

- src/mlpack/CMakeLists.txt
In #3269, I added the file `namespace_compat.hpp`, but forgot to actually modify CMake so that that file gets installed.
This one-line PR just adds `namespace_compat.hpp` to the list of sources to install when `make install` is called.
> Actually install `namespace_compat.hpp`

- src/mlpack/bindings/go/mlpack/capi/arma_util.cpp
- src/mlpack/bindings/go/mlpack/capi/io_util.cpp
- src/mlpack/bindings/go/tests/go_binding_test.go
- src/mlpack/bindings/julia/julia_util.cpp
- src/mlpack/bindings/julia/julia_util.h
- src/mlpack/bindings/julia/mlpack/params.jl.in
- src/mlpack/bindings/julia/print_input_processing_impl.hpp
- src/mlpack/bindings/julia/print_jl.cpp
- src/mlpack/bindings/julia/print_output_processing_impl.hpp
- src/mlpack/bindings/julia/print_param_defn.hpp
- src/mlpack/bindings/julia/tests/runtests.jl
I discovered in the build of #3275 that #3268 is not the only bugfix required for [this issue](https://gitlab.com/conradsnicta/armadillo-code/-/issues/218) which changes the behavior of Armadillo matrices when `std::move()` is used on aliases.
Actually, there is no need to have `strict` set to `true` for either the Julia or Go binding inputs: the inputs aren't meant to be changed by the binding anyway, so it's completely okay for Armadillo to allocate new memory if the input memory changes size if needed.
I also removed some stray debugging output that snuck its way in sometime in the past several years. :)
> Don't set `strict` for aliases in bindings.

- src/mlpack/methods/ann/layer/max_pooling.hpp
In `MaxPooling`, we use `as_scalar(find(...))` to return the index of the maximum element.  But what happens if there are multiple elements that are equivalently the maximum?  Then, `as_scalar()` will throw an exception, because `find()` will return a vector with more than one element.  So, it is safer to use `index_max()`, where this situation is not a problem.
Honestly I am surprised this situation has not already been encountered, but anyway, it is an easy bugfix.
> Handle MaxPooling index computation for identical elements

- .github/workflows/main.yml
The R GitHub action referencing r-lib/actions@master is stalled out. We need to migrate over to using r-lib/actions@v2. Within this PR, we attempt to address this issue. 
Discussion on matrix.
> Move R Github Actions workflow to r-lib/actions@v2

- README.md
This is a follow-up to #3289.  In #3265, we removed our Doxygen support, but there were a couple of leftover links in `README.md` that didn't get adapted.  This PR simply fixes those.
> Remove Doxygen links.

- README.md
CMake 3.14.0 released in March 2019 [1] added the command line config options `-S <source-dir>` and `-B <build-dir>` and the build argument `--build <build-dir>` [2]. These options are universally valid independent of the build system used (`make`, `nmake`, `ninja`, `MSBuild`,...), making the provided CMake commands more generic.
As reference Ubuntu 20.04 ships the CMake 3.16.3 [3] version.
- [1] https://gitlab.kitware.com/cmake/cmake/-/tags/v3.14.0
- [2] https://cmake.org/cmake/help/v3.14/release/3.14.html#command-line
- [3] https://packages.ubuntu.com/focal/cmake
> Update CMake usage in build instructions

- HISTORY.md
- src/mlpack/bindings/julia/julia_util.cpp
- src/mlpack/bindings/julia/tests/test_julia_binding_main.cpp
Julia is a one-indexed language; so, when the user gives us labels from Julia, we expect them to be in the range `[1, numClasses]`.  Internally, we must map them to `[0, numClasses - 1]` when passing to mlpack, since mlpack and Armadillo are zero-indexed and that is our convention.  For labels, this works just fine.
When we pass categorical data, we have the same one-indexed expectation from Julia: the Julia user will give us a `Matrix{Float64}` as well as a `Vector{Bool}`.  The boolean vector specifies which dimensions are categorical, and then those dimensions in the `Matrix{Float64}` should take values in `[1, numCategories]`.  Here, we must also do the same transformation to `[0, numCategories - 1]`.
However, that transformation was not implemented, which caused the failure in #3300. …
> Fix Julia category mapping

- src/mlpack/bindings/R/CMakeLists.txt
- src/mlpack/bindings/go/CMakeLists.txt
- src/mlpack/bindings/julia/CMakeLists.txt
- src/mlpack/bindings/python/CMakeLists.txt
This patch makes sure that any program we build, even those built for bindings, are statically linked if `BUILD_SHARED_LIBS` is `OFF`.  Essentially it just sets the linking mode to static for anything built for the bindings, using the same structure that is used for the command-line bindings and `mlpack_test`.
> Propagate BUILD_SHARED_LIBS setting to binding compilation too

- src/mlpack/bindings/python/setup.py.in
This modifies the Python binding build configuration to compile without debugging symbols, and strip the compiled libraries.  This can help result in *significantly* smaller wheels.  Compared to mlpack 3.4.2, the compiled libraries in the Python wheel are 10x smaller; part of that has to do with this patch, part of it has to do with all the other changes that have happened since mlpack 3.4.2.
The `-g0` option overrides any previous setting of `-g`; this is necessary because Cython by default will compile with `-g` (which is maybe a little bit of a confusing choice to me, but oh well).
> Optimize and strip Cython compiled libraries

- src/mlpack/bindings/python/setup.py.in
In certain situations (OS X is where I encountered it), one of the libraries in the CMake `MLPACK_LIBRARIES` variable is `"m"`, to indicate that we should link with `-lm`.  However, every other library in `MLPACK_LIBRARIES` is a direct path to a library to link against.  This means that when compiling Cython bindings, we get command-lines like
```
g++ ... /usr/lib/libarmadillo.dylib /usr/lib/libopenblas.dylib m
```
but that `m` isn't very helpful---it needs to be `-lm`.  This patch adds a workaround specifically for this case to the Cython build configuration.
> Correctly link with `-lm` in Python bindings

- src/mlpack/bindings/python/PythonInstall.cmake
As of maybe a year or so ago, the command `python setup.py install` is now [deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html).  The suggestion is to instead use `python -m pip install .`.  So, this patch adapts our CMake Python binding install configuration to do exactly that, and also adds a block for Windows where we don't need to set `--prefix` or `--root`.
Somehow, this patch was necessary to fix some builds for conda-forge on OS X.
In any case, it also makes us not depend on deprecated functionality, which is good. :)
> Use `python -m pip install` instead of `setup.py install`

- src/mlpack/bindings/python/CMakeLists.txt
The conda-forge build system uses the Ninja generator on Windows.  However, I found that Ninja complained of a dependency cycle in targets: python -> python_copy -> mlpack -> python.  I am not sure exactly how that happened, but in any case this patch, which simplifies the dependency structure of the Python targets, fixes it.  It turns out that `python_copy` actually does not depend on `mlpack`, so I removed that, and then made `python` depend on `python_copy`.  With this, Ninja is happy.
> Remove dependency of `python_copy` on mlpack for Ninja build system

- HISTORY.md
- src/mlpack/bindings/julia/julia_method.cpp.in
Ideally, when running an mlpack binding from Julia, we want to catch all exceptions, instead of crashing.
A typo in the existing code meant we only caught `std::runtime_error`s instead of any exception.  So, easy fix: just catch `std::exception` instead.
Note that for these to be caught correctly, the Julia bindings should not be compiled with `-DARMA_NO_DEBUG`, otherwise the out-of-bounds checks will not be done and may cause invalid memory accesses and segfaults, instead of throwing exceptions.
> Catch all exceptions in Julia

- src/mlpack/methods/CMakeLists.txt
Decision trees are classification algorithms, not clustering algorithms.  I must have made a typo during a refactoring.
This will fix the fact that `decision_tree()` is listed under "clustering" instead of "classification" on the binding documentation pages:
https://www.mlpack.org/doc/stable/python_documentation.html
(see the left sidebar)
> Fix documentation type for `decision_tree` binding

- HISTORY.md
- src/mlpack/bindings/R/mlpack/src/r_util.cpp
- src/mlpack/bindings/R/mlpack/tests/testthat/test-R_binding.R
- src/mlpack/bindings/R/print_input_processing.hpp
- src/mlpack/bindings/R/tests/test_r_binding_main.cpp
- src/mlpack/bindings/go/CMakeLists.txt
- src/mlpack/bindings/go/mlpack/arma_util.go
- src/mlpack/bindings/go/mlpack/capi/arma_util.cpp
- src/mlpack/bindings/go/mlpack/capi/arma_util.h
- src/mlpack/bindings/go/print_input_processing.hpp
- src/mlpack/bindings/go/tests/go_binding_test.go
- src/mlpack/bindings/go/tests/test_go_binding_main.cpp
- src/mlpack/bindings/julia/mlpack/params.jl.in
- src/mlpack/bindings/julia/print_input_processing_impl.hpp
- src/mlpack/bindings/julia/tests/runtests.jl
- src/mlpack/bindings/julia/tests/test_julia_binding_main.cpp
- src/mlpack/bindings/python/CMakeLists.txt
- src/mlpack/bindings/python/mlpack/io.pxd
- src/mlpack/bindings/python/mlpack/io_util.hpp
- src/mlpack/bindings/python/mlpack/matrix_utils.py
- src/mlpack/bindings/python/print_input_processing.hpp
- src/mlpack/bindings/python/tests/test_python_binding.py
- src/mlpack/bindings/python/tests/test_python_binding_main.cpp
Digging into #3324, I realized that none of our bindings (except command-line programs) have handling for parameters declared as `PARAM_TMATRIX_IN()` (i.e. a transposed matrix).  LARS happens to be the only binding that actually uses this parameter type, and so what happens is that in languages other than command-line bindings (such as Python), the user's data will be unexpectedly transposed.
This PR adds support for transposed matrices to Python, Go, R, and Julia bindings, which will in turn fix the strange behavior specific to LARS that was encountered in #3324 (and probably by other users).
For each language, this boils down to:
* adding a test for a `PARAM_TMATRIX_IN` parameter
* handling the `noTranspose` parameter from `ParamData` while generating the bindings
* updating the glue …
> Fix binding handling of transposed matrix parameters

- doc/developer/bindings.md
- doc/quickstart/cpp.md
This comes out of https://github.com/mlpack/mlpack.org/issues/59 --- I just took a look in the codebase for the word "doxygen", and removed it.  We don't use Doxygen anymore to document our code, so these references are out of date.
> Remove last references to doxygen in the documentation.

- README.md
- fix internal links
- take into account markdown limitations in the names of internal links (eg. "++" is not doable, so "C++" becomes "C")
- remove second "Quick Links" to reduce confusion with first "Quick Links" (on line 40)
> fix internal links in README.md

- src/mlpack/bindings/R/tests/test_r_binding_main.cpp
- src/mlpack/bindings/go/tests/test_go_binding_main.cpp
- src/mlpack/bindings/julia/tests/test_julia_binding_main.cpp
- src/mlpack/bindings/python/tests/test_python_binding_main.cpp
- src/mlpack/tests/io_test.cpp
- src/mlpack/tests/main_tests/det_test.cpp
- src/mlpack/tests/main_tests/range_search_test.cpp
I received an email from Brian Ripley:
```
clang 15 is warning:
In file included from test_r_binding.cpp:9:
./mlpack/bindings/R/tests//test_r_binding_main.cpp:99:21: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
arma::mat out = move(params.Get<arma::mat>("matrix_in"));
^
std::
...
Please correct before 2023-01-15 to safely retain your package on CRAN.
```
I can't understand the motivation of such a warning, even when there is a `using namespace std`, but anyway, whatever, here's a change that makes all uses of `std::move()` qualified, so that CRAN can be happy.
> Use qualified std::move() to fix clang warnings for CRAN

- .github/workflows/main.yml
While submitting mlpack 4.0.1 to CRAN, after the changes in #3345 that bundle cereal, I found that the file `base64.hpp` caused some CRAN warnings.  The code in question is here:
https://github.com/USCiLab/cereal/blob/master/include/cereal/external/base64.hpp#L28-L31
So, I just added it to the Github action that builds the R package to comment that bit out.
> Comment out pragmas in base64.hpp to fix CRAN warnings

- doc/tutorials/reinforcement_learning.md
Another pretty simple fix.  In #3364 @CoderSahel pointed out that the code in the reinforcement learning tutorial doesn't compile.  This is just because it uses the old mlpack 3 API for neural networks.  I adapted @AdarshSantoria's fix slightly and also fixed a compilation warning.
> Adapt reinforcement learning tutorial to mlpack 4 API

- src/mlpack/core.hpp
Remove the `MLPACK_USE_CX11` define, which is never used.
Related to https://github.com/mlpack/mlpack/pull/3380#issuecomment-1404111240
> remove unused define

- HISTORY.md
- src/mlpack/core/data/save_impl.hpp
- src/mlpack/tests/load_save_test.cpp
Change all instances of `.quiet_save()` to `.save()`.  This is to avoid compile-time deprecation warnings.
The functions `.quiet_save()` and `.quiet_load()` have been deprecated since Armadillo 11.4.4.
Since Armadillo 10.4, the default degree of warning messages has been reduced, so that failed saving / loading no longer emits warnings.
(The warning level can be manually changed via the [ARMA_WARN_LEVEL](https://arma.sourceforge.net/docs.html#config_hpp) option).
> avoid deprecation warnings in Armadillo 11.4.4+

- HISTORY.md
- doc/tutorials/approx_kfn.md
- doc/tutorials/fastmks.md
Fixed the code example in doc as mentioned in #3397 and some other doc fixes.
> Fix codes and improve doc

- src/mlpack/bindings/R/CMakeLists.txt
- src/mlpack/bindings/R/mlpack/configure
Looking over the R package files, I noticed the short (sweet and simple) `configure` script dealing with a special case for the Sun compilation that had been done for so long at CRAN.  But it is a thing of the past so this can be removed.
Now, it does no harm -- but repo clutter is still (a very minor form of) technical debt so I would remove it and suggest to do so here.
> [R] Remove configure script as sunos is no longer an issue

- HISTORY.md
- src/mlpack/methods/cf/decomposition_policies/decomposition_policies.hpp
- src/mlpack/methods/cf/decomposition_policies/quic_svd_method.hpp
- src/mlpack/methods/quic_svd/quic_svd.hpp
- src/mlpack/methods/quic_svd/quic_svd_impl.hpp
- src/mlpack/tests/cf_test.cpp
As mentioned in #3398, Quic_SVD method is added in CF and some standard changes in 'methods/quic_svd` are performed so that it can be used in cf.
> Add Quic_SVD method in CF

- src/mlpack/tests/ann/layer/hard_tanh.cpp
I noticed while trying to release a new version of mlpack that the test `hard_tanh.cpp` was missing a license---easy fix.
(We need to release a new version with the Armadillo warning fixes from #3405 for CRAN.  I guess I could hand-patch a version if someone has a particular reason to wait.)
> Add license to hard_tanh.cpp test

- src/mlpack/tests/ann/ann_test_tools.hpp
Use output of the Forward method instead of input. Fixes #3470 (See issue for more details).
> Fix JacobianTest and CustomJacobianTest (Resolves #3470)

- src/mlpack/methods/ann/layer/log_softmax_impl.hpp
- src/mlpack/tests/ann/layer/log_softmax.cpp
Update the Backward method of LogSoftMax  and fix test corresponding to it. Fixes #3468 (See issue for more details)
See this colab file for my explanation and with references for the new derivative : [LogSoftMax](https://colab.research.google.com/drive/1D_hqaXLb7mFhriFHazuEMp_DPYZmf5Ex#scrollTo=vWU2wnCesDOC).
Also to be noted, the new derivative was tested against JacobianTest(corrected version).
> Fix derivative of LogSoftMax (Resolves #3468)

- HISTORY.md
- src/mlpack/methods/ann/init_rules/gaussian_init.hpp
- src/mlpack/methods/ann/init_rules/kathirvalavakumar_subavathi_init.hpp
- src/mlpack/methods/ann/init_rules/lecun_normal_init.hpp
- src/mlpack/methods/ann/init_rules/nguyen_widrow_init.hpp
- src/mlpack/methods/ann/init_rules/orthogonal_init.hpp
Several initialization classes were missing the serialize method. Without it neural networks that use these init rules cannot be serialized.
> Add serialize to init rules (in ann)

- src/mlpack/methods/ann/layer/ftswish.hpp
- src/mlpack/methods/ann/layer/ftswish_impl.hpp
- src/mlpack/methods/ann/layer/layer_types.hpp
- src/mlpack/methods/ann/layer/serialization.hpp
- src/mlpack/tests/ann/layer/ftswish.cpp
- src/mlpack/tests/ann/layer_test.cpp
This PR Implements the FTSwish Activation Layer.
> Implemented FTSwish Activation Function

- HISTORY.md
- src/mlpack/bindings/python/print_input_processing.hpp
- src/mlpack/core/util/param.hpp
- src/mlpack/methods/preprocess/preprocess_one_hot_encoding_main.cpp
- src/mlpack/tests/main_tests/preprocess_one_hot_encode_test.cpp
- src/mlpack/tests/main_tests/softmax_regression_test.cpp
- src/mlpack/tests/nmf_test.cpp
This allows users to pass categorical matrices to the `preprocess_one_hot_encoding` binding.  This is actually a transparent change, so all user code can remain the same.  But whereas in Python a user would previously call `preprocess_one_hot_encoding(input=dataset)`, now that parameter `dataset` can also be a pandas `DataFrame` whose columns can have any type, instead of just a numpy `ndarray` or similar.
By default, if the `dimensions` parameter is not specified (it is no longer required), all categorical dimensions are one-hot encoded.
This addresses #3480.
There will need to be a new release of mlpack before this becomes available in PyPI or conda (or other languages' package managers).
> Categorical support `preprocess_one_hot_encoding`

- HISTORY.md
- src/mlpack/methods/ann/activation_functions/activation_functions.hpp
- src/mlpack/methods/ann/activation_functions/hyper_sinh_function.hpp
- src/mlpack/methods/ann/layer/base_layer.hpp
- src/mlpack/tests/ann/activation_functions_test.cpp
- src/mlpack/tests/ann/not_adapted/activation_functions_test.cpp
Implemented Hyper-Sinh activation function.
> Added Hyper-Sinh activation function

- scripts/release-mlpack.sh
When I ran the release script for 4.2.0, the file `doc/examples/sample-ml-app/README.txt` was not checked in.  This PR just fixes that.
> Add missing file to git commit for release script

- HISTORY.md
- src/mlpack/methods/reinforcement_learning/ddpg.hpp
- src/mlpack/methods/reinforcement_learning/ddpg_impl.hpp
- src/mlpack/methods/reinforcement_learning/reinforcement_learning.hpp
- src/mlpack/tests/q_learning_test.cpp
This pull request implements the DDPG (Deep Deterministic Policy Gradient) algorithm, along with 2 test cases. 
DDPG is an actor-critic algorithm designed for continuous action spaces. It combines deep neural networks with deterministic policy gradients to learn optimal policies in a continuous control setting.
Implemented four networks:
- `policyNetwork` (actor network)
- `targetPNetwork` (target actor network)
- `learningQNetwork` (critic network)
- `targetQNetwork` (target critic network)
The test configurations for DDPG are adapted from the SAC (Soft Actor-Critic) implementation since both DDPG and SAC are policy gradient off-policy algorithms. This ensures consistent evaluation and comparison of the algorithms.
> Reinforcement Learning: Deep Deterministic Policy Gradient 

- src/mlpack/bindings/R/mlpack/DESCRIPTION.in
This is just a simple change to `DESCRIPTION` that references the new mlpack 4 paper instead of the somewhat older mlpack 3 paper.
> Update R package description to more recent mlpack 4 paper

- HISTORY.md
- src/mlpack/methods/reinforcement_learning/ddpg.hpp
- src/mlpack/methods/reinforcement_learning/ddpg_impl.hpp
- src/mlpack/methods/reinforcement_learning/noise/noise.hpp
- src/mlpack/methods/reinforcement_learning/noise/ornstein_uhlenbeck.hpp
- src/mlpack/methods/reinforcement_learning/reinforcement_learning.hpp
- src/mlpack/tests/q_learning_test.cpp
This pull request implements the Ornstein-Uhlenbeck noise class, along with a unit test. 
The Ornstein-Uhlenbeck process is a process that generates temporally correlated noise via a random walk with damping, which is commonly used in reinforcement learning algorithms.
- I added a new file for convenience to include new noise classes in the future. 
- The `OUNoise` class provides a `reset()` function that sets the internal state of the noise process to the specified mean (mu).
- It offers a `sample()` function to update the internal state based on the mean reversion rate (theta) and standard deviation (sigma), and returns the current state as a noise sample.
> Reinforcement Learning: Ornstein-Uhlenbeck noise

- src/mlpack/methods/reinforcement_learning/environment/cont_double_pole_cart.hpp
- src/mlpack/methods/reinforcement_learning/environment/environment.hpp
I should probably comment to point out that this PR is not a joke.  As much as I'd like it to be.  I'll do my best to keep my editorializing to a minimum.  Ah, too late.
I submitted mlpack 4.2.0 to CRAN.  It failed the checks: https://win-builder.r-project.org/incoming_pretest/mlpack_4.2.0_20230623_145416/Debian/00check.log
```
Found the following non-portable file path:
mlpack/inst/include/mlpack/methods/reinforcement_learning/environment/continuous_double_pole_cart.hpp
Tarballs are only required to store paths of up to 100 bytes and cannot
store those of more than 256 bytes, with restrictions including to 100
bytes for the final component.
```
The filename is too long, so people running R on Soviet-era PDP clones with only-standards-compliant-and-nothing-more `tar` versions could have …
> Shorten filename for CRAN tar limits

- HISTORY.md
- src/mlpack/methods/decision_tree/decision_tree.hpp
This handles #3509 by adding `DecisionTree::ClassProbabilities()`, plus a note that these are only class probabilities when the node is a leaf and not an internal node.  This could be useful not just for obtaining class probabilities but also information about the split.
> Add ClassProbabilities() member to DecisionTree.

- .ci/linux-steps.yaml
- README.md
- src/mlpack/bindings/python/CMakeLists.txt
- src/mlpack/bindings/python/PythonInstall.cmake
This addresses some of the issues in #3500 by disabling network access during the Python installation step.  (e.g., we are now doing `python -m pip install --no-index --no-deps`.  A quick explanation of the changes:
* Adding the `--no-index` option disables searching PyPI for dependencies during installation.
* Adding the `--no-deps` option is likely unnecessary but disallows the installation of any dependencies; so, we will only install mlpack (which is what we want).
* By default, pip creates a new temporary Python environment to do the installation in, and installs all build requirements of the packages there---and *then* it does the installation.  However, if no network access is available, then you need to either make all the build requirements available as wheels... or add …
> Python binding installation fixes

- HISTORY.md
- src/mlpack/methods/reinforcement_learning/reinforcement_learning.hpp
- src/mlpack/methods/reinforcement_learning/td3.hpp
- src/mlpack/methods/reinforcement_learning/td3_impl.hpp
- src/mlpack/tests/q_learning_test.cpp
This pull request implements the TD3 (Twin Delayed Deep Deterministic Policy Gradient) algorithm, along with 2 test cases. 
TD3 (Twin Delayed Deep Deterministic Policy Gradient) is a reinforcement learning algorithm designed for continuous action spaces. It builds upon DDPG and introduces twin critics and delayed updates to improve stability and performance. 
Implemented 6 networks:
- `policyNetwork` (actor network)
- `targetPNetwork` (target actor network)
- `learningQ1Network` (first critic network)
- `targetQ1Network` (first target critic network)
- `learningQ2Network` (second critic network)
- `targetQ2Network` (second target critic network)
- With TargetNetworkSyncInterval = 1 ——> -1081.52
- With TargetNetworkSyncInterval = 2 ——> -508.788
- With TargetNetworkSyncInterval = 3 ——> …
> Reinforcement Learning: Twin Delayed Deep Deterministic Policy Gradient

- .ci/ci.yaml
- .ci/macos-steps.yaml
- src/mlpack/bindings/python/get_arma_type.hpp
- src/mlpack/bindings/python/get_cython_type.hpp
- src/mlpack/bindings/python/mlpack/arma_numpy.pxd
- src/mlpack/bindings/python/mlpack/arma_numpy.pyx
- src/mlpack/bindings/python/mlpack/io.pxd
- src/mlpack/bindings/python/print_input_processing.hpp
- src/mlpack/bindings/python/print_output_processing.hpp
- src/mlpack/bindings/python/print_pyx.cpp
- src/mlpack/bindings/python/setup.py.in
This is a bugfix for https://bugzilla.redhat.com/show_bug.cgi?id=2226015.
Newer versions of Cython don't seem to properly detect all the `.pxd`s during Python binding compilation.
I am not 100% sure what the reason for this is, but in any case, adding the `mlpack/` directory specifically to the list of `include_dirs` causes Cython to correctly detect the `.pxd` files.
> Add extra mlpack/ path so Cython properly detects .pyx files.

- src/mlpack/tests/ann/layer/parametric_relu.cpp
- src/mlpack/tests/main.cpp
I wanted to fix two failing tests, but I couldn't reproduce one of them, so I'm still scratching my head about what to do there.
* I found that `PReLUIntegrationTest` was not robust and failed often.  So I changed some tolerances and allowed multiple trials.  I don't think anything is actually wrong in the implementation.
* Like ensmallen, I added support to specify the random seed in the command-line options to `mlpack_test`.  This should make it easier to test for robustness.
This plus a few other recent PRs should go a long way towards making the builds green again.
The other test I couldn't get is a `RADICAL` test, where somehow NaNs are sneaking in.
> Test fixes

- .ci/windows-steps.yaml
- src/mlpack/tests/cf_test.cpp
I noticed while going to release a patch version of mlpack that Azure Pipelines is not succeeding at building the MSI installer.  I think it is just a path issue, so let's see if this fixes it.
I also loosened some tolerances for some CFTest failures I was observing (they happened about 5% of the time).  If I see more random test failures in this PR, I'll fix them too.
> Fix Windows Azure MSI build and loosen some test tolerances

- src/mlpack/methods/ann/ffn_impl.hpp
- src/mlpack/methods/ann/layer/batch_norm_impl.hpp
- src/mlpack/methods/ann/layer/c_relu_impl.hpp
- src/mlpack/methods/ann/layer/convolution.hpp
- src/mlpack/methods/ann/layer/convolution_impl.hpp
- src/mlpack/methods/ann/layer/grouped_convolution.hpp
- src/mlpack/methods/ann/layer/grouped_convolution_impl.hpp
- src/mlpack/methods/ann/layer/leaky_relu.hpp
- src/mlpack/methods/ann/layer/leaky_relu_impl.hpp
- src/mlpack/methods/ann/layer/mean_pooling_impl.hpp
- src/mlpack/methods/ann/layer/serialization.hpp
This PR allows to compile mnist_simple with `arma::fmat` instead of the standard `arma::mat`
@rcurtin feel free to review, I only tested mnist_simple. If necessary for the other will be a new episode of Float PRs
The duck is helpful with these complex errors, it took much less time than expected this time.
> Float -- episode 1 

- HISTORY.md
- src/mlpack/core/dists/regression_distribution.hpp
- src/mlpack/core/dists/regression_distribution_impl.hpp
- src/mlpack/methods/linear_regression/linear_regression.hpp
In #3540 @kiner-shah pointed out that it is possible to create a circular include loop!  I was surprised by this, but the reason is that the `RegressionDistribution` class (in `src/mlpack/core/dists/`) depends on the `LinearRegression` class (in `src/mlpack/methods/`).  This is the only situation where something in `core/` includes something in `methods/`, and as a result, if you just happen to only include `linear_regression.hpp`, you get a problem.
Anyway, one solution is to have `linear_regression.hpp` only include `mlpack/prereqs.hpp` (which does not include the `dists/`), and then include `mlpack/core.hpp` after `LinearRegression` is defined.
After this PR, the following slightly more complex example compiles:
```c++
include <mlpack/methods/linear_regression.hpp>
using namespace …
```
> Fix include ordering for `LinearRegression`

- HISTORY.md
- src/mlpack/methods/ann/regularizer/lregularizer_impl.hpp
In the case where there was a 0 in the weights, the L1Regularizer would produce a nonfinite value in the gradient due to a divide-by-zero.  This code was just attempting to implement the "sign" function, so replaced it with that.
> Fix L1 regularization in case where weight is zero

- HISTORY.md
- src/mlpack/bindings/R/mlpack/R/package.R
Second attempt (see #3536)... this time on a correct branch. :)
I got another email from Kurt Hornik about something that needs to change in the R package:
```
Dear maintainer,
You have file 'mlpack/man/mlpack.Rd' with \docType{package}, likely
intended as a package overview help file, but without the appropriate
PKGNAME-package \alias as per "Documenting packages" in R-exts.
This seems to be the consequence of the breaking change
Using @docType package no longer automatically adds a -package alias.
Instead document _PACKAGE to get all the defaults for package
documentation.
in roxygen2 7.0.0 (2019-11-12) having gone unnoticed, see
<https://github.com/r-lib/roxygen2/issues/1491>.
As explained in the issue, to get the desired PKGNAME-package \alias
back, you should either change to the new …
```
> Another cran fix round two

- HISTORY.md
- src/mlpack/base.hpp
Workaround for the byzantine ways of enabling C++17 mode in the MSVC "compiler".
MSVC uses a custom macro named `_MSVC_LANG` in addition to (or instead of) the standard `__cplusplus` macro, depending on how the user enabled C++17 mode (which itself can be confusing).
Related to https://github.com/mlpack/mlpack/issues/3549
> detect C++17 mode in MSVC

- HISTORY.md
- doc/examples/sample-ml-app/sample-ml-app/sample-ml-app.vcxproj
- doc/user/build_windows.md
- doc/user/sample_ml_app.md
This is just a follow-up to #3555, since that option is no longer required for MSVC.
> Remove other uses of /Zc:__cplusplus in the documentation.

- HISTORY.md
- src/mlpack/bindings/python/print_doc_functions_impl.hpp
- src/mlpack/methods/linear_regression/linear_regression_train_main.cpp
This is a fix for #3556, in the Python bindings.  The generated documentation would print a line like
```py
X_test, y_test, X_train, y_train = preprocess_split(input_=X, input_labels=y)
```
but `preprocess_split()` returns a Python dict with several members.  Instead, this is what's necessary to get the training/test datasets:
```py
d = preprocessd_split(input_=X, input_labels=y)
X_train = d['training']
y_train = d['training_labels']
X_test = d['test']
y_test = d['test_labels']
```
These changes update the function that prints this documentation to use the second version.  I tested that the generated code runs successfully.
> Fix call to preprocess_split() in generated documentation.

- src/mlpack/methods/ann/layer/multihead_attention.hpp
This is a fix from #3573; @akropp looks like we forgot to fix the documentation after reverting to the 0/-inf strategy for masks. :smile:
> Fix documentation for `MultiheadAttention`

- CMake/ConfigureFileOnly.cmake
- src/mlpack/bindings/python/CMakeLists.txt
- src/mlpack/bindings/python/mlpack.pc.in
- src/mlpack/bindings/python/setup.py.in
This addresses #3544: with these changes, all of the mlpack headers and also a configured `mlpack.pc` (for pkgconfig) is distributed with the mlpack Python package.  Like [pybind11](https://github.com/pybind/pybind11), the headers are packaged in `mlpack/include/` and the pkgconfig file in `mlpack/share/pkgconfig/`.
I needed to add a version of `ConfigureFile.cmake` that included the `@ONLY` option for `configure_file()`, so that `mlpack.pc.in` and its use of bash variables did not get overwritten by CMake configuration.
> Add include files and configured pkgconfig file to Python distribution

- src/mlpack/tests/perceptron_test.cpp
The perceptron `IncrementalTrainingTest` attempts to ensure that when we call `Reset()`, the reset perceptron does not have the same weights as a perceptron that has been incrementally trained more than once.
However, the dataset was small enough---and separable enough---that it was possible for both perceptrons (reset and not reset) to have the exact same solution, so that the test failed.  On my system this happened about once out of every hundred different random seeds.
To fix this, I increased the dataset size, made it less separable into two classes, and stopped checking the biases for different values, because those often happen to have exactly the same values regardless of the weights.  Plus, it's sufficient to just check the weights.
This succeeded on my system for 1000 different …
> Fix flaky `IncrementalTrainingTest`

- src/mlpack/bindings/python/CMakeLists.txt
This fixes the failing Python tests in #3565, #3578, and #3564 (and other builds).  The error comes from #3579, where I mistakenly merged the PR even though some tests were failing.  Oops...
The actual failure being fixed is this:
```
_________________ ERROR collecting tests/dataset_info_test.py __________________
import file mismatch:
imported module 'dataset_info_test' has this __file__ attribute:
/home/vsts/work/1/s/build/src/mlpack/bindings/python/mlpack/include/mlpack/bindings/python/tests/dataset_info_test.py
which is not the same as the test file we want to collect:
/home/vsts/work/1/s/build/src/mlpack/bindings/python/tests/dataset_info_test.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```
which is a result of the Python bindings …
> Fix python test duplicate filename error

- .github/workflows/main.yml
- .github/workflows/update-catch.yaml
- .github/workflows/update-cli11.yaml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> Use GITHUB_OUTPUT envvar instead of set-output command as the latter is deprecated

- src/mlpack/tests/decision_tree_regressor_test.cpp
- src/mlpack/tests/test_function_tools.hpp
This allows multiple trials for the `DecisionTreeRegressor` tests.  I found them to be failing at the rate of about one every hundred times.  With these fixes, I saw no failures at all with 1000 different random seeds.
I also combined one of the tests that had both an `fmat` and a `mat` version into a single test using `TEMPLATE_TEST_CASE()`.  That required some slight changes to some of the test tools.
> Reduce random failures for DecisionTreeRegressor tests

- src/mlpack/core/util/arma_traits.hpp
- src/mlpack/methods/ann/init_rules/const_init.hpp
- src/mlpack/methods/ann/init_rules/gaussian_init.hpp
- src/mlpack/methods/ann/init_rules/he_init.hpp
- src/mlpack/methods/ann/init_rules/kathirvalavakumar_subavathi_init.hpp
- src/mlpack/methods/ann/init_rules/lecun_normal_init.hpp
- src/mlpack/methods/ann/init_rules/nguyen_widrow_init.hpp
- src/mlpack/methods/ann/init_rules/oivs_init.hpp
- src/mlpack/methods/ann/init_rules/orthogonal_init.hpp
- src/mlpack/methods/ann/init_rules/random_init.hpp
This PR converts all the `arma::Mat<eT>` in the init methods to `MatType`.
This should be merged quickly.
> S01E05 Convert all the init methods from arma::mat to MatType

- src/mlpack/core/util/arma_traits.hpp
- src/mlpack/methods/ann/activation_functions/identity_function.hpp
- src/mlpack/methods/ann/activation_functions/swish_function.hpp
- src/mlpack/methods/ann/layer/convolution.hpp
- src/mlpack/methods/ann/layer/convolution_impl.hpp
- src/mlpack/methods/ann/layer/grouped_convolution.hpp
- src/mlpack/methods/ann/layer/grouped_convolution_impl.hpp
- src/mlpack/methods/ann/loss_functions/poisson_nll_loss.hpp
This PR addresses the last part of converting `arma::Mat`  and `arma::Cube` to `MatType` and `CubeType` in the ANN code base. In the next PR we will start addressing `arma::Col`
> S01E07 Adding the last missing part from `arma::Mat` to `MatType` and from `arma::Cube` to `CubeType`

- src/mlpack/bindings/R/mlpack/src/Makevars.win
CC: @coatless @eddelbuettel @kalibera
This is an experimental PR to try and remove the GCC-specific options from `Makevars.win`.  @kalibera pointed out via email that the R package build fails on Windows when using LLVM, because the `track-macro-expansion=0` compiler option isn't available in LLVM.  If we wanted, we could make the option conditional, but @kalibera noted that the build was actually faster under gcc without those options.  So, let's see what happens here.
Those options were originally added to decrease RAM usage so that the CRAN Windows workers would build successfully (if I remember right), but perhaps they aren't needed anymore.
First we can try this PR here, and if this succeeds, I can port these tiny changes to the existing mlpack CRAN package and see if CRAN still …
> [R] Remove extra gcc-specific options from Makevars.win

- HISTORY.md
- src/mlpack/bindings/R/mlpack/R/package.R
Fixes deprecation of `@docType package` by using `"_PACKAGE"`.
```
✖ package.R:15: `@docType "package"` is deprecated.
ℹ Please document "_PACKAGE" instead.
```
> [R] Update roxygen2 package-level documentation entry

- HISTORY.md
- src/mlpack/methods/decision_tree/best_binary_numeric_split_impl.hpp
This is among the more esoteric issues that I have come across, although it's not particularly difficult to understand.  While I was reproducing #3595, on my system I would encounter a crash when building some of the trees in the random forest.  First I will write the problem, then I will show how it led to the crash:
Suppose I have two floating-point numbers `a` and `b`, and I want to compute the midpoint `(a + b) / 2`.
If `a` and `b` are adjacent (i.e. they differ by only one bit), then the midpoint actually cannot be represented as a floating-point number, and so the system will return either `a` *or* `b` as the result of `(a + b) / 2`, which is not correct but it's the best that floating-point can do.
Here's a very simple test case you can run to see:
```c++
#include <iostream> …
```
> Handle adjacent floating-point values in `BestBinaryNumericSplit`

- src/mlpack/core/data/scaler_methods/max_abs_scaler.hpp
- src/mlpack/core/data/scaler_methods/mean_normalization.hpp
- src/mlpack/core/data/scaler_methods/min_max_scaler.hpp
- src/mlpack/core/tree/binary_space_tree/rp_tree_max_split_impl.hpp
- src/mlpack/core/tree/binary_space_tree/rp_tree_mean_split_impl.hpp
- src/mlpack/core/tree/cellbound_impl.hpp
- src/mlpack/core/tree/cosine_tree/cosine_tree_impl.hpp
- src/mlpack/core/util/using.hpp
- src/mlpack/methods/ann/init_rules/gaussian_init.hpp
- src/mlpack/methods/ann/init_rules/he_init.hpp
- src/mlpack/methods/ann/init_rules/lecun_normal_init.hpp
- src/mlpack/methods/ann/layer/parametric_relu_impl.hpp
- src/mlpack/methods/ann/layer/softmin_impl.hpp
- src/mlpack/methods/approx_kfn/approx_kfn_main.cpp
- src/mlpack/methods/decision_tree/all_categorical_split_impl.hpp
- src/mlpack/methods/decision_tree/random_binary_numeric_split_impl.hpp
- src/mlpack/methods/det/dtree_impl.hpp
- src/mlpack/methods/kmeans/elkan_kmeans_impl.hpp
- src/mlpack/methods/lmnn/constraints_impl.hpp
- src/mlpack/methods/lmnn/lmnn_function_impl.hpp
- src/mlpack/methods/lmnn/lmnn_main.cpp
- src/mlpack/methods/preprocess/preprocess_describe_main.cpp
- src/mlpack/methods/reinforcement_learning/environment/mountain_car.hpp
- src/mlpack/methods/reinforcement_learning/sac_impl.hpp
- src/mlpack/methods/reinforcement_learning/td3_impl.hpp
- src/mlpack/tests/ann/layer/parametric_relu.cpp
- src/mlpack/tests/ann/loss_functions_test.cpp
- src/mlpack/tests/ann/recurrent_network_test.cpp
- src/mlpack/tests/cosine_tree_test.cpp
Hi,
There is still one single test that is failing and I am not able to figure out where the issue is coming from. Here is the test failure:
```
./bin/mlpack_test
mlpack version: mlpack git-a62b12d4ed
armadillo version: 12.6.1 (Cortisol Retox)
random seed: 0
terminate called after throwing an instance of 'std::logic_error'
what():  as_scalar(): expression must evaluate to exactly one element
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mlpack_test is a Catch v2.13.10 host application.
Run with -? for options
-------------------------------------------------------------------------------
OneStepQLearningTest
-------------------------------------------------------------------------------
/meta/mlpack/src/mlpack/tests/ann/async_learning_test.cpp:21 …
```
> Coot 12, refactor, `arma::min`, `arma::imbue` and some other bugs

- doc/quickstart/cpp.md
I noticed while looking at the quickstart that the Debian/Ubuntu package is named wrong.  Oops, easy fix...
> Fix name of package in Debian/Ubuntu

- src/mlpack/tests/catch.hpp
adapted from upstream catch2 repo: https://github.com/catchorg/Catch2/pull/2840
same content as the PR for ensmallen: https://github.com/mlpack/ensmallen/pull/398
> catch2 workaround for recent issue under macOS

- doc/user/methods/decision_tree.md
- doc/user/methods/decision_tree_regressor.md
Noticed a few faults in the DecisionTree and DecisionTreeRegressor documentation related to the `NoRecursion` flag:
- In the code it has been defaulted to false
but in the documentation it said defaulted to true
- `NoRecursion=false` implies that it will be a full Decision Tree, and `NoRecursion=true` implies that it will be a stump, but it's the opposite in the documentation.
> DecisionTree documentation - NoRecursion flag

- doc/quickstart/cpp.md
**Description**:
This PR refines the installation section of the mlpack Quickstart guide to better serve Ubuntu LTS users, who may face issues due to outdated libmlpack-dev versions in their repositories (currently version 3.4.2). The lack of the mlpack.hpp header in these versions can hinder new users' ability to run mlpack successfully.
**Changes**:
- Included a note for Ubuntu LTS users about the older `libmlpack-dev` version. 
- Recommended building mlpack from source or using Docker for accessing the latest version.
Appreciate your review and feedback on this documentation update.
> Add Warning for Ubuntu LTS installation instructions

- doc/index.md
- doc/sidebar.html
These changes add a `Basics` section to the sidebar of the documentation, and also provide direct links to the existing CV/HPT documentation.
I think that with these changes, the documentation is ready to deploy, and we can have the `Documentation` link on the mlpack website link directly to the index.md page.
Compiled example:
[click](https://www.ratml.org/misc/mlpack-markdown-doc-2/)
I thought about having the `Basics` section expanded by default in the sidebar, but I'd love to hear others' opinions on that too---and any other details.
> Add more links to sidebar, including CV/HPT.

- src/mlpack/methods/ann/layer/add_impl.hpp
- src/mlpack/tests/ann/layer/add.cpp
- src/mlpack/tests/ann/layer_test.cpp
The current implementation of the `Add` layer (which just adds a bias to each element) does not properly handle batch sizes greater than 1.  This can be seen in the example in #3666.
The `Gradient()` function expects the `error` matrix to be of size `outSize` x `batchSize`, and the gradient matrix itself is already sized to be `weightSize` x `1`.  (For the `Add` layer, it is conveniently true that `weightSize == outSize`.)
However, the existing implementation of `gradient = error` is only correct when `batchSize = 1`.  Much like [the Linear layer](https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/ann/layer/linear_impl.hpp#L132), the bias term's gradient is computed as the *sum* across all input points in the batch.
I then noticed that the `Add` layer is not tested, so I …
> Fix batch handling for `Add::Gradient()`

- doc/user/methods/adaboost.md
I noticed while reading the AdaBoost documentation that the constructor parameters table did not render correctly; this is because of some line breaks in the table.  Oops.  This PR just makes the table line one line in the source Markdown, so that the table will render correctly again.
> Fix `AdaBoost` constructor parameter table

- HISTORY.md
- src/mlpack/bindings/R/mlpack/src/rcpp_mlpack.h
- src/mlpack/bindings/R/print_R.cpp
- src/mlpack/bindings/R/r_method.cpp.in
This fixes #3675.
I reproduced the issue and found that the `verbose` argument to mlpack's R bindings had no effect, even though the `EnableVerbose()` function was successfully being called.
This is because `Log::Info` (which is what the `EnableVerbose()` function modified) is a singleton object, and exists once *in each translation unit*.  Since `EnableVerbose()` is compiled into the translation unit for the file `r_util.cpp`, the `Log::Info` modified by `EnableVerbose()` ends up being *different* than the `Log::Info` that is being used by each individual binding---so, in essence, we are enabling verbose mode... with the wrong `Log::Info` object.
I fixed this by removing the standalone `EnableVerbose()` and `DisableVerbose()` functions, and instead modifying the `Log::Info` object's …
> Fix `verbose` for R bindings

- src/mlpack/methods/bias_svd/bias_svd.hpp
- src/mlpack/methods/bias_svd/bias_svd_function.hpp
- src/mlpack/methods/bias_svd/bias_svd_function_impl.hpp
- src/mlpack/methods/bias_svd/bias_svd_impl.hpp
I did not touch the code related to ensmallen in this file since I have no idea why it is here, and what it is supposed to do.
Maybe it should be moved to ensmallen at some point ? also why the template parameters are not filled in ?
I did not chance what is related to shuffle since we still do not have it in bandicoot.
> Move to `MatType` in bias svd

- doc/index.md
- doc/sidebar.html
- doc/user/load_save.md
- doc/user/methods/nmf.md
- scripts/build-docs.sh
- src/mlpack/core/data/detect_file_type.hpp
- src/mlpack/core/data/detect_file_type_impl.hpp
- src/mlpack/core/data/load.hpp
- src/mlpack/core/data/load_impl.hpp
- src/mlpack/core/data/types_impl.hpp
- src/mlpack/methods/amf/amf.hpp
- src/mlpack/methods/amf/amf_impl.hpp
- src/mlpack/methods/amf/init_rules/average_init.hpp
- src/mlpack/methods/amf/init_rules/given_init.hpp
- src/mlpack/methods/amf/init_rules/init_rules.hpp
- src/mlpack/methods/amf/init_rules/merge_init.hpp
- src/mlpack/methods/amf/init_rules/no_init.hpp
- src/mlpack/methods/amf/init_rules/random_acol_init.hpp
- src/mlpack/methods/amf/init_rules/random_init.hpp
- src/mlpack/methods/amf/termination_policies/max_iteration_termination.hpp
- src/mlpack/methods/amf/termination_policies/simple_residue_termination.hpp
- src/mlpack/methods/amf/termination_policies/simple_tolerance_termination.hpp
- src/mlpack/methods/amf/termination_policies/validation_rmse_termination.hpp
- src/mlpack/methods/amf/update_rules/nmf_als.hpp
- src/mlpack/methods/amf/update_rules/nmf_mult_dist.hpp
- src/mlpack/methods/amf/update_rules/nmf_mult_div.hpp
- src/mlpack/methods/nmf/nmf_main.cpp
- src/mlpack/tests/load_save_test.cpp
- src/mlpack/tests/nmf_test.cpp
I documented the `NMF` class---which actually did not exist before this PR.  Previously, you would use `AMF` with certain template types.  But, this felt strange to write in the documentation for something like `NMF`, which is a well-known technique name (whereas `AMF` is not necessarily a well-known name because it is just a general shell of an algorithm).  So, I created the `NMF` class, which is just a different name for the `AMF` class, and then wrote documentation for it.
The documentation can be seen here: https://www.ratml.org/misc/mlpack-markdown-doc/user/methods/nmf.html
In writing and testing the documentation, I changed or fixed a handful of other things:
* I noticed that `data::Load()` for sparse matrices did not autodetect types correctly; so I rewrote it internally, wrote …
> Documentation for `NMF` plus some bugfixes

- doc/quickstart/cpp.md
Hi there,
Conan just added the mlpack package. This PR adds some simple steps to install it.
Thanks in advance!
> docs: Add Conan Installation steps (quickstart)

- src/mlpack/bindings/R/mlpack/tests/testthat/test-R_binding.R
- src/mlpack/bindings/R/tests/test_r_binding_main.cpp
As suggested by @eddelbuettel [here](https://github.com/mlpack/mlpack/pull/3691#issuecomment-2062312759), I wrote a simple test to ensure that when you pass `verbose = TRUE` to an R binding, you get some kind of output at all.
I'm not R-fluent, but this seems to be correct?  I could have misunderstood something :smile:
> Test "verbose" option for R.

- src/mlpack/methods/ann/activation_functions/hyper_sinh_function.hpp
Consistently with the format of `src/mlpack/methods/ann/activation_functions/rectifier_function.hpp`
> Add reference for hyper-sinh activation function

- HISTORY.md
- src/mlpack/methods/lars/lars_impl.hpp
- src/mlpack/tests/lars_test.cpp
- src/mlpack/tests/sparse_coding_test.cpp
I noticed that the tests for LARS were failing more than once every hundred trials with different random seeds, so I started digging in to see what was wrong.  I came out with a few conclusions:
* With `float` as an element type, the `PredictTest` can be more flaky---this is expected due to less precision.  So now it allows multiple trials when the element type is `float`.
* When a singularity is encountered, we try to remove the most-recently-added variable from the active set.  However, the `activeGramMatrix` was not removing its columns correctly.
* When computing the signs of correlations, if the correlation was exactly 0, then there was a division by 0.  I fixed that just by adding a small value to the denominator.
* The check to see if an externally-passed Gram matrix satisfied the …
> Fix sometimes-failing LARS tests

- src/mlpack/bindings/cli/print_help_impl.hpp
- src/mlpack/core/dists/regression_distribution.hpp
- src/mlpack/core/dists/regression_distribution_impl.hpp
- src/mlpack/methods/adaboost/adaboost_classify_main.cpp
- src/mlpack/methods/adaboost/adaboost_main.cpp
- src/mlpack/methods/decision_tree/decision_tree_main.cpp
- src/mlpack/methods/naive_bayes/nbc_main.cpp
- src/mlpack/methods/perceptron/perceptron_main.cpp
- src/mlpack/tests/main_tests/adaboost_test.cpp
- src/mlpack/tests/main_tests/nbc_test.cpp
- src/mlpack/tests/main_tests/perceptron_test.cpp
I found a number of options to bindings and other functions that had been marked deprecated with an intent to remove for mlpack 4.0.0.  So, since the current stable version is 4.3.0, I went ahead and removed them.  Better late than never 😄
> Remove deprecated functionality

- HISTORY.md
- src/mlpack/bindings/R/default_param_impl.hpp
- src/mlpack/bindings/R/mlpack/src/r_util.cpp
- src/mlpack/bindings/R/mlpack/tests/testthat/test-R_binding.R
- src/mlpack/bindings/R/print_doc.hpp
- src/mlpack/bindings/R/print_input_param.hpp
This fixes #3692 in just the way that @cgiachalis suggested.
Instead of the `verbose` option being printed with a default of `FALSE` (e.g. `verbose = FALSE`), it is now printed as `verbose = getOption("mlpack.verbose", FALSE)`.  That is, it defaults to false unless `mlpack.verbose` has been set (at least to the best of my limited R understanding).
I also added tests to make sure that it operates correctly.
@eddelbuettel @coatless let me know what you think here, a double-check would be much appreciated. :+1:
> Use global option for R package verbosity

- doc/index.md
- doc/sidebar.html
- doc/user/methods/sparse_coding.md
- src/mlpack/methods/sparse_coding/data_dependent_random_initializer.hpp
- src/mlpack/methods/sparse_coding/nothing_initializer.hpp
- src/mlpack/methods/sparse_coding/random_initializer.hpp
- src/mlpack/methods/sparse_coding/sparse_coding.hpp
- src/mlpack/methods/sparse_coding/sparse_coding_impl.hpp
- src/mlpack/methods/sparse_coding/sparse_coding_main.cpp
- src/mlpack/tests/main_tests/sparse_coding_test.cpp
- src/mlpack/tests/sparse_coding_test.cpp
I wrote up documentation for the `SparseCoding` class.  You can see it here:
https://www.ratml.org/misc/mlpack-markdown-doc/user/methods/sparse_coding.html
I also changed `SparseCoding` so that it supports different `MatType`s.  Otherwise, not much was needed here, which made the documentation process pretty straightforward (hooray!).
> Document `SparseCoding`

- doc/user/core.md
I forgot to handle this in #3712, but it's a simple fix.
> Add equation for spherical kernel

- HISTORY.md
- src/mlpack/bindings/R/CMakeLists.txt
I managed to knock this out during a meeting.  The changes are pretty simple:
* Include `stb_image.h` and `stb_image_write.h` as part of the R package distribution.  This is important because we are not guaranteed that a user has these present on their system (which I think will cause a package installation failure if they don't).
* Patch use of `sprintf()` inside `stb_image_write.h` to `snprintf()`.  This is actually already done in a slightly different way in an [open STB patch](https://github.com/nothings/stb/pull/1619), although that still leaves an `sprintf()` call in, so maybe  the patch I did is better, at least for CRAN.
I patched this locally in the version of mlpack I just submitted to CRAN.
This fixes #3724.
> Distribute patched STB with R package

- scripts/release-mlpack.sh
While releasing mlpack 4.4.0, a couple things needed to be changed in the release script due to the new, slightly different formatting of `HISTORY.md`.
> Minor fixes for release-mlpack.sh

- src/mlpack/methods/ann/layer/batch_norm.hpp
- src/mlpack/methods/ann/layer/linear.hpp
- src/mlpack/methods/ann/layer/multi_layer.hpp
For my ONNX converter project, I need access to the `epsilon`, `gamma`, and `beta` parameters of the BatchNorm layer. However, in the current implementation of `BatchNorm`, these parameters are private. Therefore, I am making this PR to address this issue.
> Getters and setters for the epsilon, gamma, and beta parameters of BatchNorm

- doc/user/methods/adaboost.md
- doc/user/methods/decision_tree.md
- doc/user/methods/decision_tree_regressor.md
- doc/user/methods/linear_regression.md
- doc/user/methods/naive_bayes_classifier.md
- doc/user/methods/random_forest.md
- scripts/build-docs.sh
- scripts/test-docs.sh
- src/mlpack/methods/decision_tree/decision_tree_regressor.hpp
Since https://github.com/mlpack/examples/pull/229 was merged, the notebooks inside the example repository now live in different directories, so the links inside the Markdown documentation need to be updated accordingly.
> Update Jupyter notebook example links in documentation

- src/mlpack/methods/ann/layer/convolution_impl.hpp
I've made several optimizations to the backward function in the convolution code; the main areas of improvement include padding, rotation, and dilation operations. These changes aim to reduce computational overhead and a speed up.
**Changes**
_Padding Optimization_
Instead of adding padding to the input data separately, I've integrated the fixed padding values directly into the convolution operation. This reduces the number of steps required.
_Rotation Optimization_
The previous method involved rotating filters by 180 degrees. To optimize this, I replaced the rotation with a combination of matrix flipping or transposing followed by reversing. Additionally I embedded the rotation directly into the convolution step, which simplifies the overall computation.
_Dilation Optimization_
For …
> Optimized the backward convolution function

- HISTORY.md
- src/mlpack/bindings/python/mlpack/matrix_utils.py
This should fix #3723; the behavior of `np.array()` changed in NumPy 2.0.0 and now throws a `ValueError` if the `copy=False` argument is given and a copy cannot be avoided.  But we were using `copy=False` with the intention of "don't copy unless you need to"---where the more correct option is just to pass `None` instead.  According to the documentation that should be backwards-compatible with NumPy 1.x too; CI will tell us if that's true in just a few minutes. :)
@jakirkham if you happen to have a moment to review, it would be appreciated, but no worries if too much is going on. :+1:
> Handle different behavior of .array() in NumPy 2.0.0

- .github/workflows/stale.yml
Since mlpack-bot is sadly built on code that is now completely deprecated, and I can't manage to get it to start anymore, it's probably time to move on (sorry mlpack-bot!).
This uses the https://github.com/actions/stale action to mark issues as stale after 30 days, and close them after another week.  I replicated the settings that were used by mlpack-bot.
> Add stale configuration to replace mlpack-bot

- .github/workflows/auto-approve.yml
Since I can't get mlpack-bot to run anymore (and admittedly the entire stack it is built on is deprecated and mostly archived), I built a Github action to do the same thing:
https://github.com/rcurtin/auto-approve
Hopefully, if that all works correctly, adding it to the repository here should re-enable the 24-hour-delayed auto-approvals that have been missing for the past couple weeks.
> Auto-approve action

- .github/workflows/stickers.yaml
- .github/workflows/welcome-pr.yaml
This replaces the now-non-working functionality of mlpack-bot to post to new contributors about stickers.
I think that maybe it has been a while since this worked correctly.
(So if you are seeing for the first time that we mail stickers out and you want some, well, go ahead and email stickers@mlpack.org, I will get some in the mail for you :))
I am less confident that these two actions (stickers on first contribution, and a welcome message for new contributors on their first PR) work correctly, so there may be some debugging after merge here.
> Post about stickers as a Github action

- src/mlpack/core/tree/ballbound.hpp
- src/mlpack/core/tree/ballbound_impl.hpp
- src/mlpack/core/tree/binary_space_tree/binary_space_tree.hpp
- src/mlpack/core/tree/binary_space_tree/binary_space_tree_impl.hpp
- src/mlpack/core/tree/binary_space_tree/breadth_first_dual_tree_traverser.hpp
- src/mlpack/core/tree/binary_space_tree/breadth_first_dual_tree_traverser_impl.hpp
- src/mlpack/core/tree/binary_space_tree/dual_tree_traverser.hpp
- src/mlpack/core/tree/binary_space_tree/dual_tree_traverser_impl.hpp
- src/mlpack/core/tree/binary_space_tree/single_tree_traverser.hpp
- src/mlpack/core/tree/binary_space_tree/single_tree_traverser_impl.hpp
- src/mlpack/core/tree/binary_space_tree/traits.hpp
- src/mlpack/core/tree/space_split/projection_vector.hpp
- src/mlpack/tests/dbscan_test.cpp
- src/mlpack/tests/knn_test.cpp
- src/mlpack/tests/serialization_test.cpp
Currently, using mlpack's `BinarySpaceTree` with non-`double` data is awkward because the bound type has no way of automatically knowing the type of data being used.  For instance, this is the type required for a `KDTree` built on `float`s:
```
BinarySpaceTree<EuclideanDistance,
EmptyStatistic,
arma::fmat,
HRectBound<EuclideanDistance, float>>;
```
The ugly part here is that `HRectBound` that manually needs the `float` specified.
By modifying `BinarySpaceTree` to automatically apply its element type as the second template parameter of the bound type, we can resolve this and we get the much simpler:
```
BinarySpaceTree<EuclideanDistance,
EmptyStatistic,
arma::fmat>
``` 
In order to do this successfully, the `BallBound` type had to be modified to take an `ElemType` as its second template …
> Refactor `BoundType` to take `ElemType` as a second parameter

- .github/workflows/auto-approve.yml
- .github/workflows/stale.yml
- .github/workflows/stickers.yaml
This is a follow-up to #3755, #3756, and #3757.  Since I couldn't really completely test them before deploying them, there were a couple of issues that I fixed here:
* The auto-approver was only waiting for 30ms after a review instead of 24 hours... fixed via an upstream version bump.
* I specified the version of the stale action wrong.
* Incorrect YAML key name for the stickers action.
> Round one of mlpack-bot action fixes.

- scripts/build-docs.sh
It seems like some URLs that we check are perfectly valid but the servers return a 400 code.  I'm guessing this is because they are trying to filter out bot traffic.  So I added 400s to the list of HTTP return codes that we ignore...
Hopefully this will fix the documentation build...
> Filter out 400 responses from `build-docs.sh`

- .github/workflows/auto-approve.yml
- .github/workflows/stickers.yaml
This time I am hoping to fix these things:
* The auto-approve action filtered out all PR reviews less than a day old, so it missed its own review on #3758 and posted a second auto-approval message.  https://github.com/rcurtin/auto-approve/commit/157e87f2904c3accd724af6d085fbc68a100b652 is the actual underlying fix.
* I don't know why the stickers job (which currently doesn't have permissions to post the comments) thought that I was a first-time contributor in #3758, but I modified the [first-interaction](https://github.com/rcurtin/first-interaction) action to print a bit more debugging output.  So there will definitely be a third round there.
> Round two of mlpack-bot Github actions fixes

- .ci/linux-steps.yaml
- .ci/windows-steps.yaml
- CMakeLists.txt
- HISTORY.md
- README.md
- src/mlpack/bindings/go/mlpack/capi/arma_util.hpp
- src/mlpack/bindings/julia/julia_util.cpp
- src/mlpack/bindings/python/mlpack/arma_util.hpp
- src/mlpack/core/util/arma_traits.hpp
Bump minimum Armadillo version to 10.8.
This allows using the numerous Armadillo API additions and enhancements since 9.800.  It also allows assuming throughout the mlpack codebase that matrices are initialised to zero by default.
Current state of Armadillo versions in various distros:
- Ubuntu 22.04 LTS has Armadillo 10.8.2
- Ubuntu 24.04 LTS has Armadillo 12.6.7
- Debian 12 has Armadillo 11.4.2
- Debian 13 (testing) has Armadillo 12.8.2
- RHEL EPEL 8 & 9 has Armadillo 12.6.6 (subject to future upgrades)
Related: https://github.com/mlpack/ensmallen/pull/404
> Bump minimum Armadillo version to 10.8

- .github/workflows/auto-approve.yml
- .github/workflows/stickers.yaml
I think that I can make my Github actions life a little bit easier if I don't fully specify the version number down to the patch version in the Github actions configurations.
This means I can push patch releases to [rcurtin/auto-approve](https://github.com/rcurtin/auto-approve) and [rcurtin/first-contribution](https://github.com/rcurtin/first-contribution) and those changes should be automatically applied to the mlpack repository.  (So, I can fix things like the auto-approver not approving and the sticker message being sent too liberally behind-the-scenes.)
> Don't fully specify version number for Github actions

- src/mlpack/tests/distribution_test.cpp
I noticed on a bunch of CI jobs that various individual tests for the `GaussianDistribution` and `GammaDistribution` classes fail.  I ran them locally, and I think this is a result of spurious failures; I didn't see anything wrong in the implementation.
After tuning tolerances and increasing dataset sizes (so that distributions are easier to estimate), I saw no failures in 5000 runs of the `[DistributionTest]` test suite.
> Fix flaky `DistributionTest`

- .github/workflows/stale.yml
I noticed that the stale labeler was applying the incorrect label to PRs.  It turns out this is because the stale action needs different configuration for `stale-issue-label` and `stale-pr-label`; we were missing the latter, so I just added it.
> Specify label for stale PRs.

- doc/quickstart/cpp.md
- doc/user/core.md
Aligned the cpp quickstart fedora package with the instructions from https://www.mlpack.org/download.html
> Update the name of the fedora package

- COPYRIGHT.txt
- HISTORY.md
- src/mlpack/core/tree/octree/octree_impl.hpp
The new compiler version seems to perform more exhaustive checks on templates, even if they are not initiated. As the code was malformed also before, it is likely that it is dead code. However, this commit is mainly to ensure users using clang 19 can include the header without compilation error.
Note that this commit does not guarantee that currently other code might not compile with clang 19, it just fixes some code which was used transitevily and caused problems.
> Fix compilation errors with clang 19

- doc/developer/trees.md
- doc/sidebar.html
- doc/user/core/trees.md
- doc/user/core/trees/binary_space_tree.md
- doc/user/core/trees/kdtree.md
- doc/user/core/trees/mean_split_kdtree.md
- src/mlpack/core/tree/binary_space_tree/typedef.hpp
The `MeanSplitKDTree` class is just a typedef of `BinarySpaceTree`, so it was pretty simple to document.  I adapted `kdtree.md` to `mean_split_kdtree.md`, and added a section for `MeanSplit` in `binary_space_tree.md`.
I know that duplicates a lot of documentation, but I think it is easier for the user to be presented with a single page that describes everything `MeanSplitKDTree` does, instead of having to jump between pages to the `BinarySpaceTree` documentation and other places.
* `MeanSplitKDTree` documentation: [link](http://ci.mlpack.org/job/pull-request%20documentation%20build%20and%20test/872/Built_20documentation/user/core/trees/mean_split_kdtree.html)
* `MeanSplit` documentation: [link](http://ci.mlpack.org/job/pull-request%20documentation%20build%20and%20test/872/Built_20documenta …
> Document `MeanSplit` and `MeanSplitKDTree`

- HISTORY.md
- src/mlpack/methods/ann/layer/lstm_impl.hpp
I debugged mlpack/examples#239 and found that the `LSTM` layer did not properly copy all of its internal members, leading to an attempted way-too-large memory allocations in some cases.
The fix is pretty simple: `inSize` and `outSize` just need to be set correctly.
Thanks @CyberShadow for the report!
> Fix copy/move constructor and operator for LSTM layer

- src/mlpack/tests/ann/layer/nearest_interpolation.cpp
The use of `operator<<` to fill matrices is deprecated since a little more than two years. In order to reduce the number of warnings during compilation of `mlpack` and reduce likelyhood that something breaks as soon as `armadillo` removes the deprecated operator, this commit uses the initializer list form as suggested by the deprecation warning from `armadillo`.
> Fix armadillo deprecation warning

- .ci/linux-steps.yaml
- .ci/macos-steps.yaml
- README.md
- doc/quickstart/go.md
- src/mlpack/bindings/go/CMakeLists.txt
- src/mlpack/bindings/go/tests/CMakeLists.txt
Just noticed that the MacOS CI builds for Go are failing, looks like because Go is not installed.  Let's see if this fixes it...
*Edit*: in the process of debugging the MacOS Go build, I figured out what was necessary to use Go modules. (This is the "new" way for Go packages as of... 2018? It's been a while.)
Basically Go in modules mode will go and get the dependencies we need during the build process (just Gonum). So, instead of checking for it in the CMake configuration step, we can just depend on the go build system to install gonum as needed.
Then, I updated the quickstart and installation directions to work with Go modules.
> Use Go modules for Go bindings

- src/mlpack/methods/amf/update_rules/svd_incomplete_incremental_learning.hpp
The warning was detected during build of the tests on Linux with gcc 13.2.
> Fix uninitialized variable warning

- doc/embedded/crosscompile_armv7.md
I was working through the embedded tutorial for an RPi3 today and I noticed that the CMake configuration command to build the tests uses two different buildroot directories.  This simple PR makes them the same.
> Fix inconsistency in embedded tutorial

- doc/developer/community.md
- doc/developer/gsoc.md
Seems like codeproject.com is down and has been for a few days... I switched it out with Wikipedia.  The idea was just for that page to link to some resources that describe template metaprogramming, and I think Wikipedia will work fine.
> Fix documentation link that's failing

- .github/workflows/main.yml
- src/mlpack/methods/adaboost/adaboost_impl.hpp
- src/mlpack/methods/approx_kfn/drusilla_select_impl.hpp
- src/mlpack/methods/decision_tree/decision_tree_impl.hpp
- src/mlpack/methods/hmm/hmm_impl.hpp
- src/mlpack/methods/hoeffding_trees/binary_numeric_split_impl.hpp
- src/mlpack/methods/hoeffding_trees/hoeffding_categorical_split_impl.hpp
- src/mlpack/methods/hoeffding_trees/hoeffding_numeric_split_impl.hpp
- src/mlpack/methods/kmeans/max_variance_new_cluster_impl.hpp
- src/mlpack/methods/naive_bayes/naive_bayes_classifier_impl.hpp
- src/mlpack/methods/perceptron/perceptron_impl.hpp
- src/mlpack/methods/radical/radical_impl.hpp
- src/mlpack/methods/random_forest/random_forest_impl.hpp
This is a PR in response to an Armadillo 14.2.0 change that creates a fair amount of compilation noise for mlpack right now.  A corresponding (if smaller) PR for ensmallen [was made yesterday](https://github.com/mlpack/ensmallen/pull/409), tested fine, and is pending.
This PR driven primarily by the changes CRAN currently shows ([link here](https://cloud.r-project.org/web/checks/check_results_mlpack.html), screenshot of pertinent part below as the link will will change).
(and similarly for the other OS/compiler combinations).
There is one warning I have addressed, namely
https://github.com/mlpack/mlpack/blob/4653e10b800f78b0cb1b5ef0a27a8af46b424bcb/src/mlpack/methods/perceptron/perceptron_impl.hpp#L247
This warns without a suggested alternate. If `std::max()` is to be used, then I may not …
> Update deprecated .max(ind), .min(ind) to .index_max(), .index_min()

- src/mlpack/methods/adaboost/adaboost_impl.hpp
- src/mlpack/methods/ann/loss_functions/vr_class_reward_impl.hpp
- src/mlpack/methods/naive_bayes/naive_bayes_classifier_impl.hpp
- src/mlpack/tests/adaboost_test.cpp
- src/mlpack/tests/mean_shift_test.cpp
@rcurtin followup to #3835, changing the remaining instances of deprecated`.max(index)` to `.index_max()` et al.
> rest of .max(index) to .index_max() changes

- COPYRIGHT.txt
As can be seen on the [CRAN page for mlpack](https://cloud.r-project.org/web/packages/mlpack/index.html), @coatless is listed twice (as both fourth, and fifth-last author/contributor).   There is filtering via a `CMakeLists.txt` variable `SPECIAL_AUTHORS` but somehow that code would not 'bite' and leave the redundant second entry. Doing it as done here by adjusting the entry in `COPYRIGHT.txt` avoids a duplicate entry in a local build.
I also rolled the copyright year for his and my entry after eyeballing the one-line `git ls` output here.  That part could be reversed if there is a desire to keep PRs more single-focus.
> Adjust COPYRIGHT.txt entry for @coatless to avoid dupe

- CMakeLists.txt
This is a very minor 'quality of life' improvement.  On systems such as mine, STB is found system-wide (no we cannot alter it) and under the current compiler flags nags for pages on end with
```
In file included from /home/edd/git/mlpack/src/mlpack/core/data/save_image.hpp:24,  
from /home/edd/git/mlpack/src/mlpack/core/data/save.hpp:24,        
from /home/edd/git/mlpack/src/mlpack/core/util/io.hpp:32,          
from /home/edd/git/mlpack/src/mlpack/core.hpp:44,                  
from /home/edd/git/mlpack/build/src/mlpack/bindings/R/build/generate_r_bayesian_linear_regression.cpp:24:                       
/usr/include/stb/stb_image_write.h: In function ‘int stbi_write_bmp_to_func(void (*)(void*, void*, int), void*, int, int, int, const void*)’:
/usr/include/stb/stb_image_write.h:514:32: …
```
> Quieten STB compilation with -Wno-missing-field-initializers

- src/mlpack/methods/adaboost/adaboost_impl.hpp
This was reported by CRAN.  (I just fixed it manually in the tarball I uploaded, but wanted to get the fix into mlpack too, of course.)
```
../inst/include/mlpack/methods/adaboost/adaboost_impl.hpp:337:19: warning: assigning field to itself [-Wself-assign-field]    
```
Looks like some legacy code got left behind that is no longer needed.  `this->tolerance` is set by the `Train()` function, and doesn't need to be set in the `TrainInternal()` function.
> Fix `-Wself-assign-field` in AdaBoost

- .ci/linux-steps.yaml
Shortens yaml file a little, a check with `apt-cache show ...` confirms that we get essentially all the same package versions (cereal is 1.3.2 vs 1.3.1).  Should not have side effects.
Also removes g++ as explicit target as it should always be present.
> Install stb and cereal via apt just like brew does

- .ci/linux-steps.yaml
- .ci/macos-steps.yaml
- .github/workflows/main.yml
- README.md
- doc/embedded/supported_boards.md
- doc/quickstart/cpp.md
- doc/user/install.md
This is an attempt to fix #3852 by setting `OMP_NUM_THREADS` appropriately for CI jobs, and clarifying documentation throughout to point this issue out.
I wish that there was a better thing we could do to prevent this issue, but I think that we are stuck with it until Ubuntu 24.04 goes out of favor...
> Attempt to work around OpenBLAS thread thrashing issue

- doc/embedded/supported_boards.md
- doc/sidebar.html
- doc/user/core/trees.md
- doc/user/core/trees/ball_tree.md
- doc/user/core/trees/binary_space_tree.md
- doc/user/core/trees/cover_tree.md
- doc/user/core/trees/kdtree.md
- doc/user/core/trees/max_rp_tree.md
- doc/user/core/trees/mean_split_ball_tree.md
- doc/user/core/trees/mean_split_kdtree.md
- doc/user/core/trees/rp_tree.md
- doc/user/core/trees/ub_tree.md
- doc/user/core/trees/vptree.md
- src/mlpack/core/tree/cover_tree/cover_tree.hpp
Back to the documentation of trees... today I documented `CoverTree`.  Fairly self-explanatory PR, no code changes, just added documentation.
Link to built `CoverTree` page: _(not built yet... link forthcoming)_
I also noticed some small typos on a few other tree pages and inconsistencies which I fixed.
> Document `CoverTree`

- .github/workflows/main.yml
This addresses a concern by GitHub expressed in mass-mail to repo owners (so I got it for other repos) and updates one remaining artifact action from the soon-to-be inactive @v3 to one of the @v4* values we already use in the same file in another spot.
> Switch remaining upload-artifact to v4*

- doc/user/core/split.md
- src/mlpack/core/data/split_data.hpp
- src/mlpack/core/util/arma_traits.hpp
- src/mlpack/tests/split_data_test.cpp
In my work on an RNN example, I realized that I couldn't use `data::Split()` because:
* it didn't support `arma::cube`s, and
* it didn't have a way for me to also split the sequence lengths
So, I adapted `data::Split()` to support `cube`s, and added another overload that also takes a set of input `weights`.  I added tests for all of these and updated the documentation accordingly.
I was able to remove an overload of `data::Split()` for fields, but the functionality is still there---it is just merged with the other overloads now.  So from a user perspective nothing is changed, there is just new support added.
> Add support for weights to data::Split() and allow cube types.

- .github/workflows/main.yml
I got an email indicating that we were using old versions of the `cache` action.  Let's try updating them... as far as I can tell, they work the same as before.
> Update cache Github action to v4

- src/mlpack/base.hpp
This is a follow-up for #3873.  mlpack's CMake configuration will refuse to enable OpenMP for Visual Studio, where the OpenMP version is very old, but that only helps a user if they are building mlpack directly.  If a user is building their own project, they may simply enable `/OPENMP` when using Visual Studio.  But this will then result in compilation errors, because the Visual Studio OpenMP support is too old. Even though `base.hpp` does disable `MLPACK_USE_OPENMP`, this does not help compilation because we use unguarded `#pragma omp`s throughout the codebase (and I'd prefer to keep it this way: less boilerplate, simpler to read, and if you are compiling without OpenMP the pragmas just get ignored).
I thought about it for a little while and I think the best solution is to issue a …
> Turn silent disabling of OpenMP into an actual compilation error

- doc/developer/ci.md
- src/mlpack/core/math/random.hpp
- src/mlpack/core/tree/address.hpp
- src/mlpack/core/tree/cellbound.hpp
- src/mlpack/core/tree/rectangle_tree/discrete_hilbert_value.hpp
- src/mlpack/tests/hmm_test.cpp
- src/mlpack/tests/main_tests/hmm_train_test.cpp
- src/mlpack/tests/split_data_test.cpp
- src/mlpack/tests/ub_tree_test.cpp
While cleaning up Jenkins jobs, I updated the version of [`cpplint`](https://github.com/cpplint/cpplint) we use to version 2.  This is controlled in [`lint.sh`](https://github.com/mlpack/jenkins-conf/blob/master/linter/lint.sh) in the jenkins-conf repository.
The update was made as part of a larger Jenkins cleanup---I removed the `cppcheck` plugin from Jenkins because it was outdated and deprecated, and then I modified the lint scripts to output to JUnit XML directly, which can then be parsed with another (newer) plugin.
As part of this, there were a couple small style issues that cpplint asked to be handled and I obliged.
> Fix style issues that cpplint 2 found

- doc/sidebar.html
- doc/user/core/trees.md
- doc/user/core/trees/octree.md
- src/mlpack/core/tree/octree/octree.hpp
- src/mlpack/core/tree/octree/octree_impl.hpp
- src/mlpack/core/util/arma_traits.hpp
I documented the `Octree`, yet another one of mlpack's trees.  It almost (...almost) feels like the end might be in sight for trees.  For the most part, this follows the same general formula for documentation of previous trees, as they all pretty much implement the same methods.
I discovered that `Octree` needed a few changes to correctly work with `float` element types.
Built documentation: http://ci.mlpack.org/job/pull-request%20documentation%20build%20and%20test/1193/Built_20documentation/user/core/trees/octree.html
> Add documentation for `Octree`

- src/mlpack/core/data/string_algorithms.hpp
The old implementations of `Trim()` and `TimIf()` had some problems:
- For inputs that consist only whitespace but do not contain a normal space (e.g. the string "\t"), `Trim()` accesses the input string at an invalid index. `endIndex` is decremented when it is already zero and the result is passed to the `[]` operator of the string.
- `TrimIf()` checks for the presence of spaces in the input string, regardless of the function that is passed. E.g. `std::string s = " "; TrimIf(s, [](char c){ return c == 'a';});` results in an emptry string instead of leaving the string untouched.
> fix Trim() and TrimIf()

- doc/developer/trees.md
- doc/sidebar.html
- doc/user/core/trees.md
- doc/user/core/trees/ball_tree.md
- doc/user/core/trees/binary_space_tree.md
- doc/user/core/trees/cover_tree.md
- doc/user/core/trees/kdtree.md
- doc/user/core/trees/max_rp_tree.md
- doc/user/core/trees/mean_split_ball_tree.md
- doc/user/core/trees/mean_split_kdtree.md
- doc/user/core/trees/r_tree.md
- doc/user/core/trees/rectangle_tree.md
- doc/user/core/trees/rp_tree.md
- doc/user/core/trees/ub_tree.md
- doc/user/core/trees/vptree.md
- src/mlpack/core/tree/hrectbound_impl.hpp
- src/mlpack/core/tree/rectangle_tree/rectangle_tree.hpp
- src/mlpack/core/tree/rectangle_tree/rectangle_tree_impl.hpp
- src/mlpack/core/tree/rectangle_tree/typedef.hpp
- src/mlpack/tests/rectangle_tree_test.cpp
- src/mlpack/tests/serialization_test.cpp
While waiting on the CI jobs to iterate, I documented `RectangleTree` and `RTree`.  `RectangleTree` is the base class underlying `RTree` and a whole host of other trees that will end up with documentation pages that look a whole lot like the rest of the trees.
Some minor changes were needed to the code:
* Change `HRectBound` so that if you do `bound |= other` and `bound` is empty (i.e. has dimensionality 0), the dimensionality will be set to that of `other`.  This is a convenience to make it easier to construct an `HRectBound` without any arguments, and then grow it to match points.  The `RectangleTree` growth code depends on this.
* Make default constructor for `RectangleTree` public.
* Add `Insert(point)` and `Delete(pointIndex)` functions to `RectangleTree`, so that the tree can be …
> Document `RectangleTree` and `RTree`

- HISTORY.md
- src/mlpack/bindings/python/mlpack/preprocess_json_params.py
This fixes #3886.  Basically, the crash there happens like this:
* When a user calls `.get_cpp_params()` on an mlpack object in Python, this uses cereal to serialize the C++ object to JSON.
* We then load the JSON object into a Python dict with Python's `json.loads()`.
* We detect any Armadillo objects in the dict and convert them to numpy objects.
* During that conversion, we look for the `elem` key in the dictionary representation of the Armadillo object; but the code crashes, because for an empty Armadillo matrix (e.g. 0 rows or 0 columns), no `elem` key is serialized by cereal...
so, I addressed this by checking if the number of rows or columns is 0, and if so, returning an empty numpy object with the correct size.
> Handle empty Armadillo objects in Python JSON conversion

- .github/workflows/ci.yml
- src/mlpack/tests/load_save_test.cpp
The current GHA pipelines code, when it runs the tests, redirects all output into a file which it then parses to remove unnecessary output.  But Catch2 offers a `-o` option which could mean we don't even need the redirect/postprocessing!
For testing, I have forced a test to fail and give stdout and stderr output, so that I can ensure this is still visible from the GHA test output.  If everything works, I'll remove that, and the only change will be `ci.yml`.
> Use catch `-o` option for junit output

- .jenkins/cross-compilation/Jenkinsfile
- .jenkins/doc-link-check/Jenkinsfile
- .jenkins/doc-snippet-build/Jenkinsfile
- .jenkins/memory-checks/Jenkinsfile
- .jenkins/style-checks/Jenkinsfile
- .jenkins/utils.groovy
- src/mlpack/tests/load_save_test.cpp
I fixed a few issues with the Jenkins CI jobs in this PR:
* Jenkins backref links are really bad---you click on a failed build and it brings you to some random pipeline page.  Now it takes you to the build page itself, or the test report page if any tests failed.
* Jenkins statuses are strange, and sometimes don't work correctly.  Now we use the Github Checks plugin which seems to be more reliable.
* Jenkins workspace cleanings sometimes fail, because Jenkinsfiles are surprisingly brittle and I have to do all the error checking myself, I guess.  So now I don't check the repo out from git automatically, and instead always clean the workspace before and after a build, and check out manually after that cleaning step is done.
> Minor CI cleanups

- .jenkins/cross-compilation/Jenkinsfile
- HISTORY.md
- src/mlpack/methods/ann/layer/lstm.hpp
- src/mlpack/tests/ann/layer/lstm.cpp
As @nzachary pointed out in #3912, currently, the `LSTM` layer computes the size of its input by accumulating the input dimensions.  But this is not correct: it should be the product instead.
This simple PR fixes that and adds a test case.
> Fix `LSTM` input size calculation

- .github/workflows/ci.yml
Two problems to be fixed here:
* The build of Armadillo is not failing when CMake configuration fails.  (It fails at a later step.  It should fail earlier.)
* CMake is refusing to configure the older Armadillo 10.8.2, which requests CMake 2.8.12+ compatibility.  New CMake dropped reverse compatibility for anything older than 3.5, so probably this just needs a workaround option.
> Fix CMake configuration for older Armadillo versions on CI

- src/mlpack/methods/CMakeLists.txt
While packaging mlpack 4.6.0, I noticed that `mlpack_image_converter` wasn't building.  I realized that this was because the `STB_AVAILABLE` variable in CMake is no longer present, since we are bundling STB.  So, this quick patch fixes the issue.
> Always build `image_converter` binding

- COPYRIGHT.txt
- HISTORY.md
- src/mlpack/core/math/shuffle_data.hpp
- src/mlpack/methods/ann/rnn_impl.hpp
- src/mlpack/tests/math_test.cpp
I noticed that rnns don't shuffle the sequence lengths with the data/labels
This pr should fix that
> Shuffle sequence lengths

- .jenkins/cross-compilation/Jenkinsfile
For the cross-compilation job, there was nothing to make sure that the embedded devices weren't running 1000 `mlpack_test`s at a time.  This actually happened a decent bit and would cause one of the RPis to go down.  Hopefully this PR should fix it, by using the `lockfile` command to make sure that there is only one test running at a time.
> Use a lockfile to prevent oversaturating the embedded devices

- src/mlpack/methods/lmnn/lmnn_impl.hpp
Replace `arma::is_finite(X)` with `X.is_finite()`.
The function `arma::is_finite()` has long been silently deprecated in Armadillo (ie. undocumented).  It has now been explicitly marked as deprecated upstream, which will produce a compile time warning when compiling mlpack.
The replacement in this PR is to avoid various forms of "feedback" from CRAN.
> use non-deprecated form of is_finite()

- HISTORY.md
- src/mlpack/core/data/save_impl.hpp
- src/mlpack/core/data/utilities.hpp
While compiling Python bindings on a system that had HDF5 enabled, I encountered a compilation failure:
http://ci.mlpack.org/job/mlpack-wheels/111/pipeline-console/?selected-node=67
Uh, it's really hard to find the failure in there, but basically in `SaveMatrix()`, when `ARMA_USE_HDF5` is set, then the `filename` parameter doesn't exist.  So I threaded the `filename` parameter through `SaveDense()` and `SaveSparse()` to fix the issue.
The reason that `filename` is needed is that Armadillo doesn't support saving HDF5 to streams---it only saves to filenames.
CC: @shrit because this is related to #3927.
> Fix compilation of `Save()` when HDF5 is enabled

- scripts/release-mlpack.sh
Sometime in the past, the `sample_ml_app.md` documentation was moved to `deploy_windows.md`.  This PR updates the release script accordingly, so that the version of mlpack listed there is kept up to date when releasing a new version of mlpack.
> Update release scripts for new documentation location

- HISTORY.md
- src/mlpack/bindings/R/CMakeLists.txt
We have a manual patch for CRAN in `stb_image_write.h`, because CRAN complains about the use of `sprintf`.  The patch is simple---just modify and use `snprintf` instead.
However, I noticed that this patch is not being applied to the R sources anymore; this is because we are now bundling STB with mlpack instead of depending on it from external sources.
Therefore, now, we need to directly patch the bundled file (and we need to do it always).
There's no need for a new release specifically for CRAN after this PR---I just made the change manually to the 4.6.1 tarball.
> Update location of patched file for CRAN

- HISTORY.md
- src/mlpack/bindings/R/CMakeLists.txt
The fact that `STBIRDEF` in `stb_image_resize2.h` is a macro defined as `static` causes a warning on CRAN:
```
../inst/include/mlpack/core/stb/bundled/stb_image_resize2.h:7983:26: warning: 'static' function 'stbir_resize_uint8_linear' declared in header file should be declared 'static inline' [-Wunneeded-internal-declaration]
```
CRAN calls this a `significant warning`.  I don't.  But in any case, just like the other patch we apply to STB sources, I did this one in the same way.  I don't have a particularly strong justification for doing it here instead of updating our bundled version, I'm just sticking with the technique we're already doing (just above my patch).
> Fix another CRAN warning for the definition of `STBIRDEF`

- HISTORY.md
- src/mlpack/core/data/detect_file_type_impl.hpp
(CC @shrit)
This should fix #3960.  In essence the problem seen there is that a categorical CSV is not correctly detected based on its extension.  This problem surfaced in mlpack 4.6.2 due to the refactoring that is in progress to replace the existing `Load()` interface with a much nicer `DataOptions` class.
Prior to #3927, the code path taken for `Load()` on categorical matrices was separate, and file formats were inferred based on the extension alone.  But after #3927, this now uses the function `AutoDetectFile()` and the rest of the machinery that is used for regular matrices.  (That is a good thing!)
However, one line of code in there, which was meant to check whether or not a character was a numeric or possibly-numeric ASCII character, happens to fail specifically with the …
> Use a looser check for non-printable ASCII characters

- .jenkins/doc-link-check/Jenkinsfile
This PR only runs the documentation link checking job on hosts that don't seem to have problems with Cloudflare blocking (sigh... the modern internet).
> Try to restrict link checking job to certain nodes

- doc/sidebar.html
@shrit and I noticed that these two pages were missing from the cross-compilation documentation:
https://www.mlpack.org/doc/embedded/supported_boards.html
https://www.mlpack.org/doc/embedded/crosscompile_example.html
I added them to `sidebar.html` and reorganized things just a little bit.
> Add links to cross-compilation pages

- src/mlpack/methods/ann/layer/ftswish_impl.hpp
- src/mlpack/tests/hmm_test.cpp
While I was going through the NN layers, I also found that the `FTSwish` implementation could be improved by making it a one-liner.  Timing on a simple 1M input layer before:
```
Forward(): 0.0130176s
Backward(): 0.0200074s
```
After:
```
Forward(): 0.0129755s
Backward(): 0.00884357s
```
This will have an outsized effect when using Bandicoot, because the previous iterate-over-each-element implementation is pretty much worst-case for Bandicoot (which needs everything as one big expression it can put on the GPU).
> Improve `FTSwish` implementation

- src/mlpack/tests/ann/ann_test_tools.hpp
I fixed several instances of failing tests that depended on the [old ensmallen step size strategy](https://github.com/mlpack/ensmallen/pull/431), in the PR #4002.  However, it seems like I missed a couple of places, causing the mlpack integration test in [this PR](https://github.com/mlpack/ensmallen/pull/439) to fail.
I tested locally and these fixes will cause those tests to pass.
> Make sure ensmallen 3 tests with the right step size.
