README.md

I have updated the path.Since, mlpack has been installed in my local directory.

Updated path of install in Readme

---

src/mlpack/core/math/random.cpp
src/mlpack/core/math/random.hpp

if we use c++11 we can use std random module instead of boost random.

Use c++11 random.

---

src/mlpack/methods/ann/cnn.hpp
src/mlpack/methods/ann/ffn.hpp

Fix part of the compile time issues of vc2015

fix vc2015 compile issue

---

src/mlpack/methods/ann/init_rules/oivs_init.hpp

fix bugs
1 : Forgot to define the data member "epsilon"
2 : The data member "b" should initialize at initialization list

fix constructor bug(oivs_init.hpp)

---

src/mlpack/methods/ann/layer/dropout_layer.hpp

DropOutLayer forgot to initialize the scale parameter(I hope this is the correct way to initialize it)

Fix drop out layer

---

src/mlpack/core/math/CMakeLists.txt
src/mlpack/core/math/columns_to_blocks.cpp
src/mlpack/core/math/columns_to_blocks.hpp
src/mlpack/methods/sparse_autoencoder/CMakeLists.txt
src/mlpack/methods/sparse_autoencoder/maximal_inputs.cpp
src/mlpack/methods/sparse_autoencoder/maximal_inputs.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/maximal_inputs_test.cpp

Still lack a meaningful unit test, up until now I only compare the results with the one shown at this website(http://deeplearning.stanford.edu/wiki/index.php/Visualizing_a_Trained_Autoencoder).

Create a function to visualize the features learned by sparse autoencoder

---

src/mlpack/core/arma_extend/CMakeLists.txt
src/mlpack/core/arma_extend/Cube_extra_bones.hpp
src/mlpack/core/arma_extend/Cube_extra_meat.hpp
src/mlpack/core/arma_extend/arma_extend.hpp
src/mlpack/tests/serialization.hpp
src/mlpack/tests/serialization_test.cpp

Implement arma::Cube serialization

Cube serialize

---

src/mlpack/methods/ann/layer/conv_layer.hpp
src/mlpack/methods/ann/layer/dropout_layer.hpp
src/mlpack/methods/ann/layer/linear_layer.hpp
src/mlpack/methods/ann/layer/lstm_layer.hpp
src/mlpack/methods/ann/layer/multiclass_classification_layer.hpp
src/mlpack/methods/ann/layer/one_hot_layer.hpp
src/mlpack/methods/ann/layer/pooling_layer.hpp
src/mlpack/methods/ann/layer/recurrent_layer.hpp
src/mlpack/methods/ann/layer/softmax_layer.hpp
src/mlpack/methods/ann/layer/sparse_bias_layer.hpp
src/mlpack/methods/ann/layer/sparse_input_layer.hpp
src/mlpack/methods/ann/layer/sparse_output_layer.hpp

Remove move assignment and move constructor, since armadillo support it if you deifne ARMA_USE_CXX11

Remove move implement

---

src/mlpack/methods/ann/layer/hard_tanh_layer.hpp
src/mlpack/tests/activation_functions_test.cpp

@zoq Hi so all the tests have passed on my system. Solution to #540 .  Currently recurrent network test is failing the build, hardtanh has passed.

Added HardTanH Layer and its tests

---

src/mlpack/methods/ann/layer/CMakeLists.txt
src/mlpack/methods/ann/layer/leaky_relu_layer.hpp
src/mlpack/tests/activation_functions_test.cpp

@zoq All tests passing on my system. Issue #412

Added LeakyReLU Layer and its tests; Change the Cmakelists

---

src/mlpack/methods/ann/layer/log_softmax_layer.hpp

use constexpr to replace static const

---

src/mlpack/methods/neighbor_search/CMakeLists.txt

Updated to correctly account for #618

Fix configuration when BUILD_CLI_EXECUTABLES=OFF

---

src/mlpack/core/data/serialization_template_version.hpp

Waiting on AppVeyor results...

Marcus thinks this will fix the Windows build... let's find out.

---

src/mlpack/core/data/load_impl.hpp
src/mlpack/tests/load_save_test.cpp

Fix the issue mentioned in #658

Fix mapping issue

---

src/mlpack/tests/load_save_test.cpp

This will supplement Tham's changes in #660, which are to fix #658. @stereomatchingkiss @keonkim

More tests for DatasetInfo

---

src/mlpack/methods/neighbor_search/neighbor_search_impl.hpp
src/mlpack/methods/neighbor_search/neighbor_search_stat.hpp

Hi,
Something happened with previous pull request: https://github.com/mlpack/mlpack/pull/673 . The commit disappeared!

Properly resetting auxBound. 

---

src/mlpack/core/tree/rectangle_tree/discrete_hilbert_value.hpp
src/mlpack/core/tree/rectangle_tree/discrete_hilbert_value_impl.hpp
src/mlpack/core/tree/rectangle_tree/hilbert_r_tree_auxiliary_information.hpp
src/mlpack/core/tree/rectangle_tree/hilbert_r_tree_auxiliary_information_impl.hpp
src/mlpack/methods/neighbor_search/kfn_main.cpp
src/mlpack/methods/neighbor_search/knn_main.cpp
src/mlpack/methods/neighbor_search/ns_model.hpp
src/mlpack/methods/neighbor_search/ns_model_impl.hpp
src/mlpack/methods/range_search/range_search_main.cpp
src/mlpack/methods/range_search/rs_model.cpp
src/mlpack/methods/range_search/rs_model.hpp
src/mlpack/methods/range_search/rs_model_impl.hpp
src/mlpack/methods/rann/krann_main.cpp
src/mlpack/methods/rann/ra_model.hpp
src/mlpack/methods/rann/ra_model_impl.hpp
src/mlpack/tests/aknn_test.cpp
src/mlpack/tests/knn_test.cpp
src/mlpack/tests/krann_search_test.cpp
src/mlpack/tests/range_search_test.cpp

I found some weird errors in the Hilbert R tree implementation. I fixed them in 05fbd27.
Moreover, I added the Hilbert R tree to (NS, RS, RA)Model and (A)KNNTest, RangeSearchTest and KRANNTest.

Hilbert R tree fixes

---

src/mlpack/prereqs.hpp

I'll play around with this until I figure out what's wrong and AppVeyor successfully builds.

Try to fix Windows build

---

COPYRIGHT.txt
src/mlpack/core.hpp

Adds my name and email to the list of contributors in COPYRIGHT.txt and  src/mlpack/core.hpp .

Adds my name and email to the list of contributors in COPYRIGHT.txt and  src/mlpack/core.hpp .

---

.travis.yml

This might improve the travis build time, let's see.

Test travis trusty image

---

COPYRIGHT.txt
src/mlpack/methods/ann/activation_functions/CMakeLists.txt
src/mlpack/methods/ann/activation_functions/softplus_function.hpp
src/mlpack/tests/activation_functions_test.cpp

All tests pass locally. Please review.
Now, working on adding ELU layer. Will open a PR ASAP.

Add Softplus activation function

---

src/mlpack/methods/ann/layer/CMakeLists.txt
src/mlpack/methods/ann/layer/elu.hpp
src/mlpack/methods/ann/layer/elu_impl.hpp
src/mlpack/methods/ann/layer/layer_types.hpp
src/mlpack/tests/activation_functions_test.cpp

All tests pass locally. Please review. Thanks!

Add Exponential Linear Unit (ELU) activation function

---

src/mlpack/core/data/load.hpp
src/mlpack/core/data/load_impl.hpp
src/mlpack/tests/load_save_test.cpp

Improved Load to load column vectors #844

---

src/mlpack/methods/decision_tree/decision_tree_main.cpp

add support of "use last dimension as label" to decision_tree

---

src/mlpack/methods/ann/activation_functions/identity_function.hpp
src/mlpack/methods/ann/activation_functions/logistic_function.hpp
src/mlpack/methods/ann/activation_functions/rectifier_function.hpp
src/mlpack/methods/ann/activation_functions/softplus_function.hpp
src/mlpack/methods/ann/activation_functions/softsign_function.hpp
src/mlpack/methods/ann/activation_functions/tanh_function.hpp
src/mlpack/methods/ann/init_rules/oivs_init.hpp
src/mlpack/methods/ann/layer/base_layer.hpp
src/mlpack/methods/ann/layer/elu.hpp
src/mlpack/methods/ann/layer/elu_impl.hpp
src/mlpack/tests/activation_functions_test.cpp

These are for issue #902 
fn to Fn
deriv to Deriv
inv to Inv

Camel Case updates to fix #902

---

src/mlpack/core/optimizers/sgd/sgd.hpp
src/mlpack/core/optimizers/sgd/sgd_impl.hpp
src/mlpack/core/optimizers/sgd/update_policies/CMakeLists.txt
src/mlpack/core/optimizers/sgd/update_policies/empty_update.hpp
src/mlpack/core/optimizers/sgd/update_policies/momentum_update.hpp
src/mlpack/core/optimizers/sgd/update_policies/vanilla_update.hpp
src/mlpack/methods/ann/rnn.hpp
src/mlpack/methods/logistic_regression/logistic_regression.hpp
src/mlpack/methods/logistic_regression/logistic_regression_function_impl.hpp
src/mlpack/methods/logistic_regression/logistic_regression_impl.hpp
src/mlpack/methods/logistic_regression/logistic_regression_main.cpp
src/mlpack/methods/nca/nca.hpp
src/mlpack/methods/regularized_svd/regularized_svd.hpp
src/mlpack/methods/regularized_svd/regularized_svd_function.cpp
src/mlpack/methods/regularized_svd/regularized_svd_function.hpp
src/mlpack/methods/regularized_svd/regularized_svd_impl.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/logistic_regression_test.cpp
src/mlpack/tests/minibatch_sgd_test.cpp
src/mlpack/tests/momentum_sgd_test.cpp
src/mlpack/tests/recurrent_network_test.cpp
src/mlpack/tests/regularized_svd_test.cpp

Implemented SGD with the momentum update using policy class towards  #893.

Sgd momentum updates with policy class.

---

src/mlpack/methods/softmax_regression/softmax_regression.hpp
src/mlpack/methods/softmax_regression/softmax_regression_impl.hpp
src/mlpack/methods/softmax_regression/softmax_regression_main.cpp

Fix for [#935](https://github.com/mlpack/mlpack/issues/935)

Add Classify in SoftmaxRegression

---

src/mlpack/methods/lars/lars.cpp
src/mlpack/methods/lars/lars.hpp
src/mlpack/tests/lars_test.cpp

Fix for [#948](https://github.com/mlpack/mlpack/issues/948)

Add training constructors to LARS

---

src/mlpack/methods/ann/init_rules/CMakeLists.txt
src/mlpack/methods/ann/init_rules/gaussian_init.hpp
src/mlpack/tests/init_rules_test.cpp

This add gaussian initialisation. To the weights. I am not sure which test should be added so any suggestions on that would be great.

Gaussian_Init

---

src/mlpack/tests/cli_test.cpp

Sorry, I accidently deleted my repo and had to re-fork.

Follow standard procedure for 'TestBooleanOption'

---

README.md

It looks like github updated the markdown preprocessor.

Github listing fix

---

COPYRIGHT.txt
src/mlpack/core.hpp

Add contributor name

---

src/mlpack/methods/lars/lars.cpp
src/mlpack/methods/lars/lars.hpp
src/mlpack/tests/lars_test.cpp

Implementing suggestions from the comment to [the PR #957](https://github.com/mlpack/mlpack/pull/957).

Overloading Train and accessing Beta in LARS

---

src/mlpack/core/optimizers/rmsprop/CMakeLists.txt
src/mlpack/core/optimizers/rmsprop/rmsprop.hpp
src/mlpack/core/optimizers/rmsprop/rmsprop_impl.hpp
src/mlpack/core/optimizers/rmsprop/rmsprop_update.hpp
src/mlpack/methods/ann/ffn.hpp
src/mlpack/tests/convolutional_network_test.cpp
src/mlpack/tests/feedforward_network_test.cpp
src/mlpack/tests/ksinit_test.cpp
src/mlpack/tests/rmsprop_test.cpp

Implementation of the RMSprop optimizer using the RMSpropUpdate policy class. All tests pass locally. Please review, thanks.

RMSprop update policy implementation

---

.appveyor.yml

Appveyor matrix build for Visual Studio 2015 and Visual Studio 2017.

Build against Visual Studio 2015 and Visual Studio 2017

---

src/mlpack/tests/mlpack_test.cpp

Enables us to print all test cases with ``mlpack_test tests``.  We could change ``tests`` if someone comes up with something else.
<details><summary>mlpack_test tests output</summary><p>
ActivationFunctionsTest/TanhFunctionTest
ActivationFunctionsTest/LogisticFunctionTest
ActivationFunctionsTest/SoftsignFunctionTest
ActivationFunctionsTest/IdentityFunctionTest
ActivationFunctionsTest/RectifierFunctionTest
ActivationFunctionsTest/LeakyReLUFunctionTest
ActivationFunctionsTest/HardTanHFunctionTest
ActivationFunctionsTest/ELUFunctionTest
ActivationFunctionsTest/SoftplusFunctionTest
ActivationFunctionsTest/PReLUFunctionTest
AdaBoostTest/HammingLossBoundIris
AdaBoostTest/WeakLearnerErrorIris
AdaBoostTest/HammingLossBoundVertebralColumn
AdaBoostTest/WeakLearnerErrorVertebralColumn …

Print tests suites/cases

---

README.md

I'm not sure which version looks better the one with a header or the one without.
With header: https://github.com/zoq/mlpack/tree/readme_header
Without header: https://github.com/mlpack/mlpack

Readme header

---

src/mlpack/core/dists/regression_distribution.cpp
src/mlpack/core/dists/regression_distribution.hpp
src/mlpack/methods/lars/lars.cpp
src/mlpack/methods/lars/lars.hpp
src/mlpack/methods/lars/lars_main.cpp
src/mlpack/methods/linear_regression/linear_regression.cpp
src/mlpack/methods/linear_regression/linear_regression.hpp
src/mlpack/methods/linear_regression/linear_regression_main.cpp
src/mlpack/methods/local_coordinate_coding/lcc.cpp
src/mlpack/methods/sparse_coding/sparse_coding.cpp
src/mlpack/tests/lars_test.cpp
src/mlpack/tests/linear_regression_test.cpp
src/mlpack/tests/serialization_test.cpp

Fix #963. Also separate signatures of constructors and Train methods in Linear Regression for learning with weights and without them as discussed in #929.

Column-major responses in Linear Regression and LARS

---

src/mlpack/methods/decision_tree/decision_tree_impl.hpp

For more Information take a look at #1009.

Fix non-static member function issue

---

src/mlpack/methods/hoeffding_trees/hoeffding_tree.hpp
src/mlpack/methods/hoeffding_trees/hoeffding_tree_impl.hpp
src/mlpack/tests/hoeffding_tree_test.cpp

Add NumDescendants to hoeffding tree

---

src/mlpack/methods/decision_tree/decision_tree_impl.hpp
src/mlpack/tests/decision_tree_test.cpp

Passing const data to DecisionTree constructors

---

README.md

Added a license badge to the readme and also did some minor style changes. Let me know what you all think.
Link: https://github.com/zoq/mlpack/tree/license_batch_readme

Add license badge to the readme

---

.travis.yml

Build mlpack with ``DEBUG=ON`` and ``DEBUG=OFF``.

Test Debug and Release mode.

---

src/mlpack/tests/ann_layer_test.cpp

Simple test for the mean squared error layer.

Simple test for the Mean Squared Error layer.

---

src/mlpack/methods/linear_regression/linear_regression.cpp
src/mlpack/methods/linear_regression/linear_regression.hpp

Remove LinearRegression explicit copy constructor

---

HISTORY.md
README.md

I realized that the README doesn't mention anything about the Python bindings, so this helps fix that.  New readme example:
https://github.com/rcurtin/mlpack/tree/python-readme
If anyone has any feedback or ideas for how it could be improved (or if this is sufficient), I'd appreciate it.

Update README to discuss Python bindings

---

src/mlpack/methods/ann/activation_functions/CMakeLists.txt
src/mlpack/methods/ann/activation_functions/swish_function.hpp
src/mlpack/tests/activation_functions_test.cpp

This PR adds Swish activation function as proposed by Prajit Ramachandran, Barret Zoph and Quoc V. Le in [Swish: A self-gated activation function](https://arxiv.org/pdf/1710.05941.pdf).

Swish Activation Function

---

src/mlpack/core/util/mlpack_main.hpp
src/mlpack/core/util/timers.cpp

Do not ignore the 'total_time' timer in the Start method.

Use StartTimer to start the 'total_timer'.

---

src/mlpack/core/optimizers/CMakeLists.txt
src/mlpack/core/optimizers/spalera_sgd/CMakeLists.txt
src/mlpack/core/optimizers/spalera_sgd/spalera_sgd.hpp
src/mlpack/core/optimizers/spalera_sgd/spalera_sgd_impl.hpp
src/mlpack/core/optimizers/spalera_sgd/spalera_stepsize.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/spalera_sgd_test.cpp

Implementation of SPALeRA Stochastic Gradient Descent as proposed by A. Schoenauer-Sebag in "Stochastic Gradient Descent: Going As Fast As Possible But Not Faster".

SPALeRA Stochastic Gradient Descent

---

.travis.yml
src/mlpack/bindings/python/CMakeLists.txt
src/mlpack/core/optimizers/CMakeLists.txt
src/mlpack/core/optimizers/iqn/CMakeLists.txt
src/mlpack/core/optimizers/iqn/iqn.hpp
src/mlpack/core/optimizers/iqn/iqn_impl.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/iqn_test.cpp

Implementation of the incremental Quasi-Newton with local superlinear convergence rate as proposed by A. Mokhtari et al. in "IQN: An Incremental Quasi-Newton Method with Local Superlinear Convergence Rate".

IQN - An Incremental Quasi-Newton Method with Local Superlinear Convergence Rate

---

src/mlpack/core/optimizers/CMakeLists.txt
src/mlpack/core/optimizers/cmaes/CMakeLists.txt
src/mlpack/core/optimizers/cmaes/cmaes.hpp
src/mlpack/core/optimizers/cmaes/cmaes_impl.hpp
src/mlpack/core/optimizers/cmaes/full_selection.hpp
src/mlpack/core/optimizers/cmaes/random_selection.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/cmaes_test.cpp

Implementation of the Covariance Matrix Adaptation Evolution Strategy as proposed by N. Hansen et al. in "Completely Derandomized Self-Adaptation in Evolution Strategies". I used #938 as a basis and simplified the code here and there. @kartik-nighania maybe you have time to take a look at the code.

Covariance Matrix Adaptation Evolution Strategy (CMA-ES)

---

.travis.yml
CMakeLists.txt

This is a patch from @extrowerk.  (Thanks!)

Fix Haiku: link against librt

---

src/mlpack/core/optimizers/adam/CMakeLists.txt
src/mlpack/core/optimizers/adam/adam.hpp
src/mlpack/core/optimizers/adam/adam_impl.hpp
src/mlpack/core/optimizers/adam/amsgrad_update.hpp
src/mlpack/tests/adam_test.cpp

ams_grad optimizer implementation

---

src/mlpack/methods/logistic_regression/logistic_regression_main.cpp

Super simple fix: the tolerance can also be 0.

Fix logistic regression tolerance checks.

---

src/mlpack/methods/amf/amf.hpp
src/mlpack/methods/cf/cf_main.cpp

AMF, remove C++11 alternative branch.

---

src/mlpack/tests/cf_test.cpp

This is a simple test fix for the remaining failing tests.  If nobody has any comments I'll merge it in 3 days.

300 different users don't exist now with the smaller GroupLens; use only 50.

---

.travis.yml
src/mlpack/bindings/python/CMakeLists.txt
src/mlpack/bindings/python/mlpack/matrix_utils.py
src/mlpack/bindings/python/print_input_processing.hpp
src/mlpack/bindings/python/print_output_processing.hpp
src/mlpack/bindings/python/tests/dataset_info_test.py

This PR contains a number of small fixes that solve problems that dan_dan pointed out in IRC, mostly having to do with making sure that the bindings use Python3.

Fixes for python3

---

COPYRIGHT.txt
src/mlpack/core.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/emst_test.cpp

Bindings Tests of mlpackMain() for emst_main.cpp.

Bindings tests for emst

---

src/mlpack/core/optimizers/adam/CMakeLists.txt
src/mlpack/core/optimizers/adam/adam.hpp
src/mlpack/core/optimizers/adam/adam_impl.hpp
src/mlpack/core/optimizers/adam/nadam_update.hpp
src/mlpack/core/optimizers/adam/nadamax_update.hpp
src/mlpack/tests/adam_test.cpp

I have added the code for NadaMax Update. I have not added the reference Paper. Let me know which one to put?

Added Optimizer Nadamax

---

CMake/cotire.cmake
CMakeLists.txt
src/mlpack/CMakeLists.txt
src/mlpack/tests/CMakeLists.txt

Use precompiled headers

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/sparse_coding_test.cpp

Include bindings tests for sparse_coding_main.cpp

Sparse Coding  Bindings Tests

---

COPYRIGHT.txt
src/mlpack/core.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/adaboost_test.cpp

Contains binding test for adaboost algorithm as asked in issue #1152

AdaBoost binding tests

---

src/mlpack/core/data/CMakeLists.txt
src/mlpack/core/data/is_naninf.hpp
src/mlpack/core/data/load_arff_impl.hpp

Pretty simple---I just pulled `convert_naninf()` out of Armadillo and switched to an internal implementation.  This is meant to solve #1223.

Don't use Armadillo internal API.

---

.travis.yml
src/mlpack/bindings/python/py_option.hpp

This should fix some of the Travis build issues we have been seeing.

Travis fixes

---

COPYRIGHT.txt
src/mlpack/bindings/python/setup.py.in
src/mlpack/core.hpp

Resolves #1231
Here is the documentation : http://setuptools.readthedocs.io/en/latest/setuptools.html#setting-the-zip-safe-flag
It now extracts the files in dist-packages and import time in python is drastically reduced.

Added zip_safe to setup options in setup.py.in

---

src/mlpack/core/optimizers/problems/sphere_function.cpp

Changing the comments to go inline with the initialisation .

minor changes in comment

---

COPYRIGHT.txt
src/mlpack/core.hpp
src/mlpack/tests/nmf_test.cpp

To make sure all elements in W and H matrices are non-negative.

add non-negative check for nmf_test

---

src/mlpack/tests/main_tests/decision_tree_test.cpp

Rectify error in DecisionTreeMinimumLeafSizeTest pointed out by @akhandait in #1174

Rectify Decision Tree Bindings Test Implementation

---

src/mlpack/methods/dbscan/dbscan_main.cpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/dbscan_test.cpp

DBSCAN Binding test as required from issue #1152

DBSCAN Binding test

---

src/mlpack/tests/main_tests/dbscan_test.cpp
src/mlpack/tests/main_tests/decision_tree_test.cpp
src/mlpack/tests/main_tests/logistic_regression_test.cpp

Minor style fixes

---

src/mlpack/core/util/param_checks.hpp
src/mlpack/core/util/param_checks_impl.hpp
src/mlpack/methods/amf/init_rules/given_init.hpp
src/mlpack/methods/nmf/nmf_main.cpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/nmf_test.cpp

Added the nmf_test.cpp for nmf binding. (related issue: #1152)
I also found a bug in the process. I opened a dedicated PR(#1260) for that.

add nmf binding test

---

src/mlpack/methods/logistic_regression/logistic_regression_function.hpp

This fixes #1299.
@AdamWill: do you want me to get you a patch for this built on mlpack-2.2.5?

Fix definition of Responses().

---

src/mlpack/methods/kmeans/kmeans_main.cpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/kmeans_test.cpp

#1152 
Following Tests were added for Kmeans
1.Different Algorithms should yield similar Result
2.Number of Clusters should be Non Negative
3.Number of Clusters Should be Integer
4.Maximum Iteration should be Integer
5.Refined Percentage should be b/w 0 & 1
6.Size and Dimensionality of Output should be correct
7.Size and Dimensionality of Input File should be Correct when --inplace is specified
8. Absence of Input is checked
9. Absence of Number Of clusters is checked
10. Number of Clusters should be less than number of points

Added tests for kmeans_main.cpp

---

src/mlpack/CMakeLists.txt
src/mlpack/methods/ann/init_rules/CMakeLists.txt
src/mlpack/methods/ann/init_rules/glorot_init.hpp
src/mlpack/tests/init_rules_test.cpp

#1112 
I've added the Glorot initialization method as proposed by @zoq

Added Glorot Initialization method

---

COPYRIGHT.txt
src/mlpack/core.hpp
src/mlpack/core/optimizers/adam/CMakeLists.txt
src/mlpack/core/optimizers/adam/adam.hpp
src/mlpack/core/optimizers/adam/adamirror_update.hpp
src/mlpack/core/optimizers/adam/optimisticadam_update.hpp
src/mlpack/tests/adam_test.cpp

* Implemented Optimistic ADAM algorithm proposed in https://openreview.net/forum?id=SJJySbbAZ. 
* Added basic test cases for the optmizer.

Optmistic Mirror Descent for Adam Optimizer

---

doc/tutorials/ann/ann.txt
doc/tutorials/tutorials.txt

This is a basic Neural Network tutorial, that describes the existing framework from a higher level. For details, we should point to the layer-specific documentation.

Add basic ann tutorial.

---

src/mlpack/core/optimizers/sdp/lrsdp_function_impl.hpp
src/mlpack/methods/ann/convolution_rules/fft_convolution.hpp
src/mlpack/methods/ann/convolution_rules/naive_convolution.hpp
src/mlpack/methods/ann/convolution_rules/svd_convolution.hpp
src/mlpack/methods/ann/layer/convolution_impl.hpp
src/mlpack/methods/decision_tree/decision_tree_impl.hpp
src/mlpack/tests/convolution_test.cpp

@zoq I couldn't find much ways to improve upon the current implementation, as far as the code is concerned. Did you have any other idea in mind regarding this?

Improvements and Speedups to Convolution Layer and Associated Rules

---

src/mlpack/methods/ann/layer/add_merge.hpp
src/mlpack/methods/ann/layer/add_merge_impl.hpp
src/mlpack/methods/ann/layer/recurrent.hpp
src/mlpack/methods/ann/layer/recurrent_impl.hpp
src/mlpack/methods/ann/layer/sequential_impl.hpp
src/mlpack/methods/ann/rnn.hpp
src/mlpack/tests/recurrent_network_test.cpp

Fix memory issues as pointed out in https://github.com/mlpack/mlpack/issues/1187.

Fix AddMerge and Recurrent layer memory issue.

---

src/mlpack/tests/knn_test.cpp
src/mlpack/tests/mean_shift_test.cpp
src/mlpack/tests/nesterov_momentum_sgd_test.cpp
src/mlpack/tests/qdafn_test.cpp
src/mlpack/tests/svd_batch_test.cpp

I went through the list of unstable builds and adjusted these tests.  It should further reduce the test error rate.

A few more test adjustments

---

src/mlpack/tests/nesterov_momentum_sgd_test.cpp
src/mlpack/tests/pca_test.cpp
src/mlpack/tests/radical_test.cpp
src/mlpack/tests/regularized_svd_test.cpp
src/mlpack/tests/svd_batch_test.cpp
src/mlpack/tests/svd_incremental_test.cpp

Just a couple more test fixes; they are all just little tolerance adjustments except for a modification to the randomized PCA dimensionality reduction test.  Sometimes the LU factorization can fail, so we simply catch the exception and try again, up to 3 times.

More test fixes

---

src/mlpack/methods/regularized_svd/regularized_svd_impl.hpp

I have just done a very minor style fix which might cause other style builds to it.

Very minor style fix

---

src/mlpack/tests/async_learning_test.cpp

Updated Header file in the test file. The optimizer used in the test is vanilla update. This will help the users to understand the code better.

Header file : Adam  update to vanilla update

---

src/mlpack/methods/reinforcement_learning/environment/acrobat.hpp

This is minor style fixes for acrobat game. The length of line 230 was 81, which created style issues.

Minor Style

---

doc/guide/build.hpp
src/mlpack/tests/cmaes_test.cpp
src/mlpack/tests/recurrent_network_test.cpp

These are some additional test adjustments from watching the test results on masterblaster for a while.
e.g. http://masterblaster.mlpack.org/job/docker%20mlpack%20weekly%20build/

Intermittently failing test fixes

---

src/mlpack/methods/det/det_main.cpp
src/mlpack/methods/det/dt_utils.hpp
src/mlpack/methods/lsh/lsh_main.cpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/det_test.cpp
src/mlpack/tests/main_tests/lsh_test.cpp
src/mlpack/tests/main_tests/radical_test.cpp

Added bindings tests for lsh_main.cpp, det_main.cpp & radical_main.cpp.

LSH, DET and Radical bindings tests

---

src/mlpack/methods/ann/layer/recurrent.hpp

@zoq This is a very small parameter comment correction which can be merged directly.

Parameter description correction

---

src/mlpack/methods/ann/activation_functions/softplus_function.hpp

It only supported vectors previously.

Extend support of Softplus function to matrices, cubes.

---

src/mlpack/core/optimizers/bigbatch_sgd/bigbatch_sgd_impl.hpp

This solves the batch size issue as found out by @manish7294.

BigBatchSGD batch size fix.

---

src/mlpack/methods/ann/layer/atrous_convolution_impl.hpp
src/mlpack/methods/ann/layer/convolution_impl.hpp
src/mlpack/methods/ann/layer/leaky_relu.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/dcgan_test.cpp
src/mlpack/tests/gan_test.cpp

Currently this contains the commits from the GAN PR, which should be merged soon, and then this would be rebased. Just the parameters of the generator network need to be corrected for this to work, which would be done soon.

Implemented DCGAN Tests

---

src/mlpack/tests/convolutional_network_test.cpp

This should fix the random network issue; see https://github.com/mlpack/mlpack/issues/1438 for more information.

Run convolutional networks test multiple times if necessary

---

src/mlpack/methods/ann/layer/reparametrization.hpp
src/mlpack/methods/ann/layer/reparametrization_impl.hpp
src/mlpack/methods/ann/visitor/loss_visitor_impl.hpp
src/mlpack/tests/ann_layer_test.cpp

This is a follow-up PR to the sampling one where Ryan suggested some changes.

Make changes suggested in sampling PR

---

src/mlpack/methods/ann/layer/add_merge_impl.hpp
src/mlpack/methods/ann/layer/multiply_merge_impl.hpp

See https://github.com/mlpack/mlpack/pull/1427 for more information.

Serialize merge layer parameter

---

src/mlpack/methods/ann/CMakeLists.txt
src/mlpack/methods/ann/ffn.hpp
src/mlpack/methods/ann/gan.hpp
src/mlpack/methods/ann/gan/CMakeLists.txt
src/mlpack/methods/ann/gan/gan.hpp
src/mlpack/methods/ann/gan/gan_impl.hpp
src/mlpack/methods/ann/gan/gan_policies.hpp
src/mlpack/methods/ann/gan/wgan_impl.hpp
src/mlpack/methods/ann/gan/wgangp_impl.hpp
src/mlpack/methods/ann/gan_impl.hpp
src/mlpack/methods/ann/gan_policies.hpp
src/mlpack/methods/ann/loss_functions/CMakeLists.txt
src/mlpack/methods/ann/loss_functions/earth_mover_distance.hpp
src/mlpack/methods/ann/loss_functions/earth_mover_distance_impl.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/dcgan_test.cpp
src/mlpack/tests/gan_test.cpp
src/mlpack/tests/loss_functions_test.cpp
src/mlpack/tests/wgan_test.cpp

Wasserstein GAN Implementation

---

CMake/GenerateDoxyfile.cmake
CMakeLists.txt
src/mlpack/methods/ann/layer/flexible_relu.hpp

Need curly braces on arg to \begin, need arg to \right

latex syntax

---

src/mlpack/methods/ann/ffn.hpp
src/mlpack/methods/ann/ffn_impl.hpp
src/mlpack/tests/feedforward_network_test.cpp

This allows users to forward pass partially through the network.

Overload Forward() function.

---

src/mlpack/methods/ann/ffn.hpp
src/mlpack/methods/ann/ffn_impl.hpp
src/mlpack/methods/ann/layer/reparametrization.hpp
src/mlpack/methods/ann/layer/sequential.hpp
src/mlpack/methods/ann/layer/sequential_impl.hpp
src/mlpack/methods/ann/loss_functions/CMakeLists.txt
src/mlpack/methods/ann/loss_functions/cross_entropy_error.hpp
src/mlpack/methods/ann/loss_functions/earth_mover_distance.hpp
src/mlpack/methods/ann/loss_functions/mean_squared_error.hpp
src/mlpack/methods/ann/loss_functions/negative_log_likelihood.hpp
src/mlpack/methods/ann/loss_functions/reconstruction_loss.hpp
src/mlpack/methods/ann/loss_functions/reconstruction_loss_impl.hpp
src/mlpack/methods/ann/loss_functions/sigmoid_cross_entropy_error.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/ann_layer_test.cpp
src/mlpack/tests/ann_test_tools.hpp
src/mlpack/tests/loss_functions_test.cpp

splitting #1433
@sumedhghaisas

Add ReconstructionLoss

---

src/mlpack/methods/ann/layer/atrous_convolution_impl.hpp
src/mlpack/methods/ann/layer/convolution_impl.hpp
src/mlpack/methods/ann/layer/reparametrization.hpp

I'll need to test for the outputs of the GANs. Then this can be merged.

Improve Convolution Gradient() Method

---

src/mlpack/methods/cf/decomposition_policies/batch_svd_method.hpp
src/mlpack/methods/cf/decomposition_policies/bias_svd_method.hpp
src/mlpack/methods/cf/decomposition_policies/nmf_method.hpp
src/mlpack/methods/cf/decomposition_policies/randomized_svd_method.hpp
src/mlpack/methods/cf/decomposition_policies/regularized_svd_method.hpp
src/mlpack/methods/cf/decomposition_policies/svd_complete_method.hpp
src/mlpack/methods/cf/decomposition_policies/svd_incomplete_method.hpp
src/mlpack/methods/cf/decomposition_policies/svdplusplus_method.hpp
src/mlpack/methods/cf/interpolation_policies/average_interpolation.hpp
src/mlpack/methods/cf/interpolation_policies/regression_interpolation.hpp
src/mlpack/methods/cf/interpolation_policies/similarity_interpolation.hpp
src/mlpack/methods/cf/neighbor_search_policies/cosine_search.hpp
src/mlpack/methods/cf/neighbor_search_policies/lmetric_search.hpp
src/mlpack/methods/cf/neighbor_search_policies/pearson_search.hpp
src/mlpack/methods/cf/normalization/combined_normalization.hpp
src/mlpack/methods/cf/normalization/item_mean_normalization.hpp
src/mlpack/methods/cf/normalization/overall_mean_normalization.hpp
src/mlpack/methods/cf/normalization/user_mean_normalization.hpp
src/mlpack/methods/cf/normalization/z_score_normalization.hpp

This PR corrects and adds examples in the code comments on how to use the policies in CF.

Correct and add examples on how to use the policies in CF

---

src/mlpack/core.hpp
src/mlpack/core/kernels/CMakeLists.txt
src/mlpack/core/kernels/cauchy_kernel.hpp
src/mlpack/tests/kernel_test.cpp
src/mlpack/tests/kernel_traits_test.cpp

Added an implementation and tests for the Cauchy kernel described by Basak (2008) in the article _A Least Square Kernel Machine With Box Constraints_.

Add the Cauchy kernel

---

HISTORY.md
README.md
doc/examples/sample-ml-app/sample-ml-app/sample-ml-app.vcxproj
doc/guide/build.hpp
doc/guide/build_windows.hpp
doc/guide/python_quickstart.hpp
doc/guide/sample_ml_app.hpp
src/mlpack/core/util/version.hpp

This updates the documentation to use the latest released version number, and updates `version.hpp` to have a version that's after the latest stable release.

Version fixes

---

.travis.yml

This is based on the comments here: https://github.com/tianon/gosu/issues/17
I hope it will fix the unreliable travis builds; we'll see.

Try multiple different keyservers for reliability.

---

src/mlpack/methods/kernel_pca/kernel_pca_main.cpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/kernel_pca_test.cpp

Add tests for kernel_pca command line.

kernel_pca_test.cpp: Add tests

---

src/mlpack/methods/ann/ffn.hpp
src/mlpack/methods/ann/rnn.hpp
src/mlpack/methods/ann/rnn_impl.hpp

Documentation fix for EvaluateWithGradient.

ffn.hpp and rnn.hpp: Documentation fix

---

HISTORY.md

Fixed Typographical Error in HISTORY.md

Fixed Typographical Error in HISTORY.md

---

CMakeLists.txt

Add new version of Boost 1.69.0 and 1.69 to Boost_ADDITIONAL_VERSIONS

Adding new version of Boost to CMakeLists.txt

---

src/mlpack/methods/ann/layer/recurrent.hpp
src/mlpack/methods/ann/layer/recurrent_impl.hpp

Refer https://github.com/mlpack/mlpack/issues/1639

Remove use of WeightSizeVisitor in recurrent

---

src/mlpack/methods/logistic_regression/logistic_regression_main.cpp

I have made two changes - 
(1) Solved again an extra whitespace bug.
(2) Adjusted whitespace according to documentation rules. Although this change doesn't affect the output but it was not according to documentation rules.

Fixed whitespace bug and adjusted whitepace

---

src/mlpack/methods/reinforcement_learning/environment/CMakeLists.txt
src/mlpack/methods/reinforcement_learning/environment/acrobot.hpp
src/mlpack/tests/q_learning_test.cpp
src/mlpack/tests/reward_clipping_test.cpp
src/mlpack/tests/rl_components_test.cpp

Please refer to [this](https://gym.openai.com/envs/#classic_control). The file name `acrobat.hpp` should be changed to `acrobot.hpp`.

Changed the file name `acrobat.hpp` to `acrobot.hpp`.

---

src/mlpack/methods/ann/layer/elu.hpp
src/mlpack/methods/ann/layer/elu_impl.hpp
src/mlpack/tests/activation_functions_test.cpp

Improve ELU Implementation

---

src/mlpack/methods/ann/loss_functions/CMakeLists.txt
src/mlpack/methods/ann/loss_functions/dice_loss.hpp

- include Dice loss into the build routine
- minor style fixes

Minor Dice Loss adjustments

---

.gitignore

Added *.pyc in gitignore to compensate the following:
`On branch test
Untracked files:`
`(use "git add <file>..." to include in what will be committed)`
` src/mlpack/bindings/python/mlpack/__init__.pyc`

Added .pyc in .gitignore

---

src/mlpack/methods/ann/dists/bernoulli_distribution.hpp

Fix typo in Bernoulli distribution

Fix typo in Bernoulli distribution

---

src/mlpack/methods/ann/rnn_impl.hpp

Closes https://github.com/mlpack/mlpack/issues/1695

Remove saving parameters in Evaluate

---

src/mlpack/core/dists/gamma_distribution.cpp
src/mlpack/core/dists/gamma_distribution.hpp
src/mlpack/tests/distribution_test.cpp

Returns the log probability of one observation (x) for one of the Gamma's dimensions.

Extend1679

---

src/mlpack/methods/ann/brnn_impl.hpp

Closes https://github.com/mlpack/mlpack/issues/1740

Fix test failure in bidirectional rnn

---

COPYRIGHT.txt
doc/guide/build_windows.hpp
src/mlpack/core.hpp

Improve Installation Documentation on Windows

---

doc/tutorials/ann/ann.txt

Rectified misplacement of curly braces in ann.txt

rectified ann.txt (mlpack/doc)

---

src/mlpack/methods/softmax_regression/softmax_regression.hpp

Seems like the sample code for `mlpack::regression::SoftmaxRegression` in `softmax_regression.hpp` were outdated.

Documentation: updated the sample code in softmax_regression.hpp.

---

src/mlpack/methods/ann/loss_functions/cross_entropy_error.hpp
src/mlpack/methods/ann/loss_functions/dice_loss.hpp
src/mlpack/methods/ann/loss_functions/earth_mover_distance.hpp
src/mlpack/methods/ann/loss_functions/mean_squared_error.hpp
src/mlpack/methods/ann/loss_functions/reconstruction_loss.hpp
src/mlpack/methods/ann/loss_functions/sigmoid_cross_entropy_error.hpp

minor fix up the comment of loss function in the `loss_functions` folder.

minor fix up

---

src/mlpack/methods/ann/activation_functions/logistic_function.hpp
src/mlpack/methods/ann/activation_functions/rectifier_function.hpp
src/mlpack/methods/ann/activation_functions/softplus_function.hpp
src/mlpack/methods/ann/activation_functions/softsign_function.hpp
src/mlpack/methods/ann/activation_functions/swish_function.hpp
src/mlpack/methods/ann/layer/leaky_relu.hpp
src/mlpack/methods/ann/layer/parametric_relu.hpp

Minor Optimizations

---

src/mlpack/tests/imputation_test.cpp

This PR adds value of index (2,3) of rowWiseInput matrix at line 230 of MedianImputationTest in imputation_test.cpp.

Code completion

---

src/mlpack/core/tree/ballbound.hpp
src/mlpack/core/tree/cellbound.hpp
src/mlpack/core/tree/hollow_ball_bound.hpp
src/mlpack/core/tree/hrectbound.hpp

I have included description about parameters in ballbound.hpp ,cellbound.hpp,hallow_ball_bound.hpp

Documentation fixup

---

src/mlpack/methods/logistic_regression/logistic_regression_function.hpp

This PR completes the missing documentation.

Complete Documentation

---

src/mlpack/methods/ann/layer/lstm.hpp
src/mlpack/methods/ann/layer/lstm_impl.hpp
src/mlpack/tests/ann_layer_test.cpp

Resolves (#1782).
Added an overloaded Forward() to facilitate access of Cell State of LSTM.

Added cellState as output params in LSTM.

---

COPYRIGHT.txt

I have contributed #1776, I have added my name to contribution list.

Added contribution name

---

src/mlpack/methods/gmm/gmm_train_main.cpp

The purpose of this PR is to convert `DiagonalGMM` into `GMM` in the `mlpack_gmm_train`.
I tried generating some samples from trained and converted `GMM` using MNIST datasets. (Some image processing techniques, e.g., Min-Max normalization and dilation were used to refine the images)
<p align="center">
</p>

Convert DiagonalGMMs into GMMs in `mlpack_gmm_train`.

---

src/mlpack/methods/reinforcement_learning/policy/greedy_policy.hpp
src/mlpack/tests/q_learning_test.cpp
src/mlpack/tests/reward_clipping_test.cpp
src/mlpack/tests/rl_components_test.cpp

Added decay rate in `greedy_policy.hpp` file.

Added decay rate hyperparameter to greedy policy.

---

README.md

Change stable version t0 3.1.0

Change of Version in Readme

---

src/mlpack/bindings/markdown/binding_info.cpp
src/mlpack/bindings/markdown/binding_info.hpp
src/mlpack/bindings/markdown/default_param.hpp
src/mlpack/bindings/markdown/generate_markdown.binding.cpp.in
src/mlpack/bindings/markdown/generate_markdown.binding.hpp.in
src/mlpack/bindings/markdown/get_binding_name.cpp
src/mlpack/bindings/markdown/get_binding_name.hpp
src/mlpack/bindings/markdown/get_printable_type.hpp
src/mlpack/bindings/markdown/is_serializable.hpp
src/mlpack/bindings/markdown/print_doc_functions_impl.hpp
src/mlpack/bindings/markdown/print_docs.cpp
src/mlpack/bindings/markdown/print_docs.hpp
src/mlpack/bindings/markdown/print_type_doc.hpp
src/mlpack/bindings/markdown/program_doc_wrapper.hpp
src/mlpack/bindings/markdown/res/change_language.js
src/mlpack/bindings/markdown/res/formatting.css

While reading the code for the purpose of producing java bindings, I fixed a Documentation and also changed the format of one comment according to Documentation Guidelines.

Added Documentation

---

src/mlpack/bindings/markdown/binding_info.hpp
src/mlpack/methods/ann/layer/concat.hpp
src/mlpack/methods/ann/layer/concat_impl.hpp

Minor style fixes for the concat layer.

Concat layer minor style fixes.

---

Doxyfile

A trivial PR, yes. But We probably want the version number to match in the docs.

bump version to 3.1.1

---

src/mlpack/tests/main_tests/hoeffding_tree_test.cpp

Like what we said in [issue](https://github.com/mlpack/mlpack/issues/1911)

remove move() statement in hoeffding_tree_test.cpp

---

CODE_OF_CONDUCT.md

Code of Conduct as discussed here: https://github.com/mlpack/mlpack/issues/1894.

Code of Conduct.

---

src/mlpack/bindings/python/setup.py.in

While working on #1935 I got some errors regarding python bindings on CI-Travis. May this think works.

Fix CI-Travis Build

---

src/mlpack/methods/ann/layer/CMakeLists.txt
src/mlpack/methods/ann/layer/alpha_dropout.hpp
src/mlpack/methods/ann/layer/highway.hpp
src/mlpack/methods/ann/layer/highway_impl.hpp
src/mlpack/methods/ann/layer/layer.hpp
src/mlpack/methods/ann/layer/layer_types.hpp
src/mlpack/tests/ann_layer_test.cpp
src/mlpack/tests/feedforward_network_test.cpp

This is a rebase to https://github.com/mlpack/mlpack/pull/1061 
TODOS

Highway networks

---

HISTORY.md
src/mlpack/methods/reinforcement_learning/environment/CMakeLists.txt
src/mlpack/methods/reinforcement_learning/environment/continuous_double_pole_cart.hpp
src/mlpack/methods/reinforcement_learning/environment/continuous_multiple_pole_cart.hpp
src/mlpack/methods/reinforcement_learning/environment/double_pole_cart.hpp
src/mlpack/methods/reinforcement_learning/environment/multiple_pole_cart.hpp
src/mlpack/tests/q_learning_test.cpp
src/mlpack/tests/rl_components_test.cpp

I've fixed the double pole cart environments which I tested on NEAT. I'll also be adding QLearning tests for all the environments soon.

Double pole cart environments fix and RL tests

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/ann_layer_test.cpp

Let's test out some solutions.

AtrousConvolutionLayer stablize test

---

src/mlpack/tests/q_learning_test.cpp

Optimized the model settings to decrease the fail rate of the DoublePoleCart DQN test.

Optimized DoublePoleCart DQN test settings

---

src/mlpack/methods/linear_svm/linear_svm_function_impl.hpp

While working on go bindings appVeyor fails. In this pr I am trying to resolve the issue.

Resolve appVeyor issues

---

src/mlpack/methods/ann/CMakeLists.txt
src/mlpack/methods/ann/layer/layer_types.hpp
src/mlpack/methods/ann/layer/linear.hpp
src/mlpack/methods/ann/layer/linear_impl.hpp
src/mlpack/methods/ann/layer/linear_no_bias.hpp
src/mlpack/methods/ann/layer/linear_no_bias_impl.hpp
src/mlpack/methods/ann/regularizer/CMakeLists.txt
src/mlpack/methods/ann/regularizer/lregularizer.hpp
src/mlpack/methods/ann/regularizer/lregularizer_impl.hpp
src/mlpack/methods/ann/regularizer/no_regularizer.hpp
src/mlpack/methods/ann/regularizer/orthogonal_regularizer.hpp
src/mlpack/methods/ann/regularizer/orthogonal_regularizer_impl.hpp
src/mlpack/methods/ann/regularizer/regularizer.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/ann_regularizer_test.cpp
src/mlpack/tests/ann_test_tools.hpp

Currently I have implemented L1 and L2 regularizers using a class template and introduced them in `Linear` layer using a policy based design.
Let me know your thoughts regarding the design. @zoq @ShikharJ 
TODOS

Add Regularizers

---

src/mlpack/methods/ann/layer/atrous_convolution.hpp
src/mlpack/methods/ann/layer/convolution.hpp
src/mlpack/methods/ann/layer/layer_traits.hpp
src/mlpack/methods/ann/layer/linear.hpp
src/mlpack/methods/ann/layer/transposed_convolution.hpp
src/mlpack/methods/ann/visitor/CMakeLists.txt
src/mlpack/methods/ann/visitor/bias_set_visitor.hpp
src/mlpack/methods/ann/visitor/bias_set_visitor_impl.hpp
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/ann_visitor_test.cpp

Hi,
I have added a `bias_set_visitor`. It helps to set the bias parameters only. It also returns the number of bias terms in the given layer.

Bias Visitor.

---

src/mlpack/core/data/load_image_impl.hpp
src/mlpack/core/data/scaler_methods/max_abs_scaler.hpp
src/mlpack/core/data/scaler_methods/mean_normalization.hpp
src/mlpack/core/data/scaler_methods/min_max_scaler.hpp
src/mlpack/core/data/scaler_methods/pca_whitening.hpp
src/mlpack/core/data/scaler_methods/standard_scaler.hpp
src/mlpack/core/data/scaler_methods/zca_whitening.hpp
src/mlpack/methods/kde/kde_rules_impl.hpp
src/mlpack/methods/preprocess/scaling_model.hpp
src/mlpack/methods/preprocess/scaling_model_impl.hpp
src/mlpack/tests/augmented_rnns_tasks_test.cpp

Reduce style related warnings in the build process; example: https://travis-ci.org/mlpack/mlpack/jobs/570648288

Reduce style related warnings

---

COPYRIGHT.txt
src/mlpack/tests/main_tests/kfn_test.cpp
src/mlpack/tests/main_tests/knn_test.cpp

Hey @rcurtin,  I added my name in the contributor's list in this PR. Thanks for the suggestion in #1809.

Updated contributor's list

---

src/mlpack/methods/ann/layer/CMakeLists.txt
src/mlpack/methods/ann/layer/layer.hpp
src/mlpack/methods/ann/layer/layer_types.hpp
src/mlpack/methods/ann/layer/weight_norm.hpp
src/mlpack/methods/ann/layer/weight_norm_impl.hpp
src/mlpack/methods/ann/visitor/bias_set_visitor.hpp
src/mlpack/tests/ann_layer_test.cpp

This currently contains the template code of weight norm layer.

Weight Normalization Layer.

---

HISTORY.md
src/mlpack/methods/kde/kde_rules.hpp
src/mlpack/methods/kde/kde_rules_impl.hpp
src/mlpack/methods/kde/kde_stat.hpp
src/mlpack/tests/kde_test.cpp
src/mlpack/tests/main_tests/kde_test.cpp

This PR is an implementation of #1954.

[GSoC] Reclaim unused KDE error tolerance

---

src/mlpack/tests/main_tests/random_forest_test.cpp

Previously, we checked that the number of trees and the maximum leaf size had any effect by comparing the accuracy of models built with different options.  However, it's possible that the accuracy can be exactly the same.  Even when we run five times, the failure probability is still non-negligible.
However, since we have access to the random forest model itself, we can actually just check that the tree structures are different.  There is no failure probability when we do this.
I also added a test to ensure that the `maximum_depth` option makes a difference when we change it.
This is a part of #1993.

Fix `RandomForestMainTest` random failures

---

src/mlpack/methods/ann/gan/gan.hpp
src/mlpack/methods/ann/gan/gan_impl.hpp
src/mlpack/methods/ann/gan/wgan_impl.hpp
src/mlpack/methods/ann/gan/wgangp_impl.hpp
src/mlpack/methods/ann/layer/atrous_convolution.hpp
src/mlpack/methods/ann/layer/atrous_convolution_impl.hpp
src/mlpack/methods/ann/layer/convolution.hpp
src/mlpack/methods/ann/layer/convolution_impl.hpp
src/mlpack/tests/ann_layer_test.cpp
src/mlpack/tests/dcgan_test.cpp
src/mlpack/tests/gan_test.cpp
src/mlpack/tests/wgan_test.cpp

Hi this is a PR to improve gan serialization mentioned in #1558 by @ShikharJ . 
I have kept `FFN` serialization as a reference. It looks like things implemented in it are very much precise.
`Note` : There will be some modification in `gan_test.cpp` of the PR after issue in #1724 is fixed. I am making this PR as I will be stuck in my exams for the next five days. I thought it will be good if you review other part of this PR in the meantime, and guide me if I am going wrong in this.

Improving Gan Serialization.

---

src/mlpack/methods/ann/gan/gan.hpp
src/mlpack/methods/ann/gan/gan_impl.hpp
src/mlpack/tests/gan_test.cpp

extending callbacks to gan

---

CMakeLists.txt

This should fix #2064.  @marcespie let me know if this is sufficient to solve your problem, or if more should be done here. :+1:

Reference a version number in the STB directory

---

src/mlpack/methods/ann/ffn.hpp
src/mlpack/methods/ann/gan/gan.hpp
src/mlpack/methods/ann/rnn.hpp
src/mlpack/methods/logistic_regression/logistic_regression.hpp

as @rcurtin said in #2074 (comment), we should point to ens docs, so I made a PR for that
easy fix :) :rocket:

Pointing to ensmallend docs for callbacks docs

---

README.md

Show the latest mlpack release (3.2.2) in Readme.md.

Show the latest mlpack release (3.2.2) in Readme.md

---

HISTORY.md
src/mlpack/methods/ann/rnn_impl.hpp
src/mlpack/tests/recurrent_network_test.cpp

Fix:#2070  and for failure of #2086.
Sorry for creating multiple pr for single issue I messed up with my previous branch

Fixing failure due to too-large rho values

---

src/mlpack/methods/ann/layer_names.hpp
src/mlpack/tests/layer_names_test.cpp

Adds the following layer names in ANN:
- lsm
- crelu
- highway
- gru
- glimpse
- fastlstm
- weightnorm

Adds Layer Names in ANN

---

README.md
doc/guide/build.hpp

Updating tutorial as mentioned in 
https://github.com/mlpack/mlpack.org/pull/23

Update readme.md and build.hpp

---

src/mlpack/methods/ann/activation_functions/softsign_function.hpp

The original equation will confuse users with its original [derivative definition](https://en.wikipedia.org/wiki/Activation_function)

correct softsign equation in document

---

.ci/macos-steps.yaml

Hi everyone, It's an attempt to fix Build failure of Julia. This will test (https://github.com/Homebrew/homebrew-cask/pull/77272#issue-376756379).

Quick Fix Julia Build Failure

---

HISTORY.md
src/mlpack/methods/ann/loss_functions/CMakeLists.txt
src/mlpack/methods/ann/loss_functions/mean_bias_error.hpp
src/mlpack/methods/ann/loss_functions/mean_bias_error_impl.hpp
src/mlpack/tests/loss_functions_test.cpp

References: 
> https://www.sciencedirect.com/topics/engineering/mean-bias-error
> https://medium.com/human-in-a-machine-world/mae-and-rmse-which-metric-is-better-e60ac3bde13d

added mean bias loss function

---

HISTORY.md
src/mlpack/methods/ann/loss_functions/CMakeLists.txt
src/mlpack/methods/ann/loss_functions/mean_squared_error.hpp
src/mlpack/methods/ann/loss_functions/mean_squared_logarithmic_error.hpp
src/mlpack/methods/ann/loss_functions/mean_squared_logarithmic_error_impl.hpp
src/mlpack/tests/loss_functions_test.cpp

Referenced from :- 
> https://scikit-learn.org/stable/modules/model_evaluation.html#mean-squared-log-error
@kartikdutt18 , hi could you have a look at the implementation, I can proceed to add the test after it.
Thanks!!!!

added mean squared logarithic error

---

COPYRIGHT.txt
doc/guide/build.hpp

Added clarifications for building from source for older versions of Ubuntu and Debian.

Update doc about installation on different versions of ubuntu and debian

---

src/mlpack/methods/ann/layer/lstm.hpp

Just something I came across while going through the code, the documentation displayed it as a dot product but it is actually hadamard product.
Small fix!!!

Hadamard product instead of Dot product in documentation

---

src/mlpack/methods/ann/layer/elu.hpp
src/mlpack/methods/ann/layer/elu_impl.hpp
src/mlpack/methods/ann/layer/leaky_relu.hpp
src/mlpack/methods/ann/layer/leaky_relu_impl.hpp
src/mlpack/methods/ann/layer/parametric_relu.hpp
src/mlpack/methods/ann/layer/parametric_relu_impl.hpp

Hi everyone,
In reference to [this discussion](https://github.com/mlpack/mlpack/pull/2174/files#r384141238), I have restructured code for activation functions implemented as layers as suggested by @zoq.
Kindly have a look.
Thanks.

Refactor Activation Function implemented in ann/layers.

---

src/mlpack/methods/ann/layer/alpha_dropout.hpp
src/mlpack/methods/ann/layer/c_relu.hpp
src/mlpack/methods/ann/layer/dropconnect.hpp
src/mlpack/methods/ann/layer/dropout.hpp
src/mlpack/methods/ann/layer/elu.hpp
src/mlpack/methods/ann/layer/fast_lstm.hpp
src/mlpack/methods/ann/layer/glimpse.hpp
src/mlpack/methods/ann/layer/gru.hpp
src/mlpack/methods/ann/layer/recurrent_attention.hpp
src/mlpack/methods/ann/layer/reparametrization.hpp
src/mlpack/methods/ann/layer/weight_norm.hpp

While going through a file, I feel I want to reference the paper sometimes to get a better understanding so it is extremely useful to have the links mentioned.

Added URL's for Paper cited in some files

---

CONTRIBUTING.md

This is in view of messages being received by new contributors in irc/slack channels to review PR, I thought of addressing it, I have tried my best not to sound rude. 
If anyone finds this rude or as of that matter find that it is not necessary to mention explicitly and can be handled internally , I will go ahead and close it.
I really do appreciate any formatting of sentence to make it more warm and welcoming ❤️

Improving Contributing guidlines

---

src/mlpack/core/metrics/lmetric.hpp
src/mlpack/core/metrics/mahalanobis_distance.hpp
src/mlpack/core/metrics/mahalanobis_distance_impl.hpp
src/mlpack/methods/ann/layer/hardshrink.hpp
src/mlpack/methods/ann/layer/hardshrink_impl.hpp
src/mlpack/methods/ann/layer/max_pooling.hpp
src/mlpack/methods/ann/layer/mean_pooling.hpp
src/mlpack/methods/ann/layer_names.hpp
src/mlpack/methods/ann/loss_functions/log_cosh_loss.hpp
src/mlpack/methods/ann/loss_functions/log_cosh_loss_impl.hpp
src/mlpack/tests/activation_functions_test.cpp
src/mlpack/tests/loss_functions_test.cpp

closes #2287.
I have made changes to remove r-value from remaining functions. There were also some style changes that I thought should be made so I have also made them. I hope that's okay. I can also open another PR for style but since they were simple enough I've made them in this PR.
Thanks.

Removed r-value references from remaining functions [and some style fixes]

---

doc/tutorials/reinforcement_learning/reinforcement_learning.txt
doc/tutorials/rl/rl.txt

Seeing as how there isn't a tutorial for the RL module (#2217 ), I decided to go about writing a simple tutorial explaining the basics of mlpack's RL framework. 
The tutorial mainly adapts the simplest test in `q_learning_test.cpp` and I have attempted to provide a clear, concise introduction to using reinforcement learning methods in mlpack.

Reinforcement Learning Tutorial

---

.ci/ci.yaml

See https://status.dev.azure.com/_event/179641421 for more details.

Azure-pipelines: walkaround

---

.ci/ci.yaml
.ci/macos-steps.yaml

In Azure Pipeline macOS build is failing. This PR is a try resolve the failure.

Fix Azure Pipeline Failure

---

src/mlpack/tests/q_learning_test.cpp

1) Changed config.DoubleQLearning() = true; for Double DQN 
2) Comment changes

DoubleDQN doesn't utilize DoubleQLearning

---

.ci/linux-steps.yaml
.ci/macos-steps.yaml

Yet again, Python-2.7 MacOS build is failing python-bindings Ctest. This is an attempt to fix the same. At least I think the error is due to installing pandas. Reproduced this locally.
Thanks.

Attempt to Fix Azure pipeline

---

HISTORY.md
src/mlpack/methods/ann/loss_functions/cross_entropy_error.hpp
src/mlpack/methods/ann/loss_functions/cross_entropy_error_impl.hpp
src/mlpack/methods/ann/loss_functions/dice_loss.hpp
src/mlpack/methods/ann/loss_functions/dice_loss_impl.hpp
src/mlpack/methods/ann/loss_functions/earth_mover_distance.hpp
src/mlpack/methods/ann/loss_functions/earth_mover_distance_impl.hpp
src/mlpack/methods/ann/loss_functions/hinge_embedding_loss.hpp
src/mlpack/methods/ann/loss_functions/hinge_embedding_loss_impl.hpp
src/mlpack/methods/ann/loss_functions/huber_loss.hpp
src/mlpack/methods/ann/loss_functions/huber_loss_impl.hpp
src/mlpack/methods/ann/loss_functions/kl_divergence.hpp
src/mlpack/methods/ann/loss_functions/kl_divergence_impl.hpp
src/mlpack/methods/ann/loss_functions/log_cosh_loss.hpp
src/mlpack/methods/ann/loss_functions/log_cosh_loss_impl.hpp
src/mlpack/methods/ann/loss_functions/mean_bias_error.hpp
src/mlpack/methods/ann/loss_functions/mean_bias_error_impl.hpp
src/mlpack/methods/ann/loss_functions/mean_squared_error.hpp
src/mlpack/methods/ann/loss_functions/mean_squared_error_impl.hpp
src/mlpack/methods/ann/loss_functions/mean_squared_logarithmic_error.hpp
src/mlpack/methods/ann/loss_functions/mean_squared_logarithmic_error_impl.hpp
src/mlpack/methods/ann/loss_functions/negative_log_likelihood.hpp
src/mlpack/methods/ann/loss_functions/negative_log_likelihood_impl.hpp
src/mlpack/methods/ann/loss_functions/reconstruction_loss.hpp
src/mlpack/methods/ann/loss_functions/reconstruction_loss_impl.hpp
src/mlpack/methods/ann/loss_functions/sigmoid_cross_entropy_error.hpp
src/mlpack/methods/ann/loss_functions/sigmoid_cross_entropy_error_impl.hpp

In accordance to #2338
Any other suggestions/ideas are most welcome.

templating return type of loss functions

---

doc/tutorials/reinforcement_learning/reinforcement_learning.txt

As part of increasing the documentation, i have added explanation of some differences in the code wrt to the q-learning example. And then i provided a full sample code for running the algorithm right away. Hope its useful :)

added asynchronous learning tutorial

---

src/mlpack/core/data/load_image.cpp
src/mlpack/core/data/save_image.cpp

This one is attempt #2... now it's based on the correct branch. :)  See #2355 for details.

Workaround Debian buster STB include bug

---

HISTORY.md
src/mlpack/methods/ann/loss_functions/CMakeLists.txt
src/mlpack/methods/ann/loss_functions/l1_loss.hpp
src/mlpack/methods/ann/loss_functions/l1_loss_impl.hpp
src/mlpack/tests/loss_functions_test.cpp

I am trying to add l1 loss function in ann module. Paper for l1 loss https://arxiv.org/abs/1702.05659 . Related to  #2200 and #2202 .
Writing tests is left.

Adding L1 loss function

---

src/mlpack/methods/ann/gan/gan_impl.hpp
src/mlpack/methods/ann/gan/wgan_impl.hpp
src/mlpack/methods/ann/gan/wgangp_impl.hpp

This PR is for the gradient issue in  #1770.

Probable error in generator update of GANs.

---

.ci/macos-steps.yaml
HISTORY.md
src/mlpack/bindings/julia/print_doc_functions_impl.hpp
src/mlpack/bindings/python/print_doc_functions_impl.hpp

This PR is created to fix Julia documentation as discussed with @rcurtin. The `info`, `help`, `version` and `copy_all_inputs` inputs aren't actually a part of the Julia binding as printed in the binding documentation.

Fix Julia documentation.

---

src/mlpack/core/util/CMakeLists.txt
src/mlpack/core/util/to_lower.hpp
src/mlpack/methods/ann/layer/atrous_convolution.hpp
src/mlpack/methods/ann/layer/atrous_convolution_impl.hpp
src/mlpack/methods/ann/layer/convolution.hpp
src/mlpack/methods/ann/layer/convolution_impl.hpp
src/mlpack/methods/ann/layer/transposed_convolution.hpp
src/mlpack/methods/ann/layer/transposed_convolution_impl.hpp

As suggested by @zoq . In https://github.com/mlpack/mlpack/pull/2324#discussion_r409762874 . I have added a `ToLower` to convert any string to lower.

Adding String lower case converter in util

---

src/mlpack/tests/gmm_test.cpp

This PR tries to fix #2393.
I have increased the percentage of tolerance from `10%` to `13%`.

GMMTest Tolerance update

---

HISTORY.md
src/mlpack/methods/reinforcement_learning/q_learning.hpp
src/mlpack/methods/reinforcement_learning/q_learning_impl.hpp
src/mlpack/tests/q_learning_test.cpp

Hey!
This should give the ability to change the actions for the agent. So with state, action, reward and terminal exposed for the agent, we can run the agent on an external env.

Accessor and Mutator for action in q_learning

---

src/mlpack/methods/ann/dists/normal_distribution.hpp

Found and fixed the minor typo.

Fixed the minor typo

---

Doxyfile
src/mlpack/core/util/param.hpp
src/mlpack/methods/bias_svd/bias_svd_function.hpp
src/mlpack/methods/decision_tree/all_categorical_split.hpp
src/mlpack/methods/kmeans/max_variance_new_cluster.hpp
src/mlpack/methods/linear_svm/linear_svm_function.hpp
src/mlpack/methods/regularized_svd/regularized_svd_function.hpp
src/mlpack/methods/svdplusplus/svdplusplus_function.hpp

I found sparse documentation about this documentation, so I have no citation, but I suspect the causation to be different boost versions on a workstation. May this be the mitigation of the red coloration.

Fix "nested comment" Doxygen Error

---

src/mlpack/methods/ann/layer/sequential_impl.hpp
src/mlpack/tests/ann_layer_test.cpp
src/mlpack/tests/q_learning_test.cpp

Minor style fixes (whitespace/line_length).

---

src/mlpack/methods/ann/activation_functions/CMakeLists.txt
src/mlpack/methods/ann/activation_functions/inverse_quadratic_function.hpp
src/mlpack/methods/ann/activation_functions/multi_quadratic_function.hpp
src/mlpack/methods/ann/activation_functions/poisson1_function.hpp
src/mlpack/methods/ann/activation_functions/quadratic_function.hpp
src/mlpack/methods/ann/activation_functions/spline_function.hpp
src/mlpack/tests/activation_functions_test.cpp

Related to  #2261 
I am trying to add some non-linear activation functions for rbf network in this PR.

Adding some activation functions for RBFN

---

CMake/FindArmadillo.cmake

Following @rcurtin 's comment #2401 
I'm not familiar enough with whatever about windows caused #2401 to be sure that this would resolve it, but worth a try, right?

If MSVC, always link Arma dependencies

---

src/mlpack/bindings/julia/CMakeLists.txt
src/mlpack/methods/kde/CMakeLists.txt
src/mlpack/methods/kde/kde_main.cpp

I noticed that there doesn't seem to be a `kde()` binding produced for either Go or Julia.  This quick change adds it. :)  (Let's hope it builds...)

Add KDE bindings for Julia and Go.

---

CMake/CreateArmaConfigInfo.cmake
CMake/FindArmadillo.cmake
CMakeLists.txt

This pull request cherry-picks some commits done in #2415 which is not related to Cross-compiling.
The objective of this pull request is to remove support for old Armadillo checking script.

Cmake aramdillo

---

README.md
src/mlpack/methods/ann/layer/radial_basis_function_impl.hpp
src/mlpack/methods/ann/layer/sequential_impl.hpp
src/mlpack/methods/reinforcement_learning/q_networks/simple_dqn.hpp
src/mlpack/tests/feedforward_network_test.cpp
src/mlpack/tests/q_learning_test.cpp

Hey everyone,
Adding mention of Go Bindings in cmake flag in readme.
Thanks.

Document Go in CMake Flags and Style Fixes.

---

src/mlpack/bindings/go/mlpack/capi/cli_util.cpp

Hi @lozhnikov @rcurtin, As discussed in #2482, I have tried to fix the bug here.

Fix pointer error in Go-bindings

---

src/mlpack/core/tree/cellbound_impl.hpp

Hey everyone,
These are simple style fixes in the cellbound_impl.hpp. Other than this, I removed an unnecessary "else" statement from the codebase. Kindly let me know what you think.
Regards.

Some Style Fixes.

---

src/mlpack/tests/linear_svm_test.cpp
src/mlpack/tests/logistic_regression_test.cpp
src/mlpack/tests/main_tests/nca_test.cpp
src/mlpack/tests/nmf_test.cpp

I made some fixes to tests based on recent failures that I observed:
http://ci.mlpack.org/job/mlpack%20-%20git%20commit%20test/453/display/redirect
http://ci.mlpack.org/job/mlpack%20-%20git%20commit%20test/456/display/redirect
I don't actually believe there are any problems with these tests---I think we are just randomly unlucky.  Hopefully this should help reduce spurious test failures.  I imagine, there are likely to be some more fixes in the future too. :)

Test stability fixes

---

src/mlpack/methods/reinforcement_learning/environment/CMakeLists.txt
src/mlpack/methods/reinforcement_learning/environment/acrobot.hpp
src/mlpack/methods/reinforcement_learning/environment/cart_pole.hpp
src/mlpack/methods/reinforcement_learning/environment/double_pole_cart.hpp
src/mlpack/methods/reinforcement_learning/environment/env_type.hpp
src/mlpack/methods/reinforcement_learning/environment/mountain_car.hpp
src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp
src/mlpack/methods/reinforcement_learning/policy/greedy_policy.hpp
src/mlpack/methods/reinforcement_learning/q_learning.hpp
src/mlpack/methods/reinforcement_learning/q_learning_impl.hpp
src/mlpack/methods/reinforcement_learning/replay/prioritized_replay.hpp
src/mlpack/methods/reinforcement_learning/replay/random_replay.hpp
src/mlpack/methods/reinforcement_learning/training_config.hpp
src/mlpack/methods/reinforcement_learning/worker/n_step_q_learning_worker.hpp
src/mlpack/methods/reinforcement_learning/worker/one_step_q_learning_worker.hpp
src/mlpack/methods/reinforcement_learning/worker/one_step_sarsa_worker.hpp
src/mlpack/tests/q_learning_test.cpp
src/mlpack/tests/rl_components_test.cpp

I've tried to make changes such that we can use gym_tcp_api to train and test, by using a "dummy" env by the name of  `DiscreteActionEnv`. I use the following code for training the agent using only gym_tcp_api (not using CartPole test env implemented in mlpack).
```c++
/**
* @file example.cpp
* @author Marcus Edel
*
* Simple random agent.
*/
#include <mlpack/core.hpp>
#include "../../mlpack/src/mlpack/methods/ann/ffn.hpp"
#include "../../mlpack/src/mlpack/methods/ann/init_rules/gaussian_init.hpp"
#include "../../mlpack/src/mlpack/methods/ann/layer/layer.hpp"
#include "../../mlpack/src/mlpack/methods/ann/loss_functions/mean_squared_error.hpp"
#include "../../mlpack/src/mlpack/methods/reinforcement_learning/environment/acrobot.hpp"
#include …
```

Adding support to use gym_tcp_api for training agents in q_learning

---

.ci/windows-steps.yaml

Unless anyone else can see a reason to run the test suite twice, let's remove one of them.

No reason to run the test suite twice.

---

doc/guide/cli_quickstart.hpp
doc/guide/iodoc.hpp
doc/guide/timer.hpp
src/mlpack/bindings/go/default_param.hpp
src/mlpack/bindings/go/go_option.hpp
src/mlpack/bindings/go/mlpack/capi/arma_util.cpp
src/mlpack/bindings/go/print_doc_functions.hpp
src/mlpack/bindings/go/print_doc_functions_impl.hpp
src/mlpack/bindings/go/print_input_processing.hpp
src/mlpack/bindings/markdown/print_doc_functions.hpp
src/mlpack/bindings/markdown/print_docs.hpp
src/mlpack/bindings/tests/clean_memory.cpp
src/mlpack/bindings/tests/clean_memory.hpp
src/mlpack/bindings/tests/delete_allocated_memory.hpp
src/mlpack/bindings/tests/get_allocated_memory.hpp
src/mlpack/bindings/tests/test_option.hpp
src/mlpack/core/util/mlpack_main.hpp
src/mlpack/core/util/param.hpp
src/mlpack/core/util/param_checks.hpp
src/mlpack/tests/prefixedoutstream_test.cpp
src/mlpack/tests/python_binding_test.cpp

While rebasing R-binding, I found that some of the CLIs are accidentally missed. Hence I have tried to fix those misses in this PR.
Thank You.

Fix Bad Regex from CLI11.

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/activation_functions_test.cpp

This was a quick attempt to help with #2523.  I did this partially by hand, partially with regular expressions.  I believe that it would be possible to do this all with regular expressions (plus a little bit of checking by hand afterwards). :+1:

Transition activation_functions_test.cpp to Catch

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/adaboost_test.cpp
src/mlpack/tests/main_tests/adaboost_test.cpp

Migrate adaboost test from boost to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/akfn_test.cpp
src/mlpack/tests/aknn_test.cpp
src/mlpack/tests/kfn_test.cpp
src/mlpack/tests/knn_test.cpp
src/mlpack/tests/main_tests/kfn_test.cpp
src/mlpack/tests/main_tests/knn_test.cpp

Refer - https://github.com/mlpack/mlpack/issues/2523
All KFN, KNN, AKFN, AKNN related test

Migrate KFN, KNN and related test from boost to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/load_save_test.cpp

Refer : https://github.com/mlpack/mlpack/issues/2523
This was tough :)

migrate load and save test from boost to catch2

---

src/mlpack/tests/metric_test.cpp

The PR should fix the App Veyor build.

[Ready] App Veyor build fix

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/armadillo_svd_test.cpp
src/mlpack/tests/bias_svd_test.cpp
src/mlpack/tests/block_krylov_svd_test.cpp
src/mlpack/tests/quic_svd_test.cpp
src/mlpack/tests/randomized_svd_test.cpp
src/mlpack/tests/regularized_svd_test.cpp
src/mlpack/tests/svd_batch_test.cpp
src/mlpack/tests/svd_incremental_test.cpp
src/mlpack/tests/svdplusplus_test.cpp

Refer https://github.com/mlpack/mlpack/issues/2523

Migrate svd_* and related test from boost to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/ann_dist_test.cpp
src/mlpack/tests/ann_layer_test.cpp
src/mlpack/tests/ann_regularizer_test.cpp
src/mlpack/tests/ann_visitor_test.cpp
src/mlpack/tests/test_catch_tools.hpp

migrate ann_* and related test from boost to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/decision_stump_test.cpp
src/mlpack/tests/decision_tree_test.cpp
src/mlpack/tests/main_tests/decision_stump_test.cpp
src/mlpack/tests/main_tests/decision_tree_test.cpp

Refer https://github.com/mlpack/mlpack/issues/2523

Migrate decision_* and related test from boost to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/binarize_test.cpp
src/mlpack/tests/imputation_test.cpp
src/mlpack/tests/main_tests/preprocess_binarize_test.cpp
src/mlpack/tests/main_tests/preprocess_imputer_test.cpp
src/mlpack/tests/main_tests/preprocess_scale_test.cpp
src/mlpack/tests/main_tests/preprocess_split_test.cpp
src/mlpack/tests/scaling_test.cpp
src/mlpack/tests/split_data_test.cpp

Refer : #2523 
Adding 54 more testcases 🚀

Migrate preprocess_* and related test from boost to catch2

---

src/mlpack/methods/reinforcement_learning/environment/env_type.hpp
src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp
src/mlpack/methods/reinforcement_learning/sac_impl.hpp
src/mlpack/tests/q_learning_test.cpp

Missed an important update. This change will be required in the bipedal example.

Added support for multiple actions in action space for Soft Actor Critic

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/sparse_coding_test.cpp
src/mlpack/tests/sparse_autoencoder_test.cpp
src/mlpack/tests/sparse_coding_test.cpp

migrate sparese_* related test from boost to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/cv_test.cpp

Migrate CVTest from boost to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/nca_test.cpp
src/mlpack/tests/nca_test.cpp

Migrate Nca test

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/kmeans_test.cpp
src/mlpack/tests/main_tests/kmeans_test.cpp

migrate Kmeans test from boost to catch

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/feedforward_network_test.cpp
src/mlpack/tests/rbm_network_test.cpp
src/mlpack/tests/recurrent_network_test.cpp

Migrate _network_* test from boost to catch 

---

.ci/linux-steps.yaml

Let's see if we can get some additional information to figure out what's wrong with he build.

Fix CI Linux Python build.

---

src/mlpack/CMakeLists.txt
src/mlpack/bindings/go/CMakeLists.txt
src/mlpack/bindings/julia/CMakeLists.txt
src/mlpack/bindings/python/CMakeLists.txt

Second approach to resolve #2581 
First can be found in #2587- closed due to misunderstanding of the task

Added post_x_bindings methods for Python, Go and Julia bindings

---

doc/guide/build.hpp

Name of packages upgraded in build.hpp from python2 to python3

package name upgrade python2 to python3

---

src/mlpack/methods/ann/ffn_impl.hpp
src/mlpack/methods/ann/layer/linear.hpp
src/mlpack/methods/ann/layer/linear_impl.hpp
src/mlpack/tests/feedforward_network_test.cpp

I am trying to add copy-constructor for linear layer in this PR to solve https://github.com/mlpack/mlpack/issues/2314

Adding copy constructor in linear layer

---

COPYRIGHT.txt
src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/arma_extend_test.cpp

migrate arma_extend_test from boost to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/random_forest_test.cpp
src/mlpack/tests/random_forest_test.cpp

Migrating Random Forest tests from boost to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/main_tests/pca_test.cpp
src/mlpack/tests/pca_test.cpp

Migrate PCA related tests from boost to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/loss_functions_test.cpp

Loss_function_test from boost to catch2

---

src/mlpack/methods/ann/layer/add.hpp
src/mlpack/methods/ann/layer/atrous_convolution.hpp
src/mlpack/methods/ann/layer/linear.hpp
src/mlpack/tests/ann_visitor_test.cpp

Add WeightSize() to Linear, Add and Atrous Convolution layers.

---

HISTORY.md
src/mlpack/methods/ann/layer/CMakeLists.txt
src/mlpack/methods/ann/layer/layer.hpp
src/mlpack/methods/ann/layer/softmin.hpp
src/mlpack/methods/ann/layer/softmin_impl.hpp
src/mlpack/tests/activation_functions_test.cpp

- Adding the Softmin activation function in ann/layers

Addition of softmin activation function

---

src/mlpack/tests/ann_layer_test.cpp
src/mlpack/tests/feedforward_network_test.cpp

Hey everyone,
This is an attempt to fix random failure in Azure due to a low threshold values. This PR aims to fix the same.
Thanks.

Increase Threshold for some tests where common failure occurs.

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/det_test.cpp
src/mlpack/tests/distribution_test.cpp

Migrate det and distribution test to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/sfinae_test.cpp
src/mlpack/tests/sort_policy_test.cpp
src/mlpack/tests/string_encoding_test.cpp

Refer #2523 
Migrating my GSOC test :)
Music and Coding are great stress busters ❤️

Migrate sort_policy, sfinae and string related test to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/lars_test.cpp
src/mlpack/tests/layer_names_test.cpp
src/mlpack/tests/lin_alg_test.cpp

Refer #2523 
Some more tests , Sorry for spamming :-p ---> `All tests passed (1354102 assertions in 910 test cases)`

Migrate layers_names, line_alg and lars test to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/async_learning_test.cpp
src/mlpack/tests/augmented_rnns_tasks_test.cpp

Some more passing tests :) Refer #2523 for more info

Migrate Augmentated_rnn and Async_Learning Test to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/dcgan_test.cpp
src/mlpack/tests/gan_test.cpp
src/mlpack/tests/math_test.cpp
src/mlpack/tests/wgan_test.cpp

Migration of GAN related tests and math test to Catch2 Testing

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/cf_test.cpp
src/mlpack/tests/krann_search_test.cpp
src/mlpack/tests/ksinit_test.cpp
src/mlpack/tests/main_tests/cf_test.cpp
src/mlpack/tests/main_tests/krann_test.cpp

Refer #2523 
Let's throw 5 more test out of window, 47 to go :)

Migrate krann and cf-Test from boost to catch2

---

src/mlpack/tests/CMakeLists.txt
src/mlpack/tests/kde_test.cpp
src/mlpack/tests/lmnn_test.cpp
src/mlpack/tests/main_tests/kde_test.cpp
src/mlpack/tests/main_tests/lmnn_test.cpp
src/mlpack/tests/reward_clipping_test.cpp
src/mlpack/tests/rl_components_test.cpp

Refer #2523 
Scrapped out 6 more tests, now 36 left :)

Migrate kde, lmnn , rl and rewardclipping test to catch

---

src/mlpack/methods/ann/layer/max_pooling.hpp
src/mlpack/methods/ann/layer/mean_pooling.hpp
src/mlpack/methods/ann/layer/softmax.hpp

Added WeighSize() to Softmax, Max_Pooling and Min_Pooling layers.

---

.github/workflows/main.yml
.github/workflows/update-catch.yaml
.github/workflows/update-cli11.yaml

Update CLI11 and Update catch workflow is also running on forked repositories. In this PR I have try to fix this issue.

Scheduled workflow must run on main repository only.

---

.appveyor.yml
CMakeLists.txt
doc/guide/build.hpp
doc/guide/build_windows.hpp
doc/guide/sample_ml_app.hpp
src/mlpack/bindings/cli/CMakeLists.txt
src/mlpack/bindings/python/CMakeLists.txt
src/mlpack/bindings/python/setup.py.in
src/mlpack/tests/CMakeLists.txt

In accordance with https://github.com/mlpack/mlpack/issues/2523#issuecomment-726323611
cc @zoq , @rcurtin 
Not sure if I cleaned up everything , let me know if i missed anything

some boost cleanup

---

src/mlpack/methods/ann/layer/noisylinear.hpp
src/mlpack/methods/ann/layer/noisylinear_impl.hpp
src/mlpack/tests/feedforward_network_test.cpp

Add copying and moving constructor for NoisyLinear layer

---

COPYRIGHT.txt

Pull Request [2624](https://github.com/mlpack/mlpack/pull/2624)

Added Copyright statement

---

src/mlpack/methods/ann/layer/recurrent.hpp
src/mlpack/methods/ann/layer/recurrent_impl.hpp

Changed comments from `LinearLayer` to `Recurrent` in `recurrent.hpp` and `recurrent_impl.hpp`

Comment change in recurrent

---

doc/guide/build_windows.hpp

As I had a hard time building mlpack on my Windows machine, I thought I would share the steps I had to take to get Visual Studio to build mlpack and some of its dependencies. The `REAME.md` changes outline all the steps needed to be taken by users who wish to build mlpack with Visual Studio.

README instructions for Visual Studio 2019 CMake build

---

README.md
doc/guide/build.hpp

This is to improvement on documentation to help new users get correct repositories to install and use mlpack

Improve Documentation to correctly state what repositories to get for various Linux distros

---

COPYRIGHT.txt
src/mlpack/methods/ann/layer/lstm.hpp
src/mlpack/methods/ann/layer/lstm_impl.hpp
src/mlpack/tests/ann_layer_test.cpp

This pull request is in reference to [issue#2625](https://github.com/mlpack/mlpack/issues/2625),
I'm trying to add constructors to LSTM layer

Adding Copy and Move constructors for LSTM class

---

COPYRIGHT.txt

Update the years in `COPYRIGHT.txt`, in case I missed some please feel free to comment or open another PR.

Update COPYRIGHT (year).

---

CMake/Findcereal.cmake

Fix indentation

---

src/mlpack/tests/ann_layer_test.cpp

Reference Issue #2699 
This PR continues from PR #2705

Added braced lists to ann_layer_test.cpp

---

src/mlpack/tests/cv_test.cpp
src/mlpack/tests/metric_test.cpp

Reference Issue #2699
This PR covers all the remaining files under this issue.

Added braced lists to remaining files

---

src/mlpack/methods/ann/loss_functions/CMakeLists.txt
src/mlpack/methods/ann/loss_functions/binary_cross_entropy_loss.hpp
src/mlpack/methods/ann/loss_functions/binary_cross_entropy_loss_impl.hpp
src/mlpack/tests/ann_layer_test.cpp
src/mlpack/tests/loss_functions_test.cpp

Fixed BCE Loss

---

src/mlpack/methods/ann/layer/multihead_attention.hpp
src/mlpack/methods/ann/layer/multihead_attention_impl.hpp
src/mlpack/methods/ann/layer/multiply_constant.hpp
src/mlpack/methods/ann/layer/multiply_merge.hpp
src/mlpack/tests/ann_visitor_test.cpp

This is in reference with issue #2590 .

Added WeightSize function for multihead_attention, multiply_constant and multiply_merge layers.

---

HISTORY.md

We forgot to add the changes to changelog

Add cereal library to history

---

.ci/linux-steps.yaml

Remove libarmadillo-dev, keep the manually installed one

---

src/mlpack/methods/ann/activation_functions/CMakeLists.txt
src/mlpack/methods/ann/activation_functions/hard_swish_function.hpp
src/mlpack/methods/ann/layer/base_layer.hpp
src/mlpack/tests/activation_functions_test.cpp

Implements the Hard Swish Activation Function.
[Pytorch](https://pytorch.org/docs/stable/generated/torch.nn.Hardswish.html) Reference.

Hard swish Activation Function

---

src/mlpack/methods/ann/layer/constant.hpp
src/mlpack/methods/ann/layer/linear_no_bias.hpp
src/mlpack/methods/ann/layer/linear_no_bias_impl.hpp
src/mlpack/methods/ann/layer/radial_basis_function.hpp

add WeightSize() for linear_no_bias, rbf, constant
Fixes #2590

add WeightSize() for linear_no_bias, rbf, constant

---

src/mlpack/tests/split_data_test.cpp

Fixed the names of variables from snake_case to camelCase in `split_data_test.cpp`

Fixed variable names in #2746

---

src/mlpack/methods/decision_tree/information_gain.hpp

Fixed documentation in information_gain.hpp.

---

doc/tutorials/linear_regression/linear_regression.txt

This is my PR for improving the documentation at Linear_regression [(this)](https://mlpack.org/doc/mlpack-git/doxygen/lrtutorial.html) by adding some example regarding Multivariate Linear Regression using CLI.

Improve Linear Regression Docs.

---

doc/tutorials/reinforcement_learning/reinforcement_learning.txt

Update Reinforcement Learning tutorial for custom DQN network

---

src/mlpack/methods/ann/layer/mean_pooling.hpp
src/mlpack/methods/ann/layer/mean_pooling_impl.hpp
src/mlpack/tests/ann_layer_test.cpp

Fixed ceil_mode in mean pooling layer

Fixed  mean poolinglayer for correct ceil_mode

---

doc/tutorials/reinforcement_learning/reinforcement_learning.txt

this PR means to fix a little typo in [this docs.](https://www.mlpack.org/doc/mlpack-git/doxygen/rltutorial.html)

fix typo in rl tutorial

---

COPYRIGHT.txt
src/mlpack/methods/reinforcement_learning/q_learning_impl.hpp

This resolves the issue of #2855. I have implemented an if statement that looks if weights are loaded or not. If  weights are not loaded, they are reset. Otherwise they are not reset. (The network is empty if nothing is loaded.)

Fixed ResetParameters() in #2855

---

.ci/linux-steps.yaml

Download all boost instead of a specific version.

---

src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp
src/mlpack/core/tree/cover_tree/dual_tree_traverser_impl.hpp
src/mlpack/core/tree/cover_tree/single_tree_traverser_impl.hpp
src/mlpack/tests/akfn_test.cpp
src/mlpack/tests/krann_search_test.cpp

This pull request closes #2869 and fixes all errors from cover tree
when trying to put mlpack on arm64 devices.
Thanks to @rcurtin to put all effort to resolve this one.
Authored-by: Ryan Curtin <ryan@ratml.org>

Fix cover tree issues by @rcurtin fixes #2869

---

src/mlpack/bindings/go/print_doc_functions_impl.hpp
src/mlpack/core/kernels/epanechnikov_kernel_impl.hpp
src/mlpack/core/kernels/spherical_kernel.hpp
src/mlpack/core/metrics/bleu_impl.hpp
src/mlpack/core/tree/rectangle_tree/x_tree_split_impl.hpp
src/mlpack/methods/amf/termination_policies/simple_tolerance_termination.hpp
src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression.cpp
src/mlpack/methods/cf/cf_model.cpp
src/mlpack/methods/det/dtree_impl.hpp
src/mlpack/methods/fastmks/fastmks_main.cpp
src/mlpack/methods/linear_svm/linear_svm_main.cpp
src/mlpack/methods/neighbor_search/neighbor_search_rules_impl.hpp
src/mlpack/tests/det_test.cpp
src/mlpack/tests/serialization.hpp

The PR is mainly used to identify correct warnings, and later fix the issues.

Solve static code analysis issues

---

src/mlpack/methods/ann/layer/lp_pooling.hpp
src/mlpack/methods/ann/layer/lp_pooling_impl.hpp
src/mlpack/methods/ann/layer/max_pooling.hpp
src/mlpack/methods/ann/layer/max_pooling_impl.hpp

Fixed        ceil in max    and       lp pooling

Fixed ceil  parameter  in max and lp    pooling layer

---

COPYRIGHT.txt
HISTORY.md
src/mlpack/methods/ann/layer/CMakeLists.txt
src/mlpack/methods/ann/layer/flatten_t_swish.hpp
src/mlpack/methods/ann/layer/flatten_t_swish_impl.hpp
src/mlpack/methods/ann/layer/layer.hpp
src/mlpack/tests/activation_functions_test.cpp

This PR means to implement this [paper](https://arxiv.org/abs/1812.06247).

Adding Flatten T Swish Activation Function

---

src/mlpack/methods/ann/layer/recurrent_attention_impl.hpp
src/mlpack/methods/reinforcement_learning/q_networks/categorical_dqn.hpp
src/mlpack/tests/decision_tree_test.cpp
src/mlpack/tests/lsh_test.cpp
src/mlpack/tests/main_tests/hoeffding_tree_test.cpp
src/mlpack/tests/main_tests/kmeans_test.cpp
src/mlpack/tests/main_tests/local_coordinate_coding_test.cpp
src/mlpack/tests/main_tests/mean_shift_test.cpp
src/mlpack/tests/main_tests/preprocess_split_test.cpp
src/mlpack/tests/random_forest_test.cpp
src/mlpack/tests/rectangle_tree_test.cpp

I think that this will fix the failing static code analysis builds I've been seeing.  Hopefully! :)

Try to fix the static code analysis issue

---

.github/workflows/main.yml
src/mlpack/core/data/load.hpp

I figured I'd give #2966 a shot... I have no idea if I'll have any success. :)

Try to fix R build

---

src/mlpack/bindings/markdown/print_docs.cpp
src/mlpack/core/data/load_model_impl.hpp

Let us see if the CI agrees with me.

I do think these headers are useless here in this file.

---

src/mlpack/bindings/python/print_class_defn.hpp
src/mlpack/bindings/python/print_pyx.cpp
src/mlpack/methods/ann/layer/mean_pooling.hpp
src/mlpack/methods/ann/layer/padding.hpp
src/mlpack/methods/ann/layer/padding_impl.hpp
src/mlpack/tests/ann_layer_test.cpp

Style fixes (line length, extra spaces, newline).

---

src/mlpack/core/data/save.hpp

Fix small bug JSON -> txt

---

src/mlpack/methods/ann/layer/concat.hpp
src/mlpack/methods/ann/layer/concat_performance.hpp
src/mlpack/methods/ann/layer/highway.hpp
src/mlpack/methods/ann/layer/recurrent_attention.hpp
src/mlpack/methods/ann/layer/sequential.hpp
src/mlpack/methods/dbscan/dbscan.hpp
src/mlpack/methods/mean_shift/mean_shift.hpp
src/mlpack/tests/lrsdp_test.cpp
src/mlpack/tests/test_catch_tools.hpp

Just wondering why it is here in the first place? :smiley:

Remove this boost pointer vector header.

---

HISTORY.md

I forgot to make this change in #2995, so, here is a new PR to fix the HISTORY.  Thanks @jeffin143 for pointing this out. :)

Update HISTORY for threadsafe-io branch

---

src/mlpack/core/kernels/spherical_kernel.hpp

Remove forgetten boost math

---

HISTORY.md

We need to be better at keeping the changelog updated :smile:.

The CHANGELOG.

---

src/mlpack/methods/ann/layer/parametric_relu_impl.hpp
src/mlpack/tests/feedforward_network_test.cpp

Related to #3113 
@zoq How do I test this in Azure Pipeline?

PReLU Hotfix

---

.github/workflows/main.yml
CMakeLists.txt

Fixed macOS R environment by downgrading macOS version to 10.15.
Changed macOS version detection regex logic

MacOS CI Fix

---

.github/workflows/update-boost-version.yaml

This should fix the boost update action - https://github.com/mlpack/mlpack/actions/runs/1645847471.

Fix Boost Update Action

---

src/mlpack/methods/ann/layer/padding_impl.hpp

https://github.com/mlpack/mlpack/pull/3116#discussion_r777041677

Padding Layer Unitialized Warning

---

src/mlpack/methods/ann/layer/linear_no_bias.hpp
src/mlpack/methods/ann/layer/linear_no_bias_impl.hpp
src/mlpack/tests/feedforward_network_test.cpp

linear no bias copy and move constructor created

---

src/mlpack/methods/ann/layer/CMakeLists.txt
src/mlpack/methods/ann/layer/instance_norm.hpp
src/mlpack/methods/ann/layer/instance_norm_impl.hpp
src/mlpack/methods/ann/layer/layer.hpp
src/mlpack/methods/ann/layer/layer_types.hpp
src/mlpack/tests/ann_layer_test.cpp

I'm creating a new PR for #2900 as I've lost access to that branch. 
@zoq I've rebased this layer against the latest master branch as discussed on the IRC.

Instance Norm

---

.github/workflows/main.yml

Forced `pkgbuild` to install for now.

R Build Fix

---

src/mlpack/bindings/python/copy_artifacts.py
src/mlpack/bindings/python/setup.cfg

Changed the strict hard-coding to softer one using glob library.

Python Build Fix

---

.ci/linux-steps.yaml
.ci/macos-steps.yaml
CMake/FindGo.cmake
CMake/FindGonum.cmake

It is a temporary fix. 
From Go 1.18 onwards, we may be forced to use modules. I will open a separate issue for this.

Go Build Fix

---

.github/ISSUE_TEMPLATE/2-question.md
src/mlpack/methods/reinforcement_learning/environment/acrobot.hpp
src/mlpack/methods/reinforcement_learning/environment/cart_pole.hpp
src/mlpack/methods/reinforcement_learning/environment/continuous_mountain_car.hpp
src/mlpack/methods/reinforcement_learning/environment/mountain_car.hpp
src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp

Fixes #3211 
Fixed broken links in documentation

Fixed All Link Related Issues

---

src/mlpack/methods/ann/layer/CMakeLists.txt
src/mlpack/methods/ann/layer/identity.hpp
src/mlpack/methods/ann/layer/identity_impl.hpp
src/mlpack/methods/ann/layer/layer_types.hpp
src/mlpack/methods/ann/layer/serialization.hpp
src/mlpack/tests/ann_layer_test.cpp

Identity Layer implementation

---

src/mlpack/methods/ann/layer/convolution.hpp
src/mlpack/methods/ann/layer/convolution_impl.hpp
src/mlpack/tests/ann_layer_test.cpp

Added boolean to disable bias addition in Convolution layer.

Bias Boolean in Convolution layer

---

src/mlpack/CMakeLists.txt

Corrects copying of `core` and `methods` folder.

Make Install BugFix

---

src/mlpack/core/tree/rectangle_tree/x_tree_split_impl.hpp

Switch from bitwise to logical comparison

---

src/mlpack/tests/catch.hpp

aiming to sneak this in before the mlpack 4.0.0 release in #3286

update to catch v2.13.10

---

scripts/release-mlpack.sh

This has just a few fixes for the release script when I ran it through.  Once we can merge this, I can run the release script and generate a new PR to release mlpack 4. :)

Fix release script

---

doc/tutorials/ann.md

1. Removed some unnecessary characters
2. Added a image which was labelled as `TODO`

Improving ann doc 

---

COPYRIGHT.txt
doc/quickstart/python.md

**Changes in this PR**
1. Made the changes regarding issue #3336 
2. Added my name to `COPYRIGHT.txt`

input to input_ in python quickstart

---

doc/quickstart/cpp.md

Thanks @sandeep-ps for pointing out this issue! :+1:

Fix name of RandomForest class in C++ quickstart

---

doc/user/hpt.md

A minor effort to improve documentation.

A small typo fix in the doc hpt.md

---

README.md

new JOSS article has been accepted (https://doi.org/10.21105/joss.05026), so update the citation details

update citation details

---

doc/user/formats.md

I found a typo here, correct me if wrong.

Fix a typo

---

doc/developer/kernels.md
doc/developer/metrics.md
doc/developer/trees.md
doc/tutorials/approx_kfn.md
doc/tutorials/cf.md
doc/tutorials/image.md
doc/tutorials/range_search.md
doc/user/cv.md
doc/user/hpt.md

An attempt to fix some typos in the doc.

Some similar typos in doc

---

src/mlpack/bindings/R/generate_R.cpp.in
src/mlpack/bindings/julia/generate_jl.cpp.in
src/mlpack/bindings/julia/julia_util.h
src/mlpack/bindings/julia/tests/runtests.jl
src/mlpack/bindings/markdown/generate_markdown.cpp.in
src/mlpack/bindings/python/mlpack/serialization.pxd

In some of the files, license text was missing. I have tried to include it in the files that came under my notice.

Added License text

---

doc/developer/bindings.md

I have encountered some minor doc issues while going through the file. I have tried to fix some of them.
Thanks 
Adi

Minor doc fix in bindings.md

---

doc/tutorials/amf.md

An attempt to solve #3390.
**The changes made in amf doc-**
- added a random number as the rank of the factorization
- replaced randu with sprandu for sp_mat

Fixing amf doc as in #3390

---

doc/developer/bindings.md
src/mlpack/core/util/param.hpp

Removed some redundant documentation.
Thanks,
Adi

Redundant Documentation

---

doc/tutorials/amf.md
doc/tutorials/linear_regression.md
src/mlpack/bindings/markdown/print_param_table.hpp
src/mlpack/bindings/python/print_wrapper_py.cpp
src/mlpack/core/util/param.hpp
src/mlpack/core/util/params_impl.hpp
src/mlpack/methods/linear_regression/linear_regression.hpp
src/mlpack/methods/svdplusplus/svdplusplus.hpp

While going through various files, I have found some minor doc issues. An attempt to fix the same.
I also included changes from PR #3403. 
Thanks, 
Adi.

Possible fixes

---

HISTORY.md
src/mlpack/methods/ann/layer/parametric_relu_impl.hpp
src/mlpack/tests/ann/layer/parametric_relu.cpp

Fix PReLU (Resolves #3466)

---

HISTORY.md

Oops, I forgot to do this during the merge of #3469!

Update history for #3469

---

HISTORY.md
src/mlpack/methods/ann/activation_functions/activation_functions.hpp
src/mlpack/methods/ann/activation_functions/bipolar_sigmoid_function.hpp
src/mlpack/methods/ann/activation_functions/elliot_function.hpp
src/mlpack/methods/ann/activation_functions/hyper_sinh_function.hpp
src/mlpack/methods/ann/layer/base_layer.hpp
src/mlpack/tests/ann/activation_functions_test.cpp
src/mlpack/tests/ann/ann_test_tools.hpp
src/mlpack/tests/ann/not_adapted/activation_functions_test.cpp

Implemented the bipolar sigmoid activation function
Fixed invertible activation functions 
Added jacobian testing for all of the above mentioned ones
Tested and used in various research papers:
https://www.scitepress.org/Papers/2018/100372/100372.pdf
https://iopscience.iop.org/article/10.1088/1742-6596/1255/1/012023/meta

Bipolar sigmoid added

---

src/mlpack/core/util/arma_traits.hpp
src/mlpack/methods/ann/init_rules/glorot_init.hpp

Prepare the following function signature for coot.
In the first PR, we will adapt it and add additional `std::enable_if_t<IsCoot>` to make work in that case.

Coot E01S03

---

doc/user/core.md
src/mlpack/core/math/random.hpp
src/mlpack/methods/ann/init_rules/gaussian_init.hpp
src/mlpack/methods/ann/init_rules/glorot_init.hpp
src/mlpack/methods/reinforcement_learning/noise/gaussian.hpp
src/mlpack/tests/ann/not_adapted/gan_test.cpp
src/mlpack/tests/policy_gradient_test.cpp

Hi,
This is a fix for this bug.

BUG Fix RandNormal() to take the standard deviation as a parameter instead of the variance

---

doc/quickstart/python.md

This is the correction for the issue #3672

Corrected the example code for python bindings quick starter

---

src/mlpack/methods/ann/layer/log_softmax.hpp
src/mlpack/methods/ann/layer/log_softmax_impl.hpp

@MarkFischinger please feel free to open a PR to replace the current implementation with Padé

Coot15, Do not use the transform function if we are using bandicoot in softmax layer

---

doc/user/core.md
scripts/build-docs.sh
src/mlpack/core/kernels/cauchy_kernel.hpp
src/mlpack/core/kernels/cosine_similarity.hpp
src/mlpack/core/kernels/cosine_similarity_impl.hpp
src/mlpack/core/kernels/epanechnikov_kernel.hpp
src/mlpack/core/kernels/hyperbolic_tangent_kernel.hpp
src/mlpack/core/kernels/kernels.hpp
src/mlpack/core/kernels/laplacian_kernel.hpp
src/mlpack/core/kernels/polynomial_kernel.hpp
src/mlpack/core/kernels/pspectrum_string_kernel_impl.hpp
src/mlpack/core/kernels/spherical_kernel.hpp
src/mlpack/core/kernels/triangular_kernel.hpp
src/mlpack/methods/fastmks/fastmks_main.cpp
src/mlpack/methods/fastmks/fastmks_model.hpp
src/mlpack/methods/fastmks/fastmks_model_impl.hpp
src/mlpack/tests/fastmks_test.cpp
src/mlpack/tests/kernel_test.cpp

I went through all the kernels in `core/kernels/` and documented each of them.  Here is a rendered page:
http://ratml.org/misc/mlpack-markdown-doc/user/core.html#kernels
In a few places minor changes were needed to add ways to change the bandwidth, or print properties, or little things like this.  Otherwise everything was pretty straightforward.
I intentionally did not run the link checker locally because I want to exercise the CI job and make sure it is failing correctly. :)

Document all of kernels/ directory.

---

HISTORY.md
src/mlpack/methods/ann/layer/nearest_interpolation.hpp
src/mlpack/methods/ann/layer/nearest_interpolation_impl.hpp

updated some errors from previous pr on adapting nearest interpolation

---

src/mlpack/core/util/first_element_is_arma.hpp

This file didn't have a license in it, so the release script hiccups.  Oops.

Add license to file

---

doc/embedded/crosscompile_armv7.md
doc/index.md
doc/sidebar.html

Creating again the PR since I can not push to @rcurtin directly as it seems that there is some permission problems

Embed doc 1

---

src/mlpack/methods/ann/layer/not_adapted/pixel_shuffle.hpp
src/mlpack/methods/ann/layer/not_adapted/pixel_shuffle_impl.hpp
src/mlpack/methods/ann/loss_functions/mean_absolute_percentage_error.hpp
src/mlpack/methods/ann/loss_functions/multilabel_softmargin_loss.hpp
src/mlpack/methods/ann/loss_functions/multilabel_softmargin_loss_impl.hpp
src/mlpack/methods/ann/loss_functions/triplet_margin_loss.hpp
src/mlpack/methods/ann/loss_functions/triplet_margin_loss_impl.hpp
src/mlpack/methods/lmnn/lmnn.hpp
src/mlpack/methods/lmnn/lmnn_impl.hpp
src/mlpack/methods/nca/nca.hpp
src/mlpack/methods/nca/nca_impl.hpp
src/mlpack/methods/radical/radical.hpp
src/mlpack/methods/radical/radical_impl.hpp
src/mlpack/methods/softmax_regression/softmax_regression_impl.hpp

It seems that Mr, arm-none-eabi complains about the difference in signature between the header and the implementation.
Here is a fix for it

Fix the signature of the function

---

COPYRIGHT.txt

After successfully merging [this](https://github.com/mlpack/mlpack/pull/3851) PR I would like to add my self to the contrinutors list 😄

Add geonove to contributors list

---

src/mlpack/bindings/util/camel_case.hpp

Updating comments of CamelCase Function

---

src/mlpack/methods/reinforcement_learning/environment/acrobot.hpp
src/mlpack/methods/reinforcement_learning/environment/cart_pole.hpp
src/mlpack/methods/reinforcement_learning/environment/continuous_mountain_car.hpp
src/mlpack/methods/reinforcement_learning/environment/mountain_car.hpp
src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp

This PR fixes some broken links to the OpenAI Gym environments

Fix broken links
